### ISSUE TITLE
[ENG-108] Not sane default for frontend CPU

### ISSUE THREAD

**Issue by vwbusguy** [Infisical/infisical#1005]
### Describe the bug

A [recent update](https://github.com/Infisical/infisical/commit/4d6895a793033cf2900a0c45251c8d2e3a09e6f4#diff-ec50d2bccc2ae5bdebc1fdfac71bbcbf7ebcddb4a98e1ea1ae8e13ffaf4575d8R76)  brought the default CPU for the front-end down to just 10millicores.  This was almost certainly a typo instead of 150 like the backend.  I found this after upgrading to the new helm chart and then pages were failing to consistently load and things like css and javascript would load intermittently.  Bumping the CPU limits back up in the helm values on the front-end and re-running against the same helm version fixed it.

### To Reproduce

1. Launch with the 0.3.3 helm chart version
2. Attempt to log in or do anything
3. Good luck!

### Expected behavior

Helm chart defaults are minimally sane.

### Additional context

Deployed on Rancher (2.7.6) RKE2 v1.26.7+rke2r1 .  Previous versions of the helm chart did not have this problem without the frontend CPU specified.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-108](https://linear.app/infisical/issue/ENG-108/not-sane-default-for-frontend-cpu)</sub>

**Comment by maidul98** [comment]
@vwbusguy great find. Would you be able to make a PR for this?
