### ISSUE TITLE
[ENG-118] Imports are not supported in infisical export command

### ISSUE THREAD

**Issue by OmMewt** [Infisical/infisical#1015]
When using `infisical export --path={my_path} > .env` it only exports the base directory envs, not the imports.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-118](https://linear.app/infisical/issue/ENG-118/imports-are-not-supported-in-infisical-export-command)</sub>

**Comment by pratik-codes** [comment]
@akhilmhdh @maidul98 I can work on this if open to be picked up.

**Comment by akhilmhdh** [comment]
Ohh sure @pratik-codes i think this would be easier too. Up for take indeed.

@maidul98

**Comment by maidul98** [comment]
Hey @pratik-codes let's close out https://github.com/Infisical/infisical/issues/941 before picking up another issue

**Comment by SpeedReach** [comment]
@maidul98  I can work on this if this is still open

**Comment by mich040m** [comment]
I can see the PR [https://github.com/Infisical/infisical/pull/1450](https://github.com/Infisical/infisical/pull/1450) , has been in review for 2 months now? Any idea when it will be looked into? :)

**Comment by Cristobal-M** [comment]
Hi @mich040m according to this PR https://github.com/Infisical/infisical/pull/1663 include-imports is already supported. Was merged one month ago.

I removed original commits from my branch and left one with documentation changes.
