### ISSUE TITLE
[ENG-119] Failure to update auto capitalization

### ISSUE THREAD

**Issue by 6ixfalls** [Infisical/infisical#1021]
### Describe the bug
When disabling (unchecking) Auto Capitalization in Project Settings (/project/slug/settings), the error `Failed to update auto capitalization` shows on the frontend. The backend error simply shows
 `[IFSC:backend-main] error: The server encountered an error while processing the request`

### To Reproduce
1. Go to project settings /project/slug/settings
2. Scroll to "Auto Capitalization", uncheck the box
3. Notice the error in the frontend and backend

### Expected behavior
I should be able to update the Auto Capitalization property.
![image](https://github.com/Infisical/infisical/assets/23470032/016e88b3-cf41-45db-9302-186f96214a61)

### Platform you are having the issue on:
Self-hosted Helm chart tag v0.36.0, Chrome 116.0
[values.yaml](https://gist.github.com/6ixfalls/09c3d2377a13ef2d01517e2d15a039d0)

### Additional context
Tested with a project with secrets and a project without, setting change doesn't work. Unsure if there's a way to get any more verbose logging with infisical, the network request simply returns status 500 with an empty body.

<sub>[ENG-119](https://linear.app/infisical/issue/ENG-119/failure-to-update-auto-capitalization)</sub>

**Comment by maidul98** [comment]
This issue will be fixed in about 20 minutes

**Comment by 6ixfalls** [comment]
Confirmed fixed in `v0.36.1`
