### ISSUE TITLE
[ENG-128] Option for `infisical export` to prepend the `export` command

### ISSUE THREAD

**Issue by NiklasRosenstein** [Infisical/infisical#1025]
### Feature description

It would be useful for the `infisical export` command to have an option to include the `export` command in the output. Something like:

```
$ infisical export
MY_SECRET=abc
$ infisical export --format dotenv-export
export MY_SECRET=abc
```

### Why would it be useful?

I use `direnv`, but it only works with variables that have been exported. Currently I prepend every line with `export` using `sed`, but this breaks down for variables that have newlines in them:

```
eval "$(INFISICAL_VAULT_FILE_PASSPHRASE=pass infisical export --env prod --path kubernetes-cluster | sed 's/^/export /')"
```

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-128](https://linear.app/infisical/issue/ENG-128/option-for-infisical-export-to-prepend-the-export-command)</sub>

**Comment by Salman2301** [comment]
Anyone working on this?

**Comment by Salman2301** [comment]
Would like to contribute.

**Comment by Salman2301** [comment]
I check the code looks like it has already been add

```sh
 infisical export --format dotenv-export
```

Docs: https://infisical.com/docs/cli/commands/export

Commit https://github.com/Infisical/infisical/commit/799a839940156d1ce944e55ce32d615a16ffb3a0

**Comment by maidul98** [comment]
@Salman2301  correct.
