### ISSUE TITLE
Infisical CLI, .network tld email domains not valid.

### ISSUE THREAD

**Issue by sln-guy** [Infisical/infisical#103]
### Describe the bug
Unable to use a '.network' email address when trying to run `infisical login`

When running `infisical login` via cli and when prompted to enter your email, enter an email address ending in .network. The email will be invalid and cannot proceed. 

### To Reproduce
1. Install Infisical CLI
2. Run `infisical login`
3. Type any email address ending in .network (potato@potato.network)
4. Unable to proceed due to validation error. 

### Expected behavior
Expected the TLD of .network to be processed as a valid potential email address. 

### Screenshots
<img width="346" alt="Screenshot 2022-12-08 at 8 51 09 pm" src="https://user-images.githubusercontent.com/66862578/206417753-9586c5ca-5c33-48d8-ac64-c9e037309be3.png">

### Platform you are having the issue on:
Ubuntu Server 22.04
Installed via offical apt repo

**Comment by maidul98** [comment]
The bug fix has been released. Please update your package!

**Comment by sln-guy** [comment]
Updated package, confirmed issues resolved. 

Thank you! ❤️
