### ISSUE TITLE
[ENG-138] Hasura Cloud integration

### ISSUE THREAD

**Issue by osdiab** [Infisical/infisical#1038]
### Feature description

Secrets syncing integration with Hasura Cloud [cloud.hasura.io](http://cloud.hasura.io)

### Why would it be useful?

Hasura cloud users could sync secrets to their service

### Additional context

They have a graphql api that's easy to work with, though has restrictions on what settings you can programmatically set

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-138](https://linear.app/infisical/issue/ENG-138/hasura-cloud-integration)</sub>

**Comment by SpeedReach** [comment]
@vmatsiiako I could work on this.
