### ISSUE TITLE
[ENG-139] Nested folder name not displayed in the UI

### ISSUE THREAD

**Issue by RezaRahemtola** [Infisical/infisical#1039]
### Describe the bug
In the Infisical Cloud UI, when navigating to a nested folder, the folder previous folder names are displayed as `folderName` instead of the real name.

### To Reproduce
1. Go on the secrets part in Infisical Cloud
2. Create multiple nested folders
3. Navigate to them by clicking on it
4. See the displayed `folderName` in the "path" at the top

### Expected behavior
The real folder names should be displayed instead

### Screenshots
When in the first folder, everything is fine (URL is `https://app.infisical.com/project/ID/secrets/v2/dev?secretPath=%2Ffrontend`):
![image](https://github.com/Infisical/infisical/assets/49811529/ead46316-9c59-4c3e-ad53-a8cd0b7f14e9)

But when clicking on the `web` folder (URL is `https://app.infisical.com/project/ID/secrets/v2/dev?secretPath=%2Ffrontend%2Fweb`):
![image](https://github.com/Infisical/infisical/assets/49811529/80a63e62-de33-45b8-9391-c303b7d6cfb1)

And again if I create a new folder inside `web` and click on it:
![image](https://github.com/Infisical/infisical/assets/49811529/bd2516d2-c899-4955-bf7c-3b70a28d60b3)

### Platform you are having the issue on:
Infisical Cloud

<sub>[ENG-139](https://linear.app/infisical/issue/ENG-139/nested-folder-name-not-displayed-in-the-ui)</sub>

**Comment by maidul98** [comment]
@akhilmhdh
