### ISSUE TITLE
Install CLI on Windows system

### ISSUE THREAD

**Issue by vekonylaszlo** [Infisical/infisical#104]
Path: /cli/overview.mdx

Hey!

I cannot install the cli based on the docs.

```powershell
scoop bucket add org https://github.com/Infisical/scoop-infisical.git
Checking repo... ERROR 'https://github.com/Infisical/scoop-infisical.git' doesn't look like a valid git repository

Error given:
remote: Repository not found. fatal: repository 'https://github.com/Infisical/scoop-infisical.git/' not found
```
Can you give me some tips, what should I do?

Thank you!

**Comment by maidul98** [comment]
Hello! Thank you for bringing this up. I am. working on reproducing this issue on my side

**Comment by maidul98** [comment]
Found the issue, we for some reason made the scoop repo private. I just made it public and was able to install it properly. Let me know if you run into any issues!

**Comment by vekonylaszlo** [comment]
It's working now. Thank you very much!

**Comment by ceifa** [comment]
Do I really need scoop to use infisical? Why it isn't on npm or winget?
