### ISSUE TITLE
[ENG-161] Checkly integration support for sync on group level

### ISSUE THREAD

**Issue by zigapk** [Infisical/infisical#1061]
### Feature description

Currently, the Checkly integration sync all the secrets from Infisical to **top-level** environment variables in Checkly.

I propose adding a selector for a Checkly group to sync environment variables into. If none is selected, the variables can still be synced to top-level, preserving the current behavior.

### Why would it be useful?

1. This would prevent clashes between environment variables in Checkly from different projects in Infisical.
2. This would prevent tests in checkly from project A accessing secrets from project B.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-161](https://linear.app/infisical/issue/ENG-161/checkly-integration-support-for-sync-on-group-level)</sub>

**Comment by atimapreandrew** [comment]
@dangtony98

Please assign me to this.

**Comment by dangtony98** [comment]
This has been merged in with #1145 and will be available on the next deploy 😄

**Comment by zigapk** [comment]
Thank you @atimapreandrew, works like a charm!
