### ISSUE TITLE
Infisical command not found when i try to deploy the application on vercel 

### ISSUE THREAD

**Issue by DarlonHenrique** [Infisical/infisical#107]
### Describe the bug
I connect the infisical to my project and run locally, but when I do the push in my nextJs project, I can't deploy because vercel say to me `insifical command not found` how can I deploy without this error?

### To Reproduce
1. Add Infisical to the project following the documentation
2. Make the Git Push
3. See vercel fall in the caos because they dont know the command infisical

### Expected behavior
vercel use the infisical secrets env or use they own secrets env, or show me how to set up the infisical with vercel

### Screenshots
<img width="924" alt="Screen Shot 2022-12-09 at 11 50 31 AM" src="https://user-images.githubusercontent.com/67025443/206729776-c0805370-c6b5-49d9-89e6-54eadbc78365.png">

### Platform you are having the issue on:
MacOs BigSur, Vercel, NextJs

**Comment by maidul98** [comment]
To make sure I understand, are you trying to run the infisical command in Vercel? If so the error message is correct since vercel doesn't have infisical installed. To support vercel, we will have an integration available next week so that your Vercel environment will have access to the same secrets you have in infisical. Let me know if I misunderstood your question

**Comment by maidul98** [comment]
Here is the tracking issue for Vercel integration https://github.com/Infisical/infisical/issues/60

**Comment by DarlonHenrique** [comment]
yeah, how can i dont run infisical on vercel? idk how can i stop using this on vercel

**Comment by DarlonHenrique** [comment]
<img width="1680" alt="Screen Shot 2022-12-09 at 12 26 00 PM" src="https://user-images.githubusercontent.com/67025443/206735740-58b483fa-493c-43a7-ab38-495662e6cd66.png">
i know this solve the problem, but, that not a good solution, look to verbose

**Comment by maidul98** [comment]
You don't need to modify your package.json file at all. You can simply run the normal command you would to start your application in development mode.

In your terminal just run 
```
infisical run -- npm run dev 
```

Let me know if this solves your issue
