### ISSUE TITLE
[ENG-166] Publish the CLI on npm

### ISSUE THREAD

**Issue by jgoux** [Infisical/infisical#1070]
### Feature description

Currently when coming from the JS/TS ecosystem, the only way to install infisical is to install it globally on my system.

This isn't practical because I can't pin its version to my project, and it lives outside of my other dependencies.

I'd suggest creating a repo with a small wrapper like [https://www.npmjs.com/package/hasura-cli](https://www.npmjs.com/package/hasura-cli) which would automatically publish the CLI to npm on new releases.

The JS ecosystem is *huge* and that would definitely help adoption.

### Why would it be useful?

* Local installation following our sources along with our other dependencies
* Being able to use semver/pin the version of infisical

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-166](https://linear.app/infisical/issue/ENG-166/publish-the-cli-on-npm)</sub>

**Comment by maidul98** [comment]
Great idea @jgoux

**Comment by DanielHougaard** [comment]
This can now be downloaded through our new `@infisical/cli` NPM package. After installing the package globally, you can run `infisical` in your terminal to access the CLI, thank you!
