### ISSUE TITLE
[ENG-181] Ability to create multiple organisations under one account

### ISSUE THREAD

**Issue by theramjad** [Infisical/infisical#1082]
### Feature description

When you press the button to switch organisations, add the ability to create another allowing one person to be the owner of multiple orgs.

### Why would it be useful?

I like to separate my many indie projects by organisation. Sometimes I work with others. Other times not. Currently, I just make a separate account for each of them.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-181](https://linear.app/infisical/issue/ENG-181/ability-to-create-multiple-organisations-under-one-account)</sub>

**Comment by monolithed** [comment]
I'm really sorry, but could someone explain where to find the button for creating a new organization? I can see the implementation in the code, but there’s no such option in the interface.

<img width="1124" height="505" alt="Image" src="https://github.com/user-attachments/assets/ee663d31-b349-43aa-a61f-bb4cec61158a" />

**Comment by ErlandssonA** [comment]
I am also wondering about this!

EDIT: Just looked through the code and figured out that if you go to `https://your-domain.com/organization/none` you can create another organization.

**Comment by silvercondor** [comment]
> I am also wondering about this!
> 
> EDIT: Just looked through the code and figured out that if you go to `https://your-domain.com/organization/none` you can create another organization.

small note it's `/organizations/none` (organizations with an s) incase anyone found this helpful

**Comment by ErlandssonA** [comment]
Ohh, awesome!

Yeah I did use this for a little. But realised its easier to just keep everything under the same org. Mostly because I have multiple machines and projects and I have to log into the other orgs everytime I want to work on a different project.

Now I have it all under the same org, and I can just add my machines to the machine identities.

**Comment by larssb** [comment]
Is it really true that there's no programmatic way to do this? I have to call the FQDN_OF_MY_INFISICAL_INSTANCE/organizations/none to get the prompt to create a new organization up? Even the docs explain that it should be possible to create multiple organizations on an infisical instance when self-hosted. See [1. Organization, under Organization Structure](https://infisical.com/docs/documentation/guides/organization-structure#1-organization).

Thank you so much.
