### ISSUE TITLE
[ENG-192] `infisical run` should print its messages to `stderr`

### ISSUE THREAD

**Issue by NiklasRosenstein** [Infisical/infisical#1091]
### Describe the bug

The `infisical run` command prints messages to stdout.

### To Reproduce

```
$ infisical run -- some command >/dev/null
```

I would expect it to print

```
Injecting 4 Infisical secrets into your application process
failed to wait for command termination: exit status 1
```

to stderr, but it ends up in stdout.

### Expected behavior

`infisical run` prints to stderr instead.

### Additional context

Infisical CLI v0.14.2

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-192](https://linear.app/infisical/issue/ENG-192/infisical-run-prints-to-stdout-makes-it-difficult-to-use-the-output-of)</sub>

**Comment by digant2482** [comment]
Hi, I have made relevant changes inside CLI folder. However, being new to CLI, I am unsure how to test these changes locally. Any suggestions ?

**Comment by maidul98** [comment]
You can invoke the CLI in test mode by running: `go run . <infisical sub command>` at the root of the CLI folder
