### ISSUE TITLE
[ENG-195] Cannot integrate with GCP Secret Manager via Service Account JSON 

### ISSUE THREAD

**Issue by Merton** [Infisical/infisical#1097]
### Describe the bug
When connecting a new project to GCP Secret's manager via a service account JSON, the request returns a 500 BAD REQUEST axios error.

I have a service account setup in GCP with Secret Manager Admin & Service Account User:
![Screenshot 2023-10-19 at 11 13 00](https://github.com/Infisical/infisical/assets/25505506/18deccd8-5850-4ef7-88c7-b1fee6bd9662)

### To Reproduce
1. Go to project’s integrations tab
2. Press on the GCP Secret Manager tile and paste in your GCP Service Account JSON 
3. Press "Connect to GCP Secret Manager"
4. Button spins for ~1 second, no visible error, but no progress.
5. Check network tab and see 500 error

### Expected behavior
It progresses and integrates

### Screenshots
![Screenshot 2023-10-19 at 11 06 03](https://github.com/Infisical/infisical/assets/25505506/8788cd81-5eb6-4229-ae93-91a796c04edd)

### Platform you are having the issue on:
MacBook Pro v13.5 - Firefox 118.0.1

### Additional context
This is the first time attempting to integrate with a provider

Thanks!

<sub>[ENG-195](https://linear.app/infisical/issue/ENG-195/cannot-integrate-with-gcp-secret-manager-via-service-account-json)</sub>

**Comment by dangtony98** [comment]
Hey @Merton!

Have you checked out the GCP SM integration docs [here](https://infisical.com/docs/integrations/cloud/gcp-secret-manager)?

A few parts to consider when following the docs step-by-step:
- The service account should have required permissions.
- You should enable the Service Usage API and Cloud Resource Manager API in the Google Cloud project you want to sync secrets to.

**Comment by Merton** [comment]
Hey @dangtony98 

Apologies, I double checked the enabled API's and had to enable one. Oops!

Thanks for the guidance.
