### ISSUE TITLE
Unable to store infisical cli login credentials in Ubuntu Server 22.04 system keyring.

### ISSUE THREAD

**Issue by sln-guy** [Infisical/infisical#113]
### Describe the bug
When running `infisical login --domain http://my.domain/api -d` I receive an error about being unable to store the credentials in the system keying. Specific error below:

![Screenshot_20221211_011507](https://user-images.githubusercontent.com/66862578/206882614-70e60df8-e31c-4579-b644-a7560d3fa9b6.png)

I attempted to install gnome-keyring & dbus-x11 to try resolve but ran into a different error:

![Screenshot 2022-12-11 011659](https://user-images.githubusercontent.com/66862578/206882689-1d1f8cff-335c-47c6-a47e-b4ffc581cd71.png)

### To Reproduce
1. Fresh Headless Ubuntu server 22.04 KVM w/ Docker installed
2. Install Infisical CLI from offical repo.
3. Run `infisical login --domain http://my.domain/api -d`
4. Login
5. Error message about not being able to store credentials.
6. Unable to proceed.

### Expected behavior
- Expected CLI to be able to store credentials on Ubuntu Server 22.04 or be in documentation.
- Latest updated 0.1.10 did add a more clear message about the error when not running in debug.

### Platform you are having the issue on:
Ubuntu Server 22.04.1 LTS (Linux 5.15.0-56-generic)
Infisical CLI 0.1.09/0.1.10

### Additional context
I fiddled around with gnome keyring and its secret store for quite some time  but made no head way. I attempted to replace the existing keyring using the gnome-keyring-daemon but still ran into issues. 

Thanks again.

**Comment by sln-guy** [comment]
I will do some more testing with 'github.com/zalando/go-keyring' and see what I can find. Have a feeling this is my not configuring newly installed gnome-keyring default collection correctly...

**Comment by maidul98** [comment]
Thanks for brining this up. I know we had someone also run into this issue before https://github.com/Infisical/infisical/issues/25#issuecomment-1324121629. I will investigate if we can give alternative storage options if key ring is not available and post updates here

**Comment by sln-guy** [comment]
I believe I have found a temporary solution...
Install dependencies:
`sudo apt install dbus-x11 gnome-keyring libsecret-1-0`
Delete existing keyring if exists
'rm ~/.local/share/keyrings/*'
Create and start new keyring:
`echo 'yourpassword' | gnome-keyring-daemon --unlock`
`echo 'FghFghFgh!&31799816' | /usr/bin/gnome-keyring-daemon --start`
Attempt to run `infisical login` now

Unsure how this will go after a reboot. Yet to test but I imagine auto-unlock would have to be configured in pam.

**Comment by maidul98** [comment]
Happy it's worked for you as well, please post any other issues you encounter

**Comment by changesbyjames** [comment]
@maidul98 I just wanted to add that I'm also having issues with the keyring installation and setup process, especially in dockerised development environments like GitHub codespaces. Another way of storing creds would be super appreciated to make this smoother. Thanks.

**Comment by maidul98** [comment]
If you’ve had issues logging in because of keyring problems, Infisical CLI now supports multiple vaults to save your login credentials at rest. That means if the default store doesn’t work, you can switch to a different vault. Or, if you don’t have any vaults installed at all, you can still store your credentials safely in an encrypted text file with a passphrase that only you know. Check out more info on this here https://infisical.com/docs/cli/commands/vault don’t forget to update your CLI!

**Comment by ckshen8** [comment]
@maidul98 i ran into this same issue today and solved it with your solution `infisical vault set file`.  Thanks.

**Comment by akhilmhdh** [comment]
Closing as stale
