### ISSUE TITLE
[ENG-212] Missing parentFolderId property logic

### ISSUE THREAD

**Issue by IvanMykytyn** [Infisical/infisical#1135]
[https://github.com/Infisical/infisical/blob/bc43e109ebde7f30b00c33f901c970eba249aef2/backend/src/controllers/v1/secretsFolderController.ts#L103](https://github.com/Infisical/infisical/blob/bc43e109ebde7f30b00c33f901c970eba249aef2/backend/src/controllers/v1/secretsFolderController.ts#L103)

parentFolderId parameter is not working at all. (Not handled)

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-212](https://linear.app/infisical/issue/ENG-212/missing-parentfolderid-property-logic)</sub>

**Comment by akhilmhdh** [comment]
Hey their @IvanMykytyn 

Parent folder id is removed and we are updating our API docs. U need to use the directory or the paths which is more easier. Closing as its expected
