### ISSUE TITLE
[ENG-215] copy override value

### ISSUE THREAD

**Issue by yaronlevi** [Infisical/infisical#1137]
When you have an override value and you press COPY, you get the regular value instead of the override:

![image](https://github.com/Infisical/infisical/assets/5398977/e62f27a7-3023-4d3d-a7d6-57527930a6cf)

<sub>[ENG-215](https://linear.app/infisical/issue/ENG-215/copy-override-value)</sub>

**Comment by alfredlouisw8** [comment]
hi can i take this issue?

**Comment by dangtony98** [comment]
Go for it @alfredlouisw8 😄
