### ISSUE TITLE
[ENG-222] Unable to access one project, but can access another

### ISSUE THREAD

**Issue by basperheim** [Infisical/infisical#1149]
### Describe the bug

We are a small team with two projects, and I have been granted admin access. I can sign in just fine, but I can only access one of them. The other project, when I try to view env variables for an environment, just gets "stuck" and continues to load (or sometimes I get a 400 resp).

Using the `infisical` CLI in a terminal it's the same thing. I can login just fine with `infisical login`, but I get this response when I attempt to use `infisical run` on the same project:

```
error: unable to get your encrypted workspace key. [err=CallGetEncryptedWorkspaceKey: Unsuccessful response [GET https://app.infisical.com/api/v2/workspace/........./encrypted-key] [status-code=500]]
Could not fetch secrets
If you are using a service token to fetch secrets, please ensure it is valid
If this issue continues, get support at https://infisical.com/slack
```

I'm the only one in my team who has this issue. Everyone can access the project just fine.

### Expected behavior

I should be able to access this one project like I can the other one.

### Screenshots

![](https://uploads.linear.app/23e8e853-8625-4193-88c0-0864ea047dca/e9a06c38-93e4-4ce3-b591-ee0279357798/e86a253d-f1e9-4d2b-b370-e82f60e11f7d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzIzZThlODUzLTg2MjUtNDE5My04OGMwLTA4NjRlYTA0N2RjYS9lOWEwNmMzOC05M2U0LTRjZTMtYjU5MS1lZTAyNzkzNTc3OTgvZTg2YTI1M2QtZjFlOS00ZDJiLWIzNzAtZTgyZjYwZTExZjdkIiwiaWF0IjoxNjk4ODUwODAzLCJleHAiOjE2OTg5MzcyMDN9.9dB-Fw1MS3-digy0fVgt43KW_XlxayBvxDhevyKo9O0)

### Platform you are having the issue on:

macOS terminal and Chrome

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-222](https://linear.app/infisical/issue/ENG-222/unable-to-access-one-project-but-can-access-another)</sub>

**Comment by maidul98** [comment]
Hello @basperheim, are you using Infisical cloud? If so can you please share the id of the project that is `stuck`. The ID should be available in the url

**Comment by basperheim** [comment]
> Hello @basperheim, are you using Infisical cloud? If so can you please share the id of the project that is `stuck`. The ID should be available in the url

Workspace/Project ID is: `64ca8e7b7af3a6437fab8d47`.

I just use "Infisical Cloud"--I don't know what the "Self Hosting" option refers to when logging in via terminal.

In a Chrome browser I get this `400` error when trying to load the project:
![Infisical project 400 error](https://github.com/Infisical/infisical/assets/4186751/47c72fc1-201e-4200-ba6b-f63c253e5178)

In a terminal I get this error:

```bash
$ infisical login
✔ Override current logged in user
✔ Infisical Cloud
Logging in via browser... To login via interactive mode run [infisical login -i]
>>>> Welcome to Infisical! You are now logged in as basperheim@gmail.com <<<< 

Quick links
- Learn to inject secrets into your application at https://infisical.com/docs/cli/usage
- Stuck? Join our slack for quick support https://infisical.com/slack

$ yarn run start:dev
error: unable to get your encrypted workspace key. [err=CallGetEncryptedWorkspaceKey: Unsuccessful response [GET https://app.infisical.com/api/v2/workspace/64ca8e7b7af3a6437fab8d47/encrypted-key] [status-code=500]]
Could not fetch secrets
If you are using a service token to fetch secrets, please ensure it is valid

If this issue continues, get support at https://infisical.com/slack
```

`start:dev` runs: `infisical run --env=dev`

**Comment by akhilmhdh** [comment]
Hey @basperheim Are you in  our slack. We are trying to find a way to reproduce this bug on our side. Would really appreciate to chat how this happened.

**Comment by basperheim** [comment]
> Hey @basperheim Are you in our slack. We are trying to find a way to reproduce this bug on our side. Would really appreciate to chat how this happened.

Yes, I joined your slack and sent @maidul98 a DM just now. Is there a particular channel I should bring this up in?
