### ISSUE TITLE
[ENG-229] Both the Cloudflare Pages & Workers integrations don't support any secret paths other than `/`

### ISSUE THREAD

**Issue by RafidMuhymin** [Infisical/infisical#1155]
### Describe the bug

Both the Cloudflare Pages & Workers integrations don't support any secret paths other than `/`

### To Reproduce

1. Install the Cloudflare Pages or Workers integration
2. Notice that there's no field for selecting a secret path (folder)

### Expected behavior

A custom secret path should be supported because one project might have many workers. Not having this feature means every worker requires its Infisical project and it hampers the experience a lot. And secret sharing also won't work.

### Screenshots

N/A

### Platform you are having the issue on:

Windows

### Additional context

N/A

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-229](https://linear.app/infisical/issue/ENG-229/the-cloudflare-pages-integration-doesnt-support-any-secret-paths-other)</sub>

**Comment by zwkee** [comment]
Hi @vmatsiiako @dangtony98, I would like to work on this.

**Comment by jurjendevries** [comment]
Hi, would be great to see this fixed as we need this working well. How can we support this? Following...

**Comment by vmatsiiako** [comment]
Hi @jurjendevries! Let me see if we can fit it in any of our next cycles. Are you planning to use it for a commercial use case?

**Comment by jurjendevries** [comment]
Hi @vmatsiiako we are using it within https://github.com/dilmaheu/dilmahtea.me

**Comment by Salman2301** [comment]
This is merged https://github.com/Infisical/infisical/pull/1495
We canc lose @vmatsiiako
