### ISSUE TITLE
[ENG-230] Add Pino transport to forward logs to AWS CloudWatch

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#1158]
### Feature description

Infisical recently added [Pino](https://github.com/pinojs/pino) for logging; currently, Pino is configured for local development.

It would be great to set up [Pino transports](https://getpino.io/#/docs/transports) to forward logs to external platforms for log aggregation/analysis etc. This specific issue is about forwarding logs to AWS CloudWatch

### Why would it be useful?

This would provide self-hosted users of Infisical more logging/observability over their instances of Infisical in production.

### Additional context

Check out Pino transports documentation [here](https://getpino.io/#/docs/transports).

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-230](https://linear.app/infisical/issue/ENG-230/add-pino-transport-to-forward-logs-to-aws-cloudwatch)</sub>

**Comment by atimapreandrew** [comment]
@dangtony98 

Please assign this to me.

**Comment by dangtony98** [comment]
Assigned @atimapreandrew 😄
