### ISSUE TITLE
[ENG-231] (Pino) Instance Log Transports from Infisical to Platform X

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#1159]
### Feature description

Infisical recently added [Pino](https://github.com/pinojs/pino) for logging; currently, Pino is configured for local development.

It would be great to set up [Pino transports](https://getpino.io/#/docs/transports) to forward logs to external platforms for log aggregation/analysis etc.

Below is a list of **needed** transports:

* [ ] AWS CloudWatch #1158
* [ ] Datadog #1160
* [ ] Elastic #1161
* [ ] Sentry #1162
* [ ] Grafana Cloud / Loki #1163
* [ ] Graylog

### Why would it be useful?

This would provide self-hosted users of Infisical more logging/observability over their instances of Infisical in production.

### Additional context

Check out Pino transports documentation [here](https://getpino.io/#/docs/transports).

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-231](https://linear.app/infisical/issue/ENG-231/pino-instance-log-transports-from-infisical-to-platform-x)</sub>

**Comment by Emiliaaah** [comment]
Would personally also love to see an option for graylog

**Comment by Salman2301** [comment]
I will work on this... Please assign it to me

**Comment by akhilmhdh** [comment]
Closing this, as we have decided that this is not something Infisical should handle. A proper log aggregator should take care of it.
