### ISSUE TITLE
[ENG-232] Add Pino transport to forward logs to Datadog

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#1160]
Infisical recently added [Pino](https://github.com/pinojs/pino) for logging; currently, Pino is configured for local development.

It would be great to set up [Pino transports](https://getpino.io/#/docs/transports) to forward logs to external platforms for log aggregation/analysis etc. This specific issue is about forwarding logs to Datadog

Why would it be useful?
This would provide self-hosted users of Infisical more logging/observability over their instances of Infisical in production.

Additional context
Check out Pino transports documentation [here](https://getpino.io/#/docs/transports).

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-232](https://linear.app/infisical/issue/ENG-232/add-pino-transport-to-forward-logs-to-datadog)</sub>

**Comment by danielvu1023** [comment]
Hi Tony, can I take up this issue?

**Comment by akhilmhdh** [comment]
Closing this, as we have decided that this is not something Infisical should handle. A proper log aggregator should take care of it.
