### ISSUE TITLE
[ENG-234] Add Pino transport to forward logs to Sentry

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#1162]
Feature description
Infisical recently added [Pino](https://github.com/pinojs/pino) for logging; currently, Pino is configured for local development.

It would be great to set up [Pino transports](https://getpino.io/#/docs/transports) to forward logs to external platforms for log aggregation/analysis etc. This specific issue is about forwarding logs to Sentry

Why would it be useful?
This would provide self-hosted users of Infisical more logging/observability over their instances of Infisical in production.

Additional context
Check out Pino transports documentation [here](https://getpino.io/#/docs/transports).

Note: Infisical does have a setup for forwarding errors to Sentry already via Sentry SDK but perhaps there is a more streamlined way that we can do it with Pino transports.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-234](https://linear.app/infisical/issue/ENG-234/add-pino-transport-to-forward-logs-to-sentry)</sub>

**Comment by Dhoni77** [comment]
Hi @dangtony98 I would like to work on this issue

**Comment by dangtony98** [comment]
@Dhoni77 Assigned 😄

**Comment by akhilmhdh** [comment]
Closing this, as we have decided that this is not something Infisical should handle. A proper log aggregator should take care of it.
