### ISSUE TITLE
[ENG-236] Create projects using Infisical Terraform Provider

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#1165]
### Feature description
Infisical Users are currently able to create secrets using [Infisical Terraform provider](https://infisical.com/docs/integrations/frameworks/terraform#5-run-terraform). It would be great to add a possibility of creating projects using terraform. 

### Why would it be useful?
Many users have asked about this possibilty, and it will enable a more complete managing of Infisical using terraform.

### Additional context
In addition, users could also be able to create environments. 

<sub>[ENG-236](https://linear.app/infisical/issue/ENG-236/create-projects-using-infisical-terraform-provider)</sub>

**Comment by vmatsiiako** [comment]
Hi @quinton11! This would be awesome, it has been requested many times now. I'm assigning it to you. 

If you have any questions, feel free to leave comments or ask us in the community slack for contributors: https://infisical.com/slack

**Comment by akhilmhdh** [comment]
Closing as stale!
