### ISSUE TITLE
:truck: Abstract the Dashboard Page into More reusable components and hooks.

### ISSUE THREAD

**Issue by LemmyMwaura** [Infisical/infisical#118]
### Feature description
At the moment the dashboard [id] page acts as the main source for most of the content in the dashboard. As the project scales and we shift all components and pages to using typescript the file might become unmanageable and cluttered and could potentially become a source for more bugs or poor implementation of logic if we leave it as is.

Separating it into more reusable components and hooks will make it easier to manage and add new dashboard-related features.

### Why would it be useful?
- It will essentially make it easier to manage and optimize the dashboard as the project grows.
- Better developer experience.

**Comment by mv-turtle** [comment]
This is awesome @LemmyMwaura! Would be very helpful! Something to keep in mind here is performance for users who have 100+ secrets (it can get slow). 

Let me know if you need any help :)

**Comment by dangtony98** [comment]
This is ... so needed  @LemmyMwaura awesome initiative here!

**Comment by mv-turtle** [comment]
Hi @LemmyMwaura! I was wondering if you had any time to work on this? I will be doing a dashboard sidebar soon - so I can also help :)

**Comment by LemmyMwaura** [comment]
@mv-turtle Hey, Yes. I've been a little busy so I had to put it on the side but I'll try to get a PR up within the next two days. That would be awesome. We can communicate on slack.

**Comment by LemmyMwaura** [comment]
Closing this as completed, Bigup to @akhilmhdh  -> #443
