### ISSUE TITLE
[ENG-267] Self hosting not working !

### ISSUE THREAD

**Issue by CypriotUnknown** [Infisical/infisical#1199]
Path: /self-hosting/deployment-options/docker-compose

I am trying to set up a self hosted environment for infisical. I am following the documentation to host with a Docker Compose file. This is the http response I get when trying to connect to the 'infisical-backend':
{
"\_logLevel": 30,
"\_logName": "INFO",
"statusCode": 404,
"type": "route_not_found",
"context": {},
"extra": \[\]
}

---

I have been trying to do this on and off for months but I am failing miserably. There's no proper support and obviously the documentation has some faults. Please help.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-267](https://linear.app/infisical/issue/ENG-267/self-hosting-not-working)</sub>

**Comment by dangtony98** [comment]
cc @maidul98
