### ISSUE TITLE
[ENG-268] SDK for .Net

### ISSUE THREAD

**Issue by alberk8** [Infisical/infisical#1200]
### Feature description

A sdk for dotnet.

### Why would it be useful?

Why would this feature be useful for Infisical users?
Provide an alternative to HashiCorp Vault for DotNet.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-268](https://linear.app/infisical/issue/ENG-268/sdk-for-net)</sub>

**Comment by DanielHougaard** [comment]
Hi @alberk8, thanks for the suggestion! We recently rolled out a new [cross-language SDK](https://github.com/Infisical/sdk), which will speed up the development process greatly for new SDK's. C# is actually the next SDK we intend on adding, and I'll keep you updated on the progress!

**Comment by DanielHougaard** [comment]
@alberk8 .NET SDK should be released before the day is over. I'll update you once it's live!
