### ISSUE TITLE
Configure GoReleaser to publish to arch repository

### ISSUE THREAD

**Issue by afwilliams** [Infisical/infisical#121]
I currently try to install Infisical but my personal laptop run Arch Linux SO and i don't know how to install it.

Someone can help me?

**Comment by maidul98** [comment]
We currently don't have a build for arch linux. However, it looks possible to generate a package for arch as well following this https://goreleaser.com/customization/aur/. I will get back to you once we configure our Go releaser to also publish to a arch repository

**Comment by maidul98** [comment]
@afwilliams you may install infisical on your arch linux: https://infisical.com/docs/cli/overview

**Comment by roospk16-boop** [comment]
Ահա մենք, ցանկացած հարցի դեպքում, խնդրում եմ կապվեք ինձ հետ։> I currently try to install Infisical but my personal laptop run Arch Linux SO and i don't know how to install it.
> 
> Someone can help me?

**Comment by roospk16-boop** [comment]
Ահա մենք, ցանկացած հարցի դեպքում, խնդրում եմ կապվեք ինձ հետ։> I currently try to install Infisical but my personal laptop run Arch Linux SO and i don't know how to install it.
> Soy Rodolfo.
> Someone can help me?
