### ISSUE TITLE
[ENG-315] Ability to hot reload env variables

### ISSUE THREAD

**Issue by BearTS** [Infisical/infisical#1219]
### Feature description

The capability of dynamically updating and applying changes to environment variables without requiring a full application restart. This feature would allow users to modify configuration settings on the fly, enhancing the development and debugging experience

### Why would it be useful?

Debugging and Testing: The ability to hot reload environment variables facilitates easier debugging and testing. Developers can quickly tweak configurations to observe the immediate impact on the application's behavior without interrupting the debugging or testing session.

Real-time Configuration Updates: For applications with a dynamic configuration or where settings need frequent adjustments, hot reloading environment variables provides a seamless way to apply changes in real-time. This is particularly beneficial for applications that rely heavily on configuration settings.

User Experience: Infisical users will benefit from a smoother and more responsive user experience during development and testing phases. Developers can fine-tune application settings without causing disruptions, ensuring a more efficient workflow.

### Additional context

In my opinion, this should be an opt-in option! If `--live-reload` is passed as an arg in the cli or the sdk, it will automatically reload, if not, then it would required a restart

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-315](https://linear.app/infisical/issue/ENG-315/ability-to-hot-reload-env-variables)</sub>

**Comment by akhilmhdh** [comment]
Closing as we have now watch mode in CLI

https://infisical.com/docs/cli/commands/run#infisical-run:watch
