### ISSUE TITLE
[ENG-323] External Secrets Provider

### ISSUE THREAD

**Issue by enmanuelmoreira** [Infisical/infisical#1227]
### Feature description

It would be awesome if Infisical could have External Secrets compatibility to manage K8S secrets.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-323](https://linear.app/infisical/issue/ENG-323/external-secrets-provider)</sub>

**Comment by maidul98** [comment]
Great suggestion, i know a few other people have also asked

**Comment by Sammcb** [comment]
Would also love to see this functionality as this is the main reason I'm using a closed-source solution.

**Comment by rwarford** [comment]
I was waiting for this too.  Apparently it has been done and looks likely to be in the next release of the External Secrets provider.
The pull request for the Infisical Provider for the External Secrets Operator is [here](https://github.com/external-secrets/external-secrets/pull/3477).

I was able to use the Kubernetes Provider as a workaround, see my comment [here](https://github.com/Infisical/infisical/issues/1072#issuecomment-2200458805).

**Comment by maidul98** [comment]
Hey folks, I have asked in the external secrets slack channel and it looks like they do not have any formal release cycle. We will have to wait when someone on the team has time to make a release unfortunately  
![CleanShot 2024-07-05 at 19 27 32@2x](https://github.com/Infisical/infisical/assets/9300960/15257d3c-73e2-42c7-876c-d8a4902bc956)

**Comment by maidul98** [comment]
A release has been made: https://external-secrets.io/latest/provider/infisical/
