### ISSUE TITLE
[ENG-340] can't authenticate using INFISICAL_API_URL, INFISICAL_TOKEN environment variables (self hosted server)

### ISSUE THREAD

**Issue by akfmdl** [Infisical/infisical#1233]
### Describe the bug

can't authenticate using INFISICAL_API_URL, INFISICAL_TOKEN environment variables

### To Reproduce

1. Installed self-hosted server using helm chart
2. Generate a Infisical service token from self-hosted server
3. Try to run a command with environment variable INFISICAL_API_URL=<you domain>, INFISICAL_TOKEN=<your token>

### Expected behavior

Expected to run commands without need to run infisical login.

### Screenshots

This is errors when i run command 'infisical secrets'
`error: unable to get service token details. [err=CallGetServiceTokenDetails: Unsuccessful response: [response=<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/css/670782a328c4a5af.css" as="style"/><link rel="stylesheet" href="/_next/static/css/670782a328c4a5af.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-74fe010cd18e2400.js" defer=""></script><script src="/_next/static/chunks/framework-79bce4a3a540b080.js" defer=""></script><script src="/_next/static/chunks/main-5ec97f4390710bd2.js" defer=""></script><script src="/_next/static/chunks/pages/_app-e2d1b6f26f523c51.js" defer=""></script><script src="/_next/static/chunks/pages/404-a3659c43acccd085.js" defer=""></script><script src="/_next/static/1NoYrlyyo01hJg5hn8bw4/_buildManifest.js" defer=""></script><script src="/_next/static/1NoYrlyyo01hJg5hn8bw4/_ssgManifest.js" defer=""></script></head><body><div id="__next" data-reactroot=""><div class="bg-bunker-800"><div class="container mx-auto flex relative flex-col h-screen w-full items-center justify-center px-8 text-mineshaft-50 dark:[color-scheme:dark] space-y-8"><img src="/images/loading/loading.gif" height="70" width="120" alt="loading animation"/><div class="text-primary text-xs">Loading configurations</div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/404","query":{},"buildId":"1NoYrlyyo01hJg5hn8bw4","nextExport":true,"autoExport":true,"isFallback":false,"locale":"en","locales":["en","ko","fr","pt-BR","pt-PT","es"],"defaultLocale":"en","scriptLoader":[]}</script></body></html>]]`

### Platform you are having the issue on:

infisical version 0.15.2

### Additional context

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-340](https://linear.app/infisical/issue/ENG-340/cant-authenticate-using-infisical-api-url-infisical-token-environment)</sub>

**Comment by akhilmhdh** [comment]
I think you accidentally put the wrong api url. Did u miss `/api`

**Comment by akfmdl** [comment]
@akhilmhdh OMG you are right!! putting `/api`at the end of domain url works! You saved my days THX!
