### ISSUE TITLE
[ENG-342] Too much recursion when creating a service token and changing the environment on Firefox

### ISSUE THREAD

**Issue by keithbrink** [Infisical/infisical#1234]
### Describe the bug

On Firefox, when I try to create a service token and select a different environment from the dropdown, the browser freezes and console displays a too much recursion error.

### To Reproduce

On Firefox:

1. Open the create a service token modal
2. Click on the environment dropdown
3. Try to select an environment
4. Browser freezes

### Expected behavior

I can select a different environment

### Screenshots

[https://cln.sh/TK6LztV4](https://cln.sh/TK6LztV4)

### Platform you are having the issue on:

Firefox - Infisical Cloud

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-342](https://linear.app/infisical/issue/ENG-342/too-much-recursion-when-creating-a-service-token-and-changing-the)</sub>

**Comment by Mann-webspider** [comment]
It seems working fine in my machine 


**machine spec:**
Laptop : Acer aspire 7
OS: Linux , Ubuntu 22.04
Ram : 8gb
Processor : AMD Ryzen 5000
Browser: Firefox

**Comment by matti-kz** [comment]
Issue seems to be resolved on infisical.com, but still present in `infisical/infisical:v.0.43.5`

**Comment by maidul98** [comment]
Hmm, app.infisical.com is running the latest image. Where have you deployed Infisical? @matti-kz

**Comment by matti-kz** [comment]
Sorry my mistake, indeed the issue is fixed `infisical/infisical:v.0.43.5` :)
