### ISSUE TITLE
[ENG-343] CLI Login not working through Safari

### ISSUE THREAD

**Issue by hhaustreis** [Infisical/infisical#1235]
### Describe the bug

When attempting to login using `infisical login` it opens the website on safari, prompts me to login but when I get to the master password phase it returns an error message stating it is wrong while it is the exact same i use when logging in normally.
Being preemptively logged in does not make a difference either. This is only an issue on Safari. It works as expected on a Chromium-based browser.

### To Reproduce

1. Run `infisical login`
2. Select `Infisical Cloud`
3. Open the URL in Safari
4. Select `Continue with SSO`
5. Input SSO Identifier
6. Input Master Password

### Expected behavior

Expected behaviour would be running `infisical login` and the login completing successfully.

### Screenshots

![image](https://uploads.linear.app/23e8e853-8625-4193-88c0-0864ea047dca/b13243e2-6a46-4931-bb31-fb5339edf971/e8279721-7ddd-4ddd-bdc3-34ea86cc253a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzIzZThlODUzLTg2MjUtNDE5My04OGMwLTA4NjRlYTA0N2RjYS9iMTMyNDNlMi02YTQ2LTQ5MzEtYmIzMS1mYjUzMzllZGY5NzEvZTgyNzk3MjEtN2RkZC00ZGRkLWJkYzMtMzRlYTg2Y2MyNTNhIiwiaWF0IjoxNzAyMzgyNDgwLCJleHAiOjE3MDI0Njg4ODB9.qAI3C1ja40DLn0s04X2xt7F08WDpHz-qSpBLnnYagzo)

### Platform you are having the issue on:

MacOS Sonoma 14.1.1
Browser: Safari

### Additional context

It works as intended when using a Chrome-based browser so this seems to be Safari specific.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-343](https://linear.app/infisical/issue/ENG-343/cli-login-not-working-through-safari)</sub>

**Comment by ankit-pn** [comment]
I want to work on this issue. So does anyone here assign this issue to me or I can directly start working on it?

**Comment by akhilmhdh** [comment]
CC: @maidul98 already has some insights into this. Kindly go through with him for more information on this. 

This is an identified issue on token exchange with browser based login from cli using brave or safari

**Comment by ankit-pn** [comment]
Thanks @akhilmhdh. I am trying to figure out issue behind it and it would be very helpful if @maidul98 provide his insight on it.

**Comment by ankit-pn** [comment]
For both browser issue is related to inbuilt security features of browsers which is blocking a network calls [POST] to 121.0.0.1 from https://app.infisical.com/login . 

In brave browser we are getting error as 

```
POST http://127.0.0.1:55036/ net::ERR_BLOCKED_BY_CLIENT
```

which clearly means that brave shield is blocking call to localhost server which is used for cli authentication.

You can resolve this issue by turning off brave shield or do the steps that is maintained in ref article.

Ref. -> [Brave Community Post Link Related to this issue](https://community.brave.com/t/brave-blocks-localhost-needs-shields-off-to-have-functioning-website/260084)


Safari do have similar issue and error that we are getting is

```
XMLHttpRequest cannot load http://127.0.0.1:64824/ due to access control checks.
```

This can be corrected by enabling developer option in Settings.

Safari>Settings>Advanced>Show Features for web developers

and then

Safari>Settings>Developer>Disable Cross Origin Restrictions .

**Comment by ankit-pn** [comment]
Is there any way be which we can resolve this issue without users need to change there browser settings? @maidul98 any suggestion?

**Comment by akhilmhdh** [comment]
This has been fixed with our recent release of CLI
