### ISSUE TITLE
[ENG-362] HSM Support

### ISSUE THREAD

**Issue by yudjinn** [Infisical/infisical#1254]
### Feature description

Support HSM for source of keys as well as storage - would also love a BYOK and ability to import/export keys

### Why would it be useful?

Backing all encryption with a hardware module as well as using it for storage has a BUNCH of benefits, especially towards compliance.

### Additional context

Also helps with RoT for enterprise uses.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-362](https://linear.app/infisical/issue/ENG-362/hsm-support)</sub>

**Comment by ruchinksinha** [comment]
Is there a roadmap to provide HSM Support?

**Comment by vmatsiiako** [comment]
This has now been available for a while. More HSM providers are about to be released too.
