### ISSUE TITLE
Client side error while creating a vercel integration

### ISSUE THREAD

**Issue by demirtasdurmus** [Infisical/infisical#1271]
### Describe the bug
When I try to create a vercel integration, application suddenly breaks(will attach video)

### To Reproduce
1. Go to integrations
2. Click on vercel
3. Select `preview` as Vercel App Environment in the integration dialog

### Expected behavior
I should be able to create a new integration with vercel for preview env

### Screenshots

https://github.com/Infisical/infisical/assets/70111575/f8608998-6d31-41c2-8e46-34b879eaea8a

### Platform you are having the issue on:
`
ProductName:            macOS
ProductVersion:         14.2.1
BuildVersion:           23C71
`

**Comment by DanielHougaard** [comment]
Hey @demirtasdurmus, thanks for reporting. I just opened a PR that should resolve this!
