### ISSUE TITLE
[ENG-380] Create secrets from the overview page

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#1273]
### Feature description
Currently you need to click to "Explore" a particular environment on the web dashboard if you want to create a new secret. Ideally, we want to have a way to create secrets right from the "Secret overview" screen. 

### Why would it be useful?
This would save a lot of time for users who need to create secrets on a constant basis. It has been requested many times by Infisical users. 

<sub>[ENG-380](https://linear.app/infisical/issue/ENG-380/create-secrets-from-the-overview-page)</sub>

**Comment by RohanMishra315** [comment]
hey @vmatsiiako Can I look into it ?

**Comment by jithenms** [comment]
@RohanMishra315 let me know if you are still looking into it. If not, I'd be happy to take a shot. Thanks!

**Comment by RohanMishra315** [comment]
yeah sure , go on .

**Comment by FurquanAnwer** [comment]
If no one's working, please assign this issue to me!

**Comment by vmatsiiako** [comment]
Hi @FurquanAnwer! It seems like noone is working on this yet. Assigning to you. Thank you for contributing!

**Comment by mitdonga** [comment]
Hi, @FurquanAnwer are you working on this issue?

**Comment by vmatsiiako** [comment]
Hi @mitdonga! I believe noone is working on this yet.

**Comment by mitdonga** [comment]
Can I work on this issue? @vmatsiiako

**Comment by Salman2301** [comment]
I am interested to work on this.
