### ISSUE TITLE
Secret referencing not working through Terraform provider

### ISSUE THREAD

**Issue by abdalem** [Infisical/infisical#1277]
### Describe the bug
Hi everyone. Secret referencing is not working through the Terraform provider (see screenshot below).

### To Reproduce
1. Create a secret reference in the Dashboard
2. Implement a Terraform workflow where you output this secret

### Expected behavior
The referencing should be parsed and replaced as it is through the CLI (see screenshot below).

#### Value through Terraform output
![Value through Terraform output](https://github.com/Infisical/infisical/assets/19971392/64ca3f9a-c624-4792-a0d2-beace7e01b52)

#### Value through CLI
![image](https://github.com/Infisical/infisical/assets/19971392/d76ffcc8-d23b-45e8-8168-17127bb5af8d)

### Platform you are having the issue on:
Terraform Provider

## EDIT
After investigation it seems that when the referencing is straight without any concatenation, it's working, but when you want to concatenate with multple referencing or with a string, it's not.
Example:
- `${AUTH0_ISSUER}` => ✅ OK
- `https://${AUTH0_DOMAIN}` => ❌ KO

**Comment by vmatsiiako** [comment]
This indeed has not been implemented for Terraform yet. We will work on this soon.

**Comment by abdalem** [comment]
## Edit

@vmatsiiako It seems to works when there is no concatenation. Example:
- `${SOME_OTHER_SECRET}` => ✅ OK
- `anything${SOME_OTHER_SECRET}` => ❌ KO

**Comment by vmatsiiako** [comment]
@maidul98 should be able to comment on this

**Comment by maidul98** [comment]
@abdalem Terraform provider does not have any logic in it to handle secret referencing. We will aim to add support for this in the coming sprint

**Comment by abdalem** [comment]
@maidul98 So it's pure luck that secrets without concatenation work ? Many devs uses terraform, for me it's more a bug than a feature request, as nowhere in the docs it's stated that secrets referencing does not work through terraform, so as a devops, it should work same way as in dev environnement.

**Comment by jithenms** [comment]
> @abdalem Terraform provider does not have any logic in it to handle secret referencing. We will aim to add support for this in the coming sprint

Hey @maidul98  started a PR for this. Still a WIP but was able to successfully test it with a local instance: https://github.com/Infisical/terraform-provider-infisical/pull/30.
