### ISSUE TITLE
[docs] Secret reminders and secret override option

### ISSUE THREAD

**Issue by xevolic** [Infisical/infisical#1287]
### Feature description

I noticed (on free, fresh, cloud account) that I cannot set a **Secret reminder** for the secrets, which have **Override** option on. 

Can you **clarify** why is it working like that?
https://infisical.com/docs/documentation/platform/project#personal-overrides

### Why would it be useful?

I would like to know how Infisical works **in details** :)

### Additional context

none

**Comment by maidul98** [comment]
cc @DanielHougaard

**Comment by DanielHougaard** [comment]
Hi @xevolic

Thank you for the heads up. I've added a small section to the documentation page you linked to let the user know that secret reminders aren't compatible with personal overrides.
