### ISSUE TITLE
[Secret reminders] Multiple mails sent when set two or more days

### ISSUE THREAD

**Issue by xevolic** [Infisical/infisical#1288]
### Describe the bug

At first I set 7-day repetition to check if mails are sent every 7 days.
That worked good.

Then I set 3-day repetition to check if mails will be sent every 3 days.

Unfortunately I got mails:
- every 7 days
- and every 3 days.

I also noticed that **mails were sent not only to me**, but also to other users in our organization, which is strange.

### To Reproduce

Steps to reproduce the behavior: I think above description is enough and I don't need to describe it again.

### Expected behavior

Only current settings should be taken into consideration.

### Screenshots

![Screenshot 2024-01-08 at 13-39-36 Poczta — Tomasz Kuter — Outlook,2](https://github.com/Infisical/infisical/assets/111504995/8e97dc00-f7b0-497e-8e2e-260ec29f4c90)

### Platform you are having the issue on:

Pro version.

### Additional context

We deleted our account in previous week.

**Comment by maidul98** [comment]
cc: @DanielHougaard

**Comment by DanielHougaard** [comment]
Hi @xevolic, you're right! There's indeed an issue with how we handle reminder updates. I've just raised a PR to resolve this. Thank you for bringing this to our attention!
