### ISSUE TITLE
[Secret reminders] Removing existing reminder

### ISSUE THREAD

**Issue by xevolic** [Infisical/infisical#1290]
### Feature description

It is good to have Secret reminder option, but also it would be nice to be able to remove it.
I could set 1000-day loop to not receive mails from the wrong configuration, but such workaround doesn't seem good.

### Why would it be useful?

Secret reminder feature without possibility to remove them is incomplete.

I suggest to add red button to Update secret reminder window and then, if you click on it you would need to type `confirm`
and that is all.

Update secret reminder:
![Update-existing-Reminder](https://github.com/Infisical/infisical/assets/111504995/29ae8321-f68c-4885-8997-a901f1b9d4b3)

### Additional context

Related issue: https://github.com/Infisical/infisical/issues/1289

**Comment by maidul98** [comment]
You should be able to remove the reminder if you click on the clock icon on the secret again.

cc: @DanielHougaard

**Comment by DanielHougaard** [comment]
Hi! Removing secret reminders is already implemented. I've attached a video that showcases how this is done :-)

https://github.com/Infisical/infisical/assets/62331820/f852df65-c6cd-4aae-b194-fb2856801ac6

**Comment by akhilmhdh** [comment]
Closing as this is completed
