### ISSUE TITLE
Allow `infisical export` to sort variables alphabetically

### ISSUE THREAD

**Issue by chronark** [Infisical/infisical#1292]
### Feature description
A flag or default behavior for the CLI to export variables sorted alphabetically.

### Why would it be useful?
Often we have multiple "grouped" variables, such as stripe products`STRIPE_PRODUCT_ID_XXX` or database connection credentials `DATABASE_HOST`, `DATABASE_USERNAME`, `DATABASE_PASSWORD`.

It's hard to find them in a `.env` file with 30+ variables if they're in seemingly random order.

Sorting them by name would automatically group them. It's probably not perfect for 100% usecases, but definitely a lot of them.

**Comment by jithenms** [comment]
Interested in tackling this! Can I be assigned to work on it? Thanks!

**Comment by jithenms** [comment]
@vmatsiiako opened a PR for this last night. Would appreciate a look thanks!

**Comment by xevolic** [comment]
Why do you need such feature?

I noticed that Infisical returns secrets in random order, but it is quite easy to fix.

In Linux you can use following command:
```
infisical export --telemetry=false --domain=$VAULT_URL/api --token=$TOKEN_MAIN --env=$ENV_MAIN | sort > .env.$APP_ENV.local
```

which creates `.env` file with sorted secrets.

**Comment by chronark** [comment]
Mainly cause I didn't think of piping it to sort, that's a good solution.

I still think offering it as part of the cli is a nice dx improvement.

**Comment by JC-ironman** [comment]
it would be really cool that export also sort by tag, Like if I have secrets with "database" tag, it export like:

```
# DATABASE 
SECRET_ONE=
SECRET_TWO

OTHER_SECRET=
OTHER_SECRET_2=
```
