### ISSUE TITLE
Bitbucket Integration for self hosted not working

### ISSUE THREAD

**Issue by Rajeev-2001** [Infisical/infisical#1297]
![image](https://github.com/Infisical/infisical/assets/86216823/0d5056a5-8ca4-450c-860c-f01a5117b4cd)

**Comment by dangtony98** [comment]
Hi @Rajeev-2001,

I suspect that you are missing the `CLIENT_ID_BITBUCKET` and `CLIENT_SECRET_BITBUCKET` environment variables for your self-hosted instance to get this integration working; you can obtain the values for these variables by setting up an OAuth application in Bitbucket.

Also, next time please use the issue template to provide additional context about the issue at hand.

**Comment by Rajeev-2001** [comment]
I have added the CLIENT_ID_BITBUCKET and CLIENT_SECRET_BITBUCKET.

I have tried with GitHub, it works but for bitbucket it does not.

**Comment by Rajeev-2001** [comment]
{"level":50,"time":1704881098477,"pid":1,"hostname":"83272b10c1ec","severity":"ERROR","msg":{"_logLevel":50,"_logName":"ERROR","statusCode":500,"type":"internal_server_error","context":{"exception":"Request failed with status code 400"},"extra":[],"stacktrace":["AxiosError: Request failed with status code 400","    at settle (/backend/node_modules/axios/dist/node/axios.cjs:1913:12)","    at IncomingMessage.handleStreamEnd (/backend/node_modules/axios/dist/node/axios.cjs:3008:11)","    at IncomingMessage.emit (node:events:525:35)","    at IncomingMessage.emit (node:domain:489:12)","    at endReadableNT (node:internal/streams/readable:1358:12)","    at processTicksAndRejections (node:internal/process/task_queues:83:21)"]}}


this is the error stack I am geting 
@dangtony98

**Comment by Rajeev-2001** [comment]
![image](https://github.com/Infisical/infisical/assets/86216823/cac154b4-7a81-4c6f-9251-fb0621a06438)
here you can see that i have given both required env variables in the docker container.

**Comment by Rajeev-2001** [comment]
http://localhost/integrations/bitbucket/oauth2/callback

this my call back url set in bitbucket.
Let me know if i need to change anything here.

**Comment by Rajeev-2001** [comment]
@dangtony98 is anyone working on this please let me know.
