### ISSUE TITLE
Persist unsaved secret state in secrets overview page

### ISSUE THREAD

**Issue by jithenms** [Infisical/infisical#1306]
### Describe the bug
Currently, if I close the accordion for each secret in the secrets overview page it loses the state of the unsaved changes. 

### To Reproduce
1. Go to the secrets overview page
2. Toggle open an existing secret
3. Modify it without saving
4. Close the accordion
5. Open it again and the unsaved changes are lost. 

### Expected behavior
A user goes to the secrets overview page, toggles open an existing secret, modifies it without saving it and closes the accordion, then decides to come back to toggle that secret once again but the unsaved changes were not lost. This is not applicable if the user decides to refresh the page.

### Additional context

<img width="1792" alt="Screenshot 2024-01-15 at 11 27 51 AM" src="https://github.com/Infisical/infisical/assets/67240543/dd55c833-9ce8-4318-8cda-b6bf539bb7be">

I'm willing to submit a PR

**Comment by maidul98** [comment]
@jithenms All changes to secrets should be intentional and having the user confirm their changes is a way to achieve that. Auto saving changes may cause changes to occur that were not indented.

**Comment by jithenms** [comment]
@maidul98 got it that makes sense in this context. On a follow up note, would it be fair to say that the state for unsaved changes to a secret should be persisted through a toggle of the accordion? Or at least prompt the user that they have unsaved changes if they try to close the accordion? Currently, if I close the accordion for each secret it loses the state of the unsaved changes. It's occurred to me where I've closed the accordion without saving a secret and then toggled it again and the state is lost.

<img width="1792" alt="Screenshot 2024-01-15 at 2 18 08 PM" src="https://github.com/Infisical/infisical/assets/67240543/49b967bf-b735-440d-a902-69fae6c74452">

**Comment by jithenms** [comment]
@maidul98 updated the issue with the follow up thought I had let me know if you think that's something work taking a look at. Thanks!

**Comment by maidul98** [comment]
If a user modifies content and does not save these modifications, they should receive a standard popup message warning them that their unsaved changes will be lost.
