### ISSUE TITLE
.NET integration

### ISSUE THREAD

**Issue by gbro3n** [Infisical/infisical#131]
### Feature description
An integration with .NET's configuration tooling would be great to see.

### Why would it be useful?
There's a lot of .NET projects out there that could benefit from this.

**Comment by mv-turtle** [comment]
Infisical mostly likely supports .NET in its current form. We just don't have the docs for it yet. We need to test it out, and I will get back to you.

**Comment by jon4hz** [comment]
That's definitely possible and .NETs [ConfigurationBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbuilder?view=dotnet-plat-ext-7.0) makes it fairly easy.

```c#
public IConfigurationRoot ConfigureConfiguration()
{
    var builder = new ConfigurationBuilder()
        .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
        .AddEnvironmentVariables();
    return builder.Build();
}
```

**Comment by mv-turtle** [comment]
Oh interesting! This makes sense - I haven't found the time to test it out and write the docs yet (not very familiar with .NET) :(

@jon4hz If you're interested in helping with this, that would be so amazing 🙏 No pressure though!

**Comment by jon4hz** [comment]
Well I'm no expert on .NET either, I just recently started learning c#. :) 
But yeah sure, what would you need for the docs? The snipped I posted should be more or less everything that's needed to parse the environment variables.

**Comment by mv-turtle** [comment]
Kinda like [this](https://infisical.com/docs/integrations/frameworks/nextjs). First step is going to be the same, and then you just need to run the start command and see if environment variables are inserted :)

The frameworks are [here](https://github.com/Infisical/infisical/tree/main/docs/integrations/frameworks).

**Comment by mv-turtle** [comment]
@gbro3n @gerwim here are the instructions for how to use Infisical with .NET: https://infisical.com/docs/integrations/frameworks/dotnet

Let us know if you have any questions
