### ISSUE TITLE
Railway Integration issue

### ISSUE THREAD

**Issue by thawankeane** [Infisical/infisical#1310]
### Describe the bug
When connecting to a Railway project, the "Railway Service" selection should be optional

### To Reproduce
1. Go to "Integrations"
2. Click on "Railway" item at the "Cloud Integrations" section
3. Input your Railway API Key
4. Click on "Connect" button

### Expected behavior
For the last select (Railway Service), the dropdown should be optional if you don't want to point the integration for a single service only, but there are no option to unselect it

### Screenshots
![image](https://github.com/Infisical/infisical/assets/26743815/7bfd846c-a112-41af-8c15-616796b1af8e)

### Platform you are having the issue on:
Railway

**Comment by abdulhakkeempa** [comment]
Hi @vmatsiiako, I want to work on this issue. Can you assign it to me?
