### ISSUE TITLE
JSON environment files for SAM lambdas support

### ISSUE THREAD

**Issue by bennytaccardi** [Infisical/infisical#1317]
### Feature description
Support to JSON environment files like those used by SAM 

### Why would it be useful?

Infisical could be used also on Lambda function projects. If you think to a monorepo project, we could found a variety of different "typology" of projects. One of those could be lambda functions handled by SAM

### Addition context

JSON format env files of these kind are as following
```
{
    "Func1": {
        "Param1": "val1",
        "Param2": "val2",
    },
    
    "Func2": {
        "Param1": "val1",
        "Param2": "val2",
    }
}

```

**Comment by vmatsiiako** [comment]
Hi @bennytaccardi! You can already add such JSON files to Infisical secret values (multiline string), and then reformat it to JSON. Would this work for you use case?

**Comment by bennytaccardi** [comment]
> Hi @bennytaccardi! You can already add such JSON files to Infisical secret values (multiline string), and then reformat it to JSON. Would this work for you use case?

Yes. It works. I have to apply some workarounds or little adjustments, but it works. Thank you. I'm going to close this issue
