### ISSUE TITLE
Allow infisical export to sort variables by tags

### ISSUE THREAD

**Issue by JC-ironman** [Infisical/infisical#1320]
### Feature description
it would be nice that export regroupe secrets by tags. Like if I have secrets with "database" tag, it export like:

```
# DATABASE 
SECRET_ONE=
SECRET_TWO=

OTHER_SECRET=
OTHER_SECRET_2=
```

**Comment by Salman2301** [comment]
@JC-ironman How would like to handle if there is multiple tags assigned to them?
Something like this?

```
# TAG_1, TAG2, TAG_3
SEC_1=

# TAG_1
SEC_2=

#TAG_3
SEC_3=


SEC_4=
SEC_5=
SEC_6=
```

**Comment by Salman2301** [comment]
I would like to contribute on this.

**Comment by JC-ironman** [comment]
@Salman2301 

Yeah ! That seems great !
