### ISSUE TITLE
Secrets with the same name are not properly synced with the AWS Parameter Store

### ISSUE THREAD

**Issue by ikovac** [Infisical/infisical#1322]
### Describe the bug
I have 2 folders within my project and those 2 folders have some secrets with the same name.
I added 2 integrations with AWS Parameter Store, one for each folder. For the first one secrets are synced with AWS Parameter Store, but for the second integration, only secrets that don’t have the same name as the previously synced ones from the other folder.

### To Reproduce
- Infisical project structure:
```
folderA
 subfolderA
   - secret1: value1
   - secret2: value2
folderB
  subfolderB
   - secret1: value3
   - secret3: value
```
- First integration is for `folderA/subfolderA` secret path in Infisical and AWS Parameter store path is `/server/dev/`
- The second integration is for `folderB/subfolderB` secret path in Infisical and AWS Parameter store path is `/frontend/dev/`
- From the first integration, all secrets are synced to the AWS Parameter Store, but from the second integration, only `secret3` is synced. The `secret1` from the `folderB` is not synced with AWS Parameter Store

### Expected behavior
All secrets should be synced to the AWS Parameter Store under the corresponding namespace.

### Platform you are having the issue on: 
AWS Parameter Store integration

### Additional context

**Update:** 
I am not sure have you already started to work on this issue, but now, it seems that two secrets with the same name are properly synced to the AWS Parameter Store, but still not all secrets are synced. Maybe the bug is not even related to secret naming, maybe is just a bug in secret syncing because there is a huge delay between two syncs (18 Dec and 23 Jan for the same integration).

**Comment by akhilmhdh** [comment]
Hey @ikovac can you test now and let me know if your still having this issue

**Comment by ikovac** [comment]
It seems that it works now, thanks! 🙌
