### ISSUE TITLE
Add universal search across all secrets

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#133]
### Feature description
A search bar at the top of the screen that lets a user browse through the secrets in all projects/environments

### Why would it be useful?
Sometimes, it can get annoying for people to browse through different projects to find that one secret. This will make the navigation much much easier

### Additional context
This will require both frontend and backend changes.

**Comment by unkletayo** [comment]
Hi @vmatsiiako I would love to take this up, if it is available

**Comment by unkletayo** [comment]
Yes @vmatsiiako I checked it out and I'm interested

**Comment by kirinnee** [comment]
Hi, is this feature confirmed to be `wontfix` ? I would love to have this feature as the the problem statement fits what I am experiencing

**Comment by akhilmhdh** [comment]
Closing as completed

**Comment by kirinnee** [comment]
i have upgrade to 0.96.1, how do i access this feature?

**Comment by maidul98** [comment]
Once you start to search, you will see a button to search all folders like so:

<img width="691" alt="CleanShot 2024-11-30 at 22 17 03@2x" src="https://github.com/user-attachments/assets/ba69594d-2100-44fe-b21c-4838a64b854d">

**Comment by akhilmhdh** [comment]
@kirinnee it's on project level
