### ISSUE TITLE
What is the way to reference secret with dot inside name, like `.htpasswd` 

### ISSUE THREAD

**Issue by istarkov** [Infisical/infisical#1331]
### Feature description
Some variable keys contains special symbols like dot, / etc
How I can reference variable with dot inside?

`${dev..htpasswd}` is not working
`${dev.\.htpasswd}` same

### Why would it be useful?

Some secrets for easy of use has keys with dots, keys like urls etc. Would be good to have ability to reference them like any other vars.

**Comment by maidul98** [comment]
cc: @akhilmhdh

**Comment by rawkode** [comment]
It would be nice to see an option to replace `.` as the folder differentiator and instead use `/`.

In my mono repository, I was using the domains as directory names, such as `rawkode.academy` and this meant I couldn't replicate that structure within Infisical.

**Comment by akhilmhdh** [comment]
@istarkov @rawkode Good one.  Changing the path name or differentiator is good choice but may be making it too complex. 

We will introduce escape string so that u can put dot as needed in references.

**Comment by vtmocanu** [comment]
Just came across this one as well, i have a secret named config.json and would like to reference it, has anyone found a workaround?
