### ISSUE TITLE
Integration with GitLab CI/CD

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#134]
### Feature description
Inject Infisical variables/secrets into GitLab CI/CD variable automatically every time you update secrets in the dashboard.

### Why would it be useful?
It will save developers a lot of time and reduce room for errors.

### Additional context
This feature should not be very complicated given the new integrations structure - although there are some interesting parts to figure out. Reach out to tony@infisical.com if you have any questions.

**Comment by devblin** [comment]
Hey @mv-turtle I would like to contribute on this integration.

**Comment by mv-turtle** [comment]
@devblin thank you so much! That would be amazing! Do you need any help understanding the code base? I’d be happy to walk you through :)

**Comment by devblin** [comment]
@mv-turtle I will check through the codebase and let you know, when I face any issue 😄 .

**Comment by devblin** [comment]
@mv-turtle If I am correct, the GitLab API endpoint required for this integratiom should be: https://docs.gitlab.com/ee/api/instance_level_ci_variables.html ?

**Comment by mv-turtle** [comment]
@devblin  Actually, I just talked to @maidul98 and he told me that he already did this integration - he just needs to release it. Sorry for the confusion... 

Would you maybe be willing to help with some other integration? Two of the very requested ones are AWS Parameter Store and GCP Secret Manager. What do you think?

**Comment by devblin** [comment]
@mv-turtle I think I can work on GCP secret manager integration.

**Comment by mv-turtle** [comment]
@devblin thank you! I created this issue :) Feel free to assign it to yourself if you want

**Comment by devblin** [comment]
@mv-turtle Thank you 🙌🏽

**Comment by maidul98** [comment]
https://infisical.com/docs/integrations/cicd/gitlab
