### ISSUE TITLE
Add comments to secrets

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#135]
### Feature description
In traditional .env files, it is possible to add comments that explain certain things about environment variables. It would be amazing if Infisical had something like 'comments/notes' that can be attached to every environment variable. 

### Why would it be useful?
Sometime people want to add reminders or explanations to certain environment variables.

### Additional context
This would require both frontend and backend work

**Comment by naorpeled** [comment]
Hey @mv-turtle 
would like to work on this task 🙏

**Comment by dangtony98** [comment]
@naorpeled Go for it 🙂

Also do join our [Slack community](https://infisical-users.slack.com/ssb/redirect)! 

We'd be happy to chat more about Infisical and contributions there; we also do initial pairing sessions to get more familiar with the codebase if you want 🙂

**Comment by naorpeled** [comment]
> @naorpeled Go for it 🙂
> 
> Also do join our [Slack community](https://infisical-users.slack.com/ssb/redirect)! 
> 
> We'd be happy to chat more about Infisical and contributions there; we also do initial pairing sessions to get more familiar with the codebase if you want 🙂
> 

Will do!
And awesome, would love to, see you there ✌️

**Comment by mv-turtle** [comment]
@naorpeled this is SO needed! Thank you so much! Yeah, [join our Slack](https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g), and we can set up a quick pairing session to help you get into the codebase :)

**Comment by mv-turtle** [comment]
Btw, we have a branch ([dashboard-sidebar](https://github.com/Infisical/infisical/tree/dashboard-sidebar)) where I'm changing how Dashboard looks like a little bit. Yesterday, I have created a quick potential design for comments. Let me know what you think :)

Feel free to work from this branch if you want 

https://user-images.githubusercontent.com/78047717/209339451-d8aeb693-bf36-422f-9a1d-a3913faa1817.mov
