### ISSUE TITLE
Intergration failed with Azure key vault

### ISSUE THREAD

**Issue by akfmdl** [Infisical/infisical#1358]
### Describe the bug
* Installed self-hosted server using helm chart in my cluster. Chart version: 0.4.2(https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/)
* After launching it, i tried to integrate my project with Azure Key Vault. but failed

### To Reproduce
* if i click the button, it shows an error message(AADSTS700016: Application with identifier 'undefined' was not found in the directory '...'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.)

### Screenshots
![image](https://github.com/Infisical/infisical/assets/31917080/b739886a-3a3e-4d40-9285-a46d68d98093)
![image](https://github.com/Infisical/infisical/assets/31917080/4ee8bd5a-8f70-4d41-be9a-25a0b4f61a5c)

### Additional context
redirect url from azure: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=undefined&response_type=code&redirect_uri=http://.../integrations/azure-key-vault/oauth2/callback&response_mode=query&scope=https://vault.azure.net/.default%20openid%20offline_access&state=1a58866d8641c8f76f58f096bb7c7e22

**Comment by akhilmhdh** [comment]
Hey @akfmdl when your self hosting you need to provide the environment variables for azure app cred. That will be

```
CLIENT_ID_AZURE
CLIENT_SECRET_AZURE

```
