### ISSUE TITLE
Token `/**` path does not wotk with CLI if it's referenced as `--path=api`

### ISSUE THREAD

**Issue by maielo** [Infisical/infisical#1370]
### Describe the bug
We should be able to create a token that has access to the whole monorepo (folders) and not add each folder to the token access path. Right now we can not edit the token so we need to re-create ~n + 1 projects, which is really annoying as monorepo grows and token is required to be run on CI

### To Reproduce
1. Create a new token with `/**` path
2. Use CLI to access some folder inside of that path (monorepo style) 
```
infisical run --path=api --token=st.xxxxxxxxxxx --env=dev --domain="https://domain.com/api" -- nx serve api
```
4. throws error:
```
error: CallGetSecretsV3: Request to access secrets with [environment=dev] [path=api] [workspaceId=xxxxxxxxxxx] is denied. Please check if your authentication method has access to the requested scope
```

### Expected behavior
To be able to serve the `/api` folder to the `nx` command

### Screenshots

![image](https://github.com/Infisical/infisical/assets/8983870/11c5ec0d-28e8-41a9-850f-a5327e1421af)

### Platform you are having the issue on:
- windows

**Comment by akhilmhdh** [comment]
Can you change the path in your command from `path=api` to `path=/api`

**Comment by maielo** [comment]
Tried. Doesn't work:

```
error: CallGetSecretsV3: Request to access secrets with [environment=dev] [path=C:/Programs/Git/api] [workspaceId=xxxx] is denied. Please check if your authentication method has access to requested scope
```
