### ISSUE TITLE
Docker container not running despite the token succesfully injested

### ISSUE THREAD

**Issue by dubem2** [Infisical/infisical#1376]
I am running a container on ubuntu, I have successfully integrated the service token and i can see the token populated when i inspect the container. The issue is the container keeps restarted and when i checked the container logs i got this:

`It looks you have not yet connected this project to Infisical
To do so, run [infisical init] then run your command again`

I have a github action file that exports the token and runs a bash script thus

`export INFISICAL_TOKEN_FOR_API=${{ secrets.INFISICAL_TOKEN_FOR_API }}`

`sudo INFISICAL_TOKEN_FOR_API=${INFISICAL_TOKEN_FOR_API} bash deploy-dev.sh`

the content of the deploy-dev.sh bash script being run by the workflow is as follows:

```
`#!/bin/bash

git pull origin secrets-management-test --no-ff --no-edit

docker compose -f docker-compose-dev.yml up -d --build --remove-orphans

exit`
```
How do i resolve this issue stated above? Any assistance or pointers will be very much appreciated

**Comment by akhilmhdh** [comment]
Its INFISICAL_TOKEN not INFISICAL_TOKEN_FOR_API

**Comment by dubem2** [comment]
thank you

**Comment by dubem2** [comment]
i

**Comment by dubem2** [comment]
it worked, thank you
