### ISSUE TITLE
API access to secrets

### ISSUE THREAD

**Issue by ppawlak** [Infisical/infisical#138]
### Feature description
It would be great to be able to retrieve secrets programmatically through an HTTP API.

### Why would it be useful?
It would offer endless integration possibilities and the ability to configure a project without using env vars.

### Additional context
On a similar product, HashiCorp Vault, I used the HVAC python library to retrieve secrets in my project and this is really handy.
Libraries for popular languages is a plus on this feature request.

**Comment by maidul98** [comment]
This is a great suggestion as it would increase the use case of Infisical. I'll make sure this gets prioritized, thank you for the request!

**Comment by dangtony98** [comment]
Hey guys! @ppawlak @Zamion101 

We're using [Mintlify](https://mintlify.com) for Infisical's docs atm — content contained in `/docs` automatically updates the production docs; should be pretty easy to get going.

You'll want to first add a new [anchor](https://mintlify.com/docs/settings/versioning#anchors) called API.

Then for reference for the docs, check out how MindsDB documents their REST API [here](https://docs.mindsdb.com/rest/databases/list-databases) with Mintlify; it'd be awesome if we can do it in a similar style for Infisical's API docs 😁

**Comment by mv-turtle** [comment]
@ppawlak the public API is now available :)
You can find the docs for it here: https://infisical.com/docs/api-reference/overview/introduction

Please let me know if you have any questions!

**Comment by ppawlak** [comment]
> @ppawlak the public API is now available :) You can find the docs for it here: https://infisical.com/docs/api-reference/overview/introduction
> 
> Please let me know if you have any questions!

Thanks a lot! I'll check it out as soon as possible.
