### ISSUE TITLE
Envfile with drag & drop cuts values with # char

### ISSUE THREAD

**Issue by meska** [Infisical/infisical#1382]
### Describe the bug
After creating a new project, I utilize drag and drop to import an .env file. One of the values contains a '#' character, which gets cut off. However, I'm able to modify the value later through the web interface.

Latest docker self hosted version as today.

Other notes:
- Would be nice to see the version somewhere in the web app.
- Python Sdk demands "project_id" but It's not clearly visible in the web app, I got it from the url of the project in the address bar
- Python Sdk: asking for list secret raises "Exception: Secret with name '' not found." but it get fixed if I remove end 2 end encryption ( not easy to spot )
- Probably End 2 End encryption should not be enabled by default

**Comment by akhilmhdh** [comment]
| Would be nice to see the version somewhere in the web app.

Its on your sidebar. Left bottom

**Comment by akhilmhdh** [comment]
CC: @DanielHougaard 

Context: Feedback on python sdk

**Comment by meska** [comment]
> | Would be nice to see the version somewhere in the web app.
> 
> Its on your sidebar. Left bottom

there isn't in the latest docker image

<img width="410" alt="image" src="https://github.com/Infisical/infisical/assets/276923/3b313e68-9737-4e66-ae25-cc611c2e74e3">

**Comment by akhilmhdh** [comment]
hey @meska Regarding the version tag its inside the help and support inside sidebar

**Comment by meska** [comment]
> hey @meska Regarding the version tag its inside the help and support inside sidebar

when I click help and support appears only 4 links

<img width="275" alt="image" src="https://github.com/Infisical/infisical/assets/276923/354b558b-d8cb-496d-b534-8228b7e4e800">

**Comment by rhythmbhiwani** [comment]
As I checked, the version is visible from the environment variable `NEXT_PUBLIC_INFISICAL_PLATFORM_VERSION`. That might not be set during deployment

**Comment by maidul98** [comment]
You may have a older version. On newer version, you check like so:

<img width="326" alt="Screenshot 2024-03-01 at 4 39 29 PM" src="https://github.com/Infisical/infisical/assets/9300960/6290b6c0-ca25-4dae-bcfe-3fdd20fa4b01">

Are you using Mongo or Postgres version of Infisical

**Comment by Ponnada96** [comment]
I would like to work on this issue. Could you please assign it to me?
