### ISSUE TITLE
Secret Sync to Grafbase

### ISSUE THREAD

**Issue by rawkode** [Infisical/infisical#1386]
### Feature description
I would like to sync secrets to Grafbase environment variables

### Why would it be useful?
Grafbase is a GraphQL service that allows a developer to provide a single API that federates to subgraphs/APIs.

Each project with Grafbase needs environment variables, and I want mine to live in Infisical and sync.

### Additional context
https://api.grafbase.com/graphql

Instropection is enabled, but you need an access token.

```gql
mutation {
  environmentVariableCreate(input:{projectId: "", name: "", value: ""}) {}
  environmentVariableUpdate(input:{projectId: "", name: "", value: ""}) {}
  environmentVariableDelete(input:{projectId: "", name: "", value: ""}) {}
}
```

**Comment by abdulhakkeempa** [comment]
Hey @akhilmhdh, can I work on this issue?

**Comment by rawkode** [comment]
> This page is down for me https://api.grafbase.com/graphql

Are you sure it's down? Are you using an API token? The instrospection requires an API token.

**Comment by Salman2301** [comment]
Will take a look again. Will update it once :)
