### ISSUE TITLE
Cancel button on create API model doesn't work

### ISSUE THREAD

**Issue by dewhurstwill** [Infisical/infisical#1399]
### To Reproduce
1. Go to Personal Settings > API Keys
2. Click on Add API Key
3. Click Cancel

### Expected behavior
Model closes

### Screenshots
![image](https://github.com/Infisical/infisical/assets/34936646/daa694d1-2f94-4659-bc5c-0d55a2f1b0fc)

### Platform you are having the issue on:
Windows 10
Microsoft Edge Version 121.0.2277.98 (Official build) (64-bit)

**Comment by abdulhakkeempa** [comment]
Hey @maidul98, I would like to work on this issue. Can you assign me this?

**Comment by DanielHougaard** [comment]
Hi @dewhurstwill and @abdulhakkeempa, I just confirmed that it's indeed an issue.

@abdulhakkeempa Thank you! I've just assigned you the issue.

**Comment by akhilmhdh** [comment]
Closing as completed
