### ISSUE TITLE
The REDIS_URL is missing in the .env file content provided in the Local Development Documentation.

### ISSUE THREAD

**Issue by abdulhakkeempa** [Infisical/infisical#1407]
### Describe the bug
While setting up the Local Development Server, it was observed that the `REDIS_URL` was missing in the `.env` file content provided at [https://infisical.com/docs/contributing/platform/developing](https://infisical.com/docs/contributing/platform/developing). However, `REDIS_URL` is mentioned as a required field at [https://infisical.com/docs/self-hosting/configuration/envars](https://infisical.com/docs/self-hosting/configuration/envars).

As a result, running the Docker containers will lead to an error, due to the missing of `REDIS_URL`.

### To Reproduce
1. Go to [https://infisical.com/docs/contributing/platform/developing](https://infisical.com/docs/contributing/platform/developing)
2. Copy the .env file content provided there.
3. Paste the content in the `.env` in the project.
4. Run the docker containers.
5. Inspect the server logs.

### Expected behavior
An application that functions properly and correctly loads the sign-up page.

### Screenshots
![image](https://github.com/Infisical/infisical/assets/92361680/14690dad-1df3-4677-835f-6ce2c3cee91d)

**Comment by akhilmhdh** [comment]
hey @abdulhakkeempa Given the document is on context of local development with docker compose the compose file already contains the redis document, that's why redis url is not passed. 

The `.env.example` mentioned on docker based deployment contains the redis url. So everything is working as expected. 

Thus i am closing this issue.

**Comment by akhilmhdh** [comment]
Haha good catch my bad. We haven't released the updated doc yet. I guess until then we can keep this issue open

**Comment by akhilmhdh** [comment]
Closing as its fixed
