### ISSUE TITLE
Unable to delete token 

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#141]
### Describe the bug
When i click the X to delete a token i have created, it does nothing.

### To Reproduce
Create a token and then try to delete it

**Comment by Zamion101** [comment]
Which token are you referring to? Secret Tokens or Service Tokens?

If you referring to Service Tokens looks like no logic implemented for deleting Service Tokens _**yet**_.
![image](https://user-images.githubusercontent.com/8071263/208796010-dda5ae59-72f4-4e02-b4a9-a571d81f5eff.png)

**Comment by mv-turtle** [comment]
Yes @Zamion101, we need to develop the backend and then attach it to frontend! I think it shouldn't be complicated, we just forgot to do it :)

**Comment by Zamion101** [comment]
Yeah, it only needs to be checked for proper permissions and then removed from mongodb. It's easy to implement. Will look while working on #138 .

**Comment by mv-turtle** [comment]
This has recently been fixed
