### ISSUE TITLE
Error expanding a secret with another nested reference in another folder

### ISSUE THREAD

**Issue by Cristobal-M** [Infisical/infisical#1410]
### Describe the bug
With the cli, when exporting a secret from a path, for example `/team1/app-abc` and there is a referenced secret in another folder which has another reference in their value, like `another-app.${BASE_DOMAIN}`. The cli gives an error
> error: Could not find refered secret -  BASE_DOMAIN

### To Reproduce
1. Create folder `app-a` in dev
2. Inside `app-a` create two secrets: `BASE_DOMAIN=test.com` and `APP_URL=https://a.${BASE_DOMAIN}`
3. Create folder `app-b` in dev
4. Inside `app-b` create a secret: `APP_A_URL=${dev.app-a.APP_URL}`
5. Using infisical cli and a service-token with permissions for both folders run an export of path `/app-b`
6. Fails with error: Could not find refered secret -  BASE_DOMAIN

### Expected behavior
Successfull ouput of secret `APP_A_URL` expanded

### Screenshots

![app-a folder](https://github.com/Infisical/infisical/assets/9591194/070ce9d6-314c-4589-bb8b-4e78f7ace57e)
![app-b folder](https://github.com/Infisical/infisical/assets/9591194/d34070d8-791c-49c6-a382-3b0ec973e1e0)

![failure](https://github.com/Infisical/infisical/assets/9591194/742ae0d8-e0d9-4cfe-b733-bf2f61c8774a)

### Platform you are having the issue on:
Ubuntu 23.10
Infisical cli 0.16.10
### Additional context
I guess this should be an unexpected behaviour. But I get it's due to an attempt to resolve the first-level reference in `app-a` in the context of `app-b`. So as a workaround I'm using full paths if I expect a secret will be referenced and it has references itself, like `APP_URL=htps://app-a.${dev.app-a.BASE_DOMAIN}`

**Comment by akhilmhdh** [comment]
Yah this is expected because the one level reference means from the same board. Here the ${BASE_DOMAIN} will be picked to resolve with respect to app-b and its not found. 

This is like using relative path and absolute path way. The way to. have changed would be the right way for references that cross references on reference board with relative way
