### ISSUE TITLE
Add input validation for text field

### ISSUE THREAD

**Issue by teyim** [Infisical/infisical#1421]
### Describe the bug
Input fields allow users to input very lengthy strings, causing the UI of the application to break

### To Reproduce
- input very long text when adding new name and organisation name on signup or project name in user dashboard

### Expected behavior
The input validation should restrict the number of characters I put in the input field.

### Screenshots
![Screenshot from 2024-02-18 16-38-16](https://github.com/Infisical/infisical/assets/48864977/218932aa-431b-4501-9e61-ac96c1532feb)

### Platform you are having the issue on:
Infisical webapp

**Comment by tanvirraj** [comment]
@akhilmhdh, you can assign it to me, 
- add a context what you guys think max length

**Comment by teyim** [comment]
i was thinking 16 characters would be good.

**Comment by vmatsiiako** [comment]
16 characters is probably too little. I would think 64?

**Comment by Salman2301** [comment]
@tanvirraj opened a PR that partial fix this issue. If you are still busy with input validation let me know. Or I can add the validation on the above mention PR together
cc: @vmatsiiako

**Comment by tanvirraj** [comment]
hey @Salman2301, i will do this in my next weekend

**Comment by Salman2301** [comment]
@vmatsiiako this can be closed
