### ISSUE TITLE
[Integration] CI/CD: Woodpecker

### ISSUE THREAD

**Issue by pat-s** [Infisical/infisical#1423]
[Woodpecker CI](https://woodpecker-ci.org/) is a FOSS CI/CD engine forked from Drone CI a few years ago.

Would be great to have an official Infisical integration for it!

(I am among the maintainers team of Woodpecker. Happy to contribute and help getting the integration up and running)

**Comment by Salman2301** [comment]
The documentation looks solid. So, we can sync secrets either [globally](https://woodpecker-ci.org/api#tag/Secrets) or [repo](https://woodpecker-ci.org/api#tag/Repository-secrets) based?. Will be a nice addition indeed.

**Comment by pat-s** [comment]
Globally (available for all user), org-wide and repo-wide. Each user has its own "private" org.
