### ISSUE TITLE
Sign In with Google

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#143]
### Feature description
With a 'Sign In with Google Option', the signup flow would consist of 2 steps:
- Sign in with Google
- Enter your password (this will be used for encrypting your secrets, so that Google doesn’t have access to them)

instead of 3 steps right now:
- Enter your email
- Go to your email, copy the code, verify that your email is correct
- Enter Name/Lastname/Password

### Why would it be useful?
This will make sign ups into Infisical SOOO much easier

### Additional context
This basically is basically called [decoupling of authentication and decryption](https://bitwarden.com/help/using-sso/), as BitWarden calls it.

**Comment by Adeee11** [comment]
Hi @mv-turtle Can I take this issue ?

**Comment by mv-turtle** [comment]
Hi @Adeee11! That would be awesome! Do you need any help to understand the codebase? If you want, I'm happy to set a quick call to answer any of your questions. 

Also, please join our Slack for contributors and users: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

**Comment by Adeee11** [comment]
Hi @mv-turtle I was able to run the dev environment locally and went throught the codebase as well . I have also joined the slack community. For now I believe I can start working on the issue . If I face any problem in the codebase I would get back to you to schedule a quick call and discuss it.

**Comment by mv-turtle** [comment]
Sounds good! Thank you so much for your help!

**Comment by mv-turtle** [comment]
Hey @Adeee11! I was wondering if you had any time to look into this? :)

**Comment by sreehari2003** [comment]
> Hey @Adeee11! I was wondering if you had any time to look into this? :)

if @Adeee11  is not working on this can I and @DarkPhoenix2704 together work on this ? 

@mv-turtle

**Comment by mv-turtle** [comment]
@sreehari2003 Absolutely! This is so needed! Appreciate your help A LOT!

Please join our Slack for contributors so that we an answer any of your questions very quickly :)
Here is the link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

**Comment by sreehari2003** [comment]
> @sreehari2003 Absolutely! This is so needed! Appreciate your help A LOT!
> 
> Please join our Slack for contributors so that we can answer any of your questions very quickly :) Here is the link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g
> 
> Also, do you need any help understanding the code base? I would be happy to set up a quick call

we will be using googleapis
step1
user click on button
step 2
redirect to google auth page and save the user email and name to db and redirect back to frontend auth page with a queru string   
step 3
we will send the query string back to server for verfication and server will send a jwt token back 
during the verification process we will show a screen showing "logging you in" with loader or something like that

**Comment by ThejanNim** [comment]
Hey @vmatsiiako, Is this still there?

**Comment by vmatsiiako** [comment]
Hi @ThejanNim! This has actually been implemented already.
