### ISSUE TITLE
Error: [Bad request]: Bot is not active

### ISSUE THREAD

**Issue by michealroberts** [Infisical/infisical#1431]
### Describe the bug

After setting up the InvisicalClient from the node sdk, I receive the following error:

```
Error: [Bad request]: Bot is not active
```

I have ensured that the project is setup, the environment is correct and that I have delegated access via Machine Identities, and hooked these up to the project.

The documentation is rather sparse and lapse, and there doesn't seem to be any support as to how to navigate this issue (searching the docs yielded no results, and a quick search of current open and closed issues also yielded no luck).

Unfortunately, I therefore do not know what this means.

### Expected behavior

Should be able to get, list etc on the InvisicalClient, but currently can't.

### Screenshots

<img width="603" alt="CleanShot 2024-02-21 at 15 06 11@2x" src="https://github.com/Infisical/infisical/assets/84131395/870f7d31-f3bd-4cf6-a133-ce73b0fcf6b3">

**Comment by maidul98** [comment]
@michealroberts please go to your Infisical project setting and uncheck `End-to-end encryption` then try again

**Comment by michealroberts** [comment]
@maidul98 Seems to have fixed it.
