### ISSUE TITLE
Access Control member search returns empty if search term has uppercase letters

### ISSUE THREAD

**Issue by snokpok** [Infisical/infisical#1434]
### Describe the bug
Making a search with an uppercase letter returns an empty result list in any Access Control pages (Organization and Project).

### To Reproduce
1. Go to either Project's or Organization's Access Control
2. Make a search with all lowercase letters
3. You should see matches
4. Now make the same search but with one or more capitalized letters
5. You should see no matches at all

### Expected behavior
Searches should be case-insensitive; searches with capitalized letters should have matches, not an empty list.

### Screenshots
![Screenshot 2024-02-21 at 10 01 22 PM](https://github.com/Infisical/infisical/assets/64177421/c2882ff4-9a47-4a05-8825-28ffc1837c6a)
but this matches:
![Screenshot 2024-02-21 at 10 01 47 PM](https://github.com/Infisical/infisical/assets/64177421/4c4b2eca-c455-427c-a41e-7e8a96cef0a2)

### Platform you are having the issue on:
Web, MacOS, on Chromium browser.

### Additional context
Open to send in a PR.

**Comment by Nithishvb** [comment]
Hi @akhilmhdh , I would like to work on this bug, could you please assign this to me?
