### ISSUE TITLE
Move secret referencing logic to Rest API 

### ISSUE THREAD

**Issue by Salman2301** [Infisical/infisical#1459]
Infisical [secret reference](https://infisical.com/docs/documentation/platform/secret-reference) is one of the cool feature but only available on CLI and Native Integration(bot). I think instead of repeating logic to parse the secret reference on different SDKs or Rust Binary which is need. We can move the logic to the Rest API and add a query param or path to request the expanded secrets `/secrets?expand_secret=true` to provide the backward compatibility. This way we can don't have to rewrite the same logic on different language or platforms. I would say make the Backend Rest API as a primary 

### Additional context
- ExpandSecrets
For ex: `recursivelyExpandSecret` function is repeated across the code base

  - [Backend Logic written in JS](https://github.com/Infisical/infisical/blob/92d237a714f1914439fedb0142099b4f1f1ae9ea/backend/src/services/secret/secret-fns.ts#L74)
  - [Cli login written in GO](https://github.com/Infisical/infisical/blob/92d237a714f1914439fedb0142099b4f1f1ae9ea/cli/packages/util/secrets.go#L342) 
  - [K8 operator written in GO](https://github.com/Infisical/infisical/blob/92d237a714f1914439fedb0142099b4f1f1ae9ea/k8-operator/packages/util/secrets.go#L268)

**Comment by Salman2301** [comment]
Same with `export` command all this CLI features should be implemented in the Rest API backend and pass it as  a request params. So, we will have the same response in both SDKs and CLI.

**Comment by akhilmhdh** [comment]
@Salman2301 The recursively logic was kept like at time of e2ee. We are still evaluating about this change in our roadmap due to changes we will be introducing regarding encryption

**Comment by rawkode** [comment]
The referencing and importing not working via the CLI and SDK's is rather frustrating at the moment, so subscribing to stay up to date with any resolution :)

**Comment by akhilmhdh** [comment]
@rawkode Secret referencing and import works in CLI. Just tested it out

**Comment by rawkode** [comment]
Not with `infisical export`

**Comment by akhilmhdh** [comment]
Secret referencing is now present in server logic. 

Regarding the cli supporting it. Its in review state.
