### ISSUE TITLE
Add deeper organizational structure for secrets

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#148]
### Feature description
Some users have pointed out that our secrets right now are just grouped by environment and split into shared/personal. It would be awesome to have a more advanced organizational structure (e.g., you can put secrets into smaller groups). One idea that I had was to add tags (e.g., #mongo, #stripe, #auth, #encryption). Then people can choose to view secrets by these groups + we can make a more advanced search that allows users to filter by tags.

Feel free to propose any other ideas is anyone wants to take this issue :)

### Why would it be useful?
This will just make it SO MUCH EASIER to navigate for people.

### Additional context
This would require both frontend and backend

**Comment by Zamion101** [comment]
Will the tags be persistent between environments or will they be confined within environment? 

For example:
In environment `dev`, I have `MONGO_HOST`, `MONGO_USER` and `MONGO_PASSWORD` and all of them under the group named `Mongo Credentials` with tag `#mongo`. Will I be able to see/access outside of `dev`?

**Comment by Zamion101** [comment]
> Maybe there is a button that says 'add this tag to all environments'

It's can be convenient if you want to add to all environments but not if you just want to duplicate to another environment. 

What about we just group the secrets? I mean like we can add button alongside `+ Add key` saying `+ Create Group` and drag and drop existing secrets inside of the group and also add `+ Add Key` button to right side of the group which will add key inside of the group. With that we can also add `Transfer to...`, `Duplicate to...` and `Make Shared/Personal` with dropdown?

But to be able to do that we need to refactorr some of the backend API and logics.

**Comment by mv-turtle** [comment]
We actually had drag and drop secrets at some point, and we decided to roll back to the static approach because of performance issues when you have 100+ drag and droppable secrets

Also, I think the groups would be great, but I'm afraid the interface will get very cluttered. How would you organize both groups and personal/shared secrets?

**Comment by Zamion101** [comment]
What is the purpose of `Personal Secrets`. I mean if developer is using Infisical to manage Secrets for it's projects, won't be the Personal Secrets eventually shown to the other people working on the project? Or those people who have access to production build? I'm bit confused with the division between `Personal` and `Shared`. If there is no major difference we can just combine them into one and make it grouping priority.

**Comment by mv-turtle** [comment]
Personal secrets are used for secrets like DB_URL - because every developer has their own version of this secret

**Comment by Zamion101** [comment]
Oh, I get it now. If this the only usage of it rather than using `Personal Secrets` what about we change it to `Override` or something like that? With that it will be more understandable to new comers like me 😄. If we do that we don't need to add group to `Override` section so it will be better of UI/UX.

**Comment by jon4hz** [comment]
I would love to able to tag secrets. 

Another use case for this would be to add a `tagSelector` to the k8s operator. This would allow a more fine-tuned control about what secrets will be deployed by an `InfisicalSecret` on Kubernetes.

**Comment by Aubermean** [comment]
@vmatsiiako is there any way to filter by tags with the Kubernetes Operator?
