### ISSUE TITLE
Add imagePullSecrets to deployments to allow private authenticated registries

### ISSUE THREAD

**Issue by corvusmod** [Infisical/infisical#1525]
### Feature description
It's a common and good practice to copy external images to internal registries to avoid deployment problems if external images are not available. In that case, internal registries usually have authentication, so the imagePullSecrets value must be defined in the helm chart to set these credentials.

### Why would it be useful?
Described above. Good practices

**Comment by vmatsiiako** [comment]
Hi @corvusmod @alvaroReina! Thank you for creating the issue and submitting the PR. This has just been merged!
