### ISSUE TITLE
[Feature] Secret Templates by Users

### ISSUE THREAD

**Issue by Zamion101** [Infisical/infisical#154]
### Feature description
Easy to use Secret templates. You can import templates from published templates or import using template id. Some of the use cases of Infisical is to distribute environment variables.

### Why would it be useful?
For example some Discord bot needs to know lots of environment variables to function properly. Developers will create `.env.example` file with examples of Environment variables. With this feature they only need only need to give template link in order to set up environment variables. It can also encourage more and more developers to use Infisical for their existing and/or upcoming projects as their Secure Secret Manager.

I would like to get your opinions on this feature.

**Comment by mv-turtle** [comment]
I personally really like this idea! This could be a great growth strategy because many developers will get familiar with Infisical this way. 

I think we can also cooperate with many open-source projects to add Infisical as an option - especially as we start getting more trust 🚀

**Comment by imakecodes** [comment]
What about adding a flag on CLI?

`infisical export --env dev --example`

The output:

```
MY_VAR=
ANOTHER_VAR=
```
