### ISSUE TITLE
Auto Complete Secret References During Creation

### ISSUE THREAD

**Issue by rawkode** [Infisical/infisical#1540]
### Feature description
Just like Doppler, it would be awesome if when we do `${` that we can auto-complete our way to the path we require.

### Why would it be useful?
I keep getting the names wrong, I'm sure others do too.

**Comment by Salman2301** [comment]
I would like to work on this

**Comment by rhythmbhiwani** [comment]
Hey @Salman2301 , actually I have already started on it, and it's partially done. I will be able to showcase it by end of next week

**Comment by Salman2301** [comment]
My bad... had started working on it... got few things working so far... Not sure if i should continue or abort.
@rhythmbhiwani 
<img width="1268" alt="Screenshot 2024-03-14 at 7 46 26 PM" src="https://github.com/Infisical/infisical/assets/40920317/73895458-56bd-4a64-94fd-5098e7787b2e">

**Comment by rhythmbhiwani** [comment]
this looks good, please go on, I'll add up to your code

**Comment by Salman2301** [comment]
#1572

**Comment by Salman2301** [comment]
Would like something for secret path too. Will add that feature, if the above PR get merged.

**Comment by maidul98** [comment]
This feature has been merged in and is now in prod.
