### ISSUE TITLE
REST API where to get workspace id

### ISSUE THREAD

**Issue by justinkumpe** [Infisical/infisical#1554]
I am trying to use REST API (self-hosted) to get secret data usign the Retrieve endpoint. Where do I find my workspaceId?

**Comment by vmatsiiako** [comment]
Hi Justin! The workspaceId is actually equivalent to the projectId. You can find it in the project setting or in the project URL.

**Comment by justinkumpe** [comment]
Thanks. It is not in the project settings but getting it from URL is easy enough.
