### ISSUE TITLE
Add ability to paste in dotenv style strings (single and multiline)

### ISSUE THREAD

**Issue by ericallam** [Infisical/infisical#1573]
### Feature description

Sometimes I want to add some env vars from a local `.env` file to infisical and I'd like to be able to just copy them and paste them into the dashboard and have them imported into a project. Should work with multiline strings as well.

### Why would it be useful?

Currently the only option is to upload an entire .env file, which is not what I want. I'd rather not have to create a whole to `.env` file with just the env vars that I want, to do bulk importing. Without this, I have to add env vars 1 by 1.

### Additional context

Would also be nice to be able to paste in a `KEY=value` string into the New Secret form and have it parsed out into both fields. Currently if pasting that into the name field it will uppercase everthing into `KEY=VALUE`, making it impossible to then copy out the value from that field and paste it into the value field.

**Comment by maidul98** [comment]
Great feature request

**Comment by maidul98** [comment]
@ericallam you can turn off auto caps in the project settings by the way

**Comment by Salman2301** [comment]
This is interesting... We can have a "Paste from .env" user can just paste the both the key and value in a text area field. And we can parse multiple envs with value. Also, can save the comments.
Would like to work on it.
