### ISSUE TITLE
UI - Space between action buttons on the confirmation modal

### ISSUE THREAD

**Issue by magnobiet** [Infisical/infisical#1579]
### Describe the bug

The action buttons of the modal to confirm upload or overwrite secrets are without space between them.

### To Reproduce

1. Go to 'https://app.infisical.com/project/:guid/secrets/:env'
2. Drag a `.env` file into the drop zone
3. See error

### Expected behavior

Add a small space between the buttons.

Maybe add a `flex gap-2` on `<CardFooter>` at `frontend/src/components/v2/Modal/Modal.tsx`:

https://github.com/Infisical/infisical/blob/56fc5a2a8c7fbdc674f2bc7bb5693d718d971dea/frontend/src/components/v2/Modal/Modal.tsx#L38

```diff
- {footerContent && <CardFooter>{footerContent}</CardFooter>} 
+ {footerContent && <CardFooter className="flex gap-2">{footerContent}</CardFooter>} 
```

Or, add a wrapper with `flex gap-2` on `footerContent` at `frontend/src/views/SecretMainPage/components/SecretDropzone/SecretDropzone.tsx`

https://github.com/Infisical/infisical/blob/56fc5a2a8c7fbdc674f2bc7bb5693d718d971dea/frontend/src/views/SecretMainPage/components/SecretDropzone/SecretDropzone.tsx#L315-L334

### Screenshots

| Confirmation | Duplicate secrets |
| - | - |
| ![Screenshot_2024-03-16_at_16_08_43](https://github.com/Infisical/infisical/assets/1743501/e4aa04aa-f621-43fc-8847-c2a2deadb6e9) | ![Screenshot_2024-03-16_at_16_00_47](https://github.com/Infisical/infisical/assets/1743501/87d29fd0-fa95-48fd-a482-91a9f1172bc4)  |

### Platform you are having the issue on:

https://app.infisical.com/

**Comment by kavinda1995** [comment]
@magnobiet  I can work on this issue if anyone else is not working currently
