### ISSUE TITLE
Github Integration is not syncing multiline secrets properly

### ISSUE THREAD

**Issue by billyovo** [Infisical/infisical#1581]
### Describe the bug
Syncing multiline secret with Github Integration is not working properly. The secret will become one line on Github's side after synced, but on Infisical side both GUI and CLI export are working properly.

### To Reproduce
1. Create a multiline secret
2. Enable sync with Github Integration
3. Try to get the line count within an action (since github will redact the secret print). For example:
```
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
run: echo "$SSH_PRIVATE_KEY" | wc -l
```
4. If sync using Github Integration, the output will be 1, but manually inputting the secret using Github GUI shows the correct line count.

### Expected behavior
Should keep and handle multiline secret correctly.

### Screenshots
These are tested with the same secret

Without Github Integration:
![image](https://github.com/Infisical/infisical/assets/30436689/a881b9a7-0f53-4d9d-85ca-a3bed5be83ec)
With Github Integration
![image](https://github.com/Infisical/infisical/assets/30436689/83729895-bc00-4af5-9f4e-38e9b9865ffd)

### Platform you are having the issue on:
Github

**Comment by fpapadamis** [comment]
I am also facing the same issue. Hope it gets fixed soon.

**Comment by maidul98** [comment]
@akhilmhdh can you please have a look at this

**Comment by akhilmhdh** [comment]
@billyovo @fpapadamis You need to toggle ON the `skipMultiLineEncoding` option inside secret details which you can get clicking the `More` icon in secret row in dashboard

**Comment by billyovo** [comment]
Thanks! It works after toggling off this option. It might not be the most intuitive so a small note on the github integration documentation page might help.

![image](https://github.com/Infisical/infisical/assets/30436689/786106f9-f033-4bcb-ac2b-85e0b5777ff0)

**Comment by fpapadamis** [comment]
Hello @akhilmhdh, @billyovo. I run a self-hosted instance of Infisical and I cannot find the option you mention.

**Comment by akhilmhdh** [comment]
@fpapadamis 

![Screenshot 2024-05-15 at 7 24 54 PM](https://github.com/Infisical/infisical/assets/31166322/d7c1ce3f-4575-4ca1-bca1-df9d5dd5d991)

![Screenshot 2024-05-15 at 7 24 25 PM](https://github.com/Infisical/infisical/assets/31166322/bb55aa32-303f-40b3-a40d-b5cc037f676f)
