### ISSUE TITLE
Environment slug bug when set to "overview"

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#1585]
### Describe the bug 🪲

When setting the environment slug to `overview`, it'll overlap with the secret overview page in the URL.

When navigating through "clicks" switching pages works great in-app, but when copy/pasting the URL or just by refreshing you'll always end up on the secret overview page and not on the correct environment page with the `overview` slug

### To Reproduce 💻

1. Go to `https://app.infisical.com/project/<project-id>/settings`
2. In the "Environment" section, edit/create an environment (e.g. `foo`) with the `overview` slug
3. Go back to the secret overview page and "explore" the `foo` environment (`https://app.infisical.com/project/<project-id>/secrets/overview`) 
5. See the same URL as the page just before
6. Refresh and see the error, you'll get back to the overview page

### Expected behavior 🔎

A project's environment URL should always lead you to the correct page. Some slugs should be reserved keywords or another logic should be implemented.

E.g. refactoring the overview path to `https://app.infisical.com/project/<project-id>/overview` and keeping the trailing `.../secrets/` for environment slugs:

- `https://app.infisical.com/project/<project-id>/overview`
- `https://app.infisical.com/project/<project-id>/secrets/<env-slug>`

This could prevent this bug

### Screenshots 🎨

![env-slug](https://github.com/Infisical/infisical/assets/72856427/d6adb7c8-942c-4384-b384-a53912e4c2d7)

### Platform you are having the issue on

Infisical Cloud + self-hosted

**Comment by Ponnada96** [comment]
Hi @akhilmhdh , I would like to work on this issue. Could you please assign it to me?
