### ISSUE TITLE
Edit key name in the secret details drawer

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#1586]
### Describe the bug 🪲

When opening a secret details (right drawer, "`...`"), I cant change the key name is that expected?

### To Reproduce 💻

1. Go to `https://app.infisical.com/project/<project-id>/secrets/<env>`
2. Click on any "`...`" (three dots) on any secret row
3. Try to edit the key name

### Expected behavior 🔎

Being able to edit the key name/value from the main environment page + in the secret details' drawer

### Screenshots 🎨

![secrets-right-drawer](https://github.com/Infisical/infisical/assets/72856427/ca4c950d-5439-4cf7-9926-d88a8a7a5338)

### Platform you are having the issue on:

Infisical Cloud + self-hosted

**Comment by akhilmhdh** [comment]
@Grraahaam yes its expected. The detail sidebar is saying that changes your seeing is based on above key
