### ISSUE TITLE
Dashboard org and user settings layout improvements (UI/UX)

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#1588]
### Improvement description 🎨

I find the organization + user settings on the left top corner a bit too tight together and IMO there's too much actions in a too small area..

1. We could either (non-exhaustive list):
    - rethink the org/user settings buttons/dropdown layout as suggested in the attached schema (commonly seen)
    - E.g. that's how github does for example, org/repo on the left and user on the right (attached screenshot)
    - or combine both org + user settings in the same dropdown with a section for both of them

2. Same thing once on the secret overview page, there's an additional "back" arrow `<-` prefixing the org name, making the area even smaller, I don't think it's necessary here since we have the navigation breadcrumb just next to it allowing the user to return to the org overview easily

3. I think we shouldn't show the "Log out" option under the org's dropdown as you log out from your account not from the org, right?

---

#### Suggestion

![image](https://github.com/Infisical/infisical/assets/72856427/1b21fbe5-06af-4a99-b81b-e2a23909b002)

#### Github layout

![image](https://github.com/Infisical/infisical/assets/72856427/3f78fbf8-fffd-474f-aac1-9f2efa26300c)

### Why would it be useful?

- improve the UX
- reduce the org name overflow when it's a bit too long
- being able to add most popular setting pages/sections in the dropdown
- adapt the layout to what we commonly see around the web (common design, easier to find common actions)

**Comment by the2MinEngineer** [comment]
Hi @Grraahaam, can this be assigned to me to work on?

**Comment by vmatsiiako** [comment]
Hi @the2MinEngineer! I think we will be working on a much larger update to UX, so it might not make sense to work on this yet. Do you want to take a look at some other issues?

**Comment by the2MinEngineer** [comment]
@vmatsiiako thank you for clarifying. I would like to take a look at some other issues please. Do you have any you would like me to specifically check out?
