### ISSUE TITLE
Make service token string easy to distinguish by including environment name in token string

### ISSUE THREAD

**Issue by drtobbyas** [Infisical/infisical#1598]
### Feature description
Make the service token string to be easily distinguishable by including the environment name in the token string. 

This will be very helpful especially when you have many tokens for different environments for a project. By looking at the token, it should be clear which environment that token was generated for. 

I have been using Doppler for a long time and trying to migrate to Infisical because of it's open-source advantages. This feature is correctly implemented in Doppler. For instance, below are some examples of how Doppler token looks, 

dp.st.dev.0CDSp6ifAxrlZd91AS9pDJwJJTYUIJytuigKKKGGht

dp.st.prd.sjeisjKUiejdiKKieksijukRmeisjiLwOkwkiwiujdU

You would agree with me that it is easy to know which token is for what environment by looking at the third segment of the token string for the environment name. 

### Why would it be useful?

This will make it easy to know which token to use (copy and paste) for the environment you are targeting without doing some trial and error with tokens. This will also help mitigate running your application against the wrong environment when debugging or troubleshooting an issue. For instance, a good use case would be when an issue is raised from the business line (Production) and you can't replicate the issue on your staging deployment. The next step would be to pull your production code (in my team, we use telepresence to connect to Kubernetes) and run the production code on local with production config to troubleshoot. Not knowing or forgetting which token to use for production can result in futile troubleshooting efforts or undesirable results.

### Additional context

**Another issue, I don't know if I should create a new thread for this**
1. The service token seems to be too long in my personal opinion and experience with other services. I don't know the rationale for the long string and I haven't looked at the codebase thoroughly to know which function or library is used to generate the service token but If uniqueness is an important factor. I think the nanoid library can generate a good unique string with less than 40 characters which would suffice.
2. The environment should default to the environment the token was created for instead of defaulting to 'dev'. This will eradicate the need to always manually add '--env' to `Infisical run` command. As long as you use the correct service token, your application should run with the token environment by default. This is helpful in cases where you have defined a `start` script in your package.json. You would only want to export your Infisical token and run `yarn start` to run your application in whatever the service token environment you exported is for. Instead of defining different `start` script for the different environment and figuring how to decide which of the 'start' script to invoke based on the environment.
3. When `infisical run` command is run, the output should also include the project name, this will help to confirm you are running the correct service token for the right project. Mix-up of service tokens might occur especially when you have many service tokens for different project, it will be good to know which project the service token belongs to.

BTW, I'm open to contribute Pull Request to this effect if needed.

**Comment by akhilmhdh** [comment]
Hey @drtobbyas 

We cannot change the service token at present moment because it would break our backward compatibility. Another important concern is we are moving away from service token to machine identity. Ofcourse we will still support it for another couple more quarters.

Regarding your 2nd issue, it depends. If your service token is single scoped and doesn't have a glob pattern attached in secret path scope, it will automatically take that environment. We cannot set it default dev as any user can edit the environments as needed. 

3. Indeed a good suggestion, if your open to contribute feel free to raise a PR

**Comment by drtobbyas** [comment]
Thanks, @akhilmhdh for the reply. 
Since you have commented that there is a plan to move away from the service token use, I don't think there is any need to drag discussions on that again. 

For the 2nd issue, I'm having a different experience from what you just described. Attached is a screenshot of the error I'm getting
![image](https://github.com/Infisical/infisical/assets/40923477/26fb4aae-96cb-4282-988a-0dc64f433b1c)

Here are some steps to reproduce the error. 
1. Create a project in infisical cloud dashboard
2. Add `NODE_ENV` as a secret with values development, staging or production corresponding to the different environments
3. Create a service token for each of the environment (i.e development, staging, production)
4. Create a mini express app with a console.log statement to output `NODE_ENV`
5. Export development environment service token and use `infisical run` to launch the app (This should work fine and you should see NODE_ENV value in the console)
6. Shutdown app process
7. Export staging environment service token and use `infisical run` to launch the app once again (This is where the error in the screenshot comes into place)

**Comment by akhilmhdh** [comment]
Closing as we are depreciating service token.
