### ISSUE TITLE
Fall back to Cache when internet/server is unavailable

### ISSUE THREAD

**Issue by drtobbyas** [Infisical/infisical#1609]
### Feature description
Fallback to cache when request to fetch config fails due to network issue or server downtime. 

There should be a mechanism to ensure Infisical is always able to fetch config even when the network is unstable or Infisical Cloud/self-hosted server is unavailable. One method by which I believe this can be achieved is by maintaining a cache of config for previously fetched responses so that Infisical can fall back to it when it's unable to reach the remote server next time. 

### Why would this feature be useful for Infisical users? 
This will greatly improve the availability of the application being run and the efficiency of Infisical eradicating the need to outrightly shut down the process whenever it can not fetch config. 

This feature is available in Doppler, here is a screenshot
![Screenshot from 2024-03-19 12-57-31](https://github.com/Infisical/infisical/assets/40923477/1b2d6372-9484-4768-a149-9254c9fec62b)

**Comment by akhilmhdh** [comment]
Closing as we now save secrets for offline access. The secrets are saved to keyring of the system as backup.
