### ISSUE TITLE
Support TOTP secrets engine

### ISSUE THREAD

**Issue by ali-master** [Infisical/infisical#1613]
### Feature description
Hi there

Is there any plan to support the TOTP secrets engine like the [Hashicorp Vault ](https://developer.hashicorp.com/vault/docs/secrets/totp) feature?
### Why would it be useful?
It help the Backend developers manage the users' TOTP codes by the Infisical without managing themselves

**Comment by akhilmhdh** [comment]
Not sure TOTP is in our roadmap yet.  May be in coming quarter.  @dangtony98 may have some insights over this
