### ISSUE TITLE
Copy to clipboard does not work (self-hosted)

### ISSUE THREAD

**Issue by petr-tuma-im** [Infisical/infisical#1635]
### Describe the bug
None of the buttons that are supposed to copy data to clipboard work. It doesn't matter if I'm trying to copy secret or trying to copy the slug / id in Project settings.

The GUI just pops up message "Failed to copy secret to clipboard", backend container does not log anything. Fails silently in Project settings page.

### To Reproduce
1. Deploy self-hosted instance (I used slightly modified example compose file)
2. Login to GUI
3. Try copy-to-clipboard anywhere (I tested with Vivaldi and Firefox browser).

### Expected behavior
Data being copied to clipboard.

### Screenshots
None.

### Platform you are having the issue on:
Self-hosted Infisical, official images, latest tag. Fedora 39 on my PC, both Vivaldi and Firefox are up to date.

### Additional context
None.

**Comment by akhilmhdh** [comment]
@petr-tuma-im You may have disabled the navigator for your browser. I just tested it in all major browsers and it works

**Comment by petr-tuma-im** [comment]
> @petr-tuma-im You may have disabled the navigator for your browser. I just tested it in all major browsers and it works

I have no idea what the **navigator** is and I don't think I disabled it, perhaps it is something distros disable in browsers by default.

On the other hand, I retested all browsers I have available (Vivaldi, Chromium, Firefox) and copy to clipboard doesn't work in any of them (I definitely did not touch sort of settings in Chromium and Firefox).

**Comment by akhilmhdh** [comment]
Navigator is the browser api called which we use to copy the value from the browser to your system keyboard.

Your not getting any server logs because this is something happening from your browsers , as the os which is fedora here is blocking it in permission.

>  for security reasons, this API is blocked by default in Fedora browsers.

If you need to use the navigator.clipboard API in a Fedora browser, you will need to enable it manually. To do this, follow these steps:

    Open the browser settings.
    Navigate to the "Privacy & Security" section.
    Scroll down to the "Permissions" section.
    Click on the "Clipboard" permission.
    Select the "Allow" option.
    Close the browser settings.

**Comment by petr-tuma-im** [comment]
Only browser where I've been able to find this particular setting is Vivaldi. I have enabled clipboard globally there, but the issue still persists. I did not find such setting neither in Firefox nor in Chromium.

Still, this seems like Infisical issue to me, because other pages that offer copy-to-clipboard functionality (e.g. github.com) work normally (i.e. I do have project URL in clipboard after I click the button).

**Comment by petr-tuma-im** [comment]
> @petr-tuma-im Are you using https on your self hosted instance? I'm pretty sure clipboard wont work if you're on http

If such is the case, where is this mentioned in docs? I don't see it mentioned anywhere.

Not to mention that I just redeployed testing pod with SSL terminating nginx proxy and it breaks Infisical completely (I don't see any secrets in the system anymore, nor can I create any new). Only good news is that copy to clipboard does seem to work now (tried it on project settings page and it works).

**Comment by petr-tuma-im** [comment]
All works.
