### ISSUE TITLE
Offline functionality not working as expected

### ISSUE THREAD

**Issue by polyphilz** [Infisical/infisical#1639]
### Describe the bug

https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1710355498164669 for context; Maidul believes recent changes may have broken offline functionality.

When the Infisical CLI runs, it doesn't appear to be saving keys in Keychain as when I turn off wifi and run it again, it doesn't run my app.

### To Reproduce

1. Run `infisical run -- ...`
2. Turn off wifi
3. Try it again; confirm offline functionality not working

### Expected behavior

Offline functionality should work and the passwords should save to Keychain

**Comment by parshva-b** [comment]
I would love to work on this issue, any pointers that can assist me here?

**Comment by Patchouli-Kenntnis** [comment]
Hello, I'm a newcomer here, it will be nice if someone can assist me to solve this issue

**Comment by sheensantoscapadngan** [comment]
yea this is done @akhilmhdh 

just awaiting on Maidul's approval

**Comment by sheensantoscapadngan** [comment]
here's the PR https://github.com/Infisical/infisical/pull/1757
