### ISSUE TITLE
Unable to use Service Token via Docker Compose (Self-Hosted)

### ISSUE THREAD

**Issue by JenangMaker** [Infisical/infisical#1641]
### Describe the bug
Unable to use Service Token on selfhosted infisical instance. Using service token with dev and path / always works, but using sub folder (eg. /subfolder) or other environemt (Staging or Production) doesnt work

### To Reproduce
1. Deploy self-hosted instance via given docker-compose (image set to latest-postgres) and also with currently deployed next js app also in docker self-hosted
2. Set-up user admin
3. Create a project
4a. Create Secret env dev only subfolder with secret, insert service token via docker compose env, doesnt work
Server Log
`2024/04/02 11:43AM 50 pid=1 hostname=5a29c819eb9e reqId=req-9 severity=ERROR err={"type":"UnauthorizedError","message":"You are not allowed to access this resource","stack":"UnauthorizedError: You are not allowed to access this resource\n    at Object.fnValidateServiceToken (file:///backend/dist/services/service-token/service-token-service.mjs:107:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.<anonymous> (file:///backend/dist/server/plugins/auth/inject-identity.mjs:103:30)","name":"UnauthorizedError"} msg=You are not allowed to access this resource
2024/04/02 11:43AM 30 pid=1 hostname=5a29c819eb9e reqId=req-9 severity=INFO res={"statusCode":403} responseTime=7.997210994362831 msg=request completed`
App Log
`error: CallGetSecretsV3: Request to access secrets with [environment=dev] [path=/] [workspaceId=cc4a7116-9866-495b-8e06-415e797fed7c] is denied. Please check if your authentication method has access to requested scope
If this issue continues, get support at https://infisical.com/slack
Could not fetch secrets`
4b. Create Secret with staging or production also doesnt work, same response and log

### Expected behavior
Properly injected secret on designated app.

### Screenshots
![image](https://github.com/Infisical/infisical/assets/33830006/a01f62ef-d461-40cc-a780-f0155ebb6e7b).
![image](https://github.com/Infisical/infisical/assets/33830006/4458ab5e-be7f-4254-a6a1-a1c91fc1f4e9)

### Platform you are having the issue on:
Selfhosted - Docker Compose

### Additional context
The currently used app for injecting secret is NextJS via Docker (already followed the instruction for modify the Dockerfile)
Example Docker file
`
...
RUN apk add --no-cache bash curl && curl -1sLf \
'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash \
&& apk add infisical
...
CMD ["infisical", "run", "--", "node", "server.js"]
`
Example Docker Compose
`
sample_app:
    image: sample_app
    container_name: sample_app
    restart: unless-stopped
    ports:
      - "8014:3000"
    environment:
      INFISICAL_TOKEN: 'TOKEN_WAS_HERE'
      INFISICAL_API_URL: http://selfhosted_app.url/api
`

**Comment by akhilmhdh** [comment]
@JenangMaker have you gave the required scopes to the token

**Comment by maidul98** [comment]
Does your service token have access to this pat: `[environment=dev] [path=/] [workspaceId=cc4a7116-9866-495b-8e06-415e797fed7c] `?

**Comment by JenangMaker** [comment]
> Does your service token have access to this pat: `[environment=dev] [path=/] [workspaceId=cc4a7116-9866-495b-8e06-415e797fed7c] `?

the current setting is 
path set to /test and env set to dev like this
![image](https://github.com/Infisical/infisical/assets/33830006/828659ba-b549-41dd-84a5-44dd42cf1c15)

But turns out I nedd to slightly modify the Dockerfile entrypoint or cmd from this
![image](https://github.com/Infisical/infisical/assets/33830006/cb88f9fd-b36c-42a8-952d-4a0f75afe5b4)
to this
![image](https://github.com/Infisical/infisical/assets/33830006/25697da2-a398-472b-9ed9-4ab2d27fb75e)
Because the CLI the documentation said I need to add additional param such as --path and --env then I added those param using inside dockerfile with docker env to dynamically changed it whenever i needed. Previously i thought i only need just token and the infisical backend automatically parsed the token to its path and environtment

Maybe there is a need for adding more documentation on Dockerfile to accommodate custom path and env, not just using INFISICAL_TOKEN
