### ISSUE TITLE
Minor frontend issues on the infisical.com site

### ISSUE THREAD

**Issue by JunedKhan101** [Infisical/infisical#1662]
### Describe the bug
I believe you guys have redesigned the infisical.com site and I noticed some minor issues

For example:
1. Site is showing a horiozontal scrollbar
2. Signup text button and Infisical brand name is being cut off on 100% default zoom (see screenshot below)

### Screenshots
![image](https://github.com/Infisical/infisical/assets/47941768/afbb978b-f1b4-4512-b209-03c22fe533c0)

### Platform you are having the issue on:
Tested on Chrome, Brave, Firefox

Also where is the dark mode? Are you guys in the process of redesigning the site? This seems like a downgrade from the old site or maybe I'm missing something...in that case feel free to close this issue 😀

**Comment by DanielHougaard** [comment]
Thank you! We'll look into this.

@vmatsiiako, seems like the new front page has a few issues. Could you look into this? Thanks!

**Comment by vmatsiiako** [comment]
Hi @JunedKhan101! Thank you for letting me know. Would you mind sharing your screen dimensions?

**Comment by JunedKhan101** [comment]
Hi @vmatsiiako! My screen resolution is 1536 x 864
I just checked myself, I'm able to reproduce the issue in chrome inspector with these dimensions.

**Comment by akhilmhdh** [comment]
@vmatsiiako Did we fix this?
