### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by servernoj** [Infisical/infisical#1665]
Path: /documentation/guides/node

The guide does not clarify how to point SDK to use a specific deployment of Infisical (cloud vs. self-hosted). There are a few references to the use of `token`, e.g., via providing `accessToken` in https://infisical.com/docs/sdks/languages/node#parameters, but the overall process doesn't look gapless.

**Comment by akhilmhdh** [comment]
Closing as parameters contains the description and example does provide it clearly
