### ISSUE TITLE
Extra whitespace in error message

### ISSUE THREAD

**Issue by JunedKhan101** [Infisical/infisical#1667]
### Describe the bug
 There is an extra white space in error message when your login fails via `infisical login`

### To Reproduce
1. Run `infisical login`
2. Deliberately type wrong credentials
3. See the extra whitespace in the error message

### Expected behavior
There shouldn't be any extra whitespace

### Screenshots
![Screenshot 2024-04-07 041635](https://github.com/Infisical/infisical/assets/47941768/5192816c-a840-4331-a9aa-8cf0cd70ebce)

### Platform you are having the issue on:
Issue is platform not dependent.

I'm willing to submit a PR, It seems like the message is coming from response of v3/auth/login1 however I don't know how the response itself gets contructed so some pointers or guidance on that would be helpful.

**Comment by JunedKhan101** [comment]
FYI: The PR above doesn't solve this issue but I still removed the extra whitespace where I could possibly find.

**Comment by JunedKhan101** [comment]
Go for it! @kiranrega

**Comment by akhilmhdh** [comment]
Closing as not a significant issue. But feel free to raise the PR, happy to merge it as first contribution if anyone is planning to take it
