### ISSUE TITLE
Issue on docs, broken link

### ISSUE THREAD

**Issue by arifer612** [Infisical/infisical#1669]
Path: /documentation/platform/token

Link to `this guide` in the blue info box is hyperlinked to "http://localhost:3000/internals/service-tokens" (see image below)
![image](https://github.com/Infisical/infisical/assets/46054733/57c252b2-b7b9-4a60-b6e6-0747f00e24b9)

**Comment by JunedKhan101** [comment]
Thanks! Created a PR for fix this.
