### ISSUE TITLE
Prioritize overridden secrets in CLI

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#167]
### Feature description
I'm currently developing a feature that would substitute 'personal secrets' to 'secret overriding'. Because of that, we will be storing both a 'shared' and a 'personal' (meaning overridded; if it exists) version of secrets. When a user pulls secrets in the CLI, we want to prioritize the injection of personal variables.

**Comment by Zamion101** [comment]
Is it related to this discussion? https://github.com/Infisical/infisical/issues/148#issuecomment-1361878754

**Comment by mv-turtle** [comment]
Yes! Exactly this - I'm trying to implement overriding, then it will also allow us to add groups to secrets

**Comment by maidul98** [comment]
Done
