### ISSUE TITLE
Self-hosted CLI login no longer works

### ISSUE THREAD

**Issue by pythoninthegrass** [Infisical/infisical#1673]
### Describe the bug
As of today, Tue Apr 9, 2024, we're no longer able to log into a self-hosted Infisical docker instance with the `infisical` CLI v0.20.1; v0.16.10 works as expected.

### To Reproduce
- Either call `infisical login -i` or wait for a terminal session to expire and unlock the keychain
- After filling out creds and selecting the org it raises the following error
```
error: CallSelectOrganization: Unsuccessful response: [response=<!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/css/670782a328c4a5af.css" as="style"/><link rel="stylesheet" href="/_next/static/css/670782a328c4a5af.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-74fe010cd18e2400.js" defer=""></script><script src="/_next/static/chunks/framework-79bce4a3a540b080.js" defer=""></script><script src="/_next/static/chunks/main-5ec97f4390710bd2.js" defer=""></script><script src="/_next/static/chunks/pages/_app-e2d1b6f26f523c51.js" defer=""></script><script src="/_next/static/chunks/pages/404-a3659c43acccd085.js" defer=""></script><script src="/_next/static/1NoYrlyyo01hJg5hn8bw4/_buildManifest.js" defer=""></script><script src="/_next/static/1NoYrlyyo01hJg5hn8bw4/_ssgManifest.js" defer=""></script></head><body><div id="__next" data-reactroot=""><div class="bg-bunker-800"><div class="container mx-auto flex relative flex-col h-screen w-full items-center justify-center px-8 text-mineshaft-50 dark:[color-scheme:dark] space-y-8"><img src="/images/loading/loading.gif" height="70" width="120" alt="loading animation"/><div class="text-primary text-xs">Loading configurations</div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{}},"page":"/404","query":{},"buildId":"1NoYrlyyo01hJg5hn8bw4","nextExport":true,"autoExport":true,"isFallback":false,"locale":"en","locales":["en","ko","fr","pt-BR","pt-PT","es"],"defaultLocale":"en","scriptLoader":[]}</script></body></html>]
```

### Expected behavior
Should be able to login or reauth a session regardless of the binary version.

### Screenshots
N/A

### Platform you are having the issue on:
**client**
Ubuntu 22.04

**server**
Official [Docker container](https://hub.docker.com/r/infisical/infisical) with the SHA: `sha256:b3e7709ef97fc84d627811adf0e0119033c51679e8f6f9c86bdd97a36a375153` (perhaps [this image](https://hub.docker.com/layers/infisical/infisical/593bdf7/images/b3e7709ef97fc84d627811adf0e0119033c51679e8f6f9c86bdd97a36a375153?context=explore)?)

### Additional context
The container hasn't been restarted/updated in 3 months. If necessary, can do the latter but since the v0.16.10 client works, would prefer to keep the server up.

**Comment by maidul98** [comment]
@pythoninthegrass I wasn't able to reproduce this. Can you please make sure you are using the latest image tag for Infisical and the CLI?

**Comment by akhilmhdh** [comment]
hey @pythoninthegrass Are you still having the above issue in latest version

**Comment by pythoninthegrass** [comment]
Hi @maidul98 && @akhilmhdh ! Sorry for the late response. Looks like all I needed to do was blow away the old `~/infisical-keyring` after updating either the server or the client.

Currently running this [SHA](https://hub.docker.com/layers/infisical/infisical/593bdf7/images/f2151d8e3af02594f42f24a740152da60f0f174f60fa24c89c042f82a0e27dad?context=explore) from nine days ago server-wise. Have mixed clients of 0.16.10 and 0.20.1 and they all work now.
