### ISSUE TITLE
ownerReferences in Kubernetes Secret Objects

### ISSUE THREAD

**Issue by erkerb4** [Infisical/infisical#1681]
### Feature description
When an InfisicalSecret object is created in Kubernetes, infisical-secret-controller manager creates the corresponding Secret object. However, these secrets do not contain `metadata.ownerReferences` field. For users who deploy InfisicalSecrets with the use of a GitOps Engine/operator _(ex: ArgoCD)_, this causes a condition where a secret is generated by a controller without ownerReferences are treated as orphaned objects. When you have ArgoCD(_GitOps operator_) to automatically sync and prune, now you have a condition where InfisicalSecret operator creates a secret, and ArgoCD controller deletes it because It thinks it's an orphaned object. So you have this condition where two operators are fighting each other non-stop. 

### Why would it be useful?
It would be great if secret objects managed by infisical-secret-controller to have ownerReference fields.

### Additional context
[Kubernetes Owner and Dependents](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/)

**Comment by maidul98** [comment]
Docs have been updated to support this: https://infisical.com/docs/integrations/platforms/kubernetes#infisicalsecret-crd-properties

<img width="874" alt="Screenshot 2024-04-12 at 12 52 33 PM" src="https://github.com/Infisical/infisical/assets/9300960/6f51d5f5-3b60-4732-86a1-6ff4cbdbd2d3">

**Comment by erkerb4** [comment]
Thank you for the pointer!
