### ISSUE TITLE
Hide Unconfigured SSO Options on Homepage

### ISSUE THREAD

**Issue by Ereaey** [Infisical/infisical#1688]
### Feature Description
Currently, all Single Sign-On (SSO) options are displayed on the homepage, including those that are not configured. The feature should ensure that only configured and operational SSO options are visible to users. Unconfigured SSO options should not appear on the homepage to avoid confusion and unsuccessful login attempts.

### Why Would It Be Useful?
This feature would improve user experience by displaying only relevant and functional login methods, making the login process clearer and faster. It would also reduce technical support queries from users attempting to use unconfigured SSO methods. Additionally, it would enhance the overall usability and professionalism of the Infisical platform by preventing user frustration and potential security concerns.

### Additional Context
This adjustment requires changes in both the SSO configuration management system and the homepage's UI rendering logic. Considerations need to be made for:
- An option in the system settings to enable or disable this feature, providing flexibility for administrators ?

Implementing this feature would involve checks during the homepage loading process to determine which SSO methods are configured and modifying the UI to display only those methods.

**Comment by DanielHougaard** [comment]
I think this is a great idea!

I would envision an implementation that uses the existing `/api/v1/admin/config` endpoint to return fields like `isLdapConfigured`, `isGoogleOauthConfigured` etc. And then render the sign-in options depending on which are configured.

@dangtony98, what do you think of this?

**Comment by maidul98** [comment]
@DanielHougaard yes, this is a great idea

**Comment by Ereaey** [comment]
I don't know if we can add it to this request but deactivating authentication by email (using an environment variable to avoid problems in production in the event of an SSO problem) could be useful also to force the use of sso.

**Comment by DanielHougaard** [comment]
> I don't know if we can add it to this request but deactivating authentication by email (using an environment variable to avoid problems in production in the event of an SSO problem) could be useful also to force the use of sso.

I would add a separate proposal for that. This a lower priority than hiding unconfigured SSO login methods though.

**Comment by OneFriendlyCoder** [comment]
Hi everyone, I was thinking of conditional rendering the Login UI based on the env variables. Will check if the env variable values are not empty and then based on that render the signIn options?

**Comment by OneFriendlyCoder** [comment]
![image](https://github.com/Infisical/infisical/assets/86824669/e780a699-0768-453b-a334-19a0d2ff1c66)

Something like this fix in the InitialSignupStep.tsx would conditionally render the SignIn options based on the creds. Do let me know if this is a right direction to proceed with or any other approach is required.

**Comment by Vishvsalvi** [comment]
Anyone working on this? If not please assign it to me, I'll do it

**Comment by DanielHougaard** [comment]
Hi @Vishvsalvi,

Thank you, I'll assign the issue to you!

Please check [this small proposal](https://github.com/Infisical/infisical/issues/1688#issuecomment-2056642660) for how I would envision the implementation to look like

**Comment by maidul98** [comment]
This feature is already released. You can control auth methods for your instances via the admin panel
<img width="2560" alt="CleanShot 2024-07-22 at 10 38 14@2x" src="https://github.com/user-attachments/assets/517058c9-502f-469f-a56e-0aafaec3398b">

**Comment by Vishvsalvi** [comment]
Please close it if that's the case
