### ISSUE TITLE
Keycloak saml sso error

### ISSUE THREAD

**Issue by vespersio** [Infisical/infisical#1690]
Path: /documentation/platform/sso/keycloak-saml
### Keycloak
version: 24.0.2
error: "Invalid requester"
log: "ERROR [org.keycloak.protocol.saml.SamlService] (executor-thread-6) request validation failed: org.keycloak.common.VerificationException: SigAlg was null"

### Infisical
image tag: v0.52.1-postgres

**Comment by dangtony98** [comment]
Thanks for reporting this @vespersio.

I’m looking into it - Will get back to you

**Comment by vespersio** [comment]
@dangtony98 
Find solution, need to **disable** in client tab **Keys** -> **Signing keys config** -> **Client signature required**

Add please to /documentation/platform/sso/keycloak-saml

<img width="623" alt="Screenshot 2024-04-17 at 14 08 04" src="https://github.com/Infisical/infisical/assets/5022435/6efd1a4a-6e76-4a5b-b948-5a976d0d8605">

**Comment by akhilmhdh** [comment]
Closing as resolved

**Comment by samuk10** [comment]
I just updated the certificate on:
`clients > <YOUR-CLIENT > keys > import`
