### ISSUE TITLE
Infisical CLI `v0.21.0` crashes while trying to use

### ISSUE THREAD

**Issue by BlankParticle** [Infisical/infisical#1691]
### Describe the bug
Infisical CLI `v0.21.0` crashes with a null pointer deference while trying to run with a env.

### To Reproduce
1. run `infisical run --env=env_name -- any_command`
2. It will crash

### Expected behavior
Run with the env variables injected

### Screenshots
![image](https://github.com/Infisical/infisical/assets/130567419/3772f806-85c9-4eee-9021-4d4b0890de8f)

### Platform you are having the issue on:
Infisical CLI `v0.21.0`
Arch Linux, x86_64, 6.8.5-arch1-1

**Comment by maidul98** [comment]
@DanielHougaard will be looking into this

**Comment by maidul98** [comment]
New release is in progress https://github.com/Infisical/infisical/actions/runs/8710763583/job/23893351270

**Comment by DanielHougaard** [comment]
@BlankParticle A new version has been released [0.21.1](https://github.com/Infisical/infisical/actions/runs/8710763583/job/23893351270)

It should be downloadable now!
