### ISSUE TITLE
[BUG] All github secrets integrations was deleted

### ISSUE THREAD

**Issue by PemaKz** [Infisical/infisical#1711]
### Describe the bug
I created same secret key into a folder on infisical, then deleted the github integration and add it again with the same parameters just changing the location. All the secrets was deleted and the one added was synced.

### To Reproduce
1. Go to create a secret on main path
2. Integrate on github organization
2. Create same secret on a folder
3. Delete github integration
4. Add exactly same integration with the new path

### Expected behavior
I dont expect to delete all my  organization secrets, just to renew the existing one.

**Comment by akhilmhdh** [comment]
@dangtony98 I think you will be able to answer this. Is this expected behavoir?
