### ISSUE TITLE
Secrets stuck in Out of Sync on EKS 1.29

### ISSUE THREAD

**Issue by josh-sherman-worthwhile** [Infisical/infisical#1732]
### Describe the bug
Everything worked fine on EKS 1.28, but after upgrading to 1.29 this issue is popping up only with Infisical secrets.  Existing secrets are fine, but when trying to deploy new ones they put the application in Out of Sync status in ArgoCD.  In the ArgoCD GUI I see: "OutOfSync (This resource is not present in the application's source. It will be deleted from Kubernetes if the prune option is enabled during sync.)"  When checking the ArgoCD logs I see the reason as ResourceUpdated.  To be clear, the secret does get deployed onto the cluster but it constantly thinks it's out of sync and will redeploy them every sync cycle.  My secret manifest below if it helps at all:

`apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: test-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: infisical
      secretsScope:
        envSlug: dev
        secretsPath: "/mypath"
  managedSecretReference:
    secretName: test-secret
    secretNamespace: mynamespace`

### To Reproduce
1. Run EKS 1.29 and deploy an Infisical secret
2. Check the sync status after it has time to deploy

### Expected behavior
I would expect it to sync the secret and check on a 60 second interval for updates without constantly being out of sync.

### Screenshots
![Screenshot 2024-04-24 at 8 56 51 AM](https://github.com/Infisical/infisical/assets/111443719/f0326f12-22c2-4a2b-883c-20c2868d9757)

### Platform you are having the issue on:
Infisical Secrets Operator 0.5.0 Helm Chart, ArgoCD 2.10 and EKS 1.29

**Comment by akhilmhdh** [comment]
@maidul98 Did we made any significant change for causing this on just v1.29.

@josh-sherman-worthwhile Are you sure was the EKS update the only thing changed?

**Comment by josh-sherman-worthwhile** [comment]
The only other change that happened was ArgoCD going from 2.9 to 2.10.  I did try rolling ArgoCD back to 2.9, but I still have the same issue.

**Comment by maidul98** [comment]
Have you set the creation policy? https://infisical.com/docs/integrations/platforms/kubernetes#infisicalsecret-crd-properties

**Comment by josh-sherman-worthwhile** [comment]
Good catch, I did not see that in the documentation.  Setting `creationPolicy: "Owner"` took care of my problem.  For my own understanding, was this a change on the Kubernetes side or Infisical side that caused this?
