### ISSUE TITLE
Add popup before secret delete 

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#175]
### Feature description
Users should be warned before deleting any secrets. Currently, it is too easy to delete secrets and users are not informed of impact that deleting secrets can have. Users should be informed that any downstream integration which relies on the secret will be impacted. We can achieve this with a pop up of some kind

### Why would it be useful?
This would make users think twice before deleting a secret.

**Comment by JoaoVictor6** [comment]
I want to resolve this issue, I would create a component named `DeleteKeyDialog` or similar. Does make sense this approach?

**Comment by mv-turtle** [comment]
Hi @JoaoVictor6! Yes, I think that makes sense. We just need to ask them something like "Are you sure you want to delete this secret? This cannot be undone." And the buttons would be 'Cancel' and 'Delete'. 

I'm currently making some changes to the deletions. Would you be fine with waiting ~1 day before starting? Thank you so much for your help :) 

Also, please, join our community Slack for our contributors and users. You can ask any questions you might have there. Here is the link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

**Comment by JoaoVictor6** [comment]
Okay! :)

**Comment by mv-turtle** [comment]
But I think we should still add a modal right? For example, Slack also has a sidebar, but they ask you any way if you want to delete a message

**Comment by JoaoVictor6** [comment]
Certainly. The confirm delete action is very simple, in this case make more sense create a dialog
