### ISSUE TITLE
GoLang SDK

### ISSUE THREAD

**Issue by chaddyc** [Infisical/infisical#1771]
### Feature description
GoLang SDK

### Why would it be useful?
GoLang developers would want to make use of this feature. Many backend and microservices are being built by companies and organizations so it is worthwhile building a GoLang SDK.

**Comment by ThejanNim** [comment]
Hey @chaddyc, can you open issue in this repo [https://github.com/Infisical/sdk/issues](infisical SDK)

**Comment by chaddyc** [comment]
@ThejanNim created the issue for `GoLang SDK` in https://github.com/Infisical/sdk/issues/30

**Comment by ThejanNim** [comment]
Thanks @chaddyc

**Comment by akhilmhdh** [comment]
Closing as in wrong repo
