### ISSUE TITLE
Compare different environment values in the dashboard

### ISSUE THREAD

**Issue by html5maker** [Infisical/infisical#1785]
### Feature description
It would be nice to have an option to compare environment variables values on the same page

### Why would it be useful?
Currently I need to open each environment separately in 2 different browser tabs to compare the values.
Usually this step is needed to prevent typos and can clearly display the differences between different environments

### Additional context
This feature request is related to the Dashboard (UX)

**Comment by vmatsiiako** [comment]
Hi @html5maker! You can already do this by clicking on a particular row in the overview screen. Then you can reveal the values for a particular secret.
