### ISSUE TITLE
CLI Login and Set Process Does Not Work Per Documentation

### ISSUE THREAD

**Issue by seancallaway** [Infisical/infisical#1802]
### Describe the bug
After logging in, running `infisical secrets set` generates a "You must be logged in to run this command. To login, run [infisical login]" error, though `infisical secrets get` (with a projectId) will return data.

### To Reproduce
1. Set INFISICAL_API_URL (`export INFISICAL_API_URL=https://<REDACTED_FQDN>/api`)
2. Login, setting token (`export INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id=<REDACTED_CLIENT_ID> --client-secret=<REDACTED_CLIENT_SECRET> --silent --plain`)
3. Try to set a secret (`infisical secrets set --env=staging TEST_SECRET=test`)
4. Get error message (`You must be logged in to run this command. To login, run [infisical login]`
5. Try to get a secret (`infisical secrets --projectId <REDACTED_PROJECT_ID> --env=staging get TEST_SECRET`)
6. Get table containing "*not found*" for the SECRET VALUE (expected, as it is unset). I am able to get a secret set via the web UI for the dev environment.

### Expected behavior
I'd expect step 3 to succeed, setting the secret properly, based on the [documentation](https://infisical.com/docs/cli/commands/secrets#infisical-secrets-set).

### Platform you are having the issue on:

**CLI**
- MacOS: infisical version 0.22.2
- Alpine (CI container): infisical version 0.22.2

**Self-Hosted Docker-Compose Setup**
Installed today using `:latest`.

### Additional context
Tested from my workstation and our GitLab CI/CD pipeline.

The machine identity in question has the following permission in the project:

![image](https://github.com/Infisical/infisical/assets/1229384/2f0a43eb-c0a1-4563-b590-265280495f88)

**Comment by seancallaway** [comment]
Team has indicated that there is, in fact, an issue with Infisical via [Slack](https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1715268345969999?thread_ts=1715192395.606039&cid=C04BSBMQAQ7).

**Comment by seancallaway** [comment]
Turns out that this just isn't a supported operation. Documentation should be fixed to indicate this or, better yet, implement this.

**Comment by DanielHougaard** [comment]
Hi @seancallaway, this has now been added in the latest CLI version. Please update your CLI to `>= 0.23.2`!
