### ISSUE TITLE
🌎 Help us translate Infisical 

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#181]
### 🌎 We want to let as many people use Infisical as possible! Help us translate it! 🚀

There are two main components that need to be translated for Infisical: README.md and Web UI. README.md is probably higher priority as it allows more people to initially understand what Infisical is. 

Here are some of the languages we are looking for: (👀 - looking for; ✅ - ready; ⚠️ - needs minor revision)

(if your language is not in this list, we would still love to have it! Please, let us know :))

|  Language | README.md status | Web UI status |
| ------------- | ------------- | ------------- |
| Arabic | 👀 | 👀 |
| English | ✅  | ✅ |
| French | 👀 | ✅ |
| German | ✅ | 👀 |
| Hindi | 👀 | 👀 |
| Indonesian | ✅ | 👀 |
| Italian | 👀 | 👀 |
| Japanese | 👀 | 👀 |
| Korean | ✅ | ✅ |
| Malay | 👀 | 👀 |
| Portuguese | 👀 | 👀 |
| Portuguese - Brazil | ✅ | ✅ |
| Spanish | ✅ | 👀 |
| Simplified Chinese | 👀 | 👀 |
| Traditional Chinese | 👀 | 👀 |
| Turkish | ✅ | ✅ |
| Ukrainian | 👀 | 👀 |
| Vietnamese | 👀 | 👀 |

For Web UI, you would need to create a new directory [here](https://github.com/Infisical/infisical/tree/main/frontend/public/locales).
For README.md, you can add them to [this folder](https://github.com/Infisical/infisical/tree/main/i18n). 

If you have any questions, just shoot them in the comments to this issue or [join our Slack](https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g).

P.S. In future, we will also have docs in different languages, but that seems like too much work right now :)

**Comment by JoaoVictor6** [comment]
I can translate the UI into Portuguese!

**Comment by mv-turtle** [comment]
That would be really amazing @JoaoVictor6! Appreciate your help :) Let me know if you need anything

**Comment by Gabriellopes232** [comment]
Hello, I'm Brazilian too! I would love to be able to help @JoaoVictor6 in this issue to translate the UI to Portuguese!

**Comment by mv-turtle** [comment]
Thank you so much @Gabriellopes232! Appreciate your help a lot. Join our Slack for easier communication: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g 🚀🚀🚀

**Comment by caioluis** [comment]
I'm a Brazilian living in Portugal. I can help with both PT-BR and PT-PT (yes, there are some differences that make Portuguese people uncomfortable, thus I think it's important to include them as well ^^)

**Comment by mv-turtle** [comment]
@caioluis! That would be really amazing! Appreciate your help! Are you thinking to translate the web UI or the readme? 😃

**Comment by samsbg** [comment]
Mexican here, would love to help out with Spanish!

**Comment by mv-turtle** [comment]
Hey @samsbg! This would be so awesome! Just saw that you joined our Slack 🚀

**Comment by esau-morais** [comment]
#199 seems not have applied translation for `forgot-password`. Should I open a new issue or can I just make a PR at once and mention this issue?

cc.: @mv-turtle

**Comment by mv-turtle** [comment]
@esau-morais just saw your PR, will try to review today! Thank you so much for fixing that. There are actually quite a few pages that are not covered by translations yet (for example, the Infisical guide)

Again, thanks for contributing :)

**Comment by esau-morais** [comment]
I can translate the rest in another PR, once I've fixed two issues in only one (I don't think it's a good practice)

**Comment by caioluis** [comment]
I will soon open a PR to fix the copies for the Brazilian Portuguese. It unfortunately shows some signs of automatic translation that takes everything too literally and is somewhat disturbing. Expect it to come later today. On the mean time, I have just opened the PR for the European Portuguese.

**Comment by eltociear** [comment]
I am Japanese, so I would like to participate in Japanese translation.

**Comment by mv-turtle** [comment]
@eltociear thank you so much! Would really appreciate your help! Feel free to join our Slack for contributors and users: https://infisical.com/slack

**Comment by dangtony98** [comment]
Hi everyone! 

After much hard thought, we've unfortunately decided to sunset translations for the `README.md` file primarily because it has evolved so much in the past few months and we've struggled to keep it in sync across all the languages and changing documentation links.

This was a sad decision on our end but we're grateful for all the translations to date; it was wonderful seeing y'all come from different parts of the world to help translate. That said, we'll be revamping our contributor docs soon and adding in a contributor program entailing many more ways to contribute to Infisical from development to writing, etc. 😄
