### ISSUE TITLE
Helm: use bitnamis mongodb chart

### ISSUE THREAD

**Issue by jon4hz** [Infisical/infisical#182]
### Feature description
What do you think about adding [bitnamis mongodb chart](https://github.com/bitnami/charts/tree/main/bitnami/mongodb) as helm dependency instead of managing the mongodb chart yourself? 

### Why would it be useful?
Currently it isn't possible to setup a productive infisical instance using helm unless you outsource the mongodb. Bitnamis Chart is extremely good and brings all the customization one would need.

**Comment by maidul98** [comment]
This is great suggestion and will allow people to have mongo db StatefulSet. Adding this should also this issue https://github.com/Infisical/infisical/issues/173

If you are familiar with that mongo chart, please feel free to post a PR

**Comment by jon4hz** [comment]
To be honest, I never used that chart myself but I can take a look at it. Will most likely be next year when I get to that though :)

**Comment by maidul98** [comment]
Sounds good

**Comment by maidul98** [comment]
Yes!
