### ISSUE TITLE
Document of installation without docker

### ISSUE THREAD

**Issue by ericdai** [Infisical/infisical#1828]
install in baremetal mode

**Comment by maidul98** [comment]
Yes, Infisical is working on developing a binary to be installed on Linux. More updates will be provided here

**Comment by divyanshchahar** [comment]
@akhilmhdh Is this PR requesting changes to setup projects locally without  docker. IF that is the case then I have solved it already, assign me the issue and I can open a PR.

**Comment by akhilmhdh** [comment]
@divyanshchahar without node and docker kore specifically 

@DanielHougaard has already wrapped up this in the meantime. He is working on documentation. You may connect with him.

**Comment by divyanshchahar** [comment]
@DanielHougaard I am really curious about how you solved this, if you could just point me in the direction of the tools you used to accomplish this task, it would be really helpful

**Comment by DanielHougaard** [comment]
Goodmorning @divyanshchahar and @ericdai. 

We recently released documentation on how to use the baremetal Infisical installation. You can [read more here](https://infisical.com/docs/self-hosting/deployment-options/native/standalone-binary).
