### ISSUE TITLE
Error while download CLI - `402 Payment required`

### ISSUE THREAD

**Issue by henrycunh** [Infisical/infisical#1849]
### Describe the bug
You have probably exceeded the bandwidth on your PPA plan, now downloading the CLI is impossible.
Which makes impossible for me to deploy anything.

### To Reproduce
- Try to download the CLI on any target platform
  - e.g. https://dl.cloudsmith.io/public/infisical/infisical-cli/deb/any-distro/pool/any-version/main/i/in/infisical_0.22.2/infisical_0.22.2_linux_armv7.deb

**Comment by DanielHougaard** [comment]
Hi @henrycunh, thanks for the report. We're looking into this!

**Comment by amnesytoolkit** [comment]
You can temporarily use this command to manually install infisical-cli in your containers: 

`wget https://github.com/Infisical/infisical/releases/download/infisical-cli%2Fv0.22.2/infisical_0.22.2_linux_amd64.deb && dpkg -i infisical_0.22.2_linux_amd64.deb && rm infisical_0.22.2_linux_amd64.deb`

**Comment by maidul98** [comment]
Cloudsmith has deployed a fix to resolve this issue. Downloads should now be possible
