### ISSUE TITLE
--path erroring out in secrets subcommand

### ISSUE THREAD

**Issue by SimulShift** [Infisical/infisical#1854]
### Describe the bug
Erroring when using --path flag in secrets subcommand. Tried all sorts of combinations --path="/" --path="myfolder" --path="/myfolder"

### To Reproduce
I just made a new project, added a folder and tried to use the path flag for example
`infisical secrets get test --path="/" --env=dev`

### Expected behavior
any command that includes the --path folder should work instead of error

### Screenshots
![image](https://github.com/Infisical/infisical/assets/62919684/3629a150-a401-4295-a84e-a2d9e75859c3)

### Platform you are having the issue on:
Windows 11
infisical version 0.22.2

**Comment by akhilmhdh** [comment]
@SimulShift can you share your workspace id. So that i can debug this furthur.

I have tried this in my local and infisical cloud, can't seem to reproduce it on our side

**Comment by SimulShift** [comment]
sure its 
"workspaceId": "f865651c-ef31-47ca-b67a-34e6b38c6569",
