### ISSUE TITLE
Helm Repository is Unavailable

### ISSUE THREAD

**Issue by ianedwards** [Infisical/infisical#1868]
### Describe the bug
Navigating to [https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts](https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts) returns a 404

### To Reproduce

Can be reproduced by either
- Navigating directly to the URL
- attempting to use the repository from the helm CLI

**Comment by maidul98** [comment]
Thank you for reporting. We have notified Cloudsmith, distribution provider

**Comment by myeong-han** [comment]
The URL is 404, but you can check that the repository is valid.
https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/index.yaml

```
helm repo add infisical https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
helm pull infisical/infisical
```

**Comment by ianedwards** [comment]
> The URL is 404, but you can check that the repository is valid. https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/index.yaml
> 
> ```
> helm repo add infisical https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
> helm pull infisical/infisical
> ```

@myeong-han Thanks, we had been seeing issues when running that previously but appears to be fine now. I'll go ahead and close this. Appreciate it!
