### ISSUE TITLE
Potential Env removal from Docs?

### ISSUE THREAD

**Issue by Willt123** [Infisical/infisical#1892]
Path: /self-hosting/configuration/envars

In a previous version we utilised: 
`INVITE_ONLY_SIGNUP=true`

This looks like it has been removed as now the ability to prevent users from signing up is not available?

**Comment by vmatsiiako** [comment]
I think this environment variable should still be available. @maidul98 will be able to comment more

**Comment by maidul98** [comment]
You should be able to set this from your admin panel 
<img width="1722" alt="Screenshot 2024-05-28 at 11 13 34 PM" src="https://github.com/Infisical/infisical/assets/9300960/baa49c26-2415-4b73-a330-0e9676ad3172">. This is accessible to the very first user that configured your instance. Does this help?

**Comment by Willt123** [comment]
Hi @maidul98 thanks for this thats super helpful. 
Took me a while to find the page. 

For the benefit of anyone else with a similar issue, the admin page can be accessed by the organisation administrator (First person to register on infisical after setup) buy selecting their user icon and selecting "Admin Panel"
<img width="584" alt="Screenshot 2024-05-29 at 3 03 50 pm" src="https://github.com/Infisical/infisical/assets/61480991/5cfc5bd0-8abc-4168-b7d2-0013b754a2c1">
