### ISSUE TITLE
Move environment keys to different folders

### ISSUE THREAD

**Issue by jmgb27** [Infisical/infisical#1910]
### Feature description
Allow users to move environment keys from one folder to another.

### Why would it be useful?
This feature would be useful for users who have created many environment keys and need to organize them into different folders. This would make it easier to find the specific key they need. 

### Additional context
Currently, the only way to move an environment key to a different folder is to copy the key and its value and then create a new key in the desired folder. This is a cumbersome process, especially for users with many keys.

**Comment by akhilmhdh** [comment]
Closing as its been released
