### ISSUE TITLE
Multiline secrets given quotes and \n in kubernetes secrets

### ISSUE THREAD

**Issue by p2bauer** [Infisical/infisical#1912]
### Describe the bug

When you set a multiline secret (RSA key) in the infisical web interface, and sync them with the kubernetes operator into a secret - the secret gets wrapped in double quotes (") and \\n instead of a proper newline.

### To Reproduce

1. Go to the web interface, and add a multiline secret (ie. RSA key)
2. Wait for it to sync with the kubernetes secret
3. Look at the secret key/value in kubernetes - it's wrapped in double quotes, and newlines show as \\n

### Expected behavior

Multiline secrets should output in kubernetes without quotes, and properly escaped so the newlines show up in kubernetes.

**Comment by vmatsiiako** [comment]
Hi @p2bauer! Have you tried using this option in the secret's sidebar? You can access the sidebar but clicking on "three dots" next to any secret. 

<img width="427" alt="Screenshot 2024-06-01 at 08 29 14" src="https://github.com/Infisical/infisical/assets/78047717/f6f4e448-b4d7-4528-bfd4-91c63ab8e704">

**Comment by p2bauer** [comment]
Thank you for the quick reply @vmatsiiako !  Hmm, I'm on the latest version v0.67.0-postgres but I don't seem to see that in the Web UI - is there some configuration I need to enable for this option to show up for secrets?  

The only icons I see next to any secret (whether value is visible or not) are copy and delete:
<img width="1156" alt="image" src="https://github.com/Infisical/infisical/assets/6989445/c32baf80-35bb-4922-9bbf-3ad727a8b67d">

**Comment by vmatsiiako** [comment]
Hi @p2bauer! Could you please click to explore a particular environment? Then you should be able to see more options. 
<img width="874" alt="Screenshot 2024-06-01 at 15 06 17" src="https://github.com/Infisical/infisical/assets/78047717/9319007c-31a5-4d68-8bc3-c32836eed72b">

**Comment by p2bauer** [comment]
Ah, thank you :-). I'm new to infisical and didn't even realise that screen existed.

So I've tried both disabling multiline encoding on the existing secret, as well as creating a new one and then disabling it.....and as per the documentation, I would expect the kubernetes secret to no longer be wrapped in quotes & with \n.  

But even after recreating the secret via the Explore page & deleting the kubernetes secret and waiting for it to be recreated, it seems it's *still* wrapped in quotes.  Any suggestions?

**Comment by akhilmhdh** [comment]
This should be fixed by today.

If your using cloud you won't need to do anything. Else for self hosted you need to update to latest version

**Comment by p2bauer** [comment]
Thank you @akhilmhdh !  Confirming after updating, it works as expected and seeing the kubernetes secret formatted correctly.....and thanks for jumping on this bug so quickly! 💯
