### ISSUE TITLE
Infisical agent should support AWS auth

### ISSUE THREAD

**Issue by jasonhernandez** [Infisical/infisical#1915]
### Feature description
The Infisical agent should support AWS auth

### Why would it be useful?
The Infisical CLI / agent is the most straightforward way to access secrets in Docker containers run with docker-compose / swarm etc. If the agent supported AWS auth, it could use the IAM role attached to the instance it is running on and not require a provisioned token / secret.

### Additional context
This would make machine identities notably more useful vs. service tokens and simplify my migration. I expect this would benefit other users. I don't use Azure or GCP but those methods would likely help users on those cloud providers. Thanks.

**Comment by vmatsiiako** [comment]
Hi @jasonhernandez! Yes, indeed. @DanielHougaard is actually working on this at the moment.

**Comment by jasonhernandez** [comment]
It looks like you implemented this - I just tested it out on an EC2 instance. Thanks!
https://infisical.com/docs/documentation/platform/identities/aws-auth
