### ISSUE TITLE
Gitlab integration - masked/protected variables

### ISSUE THREAD

**Issue by golgotow** [Infisical/infisical#1919]
### Feature description
In gitlab we can add variable to CICD with below options

    Protected: Only exposed to protected branches or protected tags.
    Masked: Hidden in job logs. Must match masking requirements.
    Expanded: Variables with $ will be treated as the start of a reference to another variable.

please add this possibility to Gitlab Integration

### Why would it be useful?
Possibility to use options for Variables for CICD like Masked, to protect pipeline output.

**Comment by sheensantoscapadngan** [comment]
hey @golgotow, this is resolved now in the latest version of Infisical (if you're self-hosting) and in the cloud
