### ISSUE TITLE
Scroll is not allowed in the member list when adding member in a project

### ISSUE THREAD

**Issue by Rookie0031** [Infisical/infisical#1922]
### Describe the bug
While adding a member to a project, the organization members are listed, but there is no scroll. So project admin can not see if it over the screen.

### To Reproduce
1. Go to project, access control
2. Click on 'add member'
3. Click username to see the members in the organization
4. See the bug

### Expected behavior
Project admin can scroll up and down to see all the member list.

### Screenshots
<img width="700" alt="image" src="https://github.com/Infisical/infisical/assets/103009135/a76e650f-5ef0-4d82-a193-04fc3fac6a39">

### Platform you are having the issue on:
Chrome

**Comment by akhilmhdh** [comment]
Closed with #1921
