### ISSUE TITLE
Multiline secrets aren't exported properly in YAML

### ISSUE THREAD

**Issue by nayyara-airlangga** [Infisical/infisical#1955]
### Describe the bug

I have a multiline secret that I want to export in YAML format. The secret looks like this

![Screenshot 2024-06-12 at 09 28 51](https://uploads.linear.app/23e8e853-8625-4193-88c0-0864ea047dca/c1ea8faa-2d98-48e7-9a9f-9367f42afd2a/d0231a12-fd75-4312-9eaa-731d2fdb2e58?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzIzZThlODUzLTg2MjUtNDE5My04OGMwLTA4NjRlYTA0N2RjYS9jMWVhOGZhYS0yZDk4LTQ4ZTctOWE5Zi05MzY3ZjQyYWZkMmEvZDAyMzFhMTItZmQ3NS00MzEyLTllYWEtNzMxZDJmZGIyZTU4IiwiaWF0IjoxNzE4MTY1MjYxLCJleHAiOjMzMjg4NzI1MjYxfQ.eWPcxXfzzCGIxHw23FipLUqqafpiaD7WqJlkFN_vP30 "=524x")

A multiline string is valid for YAML if the format looks like this

```yaml
TEST: |
  A valid
  multiline secret
  for testing
```

This is also a valid YAML multiline string

```yaml
ANOTHER_TEST: |
  Another example
    but this time this one is indented
  and this one is not
```

However, this is not

```yaml
NOT_VALID: |
    The first line shouldn't be indented further
  than the other lines
  This is not valid
```

There are ways to allow this but for how a lot of people use YAML for configuration, it's safe to just support the first two examples:

* It starts with a `|`
* And then the string itself is indented and starts from the line after it

However, the current YAML export throws this out, which isn't valid YAML

```yaml
TEST: A valid
multiline secret
for testing
```

Now there are ways in YAML to support the third example, but for configuration purposes, I believe supporting the first two examples is what's expected.

### To Reproduce

1. Create a new secret called `TEST` on any environment
2. Paste this as the value

```
A valid
multiline secret
for testing
```

3. Export the secret in YAML format with `infisical export`
4. The result will be as I've described above

### Expected behavior

What I expected from this feature was to have it exported as valid multiline string in YAML like this:

```yaml
TEST: |
  A valid
  multiline secret
  for testing
```

### Screenshots

* The secret I used for testing this

![image (1)](https://uploads.linear.app/23e8e853-8625-4193-88c0-0864ea047dca/e5eb2948-79a2-4d97-964d-cab9c09fcd0b/e34c0d58-a242-48b9-87d4-faff8a48a73b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzIzZThlODUzLTg2MjUtNDE5My04OGMwLTA4NjRlYTA0N2RjYS9lNWViMjk0OC03OWEyLTRkOTctOTY0ZC1jYWI5YzA5ZmNkMGIvZTM0YzBkNTgtYTI0Mi00OGI5LTg3ZDQtZmFmZjhhNDhhNzNiIiwiaWF0IjoxNzE4MTY1MjYxLCJleHAiOjMzMjg4NzI1MjYxfQ.ypoCXoOo_0PtTiKOXEQ3iQO9Vzlu0XLc_L79A1RNRpU)

* The result I got from the export

![image](https://uploads.linear.app/23e8e853-8625-4193-88c0-0864ea047dca/44539d82-18f2-484b-bb85-2cc4e50ba33e/93d74763-e64d-4ee9-adef-2b5d6062b3e7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzIzZThlODUzLTg2MjUtNDE5My04OGMwLTA4NjRlYTA0N2RjYS80NDUzOWQ4Mi0xOGYyLTQ4NGItYmI4NS0yY2M0ZTUwYmEzM2UvOTNkNzQ3NjMtZTY0ZC00ZWU5LWFkZWYtMmI1ZDYwNjJiM2U3IiwiaWF0IjoxNzE4MTY1MjYxLCJleHAiOjMzMjg4NzI1MjYxfQ.hj0N8OxrCFc3pFOBwhYpMya7ZywVm005NmHy4u0UgdQ)

### Platform you are having the issue on:

I initially encountered this issue on Windows but since its an export related issue, it exists on all platforms

**Comment by nayyara-airlangga** [comment]
I'd like to try and fix this issue myself if it's alright

**Comment by akhilmhdh** [comment]
Sure @nayyara-airlangga
