### ISSUE TITLE
Unable to compile TypeScript: src/controllers/v2/secretController.ts

### ISSUE THREAD

**Issue by JoaoVictor6** [Infisical/infisical#196]
### Describe the bug
The backend does not run. I try to initiate a docker-compose for development but has this error:

```
infisical-dev-backend | /app/node_modules/ts-node/src/index.ts:859
infisical-dev-backend |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
infisical-dev-backend |            ^
infisical-dev-backend | TSError: ⨯ Unable to compile TypeScript:
infisical-dev-backend | src/controllers/v2/secretController.ts(1,16): error TS2307: Cannot find module 'await-to-js' or its corresponding type declarations.
infisical-dev-backend | src/controllers/v2/secretController.ts(70,83): error TS7006: Parameter 'objectId' implicitly has an 'any' type.
infisical-dev-backend | src/controllers/v2/secretController.ts(101,83): error TS7006: Parameter 'objectId' implicitly has an 'any' type.
```

Full error:
![image](https://user-images.githubusercontent.com/68869379/210888658-cf6f83c4-31f0-4a51-b125-13665b3d89e2.png)

### To Reproduce
1. Clone the repo
2. Run this command on terminal: `docker-compose -f docker-compose.dev.yml up` 
3. See error

**Comment by mv-turtle** [comment]
For everyone who sees this in future, this is how you could solve it: 

You need to run `docker system prune -a` to delete node modules, and then run `npm install` in both frontend and backend. Then just run `make up-dev`.
