### ISSUE TITLE
Migration scripts fails with multiple issues

### ISSUE THREAD

**Issue by ch9hn** [Infisical/infisical#1990]
### Describe the bug
Infisical Migration Job failed when connecting to Kubernetes Internal Database

### To Reproduce
1. Create K8S Secret with Database URI variable: 
DB_CONNECTION_URI=postgresql://user:password@postgres-cluster-dev-ha.postgres-cluster.svc.cluster.local:5432/infisical
2. Deploy Infisical with Helmchart in the Cluster
3. Check logs of Migration Script

Error:
```
> backend@1.0.0 migration:latest
> knex --knexfile ./src/db/knexfile.ts --client pg migrate:latest
Requiring external module ts-node/register
Working directory changed to /backend/src/db
Using environment: production
getaddrinfo EAI_AGAIN base
Error: getaddrinfo EAI_AGAIN base
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
npm notice To update run: npm install -g npm@10.8.1
npm notice
```

### Expected behavior
Migration script should start up without any issues

### Screenshots
-

### Platform you are having the issue on:
Kubernetes 1.25.7
Infisical Standalone Helmchart: 1.0.8
Infisical Docker Image: v0.68.2-postgres

### Additional context
-

**Comment by ch9hn** [comment]
Furthermore now the following error appears in the migration job:

```
no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "infisicaluser", database "infisical", no encryption
error: no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "infisicaluser", database "infisical", no encryption
```

**Comment by akhilmhdh** [comment]
Hey @ch9hn 

This could be due to multiple reasons.
1. The last one being not providing SSL certificate to connect with database
2. First one is a typically its your network setup issue, Can't comment until we see your infra and docker setup

**Comment by akhilmhdh** [comment]
Closing as stale
