### ISSUE TITLE
Add docker layered cache

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#206]
We do not have any form of layer caching during docker builds in our Github actions. Saving the layers would help speed up subsequent builds and help us ship features at a more rapid pace.

**Comment by Zamion101** [comment]
Looks like https://github.com/marketplace/actions/build-and-push-docker-images#customizing supports `cache-from` and `cache-to` but not sure we can use it without exporting to somewhere or I can be wrong, need to look more into it.

**Comment by maidul98** [comment]
This has been complete with help from @cerrussell
