### ISSUE TITLE
Allow secrets deep search 

### ISSUE THREAD

**Issue by abunet** [Infisical/infisical#2063]
### Feature description
Allow secrets deep search (search from current folder and down all subfolders)

**Comment by ranjanmangla1** [comment]
hey @abunet , can i pick up this issue?

**Comment by MuhmdAjeer** [comment]
hey @akhilmhdh, can i work on this feature?

**Comment by akhilmhdh** [comment]
Regarding this we are moving towards a new architecture for secrets management. The old architecture could never support this as our keys are hashed. New one should be able to do it. But as of now we will keep this issue open until we have further timeline mapped for secret v1 architecture depreciation.

**Comment by akhilmhdh** [comment]
Closing as its now available
