### ISSUE TITLE
Allow deep import from environment 

### ISSUE THREAD

**Issue by abunet** [Infisical/infisical#2064]
### Feature description
Actually importing secrets from an environment / folder, only copy root KEYS/VALUES. Allow to copy nested folders

**Comment by akhilmhdh** [comment]
@abunet The import itself is a bit complex feature adding recursive to that introduces a lot more edge cases, like having imports inside the recursive one etc.

**Comment by abunet** [comment]
HI akhilmhdh, first of all thanks for the reply.

Sorry but I don't agree. 
In my opinion is a must have feature (I'm talking about tha management UI).

Imagine an example structure

```
(folder)myplanttemplate:
  (folder)mymicroservices:
    (folder)micro1:
      (folder)db:
        USERNAME: myuser
        PASSWORD: mypwd
      (folder)ui:
        USERNAME: myuser
        PASSWORD: mypwd
   (folder)micro2:
     (folder)db:
        USERNAME: myuser
        PASSWORD: mypwd

(folder)myplant2:
.....
```

I need to replicate this "template" structure for n plants. From web ui.
doing it manually is an huge work.

I can automate it via API, but in this way i'm moving the "master data" externally. 
I'd like to allow users to design the environment structure from Infisical, not from other data sources

Thankss

**Comment by akhilmhdh** [comment]
As you can even if an import recursive happens  your same secret key name will get override as only one secret can be at the end of the day when you pull the value.

Else you would need to prepend it with something identifier. Thus u can even put it outside the folder now.

Again you can also create required imports as needed too.

**Comment by abunet** [comment]
I cannot change the name of vars, beacause the containers that I need to deploy are thirdy party containers, and i cannot change var names. This is why i group variables in folders.

"As you can see even if an import recursive happens your same secret key name will get override as only one secret can be at the end of the day when you pull the value."

Could you be more specific? Starting from previous structure:

```
(folder)myplanttemplate:
  (folder)mymicroservices:
    (folder)micro1:
      (folder)db:
        USERNAME: myuser
        PASSWORD: mypwd
      (folder)ui:
        USERNAME: myuser
        PASSWORD: mypwd
   (folder)micro2:
     (folder)db:
        USERNAME: myuser
        PASSWORD: mypwd
``` 

i need to copy and obtain:

```
(folder)**PLANT1**:
  (folder)mymicroservices:
    (folder)micro1:
      (folder)db:
        USERNAME: myuser
        PASSWORD: mypwd
      (folder)ui:
        USERNAME: myuser
        PASSWORD: mypwd
   (folder)micro2:
     (folder)db:
        USERNAME: myuser
        PASSWORD: mypwd
``` 
and

```
(folder)**PLANT2**:
  (folder)mymicroservices:
    (folder)micro1:
      (folder)db:
        USERNAME: myuser
        PASSWORD: mypwd
      (folder)ui:
        USERNAME: myuser
        PASSWORD: mypwd
   (folder)micro2:
     (folder)db:
        USERNAME: myuser
        PASSWORD: mypwd
``` 

I know that the copy must be recursive, but we must copy the folder structure too. So there's no need to prefix variables

**Comment by abunet** [comment]
I realized that perhaps I wasn't too specific. I'm talking about importing a folder already present in physical, not importing from FileSystem

![image](https://github.com/Infisical/infisical/assets/804576/0e8bdfe6-f72f-4e7d-8d9d-6aa20ed16465)
