### ISSUE TITLE
Documentation versioning

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#2070]
### Feature description

As mentioned [here](https://github.com/Infisical/infisical/pull/1381#pullrequestreview-1869983097), it'd be nice if the https://infisical.com/docs included backward compatible docs, to keep supporting Mongo/old users with at least the old docs. 

### Why would it be useful?

Always find the right documentation for the right version/milestone

### Additional context

Here's a way to achieve it with Mintlify : https://mintlify.com/docs/settings/versioning

**Comment by maidul98** [comment]
This is something we can do going forward @Grraahaam. I have let the team know about this feature
