### ISSUE TITLE
Bad TTL in Machine Identity Secret Renders Web App Inoperable

### ISSUE THREAD

**Issue by alex0112** [Infisical/infisical#2098]
### Describe the bug
Setting a high TTL on a machine identity secret renders the app inoperable

### To Reproduce
1. Create a new machine identity
2. Generate a secret associated with the machine identity
3. Set the TTL to 9999999999 or similar
4. Observe the error that pops up in a toast notification, and refresh the page to produce the screenshots below

### Expected behavior
Either a limit on the TTL 

### Screenshots

![image](https://github.com/Infisical/infisical/assets/7142972/f93d006d-b717-4e06-a97f-92d82915c2bc)

### Platform you are having the issue on:
Web App (Firefox). Self Hosted. 

### Additional context
Purely speculation on my part: but it seems that a bad value for the TTL gets written to the database and the front end app is unable to handle the high value when it tries to render the token again. At least that seems consistent with my observations.

**Comment by DanielHougaard** [comment]
Hi @alex0112

Thank you for the report. We have this on our internal todo list currently, we'll get back to you as soon as a fix for this is live!

**Comment by sheensantoscapadngan** [comment]
Hey @alex0112! This should be resolved now in the latest release
