### ISSUE TITLE
A way to inherit/replicate an environment

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#211]
### Feature description
Now that we are going to have custom environments it would be great to be able to inherit or replicate environments. For example, when I add a secret to one environment, I'd love to have the option to add it to the other ones too. Or, when a user creates an environment, it would be awesome to be able to fill in secrets based on a template from an existing environment (a user would only need to change secret values).

### Why would it be useful?
Saves people a lot of time and creates more 'automations'. Makes it easier to keep track of everything. 

### Additional context
I'm not sure how exactly it should look like yet, so open to any ideas!

**Comment by Zamion101** [comment]
Environments can be inherted with the methods mentioned in #154.

**Comment by akhilmhdh** [comment]
Secret inheritance is possible with secret imports thus issue is resolved
