### ISSUE TITLE
LICENSE.md missing in frontend/src/ee

### ISSUE THREAD

**Issue by hauskens** [Infisical/infisical#2118]
### Describe the bug
In the license it says:
`- All content that resides under any "ee/" directory of this repository, if such directories exists, are licensed under the license defined in "ee/LICENSE".`

In `backend/src/ee` there exists a license https://github.com/Infisical/infisical/blob/b582a4a06d9c981921a5918f568231eeef902598/backend/src/ee/LICENSE.md
There are no license file in `frontend/src/ee`,  I assume the same license is intended to be applied to that folder, but maybe there should be a copy of the license inside that folder too.

**Comment by akhilmhdh** [comment]
To be honest frontend doesn't need licensing. That was an old file and all the logic's for licensee happens in backend. Even if somebody modifies frontend for there need doesn't matter much.
