### ISSUE TITLE
Add error popup to notify users if there were any network issues while proccessing their request 

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#217]
On the frontend, if there are any network releated errors during save operation, the user is not notifed. This can cause confusion as users assume that their request has been successful when in some small cases it may not. 

To fix this we need to add either central http client error handling for the frontend or pop up messages individually for each api call.

**Comment by Gabriellopes232** [comment]
I would be very happy to resolve this issue!

**Comment by Gabriellopes232** [comment]
Can you sign it for me?

**Comment by mv-turtle** [comment]
Hi @Gabriellopes232! Sounds good! That would be awesome. Assigning this to you!
It might have merge conflicts with the changes that @akhilmhdh is making right now. I will text you in Slack!

**Comment by mv-turtle** [comment]
I just realized you might not be in our Slack. Could you please join? here is the link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

**Comment by Gabriellopes232** [comment]
Hi! I joined the slack community! I'm "Gabriel Nascimento" I await your message! Thanks @mv-turtle

**Comment by akhilmhdh** [comment]
This is completed with recent changes
