### ISSUE TITLE
Failed to create secret on self-hosted server

### ISSUE THREAD

**Issue by akfmdl** [Infisical/infisical#2189]
### Describe the bug
I built a self-hosted server using the Infisical Helm chart, and it's currently at version [0.4.2](https://artifacthub.io/packages/helm/infisical/infisical). During the upgrade process to the standalone chart 1.0.8, I successfully migrated from MongoDB to PostgreSQL by following [the documentation](https://infisical.com/docs/self-hosting/guides/mongo-to-postgres), and all the secrets were transferred correctly.

However, when trying to create a secret, I'm getting an error message saying "Failed to create secret," and the Infisical backend server logs show the following message. What could be the problem?
![image](https://github.com/user-attachments/assets/899a868e-1589-4000-bc8d-566e6e2e2c14)

{"level":50,"time":1722246206462,"pid":1,"hostname":"infisical-shelley-infisical-standalone-infisical-5dfd79c77brkwf","reqId":"req-7b","severity":"ERROR","req":{"method":"POST","url":"/api/v3/secrets/TEST","hostnam
e":"127.0.0.1:9999","remoteAddress":"127.0.0.1","remotePort":39026},"res":{"statusCode":500},"err":{"type":"Error","message":"Unsupported state or unable to authenticate data","stack":"Error: Unsupported state or u
nable to authenticate data\n    at Decipheriv.final (node:internal/crypto/cipher:193:29)\n    at decryptSymmetric128BitHexKeyUTF8 (file:///backend/dist/lib/crypto/encryption.mjs:50:25)\n    at buildSecretBlindIndex
FromName (file:///backend/dist/lib/crypto/encryption.mjs:87:12)\n    at generateSecretBlindIndexBySalt (file:///backend/dist/services/secret/secret-fns.mjs:10:34)\n    at file:///backend/dist/services/secret/secret
-service.mjs:127:87\n    at Array.map (<anonymous>)\n    at fnSecretBlindIndexCheck (file:///backend/dist/services/secret/secret-service.mjs:127:63)\n    at Object.createSecret (file:///backend/dist/services/secret
/secret-service.mjs:205:42)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.handler (file:///backend/dist/server/routes/v3/secret-router.mjs:720:22)"},"msg":"
Unsupported state or unable to authenticate data"}

**Comment by KastanDay** [comment]
I'm facing a similar issue. 

It works with the template .env, but when I use my own encryption keys it fails.

I followed [these instructions](https://infisical.com/docs/self-hosting/configuration/envars) to generate my encryption keys, but no luck. 
```
ENCRYPTION_KEY
Must be a random 16 byte hex string. Can be generated with openssl rand -hex 16

AUTH_SECRET
Must be a random 32 byte base64 string. Can be generated with openssl rand -base64 32
```

```
infisical-backend       | Environment variable replacement is the same, skipping..
infisical-backend       | Environment variable replacement is the same, skipping..
infisical-backend       | Replacing pre-baked value..
infisical-backend       | Telemetry is enabled
infisical-backend       | (node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
infisical-backend       |
infisical-backend       | Please migrate your code to use AWS SDK for JavaScript (v3).
infisical-backend       | For more information, check the migration guide at https://a.co/7PzMCcy
infisical-backend       | (Use `node --trace-warnings ...` to show where the warning was created)
infisical-backend       |
infisical-backend       | {"level":30,"time":1723070882573,"pid":1,"hostname":"b9c35626da4c","severity":"INFO","msg":"KMS: Encrypted ROOT Key found from DB. Decrypting."}
infisical-backend       | {"level":50,"time":1723070882574,"pid":1,"hostname":"b9c35626da4c","severity":"ERROR","err":{"type":"Error","message":"Unsupported state or unable to authenticate data","stack":"Error: Unsupported state or unable to authenticate data\n    at Decipheriv.final (node:internal/crypto/cipher:193:29)\n    at Object.decrypt (file:///backend/dist/lib/crypto/cipher/cipher.mjs:39:16)\n    at Object.startService (file:///backend/dist/services/kms/kms-service.mjs:615:39)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async registerRoutes (file:///backend/dist/server/routes/index.mjs:1028:3)"},"msg":"Unsupported state or unable to authenticate data"}
infisical-backend exited with code 0
```

**Comment by KastanDay** [comment]
This fixed it for me: 

```
sudo docker-compose -f docker-compose.prod.yml down --volumes
sudo docker-compose -f docker-compose.prod.yml up --build
```

I think I just had to delete the volumes that were created with the demo encryption keys.
