### ISSUE TITLE
Label and placeholder are displaying two different actions

### ISSUE THREAD

**Issue by Vishvsalvi** [Infisical/infisical#2214]
### Describe the bug
The label instructs to type "delete" whereas the placeholder says "confirm". Both should have same instructions.

### To Reproduce
1. Create a secret
2. Click on delete secret.
3. The modal will appear.

### Expected behavior
The placeholder should display the deleteKey value

### Screenshots
![image](https://github.com/user-attachments/assets/fcf192db-1d43-4c4e-b49c-245194fb26ae)

## How to fix ?
![image](https://github.com/user-attachments/assets/5d09903e-a20a-44c6-8938-ac63a175a3b2)
Replace the placeholder from "Type confirm" -> {Type ${deleteKey}}  ( In string literals )

**Comment by akhilmhdh** [comment]
Good catch. @Vishvsalvi feel free to open a PR happy to get it merged
