### ISSUE TITLE
Add pagination to secrets dashboard to reduce lag  

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#2224]
### Feature description
Right now, all secrets are fetched in at a given secret path. However, when the number of secrets goes past 500, the UI will start o lag. In order to resolve this, we need to introduce pagination so that each page is limited to the number of secrets it can show. All search and download functions must work as expected as apart of this change.

**Comment by Vishvsalvi** [comment]
Is this feature approved? If yes, I can get started

**Comment by sambhav2612** [comment]
hey @Vishvsalvi are you still working on this?

**Comment by Vishvsalvi** [comment]
Yes I'm working on this one

**Comment by MuhmdAjeer** [comment]
hey @Vishvsalvi, are you working on this still ?

**Comment by Vishvsalvi** [comment]
Yes, I'm figuring few things out if I don't make a PR by 18th I'll unassign it by myself.

**Comment by Anonymous961** [comment]
@maidul98 does this look good? 
![image](https://github.com/user-attachments/assets/1d1fc5a9-06b9-4c13-93f7-e2d26818df1d)
![image](https://github.com/user-attachments/assets/4f04166f-83cb-4f40-be0b-e09ee7514f47)
can I make a PR?

**Comment by Anonymous961** [comment]
Hey @maidul98, I've raised a PR. I would like to have a code review if anything is wrong.

**Comment by VenkateshSircilla123** [comment]
I would like to work on this issue can i?

**Comment by akhilmhdh** [comment]
This feature has been released and now available.
