### ISSUE TITLE
Add tags filter support for secrets v3 API

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#2229]
### Feature description
Users should be able to send a list of tags to filter secrets by in the v3 secrets API. This will then be consued by clients such as CLI.

**Comment by JeetPatel1016** [comment]
Hi @maidul98, I'd like to work on this feature.

**Comment by ritikjadhav** [comment]
Hi @maidul98,

I've almost completed this issue. Could you please assign it to me?

**Scope:** A list of tags will be passed as query parameters to filter secrets in the v3 secrets API. (Let me know if this needs any modifications.)

**Implementation:**
1. Accept tags as query parameters.
2. Pass the tags to the service layer and filter the secrets based on the provided tags.

<img width="1440" alt="api:v3:secrets" src="https://github.com/user-attachments/assets/442aa157-2370-412f-98cf-72522d998fff">

Thank you!

**Comment by akhilmhdh** [comment]
Hey @ritikjadhav 

Due to customer requirements we had to wrap this up quickly. Apologizing for the confusion caused. 

Let me know if you want to work on any other issue. Will be happy to help you with that

**Comment by ritikjadhav** [comment]
Hi @akhilmhdh,

Sure, no problem.

Can you please assign me issue #2241?

Is there a priority list for the issues, so I can pick accordingly?
