### ISSUE TITLE
Ability to select all secrets on dashboard

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#2241]
### Feature description
Right now, you can only select secrets one by one. However, this can take a long time if you want to for example delete many secrets at once. Being able to select all secrets in one go would help solve this issue.

<img width="1619" alt="CleanShot 2024-08-05 at 21 24 26@2x" src="https://github.com/user-attachments/assets/ff783074-c03e-47c8-b5d2-24821a8675b6">

**Comment by macci001** [comment]
Hello @maidul98 , can I take this up?

**Comment by macci001** [comment]
The PR is in review

**Comment by saloni0419** [comment]
@maidul98 Can you please assign me this issue

**Comment by pushkar707** [comment]
@maidul98 Can I take up this issue? The PR linked with this issue seems to be invalid, as its not merged till date

**Comment by maidul98** [comment]
This is already possible
