### ISSUE TITLE
Failed to update via apk update when updating alpine repository metadata cache with cloudsmith packages

### ISSUE THREAD

**Issue by kylianbrun** [Infisical/infisical#2247]
### Describe the bug
Since 2 hours ago, my gitlab pipeline is not working anymore because of alpine cloudsmith infisical package installation.

### To Reproduce
Follow Infisical alpine install : 
https://infisical.com/docs/cli/overview

### Screenshots
![image](https://github.com/user-attachments/assets/cc243f96-e75c-4b52-a10d-45905ba2ea36)

### Platform you are having the issue on:
Gitlab CE runner with alpine:latest image

**Comment by Merton** [comment]
Same issue here, `node:18-alpine`, and v3.2.0 https://dl.cloudsmith.io/public/infisical/infisical-cli/alpine/v3.20/main is failing with BAD signature.

**Comment by huynextlevel** [comment]
I got the same issue too

**Comment by lskillen** [comment]
Hey folks 👋 Lee from Cloudsmith here. We host the APK packages (and others) for Infiscal.

Earlier, we had an issue with public keys being fetched for Alpine installations when using `setup.sh`:
https://status.cloudsmith.io/incidents/sz9jqlhjk3z5

This has been fixed now, so any re-runs should see the problem clear up. If you DO get any issues, drop us a line. :)

**Comment by maidul98** [comment]
Thanks for dropping by @lskillen, much appreciated
