### ISSUE TITLE
[Dashboard]: Ability to import multiple environment variables at once

### ISSUE THREAD

**Issue by veritem** [Infisical/infisical#2257]
### Feature description
using the dashboard right now, there is no way to import/add more than one environment variable. I would like to request adding support to import, let's say, everything from `.env` at once. 

### Why would it be useful?

It'd be a great user experience improvement for people who work on multiple projects. It's currently a pain in the butt, having to add one environment variable at a time.

**Comment by Ayush-Dutt-Sharma** [comment]
@veritem can i take this

**Comment by akhilmhdh** [comment]
@veritem We already support uploading via .env. Sorry are you talking about the secret overview page. If so that is expected

![Screenshot 2024-08-11 at 7 20 48 PM](https://github.com/user-attachments/assets/0c5f8f63-c8a6-4b76-b5f6-fff961975717)

**Comment by veritem** [comment]
> @veritem We already support uploading via .env. Sorry are you talking about the secret overview page. If so that is expected
> 
> ![Screenshot 2024-08-11 at 7 20 48 PM](https://private-user-images.githubusercontent.com/31166322/356882282-0c5f8f63-c8a6-4b76-b5f6-fff961975717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODYyOTcsIm5iZiI6MTcyMzM4NTk5NywicGF0aCI6Ii8zMTE2NjMyMi8zNTY4ODIyODItMGM1ZjhmNjMtYzhhNi00Yjc2LWI1ZjYtZmZmOTYxOTc1NzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE0MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMjg1YTIxNzhhM2RkNmU2YjVlYTEzMzcwMjRhOGUyNWRjNWMxMzczYmZiYjY3OGZjZTE0ODJlZjBhYzk3ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9eQcRynSbC23_VU97rh56LdMrcYpEDXADfXy504whKE)

on the secrets overview page :D 

i didn't know this existed

**Comment by akhilmhdh** [comment]
@veritem that is expected secret overview page  is for reference more complex secret operation happens inside the main page
