### ISSUE TITLE
Changes not reflecting on the project preview (frontend)

### ISSUE THREAD

**Issue by Vishvsalvi** [Infisical/infisical#2309]
### Describe the bug
Changes made in frontend dev mode not reflected in the docker container ( Windows specific problem )

### To Reproduce
Just run the docker containers using docker-compose -f docker-compose.dev.yml up --build --force-recreate

### Expected behavior
Upon making changes in the code editor for frontend the changes should be reflected on the project.

### Steps to fix ? 

![image](https://github.com/user-attachments/assets/05ec1091-85c5-4caf-9f50-f61a2f8b8eab)

Add   `- WATCHPACK_POLLING=true` in docker.compose.dev.yml file in the frontend service (as shown on line 110).

**Comment by akhilmhdh** [comment]
Is your using WSL please move it inside your WSL namespace.

**Comment by Vishvsalvi** [comment]
I'm not using WSL

**Comment by akhilmhdh** [comment]
I guess this is a nextjs issue. Feel free to raise a PR

**Comment by Vishvsalvi** [comment]
@akhilmhdh the above PR will close this issue
