### ISSUE TITLE
A way to inherit/propagate secrets between environemnts

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#232]
### Feature description
A toggle for having the same env variable values in multiple environments. Certain projects are quite big and it would be much easier to handle if users could toggle some secrets to have the same value synced between dev prod and staging etc

### Why would it be useful?
This would save a lot of time for the Infisical users, and make it easier to manage large projects

**Comment by akhilmhdh** [comment]
With release of [secret import feature, reference](https://infisical.com/docs/documentation/platform/secret-reference#import-entire-folders) and providing a copy from another environment feature in dashboard this issue has been resolved and can be closed.
