### ISSUE TITLE
An admin can't see a project created by another admin

### ISSUE THREAD

**Issue by vhartmannselfee** [Infisical/infisical#2337]
Hello,

Infisical version: 0.67.1

If an admin A create a project, another admin B can't see this project. Admin A needs to add manually Admin B user to this project, It's normal ?

Thanks for your help,

Best regards,

**Comment by Vishalll07** [comment]
how do i recreate this in my local setup

**Comment by vhartmannselfee** [comment]
@Vishalll07 in kubernetes install Infisical version 0.67.1, 

Create an admin account, create a project toto, and create another account admin,

Try to connect with this other account admin and try to see project toto

**Comment by akhilmhdh** [comment]
Yes its expected behavoir. An admin cannot see another  project unless added from the overview page. 

If another admin from an organization wants to access the project you can use the org admin panel and then get access to it. 

<img width="506" alt="Screenshot 2024-09-04 at 4 18 14 PM" src="https://github.com/user-attachments/assets/d355eaa8-aec2-4a3a-bea9-c8d45a249dda">
