### ISSUE TITLE
cert-manager integration

### ISSUE THREAD

**Issue by evilezh** [Infisical/infisical#2338]
I'm wondering where is cert-manager integration.
Cert-manager i guess one of most popular piece of software used to manage certificates in kuberentes. There are quite a lot integrations including vault. 
I know probably this should be posted in cert-manager, but as it is product specific, I feel it is better discussed here.

**Comment by dangtony98** [comment]
Hey @evilezh!

We've just released the first version of the Infisical PKI Issuer which should work alongside `cert-manager` to manage certificates in Kubernetes.

You can check it out [here](https://infisical.com/docs/documentation/platform/pki/pki-issuer).
