### ISSUE TITLE
INTERNAL_SERVER_ERROR: We are encounter with 500 in one of the projects "notification" 

### ISSUE THREAD

**Issue by AhmedBHameed** [Infisical/infisical#2339]
### Describe the bug

In our company, we can't access the environment for a specific project "notification" for the `workspaceId: 65a90f48ba0beb5ca0160b32`

### To Reproduce

If you call this cURL, you will find that it failes with 500

**TOKEN IS HIDDEN IN THE FOLLOWING CURL CALL**

```txt
curl 'https://app.infisical.com/api/v3/secrets/raw?environment=qa&workspaceId=65a90f48ba0beb5ca0160b32&secretPath=%2F' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,ar;q=0.8,de;q=0.7' \
  -H 'authorization: Bearer <HIDDEN_TOKEN>' \
  -H 'cache-control: no-cache' \
  -H 'cookie: <HIDDEN_COOKIES>' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://app.infisical.com/project/65a90f48ba0beb5ca0160b32/secrets/overview' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36'
```
Response
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Unsupported state or unable to authenticate data"
}
```

### Expected behavior

I should see the GUI to be able add/delete environments. Note that the other projects works perfectly.

### Screenshots

![image](https://github.com/user-attachments/assets/b1731c25-448b-44ed-8318-fb95abd88432)

### Platform you are having the issue on:

https://app.infisical.com/project/65a90f48ba0beb5ca0160b32/secrets/overview

### Additional context

We assume this is something with the platform not with the data entry. We are able to fetch the environment variables via node sdk "infisical-node". But still we can see the environments in the GUI.

**Comment by maidul98** [comment]
Hey @AhmedBHameed , can you please try to see if you can view the secrets now?

**Comment by AhmedBHameed** [comment]
Hey @maidul98 

I can confirm it works perfectly now!
Thank you so much for your kind support. Going to close this ticket.
