### ISSUE TITLE
PKI generated certificates are not considered as trusted even if root CA added to the trust store. 

### ISSUE THREAD

**Issue by pdomineaux** [Infisical/infisical#2346]
### Describe the bug
When creating certificate with the new PKI feature, the certificate are not valid for Chrome but are OK for Safari.

### To Reproduce
1. Create a CA
2. Create Certificate with SANs (fqdn only as IP Addresses are not valid in the field)
3. Get both root CA and server certificate
4. Import the Root CA into the keychain and set the Trust to "Always Trust"
5. Set the private key and cert to the server
6. Add the entry in /etc/hosts to match fqdn
7. Browse to the server fqdn

### Expected behavior
I expect the certificate to be trusted by my browser

### Platform you are having the issue on:
I'm using Infisical self-hosted with version 0.80.0-postgres

### Additional context

It work on Safari.

With Firefox: 
    Warning: Potential Security Risk Ahead
    but I can accept the exception and continue browsing
    
    
With Chrome, browsing is not possible:
    server.local normally uses encryption to protect your information. When Chrome tried to connect to server.local this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be server.local, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit server.local right now because the website sent scrambled credentials that Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by dangtony98** [comment]
Thanks for raising this issue @pdomineaux.

I'll be looking into this as we continue working on the new PKI feature — I don't have an estimated time frame for resolution yet given there're a lot of ongoing development but will keep you posted.

**Comment by pdomineaux** [comment]
To complete my issue.
I've tested the certs with openssl:

```
openssl verify -CAfile MyRootCert.pem -untrusted MyIntermediateCert.pem server.pem
servercert.pem: OK
```
But I still get the Chrome/Brave Browser error:
`net::ERR_CERT_INVALID`

**Comment by gs-kug** [comment]
I'm facing the same issue, and the certificate propose is not matching the intention usage (not sure what is the right code here)

![image](https://github.com/user-attachments/assets/0c47a535-f3fe-451a-ae3e-24d9ef37d99d)

![image](https://github.com/user-attachments/assets/62e136d1-dddd-4ba8-93de-f80df493327f)

Second image is in portugues. Translating: "This certificate or certificate chain are not valid for the usage mode intended."

**Comment by gs-kug** [comment]
As reference if you pick any valid certificate it should show a valid code:

![image](https://github.com/user-attachments/assets/f65781b9-f40b-4b8c-b676-fdf3d113be38)

**Comment by gs-kug** [comment]
Oh, this is happening through the chain. So anyone using this feature will need to rotate or delete all CA certificates, reisuing everything... I think you guys should add a warning on the document page that this feature is experimental. This kind of bug is an oversight, and imagine a big company root CA deployment. It would be a mess.
Please let me know if I'm wrong here.
![image](https://github.com/user-attachments/assets/74860403-e2ea-428f-b7d8-445449f277cb)

**Comment by sheensantoscapadngan** [comment]
Hey @pdomineaux @gs-kug! We've pushed an update that fixes the EKU's configured in the root CAs which should resolve this issue. You will have to renew your root CAs and migrate towards that new root certificate. Additionally, you can now configure the key usage and extended key usage extensions of certificates during the issuance flow. You should now be able to customize the extensions as needed. 


 This is indeed an oversight on our end.

**Comment by pdomineaux** [comment]
Thank you for your responsiveness.
It works like a charm. 
I had to : 
- include the chain in the leaf certificate for this to work as I 've only add the ROOT CA in my trust store.
- be sure to add the Common Name (CN) (i.e server-01.leaf.local) also in the Alternative Names (SANs).

If you don't add the last one, there will be an error saying that the **certificate's name does not match** if you try to access the server with the Common Name.
