### ISSUE TITLE
Infisical CLI Login fails with long password

### ISSUE THREAD

**Issue by Makisuo** [Infisical/infisical#236]
### Describe the bug
When trying to login to the cli with a password that is too long it fails with 
Hmm, we ran into an error: crypto/aes: invalid key size 51

### To Reproduce
1. Change to a password with a length of 51
2. Try to login in to the cli

### Expected behavior
Being able to login

### Screenshots
<img width="444" alt="image" src="https://user-images.githubusercontent.com/31933546/212949037-4eaa2655-3862-4056-b86b-78f1bebac73f.png">

**Comment by devblin** [comment]
Hey @maidul98 , I would like to work on this bug.

**Comment by dangtony98** [comment]
Hey @devblin!

We're releasing an update in a few days actually to the auth process; the patch is already there — just need to merge it soon once we've finalized it.

**Comment by mv-turtle** [comment]
I think this has now been fixed
