### ISSUE TITLE
infisical - docker won't login even if token exists and valid

### ISSUE THREAD

**Issue by danieltamas** [Infisical/infisical#2369]
### Describe the bug
When running infisical inside a docker ( Dockerfile ) this error prevents 
successful start:

```
It looks you have not yet connected this project to Infisical                                                                                                                                                             
To do so, run [infisical init] then run your command again
```

### To Reproduce
1. Follow the steps here https://infisical.com/docs/integrations/platforms/docker-intro
2. Update Dockerfile
3. Update docker-compose.yaml
4. docker compose up -d --build

### Expected behavior
The env vars should be fed in the build process

### Platform you are having the issue on:
Docker, node:20.9.0

### Additional context - the Dockerfile
```
FROM node:20.9.0

WORKDIR /app

ARG INFISICAL_API_URL
ARG INFISICAL_PROJECT_ID
ARG INFISICAL_MACHINE_IDENTITY_CLIENT_ID
ARG INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET

# Set environment variables
ENV INFISICAL_API_URL=${INFISICAL_API_URL}
ENV INFISICAL_PROJECT_ID=${INFISICAL_PROJECT_ID}
ENV INFISICAL_MACHINE_IDENTITY_CLIENT_ID=${INFISICAL_MACHINE_IDENTITY_CLIENT_ID}
ENV INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET=${INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET}

RUN apt-get upgrade -y
RUN apt-get update -y
RUN apt-get install -y nano perl python3 make g++ bash curl

# Install Infisical CLI
RUN curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash \
    && apt-get update && apt-get install -y infisical

# Authenticate with Infisical CLI and retrieve the token
RUN INFISICAL_TOKEN_NAME=$(infisical login --method=universal-auth \
    --client-id=${INFISICAL_MACHINE_IDENTITY_CLIENT_ID} \
    --client-secret=${INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET} \
    --plain --silent) \
    && echo "INFISICAL_TOKEN_NAME=$INFISICAL_TOKEN" >> /root/.bashrc

ENV INFISICAL_TOKEN_NAME=${INFISICAL_TOKEN_NAME}

# Copy application files
COPY ./app /app
RUN chmod 644 /app/yarn.lock

RUN yarn

# Generate Prisma schemas
RUN npx prisma generate --schema prisma/admin/schema.prisma
RUN npx update-browserslist-db@latest

RUN yarn build

EXPOSE 3000

# Run the application with Infisical
CMD infisical run --token="${INFISICAL_TOKEN_NAME}" --env="prod" --projectId="${INFISICAL_PROJECT_ID}" --path="/env" -- yarn start
````

Tried with both `INFISICAL_TOKEN` ( as per docs ) and `INFISICAL_TOKEN_NAME` as per [PR#1844](https://github.com/Infisical/infisical/pull/1844)

As of now, the Docker won't start ( tried a lot of combinations ) and Infisical is unusable in `prod`.
Dev works just fine

**Comment by akhilmhdh** [comment]
@danieltamas There is no `INFISICAL_TOKEN_NAME` the one your referring is a golang [variable name[(https://github.com/Infisical/infisical/blob/1a11dd954b397bfd95dc5d009d341b694bae7d2a/cli/packages/util/constants.go#L9).

The only value is INFISICAL_TOKEN itself. Your issue is mixing up with Dockerfile and a docker starting script. 

I don't think you can set environment variables like as it will be empty when you do docker run.

**Comment by danieltamas** [comment]
I see. thanks for the explanation. The above is based on the docs https://infisical.com/docs/integrations/platforms/docker 
I am using `docker compose` to start the container and have the vars. The other guides did not work so far

**Comment by danieltamas** [comment]
The instructions found here are either incomplete or missleading 
https://infisical.com/docs/integrations/platforms/docker-compose

What is the purpose of adding these to `docker-compose`?

```
environment:
      - INFISICAL_MACHINE_IDENTITY_CLIENT_ID=${INFISICAL_MACHINE_IDENTITY_CLIENT_ID_FOR_WEB}
      - INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET=${INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET_FOR_WEB}
 ```
 
nothing happens

**Comment by Niklas-Mezynski** [comment]
Same issue here. 
I personally think the docs are not clear about the docker compose usage. In the [Docker Entrypoint page](https://infisical.com/docs/integrations/platforms/docker) it says I have to:
1. Obtain an access token for the machine identity (on the host)
2. Feed the access token to the docker container using the INFISICAL_TOKEN env variable

While on the [Docker Compose page](https://infisical.com/docs/integrations/platforms/docker-compose) I should add the `INFISICAL_MACHINE_IDENTITY_CLIENT_ID ` and `INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET `. 
Can I assume that when these are present, the CLI can automatically generate a token?

In the end I did not manage to get it to wwork (both trying to generate the token myself nor setting the client id and secret)

**Comment by danieltamas** [comment]
Got it, thanks for the explanation. Ended up getting the token before `docker compose` and feeding it to the container.
