### ISSUE TITLE
Modifying default project roles

### ISSUE THREAD

**Issue by Badbird5907** [Infisical/infisical#2370]
### Feature description
Allow users to modify the permissions of default roles.

For example, we want to limit the developer role to view/modify only dev and staging, and allow admin to access dev, staging, and production.

### Why would it be useful?
This would allow more flexibility for users to configure access controls to how they see fit, without needing to create new roles with names that may clash with the immutable default roles.

### Additional context
N/A

**Comment by ngethan** [comment]
Would love to see this as well!

**Comment by akhilmhdh** [comment]
@Badbird5907 You have to create a new role to override default one. 

Its an expected behavoir. Those are predefined ones, like Github if you roles
