### ISSUE TITLE
Bug Report: Infisical CLI Token Not Recognized in Docker Environment

### ISSUE THREAD

**Issue by nmnandakishore-ordrio** [Infisical/infisical#2381]
​
Hello,

I am reaching out to report an issue I am encountering while using the Infisical CLI in my CI pipeline setup with GitHub Actions and Docker. The access token generated during the GitHub Actions workflow is not being recognized within the Docker container, leading to authentication issues.

I've attached the key sections of my Dockerfile and GitHub Actions workflow. (I have removed the actual keys and placed template from file. But these files represent the actual relevant structure.)

## Issue Encountered:
**Expected Behavior:** I expect that the Infisical CLI would recognize the token passed during the Docker build and allow the application to run without requiring a login.
**Actual Behavior:** I receive an error indicating that I must be logged in to run the command, despite the token being generated and passed.

## Additional Context:
The machine identity used has the appropriate permissions and is linked to the correct project.
I have verified that the client ID and client secret are correct.
The issue persists regardless of the environment (Azure or Porter.run).

*What I have tried so far:*

I have tried to run the command with inline universal login.
`CMD [ "/bin/sh", "-c", "infisical run --token=$(infisical login --domain=$INFISICAL_API_URL --method=universal-auth --client-id=$CLIENT_ID_INFISICAL --client-secret=$CLIENT_SECRET_INFISICAL --silent --plain) --projectId $PROJECT_ID --env $INFISICAL_SECRET_ENV --domain $INFISICAL_API_URL -- npm run start"] `

I have tried to login through a separate command. Set the token received to an environment variable and then pass it to the `infisical run` command through a parameter.

`RUN INFISICAL_TOKEN=$(infisical login --domain $INFISICAL_API_URL --method=universal-auth --client-id $CLIENT_ID_INFISICAL --client-secret $CLIENT_SECRET_INFISICAL --silent --plain) && \
    echo $INFISICAL_TOKEN && \
    echo "Exporting INFISICAL_TOKEN" && \
    echo $INFISICAL_TOKEN > /tmp/token.txt
ENV INFISICAL_TOKEN=/tmp/token.txt`

`CMD [ "/bin/sh", "-c", "infisical run --token $INFISICAL_TOKEN --projectId $PROJECT_ID --env $INFISICAL_SECRET_ENV --domain $INFISICAL_API_URL -- npm run start -b swc"]`

I would greatly appreciate any guidance or solutions you can provide regarding this issue. Thank you for your assistance. Attached how my dockerfile looks like.

```dockerfile
# Start with the official Node.js Docker image
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Installing Infisical
RUN apk add --no-cache bash sudo
RUN apk --no-cache add curl
RUN curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash
RUN apk update && sudo apk add infisical

# Set environment variables
ENV CLIENT_ID_INFISICAL <YOUR_CLIENT_ID>
ENV CLIENT_SECRET_INFISICAL <YOUR_CLIENT_SECRET>
ENV INFISICAL_API_URL <YOUR_INFISICAL_API_URL>
ENV PROJECT_ID <YOUR_PROJECT_ID>
ENV INFISICAL_SECRET_ENV dev
ENV INFISICAL_DISABLE_UPDATE_CHECK true

# Attempt to login and set token
#Option 1:
# RUN export INFISICAL_TOKEN=$(infisical login --domain=$INFISICAL_API_URL --method=universal-auth --client-id=$CLIENT_ID_INFISICAL --client-secret=$CLIENT_SECRET_INFISICAL --silent --plain)

#Option 2:
RUN INFISICAL_TOKEN=$(infisical login --domain $INFISICAL_API_URL --method=universal-auth --client-id $CLIENT_ID_INFISICAL --client-secret $CLIENT_SECRET_INFISICAL --silent --plain) && \
    echo $INFISICAL_TOKEN && \
    echo "Exporting INFISICAL_TOKEN" && \
    echo $INFISICAL_TOKEN > /tmp/token.txt
ENV INFISICAL_TOKEN=/tmp/token.txt


# Command to run the application
CMD [ "/bin/sh", "-c", "infisical run --token $INFISICAL_TOKEN --projectId $PROJECT_ID --env $INFISICAL_SECRET_ENV --domain $INFISICAL_API_URL -- npm run start -b swc"]

```

**Comment by akhilmhdh** [comment]
@nmnandakishore-ordrio I am a bit confused. Isn't the value of the token from your option2 is `/tmp/token.txt`

Also I. don't think option 1 will work. Your mixing up docker file with your starting script. What you have to do is create a custom start script and move this logic towards there, for option 1 to work.

**Comment by nmnandakishore-ordrio** [comment]
@akhilmhdh, Option1 was working very well for me until the end of august.

I tried with `RUN export INFISICAL_TOKEN=$(cat /tmp/token.txt)` and `ENV INFISICAL_TOKEN=$(cat /tmp/token.txt)` as well. Didn't help in any way.

The Infisical login command prints the token locally and doesn't print anything on the server. (Attached screenshots.)

![image](https://github.com/user-attachments/assets/3f784700-5e92-4e9e-9985-138676a6d4ab)
![image](https://github.com/user-attachments/assets/91c02dbf-41d5-4d2d-80c6-26bafc6b7880)
