### ISSUE TITLE
Machine Identity Secret Token disappear even if TTL set to 0

### ISSUE THREAD

**Issue by meilleur102** [Infisical/infisical#2393]
Hi. 
I just reinstall Infisical after a server change and I have a problem with the Machine Identity Token. 
Even if I set the TTL and number of use to 0 it disappear after about 24 hours. 
Is it a known issues with the latest image or it's a misconfiguration on my end? 

Ive decided to do a fresh install so it's all new docker images / OS, and during my testing on the "old" server, I don't recall having this issues. 
I can't recall the version that I had unfortunately but it was a couple of week ago so not old. 
If you need more info let me know. 
(PS : I just did a docker compose up --build so I have the latest image from this morning) 
Thanks

**Comment by akhilmhdh** [comment]
Hey @meilleur102 

Is this still happening. Can you please check it again. Also can you share me the version your in?

**Comment by jorgelon** [comment]
I also have some issues about a machine identity client secret that dissapears. Twice in the last 2 weeks. I am using v0.81.1-postgres

i will search in the database to see the expiration of the client secret
no relevant info in the infisical pod

**Comment by jorgelon** [comment]
I have found in the identity_ua_client_secrets table a client token with "isClientSecretRevoked" as enabled.
Lets keep investigating.
What reasons can cause this?

![image](https://github.com/user-attachments/assets/a46b6a04-c62d-4ea5-9c09-3f902491d786)

**Comment by akhilmhdh** [comment]
@jorgelon Can you please try updating to the latest image and checking it out once again. We did made some couple of patches

**Comment by jorgelon** [comment]
Ok, next week I will update to the latest release available.
Is there any place to see the reason why the clientsecret was revoked? Or is just a bug?
