### ISSUE TITLE
[bug]: AWS IAM secret rotation is not working

### ISSUE THREAD

**Issue by ThallesP** [Infisical/infisical#2402]
### Describe the bug
I'm encountering problems with IAM user credential rotation. It only works on creation, manual rotation is broken, and doesn't sync those credentials to my Railway integration. 

### To Reproduce
1. Create a secret rotation for IAM on self hosted
2. Request to a manual rotation

### Expected behavior
It should rotate the secret and sync those changes to other integrations

### Video
![2024-09-10-11-48-54](https://github.com/user-attachments/assets/6688f67c-1e1f-402e-b2f8-336376eae535)

### Additional context
And also, I suspect the Railway integration won't trigger a service redeploy when credentials change, potentially leaving old variables in use until the next manual deploy.

**Comment by akhilmhdh** [comment]
@ThallesP Can you just verify the value in dashboard is changing or is it remaining as it?

**Comment by ThallesP** [comment]
> @ThallesP Can you just verify the value in dashboard is changing or is it remaining as it?

Yes, I verified on Infisical and AWS and both stayed the same.

**Comment by Kevin222004** [comment]
@akhilmhdh I want to work on this issue.

**Comment by Kevin222004** [comment]
I want to work on this.

**Comment by akhilmhdh** [comment]
Manual rotation issue has been fixed in our recent release
