### ISSUE TITLE
WORKFLOW_SLACK_CLIENT_ID & WORKFLOW_SLACK_CLIENT_SECRET incorrectly set as NOT optional?

### ISSUE THREAD

**Issue by preteckdotdev** [Infisical/infisical#2428]
### Describe the bug
When following https://infisical.com/docs/self-hosting/deployment-options/docker-compose the following error is received:

```
infisical-backend       | {"level":50,"time":1726390829183,"pid":1,"hostname":"a85a70e8b7d6","severity":"ERROR","msg":"Invalid environment variables. Check the error below"}
infisical-backend       | {"level":50,"time":1726390829183,"pid":1,"hostname":"a85a70e8b7d6","0":{"code":"invalid_type","expected":"string","received":"undefined","path":["WORKFLOW_SLACK_CLIENT_ID"],"message":"Required"},"severity":"ERROR"}
infisical-backend exited with code 0
```

### To Reproduce
1. Follow https://infisical.com/docs/self-hosting/deployment-options/docker-compose
2. Receive error above on docker-compose up with the infisical-backend constantly restarting.

### Expected behavior
infisical-backend should start as expected.

### Screenshots
N/a

### Platform you are having the issue on:
Debian 12

### Additional context
It works in v0.83.0 - I imagine its related to this being added in v0.84.0:
feat: native slack integration by [@sheensantoscapadngan](https://github.com/sheensantoscapadngan) in [#2358](https://github.com/Infisical/infisical/pull/2358)

Specifically lines 150 / 151 in backend/src/lib/config/env.ts:
```
150: WORKFLOW_SLACK_CLIENT_ID: zpStr(z.string()).optional(),
151: WORKFLOW_SLACK_CLIENT_SECRET: zpStr(z.string()).optional()
```
  I'm don't have 100% confidence in my ability to discern the problem but should this not be be:
```
150: WORKFLOW_SLACK_CLIENT_ID: zpStr(z.string().optional()),
151: WORKFLOW_SLACK_CLIENT_SECRET: zpStr(z.string().optional())
```
Where the extra closing bracket z.string()) should be on the .optional())

**Comment by Rishabhg71** [comment]
@preteckdotdev I have confirmed the changes that you have suggested doesfix this issue
