### ISSUE TITLE
Run Infisical locally

### ISSUE THREAD

**Issue by YZD1997** [Infisical/infisical#2460]
使用
git clone https://github.com/Infisical/infisical && cd "$(basename $_ .git)" && cp .env.example .env && docker compose -f docker-compose.prod.yml up

**Comment by YZD1997** [comment]
![image](https://github.com/user-attachments/assets/36c45011-048e-4d0f-b648-a16ca3adb8e4)
![image](https://github.com/user-attachments/assets/207f6ec2-c923-4249-afab-f352def4b68e)
![image](https://github.com/user-attachments/assets/191718f7-87e0-4256-a5a4-add4e567716c)
Setting the environment variable still can't open the URL

**Comment by AmanNegi** [comment]
I am facing a similar issue, I am using docker and following the [docs](https://infisical.com/docs/contributing/platform/developing). 

## Issue

When running the docker command :

`docker compose -f docker-compose.dev.yml up --build --force-recreate`

I am facing this error:

![image](https://github.com/user-attachments/assets/c065d6ce-50a8-4222-bb19-8e5fa736d527)

> Yes, I have set the `.env` file by copying the `.env.example` file.

Followed by the above error I get this error as well when I try to access the `localhost:8080` frontend.

![image](https://github.com/user-attachments/assets/d0323b1c-3fc1-4dcb-90b9-950f23de71ee)

## Environment

- OS: Ubuntu 22.04
- Docker Client: 27.2.0

**Comment by akhilmhdh** [comment]
This has been fixed in our recent releases. The port is not 8080 please check the docker compose file. 

The default port is `80`
