### ISSUE TITLE
Terraform Integration

### ISSUE THREAD

**Issue by jffz** [Infisical/infisical#250]
### Feature description
Would be nice to have a terraform integration to read/write secrets.

### Why would it be useful?
This would allow to write terraform stacks using infisical regardless of the hosting platform

### Additional context
Need to be able populate / retrieve secrets from terraform

**Comment by asheliahut** [comment]
I have started the basis for this @maidul98 https://github.com/asheliahut/infisical-provider-terraform

If you want I can continue work on it until basically I have a lot more, but I hope that yall take ownership of it long term.

This is just a fun side project for me at night now lol

**Comment by maidul98** [comment]
haha this is awesome! Please do continue to work on it, a lot of people have been asking for this so it will be quite impactful. I can pick up on it once you want to hand it over

**Comment by maidul98** [comment]
@asheliahut  just checking in, let me know if you need my help on anything

**Comment by thehedgefrog** [comment]
+1 for this one as well, I use 1password as a source of truth and would love to leverage a Terraform provider to move secrets!

**Comment by maidul98** [comment]
We'll be adding documentation for the provider and update its APIs within the next sprint. Will keep you all in the loop

**Comment by ianwesleyarmstrong** [comment]
Hi @maidul98 - would it be possible to get a status update on this?

**Comment by maidul98** [comment]
terraform integration is now available  https://infisical.com/docs/integrations/frameworks/terraform!

**Comment by lae** [comment]
@maidul98 this request was also for writing secrets but I don't see that on the provider (nor any open issues regarding supporting it). [There are folks](https://teddit.rawbit.ninja/r/selfhosted/comments/12zb3m9/selfhosted_secrets_manager_or_something_alike/jhvnwgr/#c) who'd still want this, as reading secrets is only half the battle.

**Comment by maidul98** [comment]
A contributor was working on adding the ability to write secrets as well but I don't think he was able to finish that. Can you open a issue for writing secrets in terraform
