### ISSUE TITLE
Website is not Responsive on Web View

### ISSUE THREAD

**Issue by moizsheraz** [Infisical/infisical#2508]
![Capture](https://github.com/user-attachments/assets/a1fbca96-b589-4880-9c19-5af880246d3c)

**Comment by DavidGoyal** [comment]
can u pls tell how to reproduce the issue?

**Comment by moizsheraz** [comment]
> can u pls tell how to reproduce the issue?

Just simply open the website .

**Comment by FurquanAnwer** [comment]
@moizsheraz Could you please tell me what exactly made you think that the website is not responsive ? Because it seems to be working fine. Correct me if I am wrong.

**Comment by DavidGoyal** [comment]
> @moizsheraz Could you please tell me what exactly made you think that the website is not responsive ? Because it seems to be working fine. Correct me if I am wrong.

just open the website and see the navbar

**Comment by vmatsiiako** [comment]
Can't reproduce this right now. We will be revamping the website soon, so any issues should be less relevant.
