### ISSUE TITLE
[ENG-158] Ansible Integration

### ISSUE THREAD

**Issue by jffz** [Infisical/infisical#251]
### Feature description
An ansible module would allow to implement infisical within any ansible playbook with ease.

### Why would it be useful?
This would also allow for wider adoption

<sub>[ENG-158](https://linear.app/infisical/issue/ENG-158/ansible-integration)</sub>

**Comment by WladyX** [comment]
Maybe you can use the infisical cli and the ansible pipe lookup?
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pipe_lookup.html

**Comment by mv-turtle** [comment]
@WladyX I'm not that familiar with Ansible but that might be the way to go :)

**Comment by jffz** [comment]
This solution will require people to install infisical cli on the desired host in a separate way to then using it through a command executor.
I am not sure that people running ansible playbooks will want to do it this way; that's indeed the point of having an integration.
I don't have the need for this atm as I am using another solution but I am convinced that this would allow for a wider infisical adoption.

**Comment by WladyX** [comment]
I had the same expectations for the gitlab integration, I thought it was going to be an integration, but turns out it was just installing the cli in the pipeline, which is not necessary a bad way way to go.
So yeah, I agree a proper integration would be best, but until then we can work around that probably.

**Comment by dangtony98** [comment]
Hmm I'm not familiar with Ansible either (haven't used it) but will definitely look into that — There's a lot of integrations in the pipeline that we'll be adding in over the next quarter.

@WladyX The actual GitLab integration is coming soon 😄

**Comment by jon4hz** [comment]
Actually you can already use infisical to inject secrets to ansible by looking up environment variables in your playbook/template. 

```
{{ lookup('env', 'MY_INFISICAL_SECRET') }}
```

This will require you to execute ansible with the infisical cli like:

```
infisical run -- ansible-playbook myplaybook.yml
```

An alternative in a more ansible-native manner would be a custom lookup plugin, similar to `hashi_vault`. 
https://docs.ansible.com/ansible/latest/collections/community/hashi_vault/hashi_vault_lookup.html#ansible-collections-community-hashi-vault-hashi-vault-lookup

**Comment by vmatsiiako** [comment]
@jffz @WladyX @yodatak @nemccarthy @caedium @pemontto @vwbusguy @wesleynien we recently released support for Ansible with the docs available here: https://infisical.com/docs/integrations/platforms/ansible

I'm closing this issue for now, but let me know if you have any questions, thoughts, or issues.
