### ISSUE TITLE
Add "prettier-plugin-tailwindcss"

### ISSUE THREAD

**Issue by sanyamjain04** [Infisical/infisical#252]
### Automatic Class Sorting with Prettier 
It will sort the tailwind class names when we save the file.

## Why it is Useful?
- It brings consistency to the code.
- It is recommended by the creators of Tailwind.
- This plugin will improve the developer experience.

## ADITIONAL CONTEXT
https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Can I raise a PR?**

**Comment by sanyamjain04** [comment]
hey @maidul98  I want to work on that. Can I raise a PR ?

**Comment by maidul98** [comment]
Yeah, let's add it. Are you just adding it for frontend or both backend as well?

**Comment by sanyamjain04** [comment]
This plugin can be used only in the frontend as Tailwind is a CSS framework.
