### ISSUE TITLE
No identity with specified client ID was found while trying to log in using both API and Infisical CLI

### ISSUE THREAD

**Issue by JordanHoareau** [Infisical/infisical#2543]
I created my account today on Infisical SAAS Europe and generated the following client ID : 
![image](https://github.com/user-attachments/assets/bcd5f096-35fa-44bb-b480-26033154e028)

I ran the following command :
```
curl --request POST \
  --url https://app.infisical.com/api/v1/auth/universal-auth/login \
  --header 'Content-Type: application/json' \
  --data '{
  "clientId": "dbe...",
  "clientSecret": "27fc..."
}'
```

Or this one : 
`infisical login --method=universal-auth --client-id=dbe... --client-secret=27fc...`

Both returns a 404 :
`{"statusCode":404,"message":"No identity with specified client ID was found","error":"NotFound"}`

I created another account with another email and I had this same behaviour.

When I try to use only infisical login command : 
![image](https://github.com/user-attachments/assets/89340a28-52a2-4df0-8361-14df40c303bd)

And I follow the provided URL, I land on this : 
![image](https://github.com/user-attachments/assets/fac6fae2-6e01-45b1-bdb5-0a38839ba65c)

Might be related : when I open the "Usage & Billing" I land first on the correct page (I guess) but after 2 seconds I also land on the above page.

**Comment by JordanHoareau** [comment]
I just tried by creating a US account, it does work with the US account but not with the EU.

**Comment by maidul98** [comment]
If you created your universal auth in EU then you need to set the host to EU as well:

curl --request POST \
  --url https://eu.infisical.com/api/v1/auth/universal-auth/login \
  --header 'Content-Type: application/json' \
  --data '{
  "clientId": "dbe...",
  "clientSecret": "27fc..."
}'

**Comment by JordanHoareau** [comment]
Hi! Indeed! Thank you :)
