### ISSUE TITLE
Facing issue to setup project

### ISSUE THREAD

**Issue by shreyas4510** [Infisical/infisical#2596]
### Describe the bug
I have cloned the repo and after creating the .env file tried to setup the project using docker-compose it failed to load things as expected there is no UI loading on localhost:3000.

### To Reproduce
1. Clone the repo
2. Create .env file and copy the variables from documentation
3. Go to repo directory
4. docker compose -f docker-compose.dev.yml up --build --force-recreate

### Expected behavior
Project should be setup successfully

### Screenshots
![image](https://github.com/user-attachments/assets/89166afc-85cf-4b8a-8e6c-bb1cf394e0fd)

### Platform you are having the issue on:
Ubuntu

**Comment by akhilmhdh** [comment]
Closing as false error
