### ISSUE TITLE
Ordering when pushing and pulling is not kept

### ISSUE THREAD

**Issue by abdalem** [Infisical/infisical#26]
We have an issue in my team, when we add envs that depends on others, we need dependencies came after the source env, so sometime we reorder them, or even grouping them by microservice by adding comments (monorepo), but the order is absolutely not kept and same for comments. So each time we pull envs we have to reorder them and add comments.

To be honnest, commenting is not critical, but reordring each time the envs is really annoying.

**Comment by maidul98** [comment]
Are you adding your secrets via the UI or using our old NodeJS CLI?

**Comment by abdalem** [comment]
I tried with both and in the UI we cannot reorder (except A->Z - Z->A).

I am trying with the new CLI now, since i could not use it because of the email regex, that you have fixed.

**Comment by maidul98** [comment]
Ah i see, so you would like the ability to order your secrets and have them injected in that order?

**Comment by abdalem** [comment]
Yes exactly because I have some envs that depends on each other, example:
```
BASE_DOMAIN=something.localhost
SERVICE1_DOMAIN=s1.${BASE_DOMAIN}
SERVICE2_DOMAIN=s2.${BASE_DOMAIN}
```

**Comment by maidul98** [comment]
Oh i see, you would like to also reference environment variables created earlier. I'll let you know once we pick this task up.

**Comment by maidul98** [comment]
Good new, shell parameter expansion is now supported. It is on by default but you can turn it off with `--expand=false` on the run command. This is noted in the documentation here https://infisical.com/docs/cli/reference/run

Don't forget to update your CLI first! Let me know if you have any comments

**Comment by abdalem** [comment]
Excellent ! It is working.
