### ISSUE TITLE
Limit secret level visibility to specific role

### ISSUE THREAD

**Issue by michieriffic** [Infisical/infisical#261]
### Feature description
I've noticed that all the secrets are visible to each member of the team. In reality, not everyone in the team should have access to the keys, especially production level for security purposes.

Currently there are only two roles, admin and member, all of them have access to the secret's level. 

### Why would it be useful?
It would make their life easier because they don't need to create two projects to separate Prod key to Development-related keys.

PS Thanks for this great product! :)

**Comment by maidul98** [comment]
Thanks for bringing this up, @michieriffic. We are currently in the process of implementing more detailed access control measures, which will be available within the next one to two weeks. We'll keep you informed on its progress

**Comment by michieriffic** [comment]
Yw! The app is looking good and excited to use it :)

**Comment by maidul98** [comment]
You can now limit secret visibility by environment! Let us know if you have any questions. You can reach us quicker on slack https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g
