### ISSUE TITLE
Emergency Kit SIGN-IN URL doesn't match server URL

### ISSUE THREAD

**Issue by KNIF** [Infisical/infisical#263]
### Describe the bug
When self-hosting Infisical, the Sign-In URL shown on the PDF-File always is `https://app.infisical.com/login`, instead of the URL of the self-hosted server (set by the `SITE_URL` environment variable).

### To Reproduce
1. Self-host Infisical
2. Sign up for an account
3. Download the Emergency Kit
4. The URL shown will not match that of the server.

### Expected behavior
It should show the URL set by the `SITE_URL` environment variable.

### Screenshots
/

### Platform you are having the issue on:
Self-hosted

### Additional context
/

**Comment by KunalSin9h** [comment]
working on it!
