### ISSUE TITLE
Change Request Management

### ISSUE THREAD

**Issue by matthew-ardi** [Infisical/infisical#267]
### Feature description
- When a user wants to commit changes, it has to be approved by another peer user (optional setting)
- Customizable change control settings 
  - flexibility in setting how many approvers are needed before commit
  - specific user can be appointed as approver (unblock the changes) and/or committer (execute the changes). 

### Why would it be useful?
in an engineering team, there might be a need for secrets control, especially in a large tech team. a subset of engineers may be trusted with approving the changes while another subset may be trusted to execute the change (e.g. operational engineers). this control ensures that no engineers can accidentally change secrets while still meeting the real-time change expectation and minimizing the possibility that accidental change causes downtime. 

### Additional context
I have noticed that most secretsops solution out there do not have the capability of change management workflow. at least nothing that I know of. this could give a value proposition for infiscal over other secretops solution out there 🚀

**Comment by dangtony98** [comment]
@matthew-ardi  Thanks a lot for this feature request! - Definitely something that'd be really useful for large tech teams for sure.

@maidul98 can look into this as he's working on RBAC for Infisical right now - this falls under a similar realm.

**Comment by akhilmhdh** [comment]
This sure took sometime to close. 

But thank you @matthew-ardi for your taking valuable time and providing this feature request. This has been released and we found out the feature quite product differentiating one. 

If you can text me in slack would love to share infisical swag with you as an gift of appreciation. 

Closing as this has been launched
