### ISSUE TITLE
Error when project settings tab is opened

### ISSUE THREAD

**Issue by Neeraj138** [Infisical/infisical#268]
### Bug description
Hi, I'm new to the repository and  was exploring the app. Whenever I open project settings tab, I'm getting the below error.
![Screenshot 2023-01-28 19:16:24](https://user-images.githubusercontent.com/58552561/215269841-c757f815-0bbe-46ce-b6b4-183e3166367e.png)

### To Reproduce
(In development mode)
1. Go to app homepage
2. Click on Project settings tab

### Video

https://user-images.githubusercontent.com/58552561/215269724-63f8410d-a739-40c2-87a4-c47eb11f3404.mp4

### Platform I'm having the issue on:
Ubuntu 20.04

### Additional context
Tried to debug it and I guess that the reason is subscriptions call for the organizations is returning undefined and it's causing the error.

**Comment by dangtony98** [comment]
Hey @Neeraj138!

Thanks for pointing this out - the error occurs likely because it's missing Stripe keys that we use for Infisical Cloud; this isn't relevant though for self-hosting Infisical and developing.

@mv-turtle can add better error-handling here so this pop-up doesn't show.

Sorry about that!

**Comment by Neeraj138** [comment]
Basically, when running the auth check in useEffect for the respective component, we are sending a subscription call to get the subscriptions associated to a organization. This call is returning undefined. I guess adding the below check in `EnvironmentTable.tsx` should work.
```diff
- setPlan(subscriptions.data[0].plan.product);
+ if (subscriptions) {
+        setPlan(subscriptions.data[0].plan.product);        
+ }
```

**Comment by mv-turtle** [comment]
Hi @Neeraj138! Yes, this makes a lot of sense! I didn't catch this before. Would you be able to raise a PR please?

**Comment by Neeraj138** [comment]
Yeah, will raise a PR.

**Comment by Neeraj138** [comment]
@mv-turtle  Here's the PR for the issue. https://github.com/Infisical/infisical/pull/272
