### ISSUE TITLE
Integration with Railway

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#271]
### Feature description
User should be able to automatically sync their secrets from Infisical to Railway projects.

### Why would it be useful?
It increases the number of integrations that Infisical has, and make Infisical more useful for people. 

### Additional context
This should be similar to some other integrations that Infisical already has - just need to look into Railway's API :)

**Comment by meehawk** [comment]
@mv-turtle can I take this up?

**Comment by mv-turtle** [comment]
@meehawk yes! Please! Would you need any help understanding the codebase? 

Also, are you already in our Slack? Feel free to join :) 
https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

**Comment by meehawk** [comment]
Thanks a tonne @mv-turtle going to try to take a look at this. Would love any help or directions!

**Comment by mv-turtle** [comment]
@meehawk of course! Would you want to do a quick call to help you understand a code base? @dangtony98 is going to do one of those today if you want to join :) He also created many integrations so he knows that part of the codebase a low

**Comment by dangtony98** [comment]
Hey @meehawk!

I'd be happy to walk you through the backend codebase and the integrations part specifically :)

**Comment by Neeraj138** [comment]
> Hey @meehawk!
> 
> I'd be happy to walk you through the backend codebase and the integrations part specifically :)

Hey @dangtony98, I would also like to know the backend codebase and the integrations part. May be we can discuss and fix a time on Slack and all those interested can join!

**Comment by meehawk** [comment]
Got strayed away by #297 so will get to it by Tuesday

**Comment by mukul-mehta** [comment]
Hello! If this hasn't been picked up yet, could I pick it up? I actually need this for a personal project of mine and think this is a good way to get started with understanding the Infisical codebase

**Comment by meehawk** [comment]
Surely @mukul-mehta happy to pass the torch

**Comment by dangtony98** [comment]
Hi @meehawk @mukul-mehta!

Just wanted to check in to see how this integration is coming along? 

There's been quite a bit of demand for this integration, so I'd love to get involved too depending on the progress to date.

**Comment by dangtony98** [comment]
Completed with #491
