### ISSUE TITLE
Cannot create service token

### ISSUE THREAD

**Issue by JenangMaker** [Infisical/infisical#2753]
### Describe the bug
Cannot create service token on self hosted version.

### To Reproduce
1. Create Project
2. Filled the secret
3. Go to Access Control
4. Create service token

### Expected behavior
Service token created successfully.

### Screenshots
![image](https://github.com/user-attachments/assets/8c682315-d746-4bd2-8ff5-5566d4bbe60a)

### Platform you are having the issue on:
Self hosted on Docker

**Comment by akhilmhdh** [comment]
Please share your server log

**Comment by nicam** [comment]
I had the same issue, it didn't work in Brave but it worked in Chrome.

**Comment by akhilmhdh** [comment]
I think this is generally due to the crypto function used. Please switch to machine identity.
