### ISSUE TITLE
Auto-capitalization breaking some applications

### ISSUE THREAD

**Issue by alyx** [Infisical/infisical#276]
When using the web UI, Infisical automatically forces uppercase capitalization for variable names. This is a sensible default, but can break some applications which rely on case-sensitive variable names.

Uploading an existing `env` file retains existing capitalization.

Examples application variables which this impacts:
[GlitchTip](https://glitchtip.com/): `SOCIALACCOUNT_PROVIDERS_gitea_GITEA_URL`
[Gitea](https://gitea.io): `GITEA__service__MCAPTCHA_SECRET`

**Comment by HasanMansoor4** [comment]
hi @mv-turtle, i would like to try this? my first open source issue. I'm guessing there's a toUpperCase() somewhere in the DashboardInputField component.

**Comment by alyx** [comment]
Chiming in with some thoughts:

Uppercasing variables by default makes sense and does help to normalize these with the accepted “standard” for how to format env files.

The issue being that some apps don't follow the standard, so there should be some functionality for disabling that. 

I'd wonder if some sort of project or variable level toggle could be added for “I know why I'm doing this, let me lowercase thing”?

**Comment by mv-turtle** [comment]
@HasanMansoor4 sorry, I missed your mesage! Yes, this would be awesome 

I think by default we would still want the variables to be capitalized. However, I think we want to have an option in settings that allows to remove auto-capitalization. Would you be willing to help with that? :)

Also, please join our Slack for users and contributors: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

**Comment by HasanMansoor4** [comment]
Yeah this sounds good, I'm already working on something. I'll open a PR soon to let you guys review and give me feedback about how I went about it.

**Comment by mv-turtle** [comment]
@alyx not sure if you've seen but this has not been implemented thanks to @HasanMansoor4 :)
