### ISSUE TITLE
Add CLI version from Github tag via github action into code before building

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#278]
Currently, we have to manually increase the CLI version every time we make changes. We trigger a release by adding a new tag on as shown here: https://github.com/Infisical/infisical/blob/main/.github/workflows/release_build.yml#L7

It would be really nice if we can parse the github tag in the workflow and set it in this spot https://github.com/Infisical/infisical/blob/main/cli/packages/util/constants.go#L14

**Comment by jon4hz** [comment]
You can use goreleaser for that. Just inject the version using ldflags. `CLI_VERSION` has to be a variable and not a const though. 

e.g:
`ldflags: -X github.com/Infisical/infisical-merge/path/to/packagename.CLI_VERSION={{ .Version }}`

**Comment by maidul98** [comment]
Oh this is great, is there a working example of this I can follow?

**Comment by jon4hz** [comment]
I'm using it here: https://github.com/jon4hz/fztea/blob/main/.goreleaser.yml#L38

**Comment by maidul98** [comment]
thanks

**Comment by maidul98** [comment]
complete
