### ISSUE TITLE
Feature: Ability to generate secret

### ISSUE THREAD

**Issue by codingmatty** [Infisical/infisical#28]
For example: if I want a JWT secret, it'd be nice to be able to come into Infiscal, press a button and a new secure secret is generated for me.

**Comment by dangtony98** [comment]
Coming soon shortly! — Will keep you posted on this one :)

Secret generation + automatic rotation is on our next list.

**Comment by mv-turtle** [comment]
Hey @codingmatty! Is this something you had in mind? If so, I have just implemented it ([check this commit](https://github.com/Infisical/infisical/commit/b94326463908c4e5098ed415f7f042dc582e96b6)), and we be deploying it to Infisical Cloud by the end of the weekend (in case you are using the Cloud version).

<img width="1004" alt="Screenshot 2022-11-26 at 13 02 36" src="https://user-images.githubusercontent.com/78047717/204102734-5af15aea-dd04-4439-8269-d2e53af6560b.png">

Let me know what you think :)

**Comment by codingmatty** [comment]
Yea @mv-turtle that looks great!

**Comment by mv-turtle** [comment]
Hi @codingmatty! This is now fully deployed in production. Let me please know if you have any other ideas :)
