### ISSUE TITLE
Unable to change user roles in organization

### ISSUE THREAD

**Issue by tjazsilovsek** [Infisical/infisical#283]
### Describe the bug
I as the owner, would like to change the role of someone in my organization. There is a text field displaying the role of a user, but I am unable to click on it and pick a different role.

### To Reproduce
1. Go to Organization Settings page
2. Scroll down to Organization members
3. Try changing role of a user

### Expected behavior
I would expect, to be able to change the roles of users in my organization.

### Screenshots
![image](https://user-images.githubusercontent.com/39498974/216250538-cebe1898-79cb-47f4-863f-92629affed4b.png)

### Platform you are having the issue on:
Chrome Browser

**Comment by maidul98** [comment]
We rolled out the change to allow this last night! Are you on self-host or cloud?
