### ISSUE TITLE
Integration with Google Secret Manager

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#285]
### Feature description
Being able to sync secrets to Google Secret Manager

### Why would it be useful?
It would increase the range of Infisical's integration significantly - GCP is very requested one. And as a result it would save developers lots of time and effort. 

### Additional context
It might not be the easiest integration - I would recommend talking to @dangtony98 for help

**Comment by devblin** [comment]
@mv-turtle Can you please assign this issue to me, I can't assign myself.

**Comment by mv-turtle** [comment]
@devblin I was wondering if you had any progress on this. Can I help in any way? :)

**Comment by devblin** [comment]
Hey @mv-turtle , should I share the draft PR ? I am preety much with the oauth + project list sync, I need to  test and implement the sync part.

**Comment by mv-turtle** [comment]
Oh yeah! Take as much time as you need. I was just wondering if you needed any help 👌

**Comment by devblin** [comment]
@mv-turtle Here is the draft PR: https://github.com/Infisical/infisical/pull/361

**Comment by dangtony98** [comment]
Hello @devblin!

I'll take a look at this and get back to you. Feel free to ping me on Slack or here regarding integrations 😄

**Comment by atimapreandrew** [comment]
Hello @dangtony98 

I would love to work on this.
