### ISSUE TITLE
Integration with AWS Parameter Store

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#286]
Feature description
Being able to sync secrets to AWS Parameter Store

Why would it be useful?
It would increase the range of Infisical's integration significantly - AWS PS is one of the very requested ones. And as a result it would save developers lots of time and effort.

Additional context
Feel free to reach our to @dangtony98 for help because he did may of Infisical's integrations

**Comment by meehawk** [comment]
@mv-turtle Would love to potentially look into this after wrapping up with the Railway integration

**Comment by mv-turtle** [comment]
@meehawk sounds good! Thank you so much for helping :) 

I think it's an Oauth kind of integration. @dangtony98 should e able to help if you have any questions.
