### ISSUE TITLE
Feature request - java spring framework integration

### ISSUE THREAD

**Issue by fletch3555** [Infisical/infisical#29]
Hashicorp Vault has official support through the Spring Cloud Vault library.  I would love to see either a feature-compatible API in infisical, or a separate spring library that can connect to a common infisical API.

**Comment by maidul98** [comment]
Great suggestion. I'd like to ask why you have decided to use Spring Cloud Vault instead of having environment variables injected into your application process and accessing them via the @Value annotation?

**Comment by fletch3555** [comment]
> Great suggestion. I'd like to ask why you have decided to use Spring Cloud Vault instead of having environment variables injected into your application process and accessing them via the @Value annotation?

That's effectively what we currently do, but our deployment process doesn't make this easy to do securely.  We use docker, so environment variables are easy to do, but then they need to be in plain text in the docker-compose file.  If we use docker secrets, then we need something to read those files to make the values available to the app.  In short, the secrets will need to be somewhere, and I would rather use an external/3rd party system to centrally manage this stuff.

**Comment by maidul98** [comment]
I see. We'll add this to our todo list and I'll post our updates here for it. Meanwhile feel free to check out our Docker set up docs to see how you can inject secrets using our CLI into your docker containers. Documentation  for docker https://infisical.com/docs/integrations/docker

**Comment by vmatsiiako** [comment]
@fletch3555 This is now ready: https://infisical.com/docs/integrations/frameworks/spring-boot-maven
