### ISSUE TITLE
Merge .env files duplicates keys instead of merging with existing ones

### ISSUE THREAD

**Issue by yardenas** [Infisical/infisical#299]
### Describe the bug
Uploading a new version of .env file creates duplicate environment variables instead of merging with existing ones.

### To Reproduce
1. Upload and save a .env file with some key-value pairs.
2. Make a change in one of the values of the .env file.
3. Upload again the new .env file. 
4. Duplicate key-value pair was created, instead of asking if the user prefers a merge.

### Expected behavior
Checking if the user prefers a merge of new key-value pairs instead of creating duplicate ones.

### Screenshots
--

### Platform you are having the issue on:
infisical.com

**Comment by kanhaiya38** [comment]
Hi, I would like to work on it

**Comment by mv-turtle** [comment]
Hi @kanhaiya38! Thank you so much! That would be very helpful! Do you want to join our Slack to ask any questions that you might have along the way? Here is the invite link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g
