### ISSUE TITLE
UI bug with dots overflowing on the DashboardInputField

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#30]
### Bug Description
The dots that show up over a secret when it's not hovered, can sometimes go outside of the input field. 
I tried a bunch of options but couldn't get the desired result easily with our current setup. I think the whole structure of how we generate those dots could be rethought. It's currently very lengthy and suboptimal. [This](https://github.com/Infisical/infisical/blob/main/frontend/components/dashboard/DashboardInputField.js) is the file that would have to be changed. 

### To Reproduce
1. Add a long key value
2. Decrease your browser size if needed

### Expected behavior
It should be the bahavior like "overflow-hidden" in tailwind

### Screenshots
<img width="587" alt="Screenshot 2022-11-25 at 11 06 20" src="https://user-images.githubusercontent.com/78047717/204022224-bb391400-0981-4fb2-95c5-01f15487b56f.png">

**Comment by rabbanirizwan** [comment]
@mv-turtle kindly assign me this

**Comment by mv-turtle** [comment]
Thank you so much @rabbanirizwan! This is a tricky one! If you want, I can explain to you how the current setup works. Let me know.

Feel free to join our community Slack if you have any questions or need any help. Here is the link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

**Comment by mv-turtle** [comment]
I just fixed something else that is related to this. I think overall if made the structure of the file easier to understand.

**Comment by mv-turtle** [comment]
@rabbanirizwan after many tries, I think I just fixed this bug 🥳

Something that we want to do now is to make it possible to input multi-line environment variables. Is it something you would be interested in helping with? Let me know please :)

**Comment by mv-turtle** [comment]
@rabbanirizwan closing this issue, but please let me know if you want to contribute to anything. Any help is appreciated :)
