### ISSUE TITLE
Increase mongo db performance 

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#302]
Mongo db collections need indexes added in order to increase query performance. For each table, we need to go through and see what are the most common query patterns are and add indexes to the table accordingly. It would also be helpful if we can identify inefficient queries and pose suggestions to better them. 

Helpful read for mongo db index: https://stackoverflow.com/questions/33545339/how-does-the-order-of-compound-indexes-matter-in-mongodb-performance-wise

**Comment by akhilmhdh** [comment]
I think this is something like a never ending issue, may be a chore rather than an issue.

How about we close this now
