### ISSUE TITLE
Make scrollbars dark

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#303]
### Feature description
Make scrollbars dark across the whole app. Currently it looks strange when the whole app is in the dark mode but the scrollbars are white.

### Additional context
I managed to make a few scrollbars dark but for some reason it didn't work for the other ones. If anyone could find a solution, that would be amazing!

**Comment by Rishav1707** [comment]
I am not able to run this project locally but wanted to solve this issue.
Below is a solution for this issue👇🏻. Anyone can take this as a reference.
https://scottspence.com/posts/change-scrollbar-color-tailwind-css

**Comment by mv-turtle** [comment]
Hi @Rishav1707! Thank you for helping out! I just managed to fix it. 

Why weren't you able to run it locally? You should join our Slack: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g
