### ISSUE TITLE
Deleting a secret with a duplicate key would delete all secrets with the same key

### ISSUE THREAD

**Issue by RashidUjang** [Infisical/infisical#306]
### Describe the bug
When deleting a secret that has a duplicate name (e.g. when a user is trying to add a secret and accidentally entered the same name for the key), it will delete all secrets of the same name.

### To Reproduce
1. Navigate to the Dashboard
2. Add a new secret key with the same name as an existing key (this would 
3. Click on the ellipses to open the sidebar
4. Click on delete in the sidebar
5. Click on confirm
6. Observe that ALL keys of the same name are deleted

### Expected behavior
Deleting a key should only delete the key that's being deleted and should not delete others of the same name

### Platform you are having the issue on:
Cloud & self-hosted

### Additional context
After some exploration, it seems that deleting via the 'X' button on the Dashboard does not cause this problem and only happens when the deletion occurs via the sidebar.

**Comment by mv-turtle** [comment]
Hi @RashidUjang! Thank you for flagging this. Indeed, it seems like it only happens for the sidebar. We should look into that!

**Comment by RashidUjang** [comment]
> Hi @RashidUjang! Thank you for flagging this. Indeed, it seems like it only happens for the sidebar. We should look into that!

No problem! I'm planning to look into this issue once I have a little bit more time.
