### ISSUE TITLE
Sidebar loads incorrect data when entering a duplicate key

### ISSUE THREAD

**Issue by RashidUjang** [Infisical/infisical#308]
### Describe the bug
When trying to add a new secret, if I enter the name of a key that already exists and open the sidebar of the new secret, the sidebar content would inherit the contents of the original secret

### To Reproduce
1. Navigate to the dashboard
2. Ensure that there is an existing secret with a key, value & history
3. Add a new secret with the same key
4. Open the sidebar of the new key
5. Observe that the sidebar contents matches that of the original key

### Expected behavior
The sidebar should not be loaded with content from the original key

### Platform you are having the issue on:
Cloud & self-hosted

**Comment by umrak11** [comment]
I cannot reproduce this behaviour. Was this fixed with commit 
a37cf91 ? 
If not I can take this over and figure it out.

**Comment by mv-turtle** [comment]
Hey @umrak11! Yes, indeed, I think this was fixed. Thank you so much :)
