### ISSUE TITLE
Feature: Have the ability to add/delete/rename environments

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#31]
### Describe the feature
I would be awesome to have a project setting in which you would be able to add/remove/edit available environments. 

### Why would it be useful?
Infisical currently support supports 4 default environments (Development, Staging, Production, and Testing). Many users have requested to have their own custom environments.

**Comment by mv-turtle** [comment]
FYI @icaruk; I created an issue

**Comment by gmgale** [comment]
I would be happy to take a look as a first time issue for me. Let mew know what you think. Thanks!

**Comment by mv-turtle** [comment]
I created a front-end for this in the above commit. Just the backend left

**Comment by akhilmhdh** [comment]
Hey there.

I would love to work on this issue.

**Comment by maidul98** [comment]
This has been completed by @akhilmhdh
