### ISSUE TITLE
Optimize the backup PDF file

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#316]
### Feature description
During the signup, users have to download a backup PDF that allows them to restore access to their account. It currently comes out as a 4.8Mb file when downloaded, which is too large. The code for it is also very messy. We need to find a better way to generate it. Open to any thoughts! :)

**Comment by umrak11** [comment]
I can look into that if it's still free.

**Comment by umrak11** [comment]
I made a PR with changes. Now it's generated around 48kb - I think that is good for now. PR #341

**Comment by mv-turtle** [comment]
Yes, indeed! This was fixed thank to @umrak11! Huge improvement of 100x in size
