### ISSUE TITLE
Highlight edited/added secrets

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#318]
### Feature description
We should somehow point out which secrets are about to be changed when a user clicks the 'Save' button. Maybe highlight them in light green (when added) and light yellow (when edited)? Also maybe show red lines for deleted secrets (like VS Code does this)?

### Why would it be useful?
This would make it much easier to navigate when you are changing secrets.

### Additional context
Feel free to be creative if you want to take this issue :)

**Comment by esau-morais** [comment]
May I work on this issue?

PS.: I'm going to draft the possible solution and return it here soon

**Comment by esau-morais** [comment]
After analysing for a bit, I've divided in two different use cases:
1. Fields are dirty (onChange)
2. User has saved changes (onSubmit)

![image](https://user-images.githubusercontent.com/55207584/219037532-27f40213-4eeb-47a5-90d4-14c2c9811026.png)

**Comment by akhilmhdh** [comment]
This has been fixed. with our new dashboard release.
