### ISSUE TITLE
Feature: Make it possible to reference secrets from other projects

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#32]
### Describe the feature
It would be nice to reference secrets from other projects

### Additional context
Not sure how it would work if other people are not part of a certain project

**Comment by mv-turtle** [comment]
@Icaruk what would you say is the main use case for this? Why do you usually need to reference secrets from other projects?

**Comment by Icaruk** [comment]
> @Icaruk what would you say is the main use case for this? Why do you usually need to reference secrets from other projects?

**email_secrets**:

- EMAIL_USER: ****
- EMAIL_PASS: ****

**api_secrets**:

- EMAIL_USER: ${email_secrets.EMAIL_USER}
- EMAIL_PASS: ${email_secrets.EMAIL_PASS}

**worker_secrets**:

- EMAIL_USER: ${email_secrets.EMAIL_USER}
- EMAIL_PASS: ${email_secrets.EMAIL_PASS}

Easy to change or rotate shared passwords, tokens, etc...

**Comment by Icaruk** [comment]
> Not sure how it would work if other people are not part of a certain project

Maybe just allow to reference projects you have access to.

**Comment by akhilmhdh** [comment]
With release of (Secret Reference)[https://infisical.com/docs/documentation/platform/secret-reference#referencing-syntax] You can now reference secret from same environment or another environment and another folder. 

Closing this issue as its now been resolved

**Comment by dehoej** [comment]
Actually this has not been resolved since you can still not refer to secrets in another project?
