### ISSUE TITLE
INFISICAL_TOKEN seems not working anymore

### ISSUE THREAD

**Issue by thawankeane** [Infisical/infisical#321]
### Describe the bug
When attempting to run commands through environment variable `INFISICAL_TOKEN` it returns `Hmm, we ran into an error: invalid service token entered. Please double check your service token and try again`, maybe related to #190?

### To Reproduce
1. Generate a Infisical Token (see https://infisical.com/docs/getting-started/dashboard/token)
2. Try to run a command with environment variable `INFISICAL_TOKEN=<your token>`

### Expected behavior
Expected to run commands without need to run `infisical login`.

### Screenshots
![image](https://user-images.githubusercontent.com/26743815/217901899-67fe03bb-4fde-4916-a5dc-95cc53e8f3a1.png)

### Platform you are having the issue on:
MacOS Ventura (CLI installed via homebrew)

![image](https://user-images.githubusercontent.com/26743815/217902954-190e353c-cfc6-4d6f-afb8-e48847a5d0d8.png)

### Additional context
The token used is in the v2 format (`st.<IDENTIFIER>.<SECRET>`)

**Comment by maidul98** [comment]
We have reprodced the issue and are working on deploying the change shorty. I'll keep you updated in this thread

**Comment by maidul98** [comment]
I have released the fix. Thank you for bringing this up! Let us know if it is working for you

**Comment by maidul98** [comment]
@thawankeane We had to rollback due to an unrelated issue so new tokens will not work again. We are working on investigating the issue

**Comment by thawankeane** [comment]
> @thawankeane We had to rollback due to an unrelated issue so new tokens will not work again. We are working on investigating the issue

No problem, let me know if you need some help ;)

**Comment by maidul98** [comment]
Issue has been patched, let us know if you face any trouble
