### ISSUE TITLE
Cannot log in after deleting all projects

### ISSUE THREAD

**Issue by smnschmnck** [Infisical/infisical#322]
### Describe the bug
After deleting all projects and then navigating to infisical.com and clicking on the "Log in button" a blank page is shown.
I can only log in after deleting all my cookies  for app.infisical.com.

### To Reproduce

1. Go to infisical.com
2. Log in
3. Delete all projects
4. Close tab
5. Go to infisical.com
6. Click on Log In

### Expected behavior
If I am still logged in I should be redirected to app.infisical.com/noprojects.

### Screenshots
![Screenshot showing blank page](https://user-images.githubusercontent.com/85026647/217940184-61496cc0-850a-4129-abe5-0b7e75366738.png)

### Platform you are having the issue on:
Linux:
- Chromium
- Firefox

**Comment by dangtony98** [comment]
@smnschmnck Thanks for bringing this up!

We'll work on a fix for this with @mv-turtle :)

**Comment by esau-morais** [comment]
Once I've deleted the last remaining project, it keeps loading and returns `undefined` in the URL

`https://app.infisical.com/dashboard/undefined`

![infisical](https://user-images.githubusercontent.com/55207584/218749887-2610c3d7-e11d-4027-8563-64c10b3cbd4d.png)

**Comment by mv-turtle** [comment]
hmmmm, i see! I think it's probably the same issue, no? @esau-morais

**Comment by esau-morais** [comment]
I don't think so, once @smnschmnck reported about a blank page, which happens after closing the page and trying to login

**Comment by Neeraj138** [comment]
When redirecting to dashboard from login, an error was occuring because after deleting all the projects, the user workspaces is undefined but we were trying to read its properties. Fixed this issue in #370
