### ISSUE TITLE
When multiple Operations are performed quickly, the action won't sync with Database. 

### ISSUE THREAD

**Issue by Aashish-Upadhyay-101** [Infisical/infisical#324]
### Describe the bug
For example when you add a secret and remove it and quickly reload the page the secret won't get removed and it is still there.

### To Reproduce
1. Go to the 'Secret page i.e main page'
2. Add a secret.
3. remove it and save the changes
4. quickly reload the page

### Expected behavior
I want the secret to be deleted.

**Comment by mv-turtle** [comment]
This should now be fixed with the latest update :)

**Comment by Aashish-Upadhyay-101** [comment]
hey @mv-turtle what was causing this issue can you please explain it to me and how do you fix it?

**Comment by dangtony98** [comment]
@Aashish-Upadhyay-101 There were multiple issues here but one of them had to do with race-conditions of multiple CRUD operations being sent to the server; we've instead now batched operations so all desired CRUD ops are sent in 1 request.

**Comment by Aashish-Upadhyay-101** [comment]
ohhh, and what were other issues?
