### ISSUE TITLE
Append environment name to the dashboard page url

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#325]
Currently, the url for projects page looks like this regradress of what environment you are in 

```
/dashboard/63e5ea1e7a65573dc1e20ee9
```

This is fine, but when you refresh the page you lose the environment you were in and then have to manually navigate to it. It would be better if it was more like this

```
/dashboard/63e5ea1e7a65573dc1e20ee9/{env name}
```

Example 

```
/dashboard/63e5ea1e7a65573dc1e20ee9/dev
```

**Comment by RashidUjang** [comment]
Just throwing this out there, would it be sufficient if we were to use some sort of browser storage (IndexedDB or Local Storage) to store the environment of the user for this instead of changing the URL?

**Comment by dangtony98** [comment]
@RashidUjang Why not include it in the URL?

**Comment by RashidUjang** [comment]
@dangtony98 I'm just exploring other ideas as I think it'd look neater not having in the URL as its sort of a temporary state that's useful only in the context of the user's current session (compared it with the Postman web client).

Just as I'm typing this though, having it in the URL does have an added benefit of making it easy to save & share a URL to go directly to an environment of a particular ID. 

Feel free to dictate the direction, just adding some discourse!

**Comment by dangtony98** [comment]
Ah ya that makes sense.

The main benefit I see from having the `env` be in the URL is having the shareability component as you mentioned for sure!

And yea down for discourse as well; I think @maidul98 can chime in here.

**Comment by esau-morais** [comment]
May I work on this issue?

**Comment by maidul98** [comment]
@RashidUjang Yes, I think having the env in the URL allows for better readability and keeps place on the dashboard if the user refreshes.

@esau-morais please, that would be great!

**Comment by RashidUjang** [comment]
@maidul98 Sounds good and yes that definitely would ease sharing!

**Comment by mv-turtle** [comment]
This is implemented now thanks to @esau-morais :)
