### ISSUE TITLE
An option to never expire Service Tokens

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#33]
### Feature description
Have an option when generating a service token to make it not expire

### Why would it be useful?
There are use cases (especially in smaller projects), where it is better to not expire the service token.

**Comment by mv-turtle** [comment]
FYI @Icaruk

**Comment by sheensantoscapadngan** [comment]
I can take on this one as well

**Comment by dangtony98** [comment]
Closed with #501
