### ISSUE TITLE
After trying to delete the last remaining project, it keeps loading and returns `undefined` in the URL

### ISSUE THREAD

**Issue by esau-morais** [Infisical/infisical#330]
### Description

After deleting the last remaining project, it keeps loading and returns `undefined` in the URL

`https://app.infisical.com/dashboard/undefined`

### Screenshots
![infisical](https://user-images.githubusercontent.com/55207584/218749887-2610c3d7-e11d-4027-8563-64c10b3cbd4d.png)

**Comment by animeshdas2000** [comment]
Hey @mv-turtle can I work on this?
I believe the id is undefined here so I'll just add a condition to fix it where it'll route to `{url}/dashboard`

**Comment by mv-turtle** [comment]
Sounds good @animeshdas2000! Though I don't think it's that easy actually. Because {url}/dasboard will try to add a workspaceId, and it will be in the constant loop of redirects haha

I think the solution is to just handle it within the dashboard/[id].tsx file

**Comment by animeshdas2000** [comment]
Ah cool. Thanks for the input, that'll be helpful. I start working on it.
