### ISSUE TITLE
Redirect a user to login if they already exist

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#34]
### Feature description
When a user exists and they try to signup again, we should redirect them to login or tell them that this email is already taken. 

### Why would it be useful?
Would save people time and avoid a lot of confusion.

**Comment by sscla1** [comment]
hello! i can help

**Comment by mv-turtle** [comment]
Hi @sscla1! Thank you so much! That would be awesome! Would you be able to join our community Slack so that we can discuss there? Here is the link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

**Comment by dangtony98** [comment]
@Grraahaam Agreed with this one.

For a security solution like Infisical, it's best that we don't leak that information and just tell them that the login was unsuccessful - leaking it confirms to bad actors that in fact such an account exists.

**Comment by mv-turtle** [comment]
Sounds good! Then I will close this one
