### ISSUE TITLE
Multiple CLI Users

### ISSUE THREAD

**Issue by ngregrichardson** [Infisical/infisical#340]
### Feature description
Allow the CLI to support multiple user accounts logged in simultaneously.

### Why would it be useful?
This would allow users to easily switch between scopes (work versus personal projects) instead of re-authenticating anytime they want to run a project in a different scope.

### Additional context
The two ways I imagine it could work are:
- Automatically switching between profiles based on which would work with the current workspace. So if you run `infisical run` in a directory with a workspace id that only has access from some accounts, it would use that account. This would be ideal, but I can imagine problems with multiple accounts with different permissions on different workspaces.
- Adding a new command (maybe `infisical switch` or something similar) that would let you switch between logged-in accounts. Less ideal, but still makes the workflow of re-authenticating with your password easier.

**Comment by quinton11** [comment]
Has this been taken up by anyone yet?

**Comment by maidul98** [comment]
Hey @quinton11 no one has picked this up yet

**Comment by quinton11** [comment]
Sure, will work on this

**Comment by maidul98** [comment]
Awesome! Please join our slack if you'd like to run your ideas by me or have any questions https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g
