### ISSUE TITLE
Check for common passwords during signup

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#342]
### Feature description
It would be awesome to have a check for common passwords during signup. We currently don’t check for that, but you shouldn’t be allowed to create an account if your password is `qwerty123`

### Why would it be useful?
This would improve security and leave no room for human laziness of choosing a good password.

**Comment by prashantbhattarai123** [comment]
Hey @mv-turtle , i want to work on this issue but I am total beginner in open source so can you please guide me in which file do I need to code and what are the steps to solve this issue . That would be so helpful 😊😊

**Comment by mv-turtle** [comment]
Hi @prashantbhattarai123! Thank you so much - appreciate your help 😃

Could you please join our Slack workspace? I can help you with everything there. Here is the link: https://join.slack.com/t/infisical/shared_invite/zt-1dgg63ln8-G7PCNJdCymAT9YF3j1ewVA

**Comment by mv-turtle** [comment]
Sorry, that link is wrong! Please use this one: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g.

**Comment by derinp** [comment]
if this hasnt been done yet, or isnt fully complete, i would love to contribute here. Would help me work on my scripting and im trying to get security focused things on my resume. Please let me know if this is still available to work on!

**Comment by mv-turtle** [comment]
@derinp thank you so much! that would be great! Please, let me know if you have any questions or need any help! You should also join our slack for contributors if you want: https://infisical.com/slack

**Comment by derinp** [comment]
> @derinp thank you so much! that would be great! Please, let me know if you have any questions or need any help! You should also join our slack for contributors if you want: https://infisical.com/slack

Awesome, I'll join the slack. Can't wait to get started on this!

**Comment by akhilmhdh** [comment]
@ragnarbull can we close this issue. If so go ahead and close this.

**Comment by ragnarbull** [comment]
@akhilmhdh yes we can close this.
