### ISSUE TITLE
Bug(Self-Hosted): Cannot Login via CLI

### ISSUE THREAD

**Issue by EmirBoyaci** [Infisical/infisical#351]
### Describe the bug
When I followed docs and wanted to login Infisical via CLI, I am getting error.

### To Reproduce
Follow docs here: https://infisical.com/docs/cli/overview

### Expected behavior
Login successfully.

### Screenshots
See below screenshot, I am running Infisical correctly (to show, I enter wrong password):
<img width="842" alt="Screenshot 2023-02-22 at 10 26 43" src="https://user-images.githubusercontent.com/59085992/220552224-5aa5615a-e10b-4481-9332-d11707249caa.png">

There the error comes when I enter correct password:
<img width="685" alt="Screenshot 2023-02-22 at 10 26 48" src="https://user-images.githubusercontent.com/59085992/220552437-3f4702b6-2b38-4649-a9f9-6e4f8313861c.png">

### Platform you are having the issue on:
MacOS

**Comment by EmirBoyaci** [comment]
I am using Infisical CLI version 0.2.24 which is latest I think:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/59085992/220552955-d0008ae3-9817-4c0e-8a2f-991414470dda.png">

**Comment by dangtony98** [comment]
Hi @EmirBoyaci!

Thanks for reporting this — @maidul98 can assist you with this as he works on the CLI-front.

In the meantime, feel free to join our Slack community [here](https://infisical-users.slack.com/ssb/redirect)? It's often easier to communicate and assist in real-time 😄

**Comment by niklasdiehm** [comment]
I also had the issue, upgrading to 0.3.1 fixed the problem. I'm using Windows.

**Comment by maidul98** [comment]
Thank you for bringing this to our attention. This bug has been patched and is now being released. Please allow the release to complete before attempting to update your CLI https://github.com/Infisical/infisical/actions/runs/4256048158/jobs/7404435500

**Comment by maidul98** [comment]
@EmirBoyaci can you please update your CLI to the latest version? Also, are you using `INFISICAL_API_URL` environment variable to point the CLI to your self-hosted instance?

**Comment by EmirBoyaci** [comment]
> @EmirBoyaci can you please update your CLI to the latest version? Also, are you using `INFISICAL_API_URL` environment variable to point the CLI to your self-hosted instance?

Hi, it seems that now it is fixed. I am not using env. variable for now, just trying Infisical.
