### ISSUE TITLE
Delete multiple secrets at the same time.

### ISSUE THREAD

**Issue by Aashish-Upadhyay-101** [Infisical/infisical#367]
### Feature description
Being able to delete multiple secrets at the same time.

### Why would it be useful?
This would be so time saving as users don't have to manually delete secrets one by one.

**Comment by sheensantoscapadngan** [comment]
I can take on this feature

**Comment by mv-turtle** [comment]
Hi @sheensantoscapadngan! I just realized that this issue is still open. Really sorry about that. I will review it today!

**Comment by akhilmhdh** [comment]
Closing as this a stale issue and at present you can delete multiple secrets at same time.
