### ISSUE TITLE
Custom tag colors

### ISSUE THREAD

**Issue by jon4hz** [Infisical/infisical#368]
### Feature description
It would be amazing if you could specify the color of tags. Currently it seems to pick a color randomly and "terraform" being yellow just looks wrong.

### Why would it be useful?
Not really useful, it's more a nice-to-have feature :)

**Comment by rksingh2001** [comment]
Can I take up this issue?

**Comment by EBEN4REAL** [comment]
is this issue being worked on already?

**Comment by vmatsiiako** [comment]
@EBEN4REAL sound great! Let me know if you need any help.
