### ISSUE TITLE
Improved access control

### ISSUE THREAD

**Issue by jon4hz** [Infisical/infisical#381]
### Feature description
At the moment, the only option to prevent `infisical` to inject all secrets from an environment is to use the `--tags` option. This is useful when you want to make sure, that an application sees only certain secrets. 
However that sort of access control is only on the client side and if your token gets leaked, a bad actor could still access all your secrets. 
It would be great, if you could generate access tokens with limited scopes which can only access certain tags. 

This sort of access control should also be available for the cloud integrations.

### Why would it be useful?
In my option, this feature would greatly increase security. It allows using `infisical` with a least privilege principle by exposing only the secrets that are actually required.

**Comment by jon4hz** [comment]
That looks amazing! Service accounts as you described them would be even better that just scoped access tokens.

**Comment by dangtony98** [comment]
@jon4hz Currently, service tokens allow users to pull and inject all secrets from a given project and environment. Would it suffice to add a third field `tags` to service tokens to filter secrets by project, environment, and tags to be returned from the backend?

@Grraahaam Very cool! Is the concept of a service account similar to the concept of a service token but with broader scope here? It sounds like broader type of service token that can access multiple projects and environments and tags within them?

Also, the custom roles feature will definitely be coming next soon (just added it to the public [roadmap](https://www.notion.so/infisical/be2d2585a6694e40889b03aef96ea36b?v=5b19a8127d1a4060b54769567a8785fa)).

**Comment by jon4hz** [comment]
Yeah, a third field to limit access tokens to certain `tags` would be a great improvement and cover a lot of use-cases. 

I didn't have the need (at least not yet) to generate access tokens which have permission to more than one environment but I'm sure others might have that need and @Grraahaam's proposal would cover these. So having both options - limited access tokens and service accounts - would be amazing.

**Comment by jon4hz** [comment]
Since you already mentioned the TTL of service tokens, what do you think about adding an option to create tokens without expiry?  Certainly it isn't best practice to use such tokens but I think it should be up to the user to decide.

**Comment by mv-turtle** [comment]
@jon4hz indeed! there is an issue for that actually: https://github.com/Infisical/infisical/issues/33

**Comment by akhilmhdh** [comment]
Closing this issue as Infisical has now granular permission system, service tokens and other security measures like ip whitelisting
