### ISSUE TITLE
Show some sort of error or invalid token message to the user.

### ISSUE THREAD

**Issue by Aashish-Upadhyay-101** [Infisical/infisical#385]
### Describe the bug
For example, while integrating with token-based services like flyio, circleci, etc, if the token that user entered is wrong or invalid then show some error message to the user that the personal access token they entered was incorrect or something.

right now it just shows nothing...

**Comment by dangtony98** [comment]
Totally.

I was gonna add a function for all such token-based services to validate whether or not access tokens correctly connect and return an error to be rendered to users if the token is invalid.

**Comment by the2MinEngineer** [comment]
I would like to work on this

**Comment by akhilmhdh** [comment]
This has been completed with our recent releases.
