### ISSUE TITLE
Cloud 66 Integration

### ISSUE THREAD

**Issue by khash** [Infisical/infisical#388]
### Feature description
Add native integration for applications deployed via Cloud 66

### Why would it be useful?
Cloud 66 support Rails, container and static (JAMStack) application deployments to any cloud provider. Secret management integrated with Infisical is a very useful for those applications.

### Additional context
Website: www.cloud66.com

**Comment by dangtony98** [comment]
Added to our [roadmap](https://www.notion.so/infisical/be2d2585a6694e40889b03aef96ea36b?v=5b19a8127d1a4060b54769567a8785fa&p=5fe284ae12db44fe83922d09ba885a9d&pm=s) for March 😄

**Comment by mv-turtle** [comment]
If you have time and interest, feel free to send a PR too :)

**Comment by Neeraj138** [comment]
@dangtony98 Is anyone working on this currently? If not, I would like to work on this.

**Comment by dangtony98** [comment]
@Neeraj138 Happy to have you take a stab at it!

Let me know if you've any questions on the integrations end (can always ping me on Slack); integrations are always really fun to do 😄

**Comment by afrieirham** [comment]
Is this issue still active? If not then I would love to work on this.

cc @Neeraj138 @dangtony98

**Comment by dangtony98** [comment]
Go for it @afrieirham 😄
