### ISSUE TITLE
Localize Web UI

### ISSUE THREAD

**Issue by gangjun06** [Infisical/infisical#39]
### Feature description
Add localizing package to frontend. Such as [next-translate](https://github.com/aralroca/next-translate) [next-i18next](https://github.com/i18next/next-i18next).

### Why would it be useful?
People in many countries will be able to use the web UI more convenient.

### Additional context

**Comment by mv-turtle** [comment]
This is an awesome idea! Would you be able to help with Korean?

**Comment by gangjun06** [comment]
Of course! I can translate english into korean. And if you want, I will create PR for apply i18 to frontend project.

**Comment by mv-turtle** [comment]
Yes, this is great! Thank you so much for your help!

**Comment by mv-turtle** [comment]
Also, if you want, we have a community Slack channel for our contributors. We would love to have you join!

Here is the link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g
