### ISSUE TITLE
Unable to install on Pop!_OS 22.04

### ISSUE THREAD

**Issue by leanjunio** [Infisical/infisical#397]
### Describe the bug
I can't install Infisical CLI using the following scripts:

```bash
curl -1sLf \ 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' \ | sudo -E bash
sudo apt-get update && sudo apt-get install -y infisical
```

### To Reproduce
1. curl -1sLf \ 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' \ | sudo -E bash
2. sudo apt-get update && sudo apt-get install -y infisical

The above steps yields the following:
```bash
Hit:1 http://apt.pop-os.org/proprietary jammy InRelease
Hit:2 https://downloads.1password.com/linux/debian/amd64 stable InRelease
Hit:3 http://packages.microsoft.com/repos/code stable InRelease
Hit:4 http://apt.pop-os.org/release jammy InRelease
Hit:5 http://apt.pop-os.org/ubuntu jammy InRelease
Hit:6 http://apt.pop-os.org/ubuntu jammy-security InRelease
Hit:7 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Hit:8 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package infisical
```

### Expected behavior
Expected `infisical` to be found and installed

### Platform you are having the issue on:
Pop!_OS 22.04

**Comment by maidul98** [comment]
Hey Lean, I am looking into this. I will update you once I have some findings

**Comment by maidul98** [comment]
Our friends at Cloudsmith has looked into this issue. They were able to download the CLI on Pop Os VM. It is likely a misconfiguration on your machine. From the logs you have provided it looks like it isn't even connecting to cloudsmith servers. 

<img width="1913" alt="image (2)" src="https://user-images.githubusercontent.com/9300960/222737612-fd9e3c87-f726-4dbe-a360-62a933399834.png">

**Comment by leanjunio** [comment]
> Our friends at Cloudsmith has looked into this issue. They were able to download the CLI on Pop Os VM. It is likely a misconfiguration on your machine. From the logs you have provided it looks like it isn't even connecting to cloudsmith servers.
> 
> <img alt="image (2)" width="1913" src="https://user-images.githubusercontent.com/9300960/222737612-fd9e3c87-f726-4dbe-a360-62a933399834.png">

Hmm I see, thanks for looking into this. I was able to just download the `.deb` release on the releases page yesterday so that works on my end so I'll be using that for now to circumvent.

Thanks for the help!
