### ISSUE TITLE
Add number of secrets injected into terminal output 

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#40]
Currently, we just say that secrets have been injected upon a successful injection. It would be helpful to also point out how many secrets have been injected along with the successful injection text. This would help the user know for sure how many secrets if any were injected.

This is the current text we output: https://github.com/Infisical/infisical/blob/main/cli/packages/cmd/run.go#L97

If we can say something along the lines of "Successfully injected 23 secrets..." that would be great.

**Comment by dangtony98** [comment]
It would also be really useful to print out what environment the secrets are being injected from!
