### ISSUE TITLE
Integration with Cloudflare Pages

### ISSUE THREAD

**Issue by jerriclynsjohn** [Infisical/infisical#404]
### Feature description
Users should be able to automatically sync their secrets from Infisical to Cloudflare pages

### Why would it be useful?
It increases the number of integrations that Infisical has, and makes Infisical more useful for people. There are some amazing users who prefer to use Cloudflare pages over Vercel and Netlify

### Additional context
This should be similar to some other integrations that Infisical already has

**Comment by jerriclynsjohn** [comment]
Any progress on this?

**Comment by mv-turtle** [comment]
Hey @jerriclynsjohn! We have unfortunately paused this for now because very few people have requested this. If you have time, we'd be open to a PR for this integration. Let me know if that's an option, otherwise we will try to implement this a little bit later.

**Comment by dangtony98** [comment]
@jerriclynsjohn This integration has just been added to the codebase; will be deployed shortly in the next day or two 😄
