### ISSUE TITLE
[GITHUB] Github Action Secrets integration (Organization, Repository, Environment)

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#408]
### Feature description

Well done for the Github repository secrets integration (https://github.com/Infisical/infisical/issues/54)! Great work 🎉 

Although, would it be possible to sync secrets with an entire Github **organization** and **environment,** not just at repository level?

#### Organization

**Use case** : Most of my apps use common secrets in their corresponding CI/CD pipelines, creating syncs for +100 repos seems a bit redundant and prone to errors IMO. Having a global sync across the entire organization would allow us to centralize those common variables, **while keeping the repo level sync** for more granularity/security (e.g. exposing critical secrets only to specific apps)

#### Environment

**Use case** : See above, more or less the same needs, but per environment to provide corresponding Infisical secrets 

### Additional context

It seems possible to sync Github organization secrets through their API, and you could even automatically import existing Github secrets to a Infisical project as well (they have `LIST`/`GET` endpoints). But there may be some security concerns behind, which I’m not aware of yet. Anyway here’s the mentioned API if ever you guys plan to support it (I’d love it) :

- [GH Secrets - List Organization Secrets](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#list-repository-secrets)
- [GH Secrets - Create/Update Organization Secrets](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-an-organization-secret)

## Edit

There's **3** Github Action secret scopes for now (2024-02) : 

- 🌐 [Github Action Secrets - Organization](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-an-organization)
  - https://github.com/Infisical/infisical/pull/1398
- 📕 [Github Action Secrets - Repository](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository)
  - https://github.com/Infisical/infisical/issues/54 (done)
- 🌱 [Github Action Secrets - Environment](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-an-environment)
  - https://github.com/Infisical/infisical/pull/1194
  - https://github.com/Infisical/infisical/issues/1154
  - https://github.com/Infisical/infisical/pull/1398

And limitations seems different from [Github Codespace Secrets](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-development-environment-secrets-for-your-repository-or-organization) ⚠️ 

I think the Infisical docs about [Github Action](https://infisical.com/docs/integrations/cicd/githubactions) should quickly describe and point to the GHA Secrets limitations, listed below to raise user's awareness : 
- [Limits](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#limits-for-secrets)
- [Naming](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#naming-your-secrets)

It's maybe mentioned somewhere in-app when integrating Infisical with GHA, but I don't see anything in the docs.

Cheers! 🍻

**Comment by Salman2301** [comment]
Thanks @Grraahaam for clearly stating the issue.
I would like to see. If I can attempt this.

**Comment by dangtony98** [comment]
This is now completed with #1398 😄
