### ISSUE TITLE
[FEATURE] [UI/API] Change default environment slugs to shorter one 🏷️

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#413]
### Feature description

Today, I can't change the existing environment slugs names. Slugs are aimed to be short and can try to follow a convention (e.g. three letters max.)

Here's a suggestion for the default environment (included in the **free** plan) :

| **Environment** | **Current slug** | **Suggested slug** |
| --------------- | ---------------- | ------------------ |
| Development     | dev              | dev                |
| Staging         | staging          | stg                |
| Testing*        | test             | tst                |
| Production      | prod             | prd                |

\* *What's the `Testing` use case by the way? In our company, we often use it for pre-release stress tests, it's a copy of the `prd` environment*

Or would it be possible to edit the default slugs in the free plan?

### Why would it be useful?

Normalize the default slugs, following a convention to ease users' understanding

**Comment by dangtony98** [comment]
Agree here; this would be good — we'd have to think about migrating users and updating the DB carefully on our end to make sure nothing breaks.

Regarding `Testing`, it's one of the 4 deployment environments [here](https://en.wikipedia.org/wiki/Deployment_environment). We thought we'd include it for sake of completion.

**Comment by Amanshenoy008** [comment]
hey, can i work on this issue

**Comment by mitdonga** [comment]
Hi @dangtony98 

Can I work on this issue?

**Comment by mit-complitech** [comment]
I just raised the PR [#1392](https://github.com/Infisical/infisical/pull/1392) for this issue

**Comment by mitdonga** [comment]
I just raised the PR #1392  please review @dangtony98

**Comment by akhilmhdh** [comment]
Hey everyone. This is my take over this. Slugs should be short but at the same time it should be easier to understand. 

The issue with naming it as `prd` or `tst` is its confusing and not able to understand for many people at first. `prd`-> could also mean `pre-prod` used by some people instance naming for staging. 

Its easier to understand in one go `prod` or `test` rather than the suggested one

**Comment by akhilmhdh** [comment]
We are closing this issue and the PR in favour of keeping the old ones as its more easier to understand.
