### ISSUE TITLE
[FEATURE] [UI/API] User & Organization deletion 🗑️

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#414]
### Feature description

Today, I can't find a way to delete my **user** or my **organization** (if I'm the admin/owner). It'd be good if we could, IMO 💡

### Why would it be useful?

People wanting to be in control of their data, or sometimes being able to start a new org from scratch because you messed up with the first one

### Additional context

The page I'm thinking of is : `https://app.infisical.com/settings/org/<org-id>`

**Comment by Aashish-Upadhyay-101** [comment]
@dangtony98 I want to work on this ! 🚀

**Comment by dangtony98** [comment]
@Aashish-Upadhyay-101 Go for it 😄

I think you can do them one at a time so pick one and go for it!

**Comment by dangtony98** [comment]
This was implemented last month — delete user, project, and organization 😄
