### ISSUE TITLE
[BUG] [UX] <ENTER> doesn't submit the form in some modals ⌨️

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#415]
### Feature description

When pressing the `ENTER` key, I expect the frontend to submit the focused form/inputs. Today, in some modals it's not the case, so far I've found those :
- `https://app.infisical.com/signup`
    - [ ] Verification code modal
    - [ ] Sign up completion modal (names, password)

Maybe there's some factoring to do, by adding this `ENTER` key listening event in the modals component ?

### Why would it be useful?

Improve the user experience, as it's quite common and it is HTML default behaviour

**Comment by Budhathoki356** [comment]
hey I would like to work on this. Could you assign this to me?

**Comment by afrieirham** [comment]
Hey @Grraahaam, I've open PR to solve this issue. I fix this issue in these pages as well (`signup`, `login`, `verify-email`)
