### ISSUE TITLE
Infisical Python SDK

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#433]
### Feature description
Currently Infisical only has the [Node SDK](https://github.com/Infisical/infisical-node) that enables users to install a package into their apps to fetch back and access their secrets.

It would be great to have a **mirror** Python SDK that does the same for Python users.

### Why would it be useful?
This would help Python users more easily connect their apps to Infisical.

### Additional context
The Python SDK has been started already [here](https://github.com/Astropilot/infisicalpy) kuddos to @Astropilot — pending ownership transfer.

Feel free to help out and join the [Slack community](https://infisical.com/slack).

**Comment by florent-martineau** [comment]
Hi !

You most probably already have thought about it, and there is probably a good reason not doing it, but I was wondering why not use OpenAPI SDK generators to generate the SDK from the OpenAPI spec?

Indeed, I've seen a number of SDKs planned ([Rust](https://github.com/Infisical/infisical/issues/437), [Go](https://github.com/Infisical/infisical/issues/436), [Ruby](https://github.com/Infisical/infisical/issues/435), [Java](https://github.com/Infisical/infisical/issues/434), and [Python](https://github.com/Infisical/infisical/issues/433)), and leveraging automated code generation could help save some precious engineering time? 

It would save some time implementing the SDKs, which could be reinvested to document those SDKs better for instance.

Tell me what you think about that approach, and if it seems reasonable to you, I can try to implement it.

**Comment by maidul98** [comment]
Looking promising, what do you think @dangtony98

**Comment by dangtony98** [comment]
@florent-martineau Thanks for this!

I'm currently working on another feature for Infisical that's directly related and even a prerequisite for the SDKs — We're deprecating API Keys in favor of Service Accounts that have public/private key pairs as credentials (similar to that of an IAM user in AWS). Once this is done, we will move the Node SDK to use Service Accounts instead of Service Tokens and API keys as currently being done. As soon as I'm done with that, I'll hop back onto SDKs. I actually haven't tried the OpenAPI SDK generators but it seems promising!

Thus far, we've only completed the Node SDK (Python is underway by another contributor) but the initial rationale was:
- Unique `async` logic for SDK currently requiring all secrets to be pulled first, and only then be indexed; this is an inconvenience that we wanted to solve first by enabling targeted secrets to be pulled individually by calling on their `key` name.
- Heavy encryption/decryption logic that we felt would have to be done as custom work anyways.

That said, I'm definitely lacking understanding and experience working with the OpenAPI SDK generators so I'll have to give it a go first and test 1-2 more SDKs for other languages. I'm very optimistic about things that help standardize the process and make things more efficient so this seems great.

**Comment by dangtony98** [comment]
Done 😄

https://github.com/Infisical/infisical-python
