### ISSUE TITLE
Infisical Go SDK

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#436]
### Feature description
Currently Infisical only has the [Node SDK](https://github.com/Infisical/infisical-node) that enables users to install a package into their apps to fetch back and access their secrets.

It would be great to have a **mirror** Go SDK that does the same for Go users.

### Why would it be useful?
This would help Go users more easily connect their apps to Infisical.

### Additional context
Feel free to help out and join the [Slack community](https://infisical.com/slack).

**Comment by meehawk** [comment]
@dangtony98 whats the plan/timeline for this? This sounds interesting + easy to support

**Comment by aenawi** [comment]
Yes, please put it in your priority list! Can't wait to try it out.

Thanks guys.

**Comment by JamesArthurHolland** [comment]
Any update on Go SDK?

**Comment by dangtony98** [comment]
Hi @JamesArthurHolland,

There's been a hold up on developing this SDK-specifically (there're a lot to tackle) but we're opening up an option for users to be able to opt out of E2EE and query for a secret to be returned in plaintext via HTTP call, similar to other secret management platforms, by Monday.

Perhaps you can use that in the meantime! — Go SDK specifically will likely be next quarter.

**Comment by JamesArthurHolland** [comment]
I think we can get by with the kubernetes integration but thanks

**Comment by sbshah97** [comment]
Hey @dangtony98 would love to help support / work on this as well.

**Comment by SpeedReach** [comment]
I tried to write a cypher function like the javascript example, but I can't get it to work on decrypting the project key.
It shows that: cipher: message authentication failed.
How should I do this correctly

```go
func decrypt(ciphertext, iv, tag, secret string) (string, error) {
	ciphertextBytes, _ := base64.StdEncoding.DecodeString(ciphertext)
	ivBytes, _ := base64.StdEncoding.DecodeString(iv)
	tagBytes, _ := base64.StdEncoding.DecodeString(tag)

	block, err := aes.NewCipher([]byte(secret))
	if err != nil {
		return "", err
	}

	aesgcm, err := cipher.NewGCMWithNonceSize(block, len(ivBytes))
	if err != nil {
		return "", err
	}


	decipheredBytes, err := aesgcm.Open(nil, ivBytes, ciphertextBytes, tagBytes)
	if err != nil {
		return "", err
	}

	return string(decipheredBytes), nil
}
```

**Comment by AndrewShear** [comment]
Any update on this? @dangtony98 

Any branch's started?

**Comment by sbshah97** [comment]
Hey I started some work on this but got caught up with work. If this is priority please feel free to re-assign

**Comment by dezren39** [comment]
This would be really core for my team using infisical. I basically would have to try to make one myself otherwise, and I'm not sure I'm prepared for that.

**Comment by hekike** [comment]
+1 would be great to have a Go SDK

**Comment by SpeedReach** [comment]
wrote a simple working code that we can use while waiting for the sdk to come out.
https://github.com/Infisical/infisical-go-client/pull/2

**Comment by DanielHougaard** [comment]
Hi everyone, we have just released a native Go Lang SDK!

Repository: https://github.com/Infisical/go-sdk
Documentation: https://infisical.com/docs/sdks/languages/go
