### ISSUE TITLE
Infisical Rust SDK

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#437]
### Feature description
Currently Infisical only has the [Node SDK](https://github.com/Infisical/infisical-node) that enables users to install a package into their apps to fetch back and access their secrets.

It would be great to have a **mirror** Rust SDK that does the same for Rust users.

### Why would it be useful?
This would help Rust users more easily connect their apps to Infisical.

### Additional context
Feel free to help out and join the [Slack community](https://infisical.com/slack).

**Comment by hsantesteban** [comment]
In a private monorepo, I've implemented an MVP async client using the Service Token authentication method. Now I'm implementing sync thread-safe/non-thread-safe variants.

I have no problems submitting a copy if it helps to make progress.

**Comment by dangtony98** [comment]
Hey @hsantesteban!

Thanks for this — We'll be prioritizing this next quarter; I'll definitely reach out around then!

**Comment by cfi2017** [comment]
It would be convenient if this client exposed interop with the `config` crate through a feature flag:

https://github.com/mehcode/config-rs/blob/master/examples/async_source/main.rs

**Comment by akhilmhdh** [comment]
Closing as we have a different repo for sdk
