### ISSUE TITLE
Add Infisical API Key + API documentation with Mintlify

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#44]
### Feature description
The API needs documentation for every endpoint for users and contributors to know what routes are available as well as API keys so users can make requests to the API. We need to update the existing [docs](https://infisical.com/docs/getting-started/introduction) to have a new "anchor" being the API docs; it uses [Mintlify](https://mintlify.com).

### Why would it be useful?
This would make it easier for contributors to visualize, test, and know what APIs are available on Infisical.

### Additional context
You can check out the [/docs](https://github.com/Infisical/infisical/tree/main/docs) folder to see examples of how the existing documentation is being created.

Feel free to direct any API-related questions to me.

**Comment by dangtony98** [comment]
Tasks (open to contribution!):

- [ ] Scaffolding with swagger-ui-express
- [ ] auth
- [ ] integration
- [ ] integrationAuth
- [ ] inviteOrg
- [ ] key
- [ ] membership
- [ ] membershipOrg
- [ ] organization
- [ ] password
- [ ] secret
- [ ] serviceToken
- [ ] signup
- [ ] stripe
- [ ] user
- [ ] userAction
- [ ] workspace

**Comment by mv-turtle** [comment]
This has been completed recently: https://infisical.com/docs/api-reference/overview/introduction
