### ISSUE TITLE
[BUG] Wrong sign-in URL used when generating the Emergency Kit

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#446]
### Describe the bug

Sign-in URL in the Emergency Kit should use the provided `SITE_URL` in the frontend.

- https://github.com/Infisical/infisical/blob/main/frontend/src/components/utilities/generateBackupPDF.ts

### Expected behavior

Users should download a version of the Emergency kit with their correct Infisical instance URL

### Additional context

Seems to hard-coded in the imported config : 
- https://github.com/Infisical/infisical/blob/b944e8bb84dc111324c16255d4b5437cf882dcc5/frontend/src/components/utilities/generateBackupPDF.ts#L3
- https://github.com/Infisical/infisical/blob/b944e8bb84dc111324c16255d4b5437cf882dcc5/frontend/src/components/utilities/config/index.ts#L7

Might be related to #416

**Comment by maidul98** [comment]
I think we can get the host name directly via `window.location.hostname` without hard coding it

**Comment by maidul98** [comment]
Addressed in https://github.com/Infisical/infisical/commit/119600b64f48d8cc6bf39bd28385a05e6e92e651
