### ISSUE TITLE
Tutorials/best practices about self-hosting and secrets-operator InfisicalSecret configuration

### ISSUE THREAD

**Issue by Grraahaam** [Infisical/infisical#448]
### Feature description

If you're within the same cluster, you could use internal DNS in InfisicalSecret's `hostAPI` to automatically sync secrets across your resources without having to expose your app externally.

- `hostAPI: <backend-svc-name>.<namespace>.svc.cluster.local:4000/api`

We could even auto-generate a custom k8s DNS endpoint to the internal backend service to make it easier for the users : 

- `<backend-svc-name>.<namespace>.svc.cluster.local:4000/api`

### Why would it be useful?

Being able to easily sync secrets across your resources without having to expose your backend externally

### Additional context

Slack thread : https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1679063105431759?thread_ts=1677573968.392549&cid=C04BSBMQAQ7

**Comment by PylotLight** [comment]
I imagine something roughly like this with what info you've already provided, unless you set a flag in helm to auto generate and configure it for you:
![image](https://user-images.githubusercontent.com/7006124/226171650-122deb68-a7af-4941-b548-1884c94ee1f8.png)

**Comment by maidul98** [comment]
Great point @Grraahaam , @PylotLight I will review your PR soon

**Comment by PylotLight** [comment]
updated branch name so had to make a new PR, also updated some of the wording. but may need some adjustments, but its a start ;p
https://github.com/Infisical/infisical/pull/452

**Comment by maidul98** [comment]
If the app is not exposed externally how will users interact with the frontend? The frontend requires the backend to also be exposed as apart of our helm chart. Let me know if I have misunderstood

**Comment by maidul98** [comment]
Yes, backend is currently exposed https://app.infisical.com/api/

**Comment by PylotLight** [comment]
My apologies you are both correct, using this example we can see that the backend service is exposed to port 4000 on the specific host path. From understanding though is that we can use services to only have internal communication by clusterIP instead of having to use an ingress for this ending up in using http://backend-service:4000/api.
```
- backend:
          service:
            name: infisical-1677064395-backend
            port:
              number: 4000
        path: /api
```

Happy to take your lead on this though.

**Comment by maidul98** [comment]
@PylotLight if you can verify this method works, i'd be happy to spin it up on my end as well

**Comment by PylotLight** [comment]
@maidul98 it worked great for me.. as per the linked slack thread for going to the service directly with the the hostAPI set to http://...
