### ISSUE TITLE
Improve Debugging Logs

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#451]
Currently, Infisical has a bunch of try-catch blocks with Sentry everywhere in the backend. As a result, whenever any function throws an error, there is no actual error output in the console because the error is sent off to Sentry — This is a problem for anyone trying to debug Infisical without a Sentry account and is frankly annoying.

What's needed is to remove these Sentry logs and replace them with throwing errors from `backend/src/utils/errors` that's [here](https://github.com/Infisical/infisical/blob/main/backend/src/utils/errors.ts). This should be fine because we've previously set up an error-handling middleware [here](https://github.com/Infisical/infisical/blob/main/backend/src/middleware/requestErrorHandler.ts) that should catch any errors thrown from within the app without crashing the server.

The task at hand here is actually fairly easy and requires:
- Searching through the codebase for any signs of Sentry and removing it in favor of throwing one of the errors in this [file](https://github.com/Infisical/infisical/blob/main/backend/src/utils/errors.ts).
- Testing each removed Sentry error to make sure the app doesn't crash and that the final error-handling middleware has caught the error.

**Comment by maidul98** [comment]
I think logs from infisical should be written to file logs file. We can do this via structured logging so that it is easy for users to search and query

**Comment by PylotLight** [comment]
Getting logs into the container would be my preference for focus as plenty of apps/services that integrate with k8s clusters can pull/extract use those logs or even just read straight from pods. I'm pretty keen on something more than nothing which is about what we have at the moment for this one. Quite keen :p

**Comment by meehawk** [comment]
Is this done, should be simple and can take this up

**Comment by PylotLight** [comment]
@meehawk I'm not seeing anyone assigned, I was also thinking about it but am a bit busy, did you want to take it?

**Comment by parthvnp** [comment]
@PylotLight I can start working on it if help is still needed on this one!

**Comment by PylotLight** [comment]
@parthvnp I never started as I didn't hear back from anyone, I'm happy to start or you can if you wish.

**Comment by parthvnp** [comment]
@dangtony98  I am happy to start working on this. Looks like it only needs couple of straightforward changes.

**Comment by parthvnp** [comment]
@Spelchure Sounds good. I will have a look at your[ changes ](https://github.com/Spelchure/infisical/tree/removing-sentry-logs)and see if there is anything left that needs changing.

**Comment by akhilmhdh** [comment]
I think this has been done and released. Closing this issue for now, feel free to open this if its not
