### ISSUE TITLE
Convert Frontend to TypeScript

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#47]
### Feature description
Convert all the files in frontend to TypeScript

### Why would it be useful?
Mainly because of the improved developer experience

### Additional context
There are quite a few JS files, so it might take a while to convert all of them

**Comment by rabbanirizwan** [comment]
@mv-turtle Please let me know about some components that you haven't yet converted so that I can assist you.

**Comment by mv-turtle** [comment]
@rabbanirizwan thank you so much for your help! Could you please help with any file in the `frontend > components > utilities` folder? For example, `file.js`, `randomId.js`, `generateBackupPDF.js`, `cryptography > aes-256-gcm.js`, etc. 

If you want, you can also look into `frontend > components > dashboard > DasboardInputField.js` or `frontend > components > basic > popups > BottomRightPopup.js`

This would be super useful! Also, if you want, you should join our community Slack: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g. You can ask any questions there, and someone will reply almost immediately :)

**Comment by mv-turtle** [comment]
Hi @rabbanirizwan! Would you still be interested in helping out here? Please let me know :)

**Comment by SH5H** [comment]
I'm gonna handle this issue.

**Comment by mv-turtle** [comment]
Thank you so much @SH5H!

**Comment by mv-turtle** [comment]
This has now been completed! Thank you everyone for your help :)
