### ISSUE TITLE
Ownership changes itself

### ISSUE THREAD

**Issue by abdalem** [Infisical/infisical#480]
### Describe the bug
I do not know when this happened, but the owner of my organizations has changed ans I appear as a member. I was the owner, and know it is affected to one the members, as you can see it in my screenshot 

### To Reproduce
I really do not know what happened and how it can be reproduced

### Expected behavior
I expect to still be the owner.

### Screenshots
![image](https://user-images.githubusercontent.com/19971392/229709770-d8cba787-ec1b-4e85-9885-ab3cd151776d.png)

### Platform you are having the issue on:
Cloud Hosting

**Comment by dangtony98** [comment]
Hey @abdalem!

I don't think this would randomly happen (we definitely don't touch/modify any data on our end). 

It could be possible that another member of your organization (another `owner`) may have demoted you to `member`?

**Comment by abdalem** [comment]
That's the problem. There was never been another owner except me, and I never touched this behaviour. I am gonna get in touch with my teammate to reset me as the owner and reach you out if I have any problem.

**Comment by akhilmhdh** [comment]
Closing as stale
