### ISSUE TITLE
exception when importing from Deno npm integration

### ISSUE THREAD

**Issue by uriva** [Infisical/infisical#494]
this is not exactly a bug with infisical, but I think you guys might be able to help anyway
```js
import infisical from "npm:infisical-node";
```
when trying to connect, i'm getting

```
Error: Not implemented: crypto.Decipheriv
    at notImplemented (ext:deno_node/_utils.ts:7:11)
    at new Decipheriv (ext:deno_node/internal/crypto/cipher.ts:67:9)
    at Object.createDecipheriv (ext:deno_node/crypto.ts:26:12)
    at decryptSymmetric (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/utils/crypto.js:100:27)
    at Function.<anonymous> (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/services/SecretService.js:75:70)
    at step (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/services/SecretService.js:33:23)
    at Object.next (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/services/SecretService.js:14:53)
    at fulfilled (file:///home/uri/.cache/deno/npm/registry.npmjs.org/infisical-node/1.0.37/lib/services/SecretService.js:5:58)
    at Object.runMicrotasks (ext:core/01_core.js:406:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:51:14)
Failed to set up the Infisical client. Please ensure that your token is valid and try again.
```

**Comment by dangtony98** [comment]
Hi @uriva!

Thanks for reporting this. I haven't personally used Deno but I'll check on this and get back to you; I'm in the middle of an update for the Node SDK anyways so this may be a good time to check on this too 😛

**Comment by uriva** [comment]
friendly ping

**Comment by neto210206** [comment]
Parece que ocorreu um erro ao tentar se conectar ao módulo "nó físico" usando o Deno. O erro indica que a função "crypto.Decipheriv" ​​​​não está implementada. Isso geralmente ocorre porque o Deno não possui todos os recursos disponíveis no Node.js. Aqui estão algumas considerações e etapas para resolver esse problema.   1. **Compatibilidade Deno/Node.js:** Certifique-se de que o módulo "inphysical-node" seja compatível com o ambiente Deno. Nem todos os módulos desenvolvidos no Node.js podem ser usados ​​diretamente no Deno sem modificações.  2. **Verifique a documentação:** Verifique a documentação do "Nó não físico" para ver se ele suporta o ambiente Deno ou se há instruções específicas para uso com o Deno.   3. **Encontre uma alternativa:** Se o Deno não for compatível diretamente, recomendamos encontrar uma biblioteca alternativa ou semelhante que seja compatível com o Deno e forneça a funcionalidade de que você precisa. 4. **Implementação alternativa:** Se você é bom em criptografia e a funcionalidade "crypto.Decipheriv" ​​​​é importante para seu aplicativo, você pode tentar  uma implementação alternativa usando as funções criptográficas nativas do Deno.   5. **Pergunte ao desenvolvedor:** Se o "nó não físico" for uma biblioteca importante para o seu projeto e você não conseguir encontrar uma solução, entre em contato com o desenvolvedor da biblioteca para ver se eles têm planos de suporte para o Deno. Existem diretrizes?   Deno e  Node.js têm diferenças significativas em  APIs e funcionalidades que podem afetar a transferência direta de módulos entre os dois. Revise a documentação e explore opções alternativas que possam atender às suas necessidades em um ambiente Deno.

**Comment by neto210206** [comment]
1. **Compatibilidade Deno/Node.js:** Verifique se o módulo "infisical-node" é compatível com o ambiente Deno. Nem todos os módulos desenvolvidos para o Node.js podem ser usados diretamente no Deno sem ajustes.

2. **Verifique a Documentação:** Consulte a documentação do "infisical-node" para verificar se ele oferece suporte ao ambiente Deno ou se há instruções específicas para uso com o Deno.

3. **Procurar Alternativas:** Se não houver suporte direto para o Deno, você pode considerar procurar uma alternativa ou biblioteca similar que seja compatível com o Deno e ofereça as funcionalidades necessárias.

4. **Implementação Alternativa:** Se você tiver conhecimento em criptografia e a funcionalidade `crypto.Decipheriv` for crítica para sua aplicação, você pode tentar implementar uma alternativa usando as capacidades criptográficas nativas do Deno.

**Comment by adoublef** [comment]
i just wanted to ask if you had tried using `esm.sh` usually the `npm` specifier fails but the `esm.sh` location can work. (haven't tested for this app yet though)

**Comment by uriva** [comment]
works now thanks
