### ISSUE TITLE
Save changes when a user is leaving the Dashboard page

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#52]
### Feature description
When a user is leaving the dashboard page and they have any saved changes, they should be asked "Do you want to save?". This is for use cases like (some of them are already implemented):
- [x] A page is being refreshed
- [ ] A tab is being closed
- [ ] A user is returning to the previous page (aka accidentally swiping right on Chrome)
- [ ] A user is switching between environments
- [ ] 'Add new tags' is clicked

### Why would it be useful?
Helps prevent use cases when users forgot to save changes.

### Additional context
This is a bit problematic because of the loading screen that shows up when the page components are being loaded. I think the whole structure of the loading animation could be rethought.

**Comment by fervillarrealm** [comment]
@mv-turtle 👋🏼 can I work on this issue?

**Comment by mv-turtle** [comment]
Hi @fervillarrealm! Yes, that would be really amazing! Do you need any help? :)
