### ISSUE TITLE
Install specific Infisical cli version on Alpine

### ISSUE THREAD

**Issue by lperrious** [Infisical/infisical#520]
### Feature description
When using Infisical in my CI/CD pipeline, I need to install the latest version of Infisical CLI in my Dockerfile.

Currently, the installation script looks like this:

```
RUN apk add --no-cache bash curl sudo && curl -1sLf \
'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash \
&& apk update && sudo apk add infisical
```

Wouldn't it be more secure to include versioning in the download script or something similar, such as:
'https://dl.cloudsmith.io/public/infisical/infisical-cli/0.4.2/setup.alpine.sh'

### Why would it be useful?
Including versioning in the installation script would help prevent deployment issues that may occur when a new version of Infisical is released, as was the case with version 0.4.1.

Thanks for this amazing product !

**Comment by maidul98** [comment]
Thanks for brining this up @lperrious, I will add docs on how to pin the CLI to a specific version

**Comment by maidul98** [comment]
You should be able to add `apk add infisical=0.4.2` instead of just infisical to pin it

**Comment by mterron** [comment]
Are you able to upstream the infisical cli instead? It'll be much easier to just `apk add infisical-cli`. Contributing/maintaining a package for Alpine is pretty easy :)
