### ISSUE TITLE
Allow members to remove themselves from projects

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#532]
### Feature description
Projects in Infisical have members and admins. Currently, only admins can remove members from projects; it would be great to have the ability for members to remove themselves (obv not other members) from projects.

### Why would it be useful?
This would be great for folks who may be stuck in projects that they want to opt out of themselves (e.g. me right now).

**Comment by VPashkov** [comment]
I assume admins also should be able to delete themselves if they are not the last admin in the project?

**Comment by dangtony98** [comment]
@VPashkov Yup! Would you be interested in taking a crack at this?

**Comment by VPashkov** [comment]
@dangtony98 sure, I'll give it a try.

**Comment by dangtony98** [comment]
@VPashkov Awesome! 

Feel free to join the [Slack community](https://infisical.com/slack) btw — Great place to chat and coordinate in case you need any help.

Happy to give a walk through the codebase if you need 😄

**Comment by Moscode** [comment]
Hello @dangtony98, has this feat been added?

If it hasn't you can assign it to me?

**Comment by dangtony98** [comment]
Hi @Moscode!

There's an open PR for for it actually #533 but it's been ongoing for a while.

@VPashkov would you have any updates?

**Comment by VPashkov** [comment]
Hi @dangtony98,
I forgot about this PR tbh. Let me take a look.

**Comment by VPashkov** [comment]
There are some comments. I'll address them today.

**Comment by akhilmhdh** [comment]
Closing as completed
