### ISSUE TITLE
Integration with GitHub Actions

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#54]
### Feature description
Be able to automatically send secrets from Infisical to GitHub repositories (for GitHub actions).

### Why would it be useful?
Many people are using GitHub Actions. Being able to sync secrets automatically would save them a lot of time and effort.

### Additional context
GitHub seems to be using Oauth 2.0, which we already have an example of (see the integration with Heroku).

**Comment by gmgale** [comment]
Hey, I would love to have a go at this, would be a first time issue for me, do you think it would be ok? Thanks in advance!

**Comment by gmgale** [comment]
Great, I have joined Slack and posted in the contributions channel 😁

**Comment by beforeoafterm** [comment]
I'm eagerly waiting for this integration! What's the news on the development for this? 😄

**Comment by mv-turtle** [comment]
@beforeoafterm I think @gmgale is looking into this issue this week. It should be ready very soon 😃🚀

**Comment by dangtony98** [comment]
Hey @beforeoafterm!

@gmgale and I are actually working on the integrations right now. We'll be releasing a few new integrations this weekend including this GitHub Actions one so stay tuned! 🙂

**Comment by mv-turtle** [comment]
@beforeoafterm @gaahrdner @leonardbinet @0xflotus this has now been released for a while; forgot to update the issue - please let me know if you have any question about how to set it up :)

the docs are here: https://infisical.com/docs/integrations/cicd/githubactions

**Comment by mv-turtle** [comment]
@Grraahaam indeed! That would be great! We just haven't gotten to that yet. Do you think you would be able to create a separate issue for this? :)
