### ISSUE TITLE
Problem with Copy Button on Add Member

### ISSUE THREAD

**Issue by rahb3rt** [Infisical/infisical#553]
### Describe the bug
When trying to invite members to the app - the copy selection does not work. You can press it but does not paste to your clipboard

### To Reproduce
1. Go to Members 
2. Add Member
3. Add Users to Org
4. Add Member, click add Member
5. Use the copy selection

### Expected behavior
Copy the url to clipboard

### Screenshots
Steps are reproducible - hard to screen shot

### Platform you are having the issue on:
EKS, Local

**Comment by maidul98** [comment]
This is regarding the copy invite for when SMTP is not set up @vmatsiiako

**Comment by maidul98** [comment]
This issue has been addressed in infisical version `v0.1.1`
