### ISSUE TITLE
Problem Going Back - Login Session Times out

### ISSUE THREAD

**Issue by rahb3rt** [Infisical/infisical#558]
### Describe the bug
When trying to go backwards or refreshing the screen in self-hosted instance, even with HTTPS_ENABLED=false the session times out and the user gets logged out. 

### To Reproduce
1. On log in press "Secrets"  at the top and it logs you out when it tries to refresh. Same thing happens when you try and refresh the page on its own.

### Expected behavior
If I go back I should be able to refresh the page or go to another screen.

### Screenshots
n/a

### Platform you are having the issue on:
EKS

**Comment by maidul98** [comment]
Hey @rahb3rt, this issue has been addressed in docker image version v0.1.1. Go ahead and set that version for the frontend and backend image tag and upgrade your helm chart

**Comment by rahb3rt** [comment]
This seems all set. I have another log out issue too but I will open another issue for that. Closing out.
