### ISSUE TITLE
[Refactoring] Overall Frontend Refactoring !!

### ISSUE THREAD

**Issue by Aashish-Upadhyay-101** [Infisical/infisical#561]
### Issue description
I think the entire front-end needs refactoring. At this point adding and removing new features are breaking other features, which are supposed to be independent. Many components are **Tangled**.

### Why would it be useful?
Becomes easy to maintain and add features without breaking anything.

@maidul98 @dangtony98 @vmatsiiako @akhilmhdh

**Comment by akhilmhdh** [comment]
Hey @Aashish-Upadhyay-101 

Indeed and we are working on that refactoring. Page by page we are now refactoring the frontend to better components. 

Some of the things happening inside this refactoring are:

1. Using infisical component library using radix ui components
2. API calls using react-query
3. Better API for components

Currently the milestone is to finish it by this month. 

Sorry to hear that it's blocking others and leaving then confused. Hopefully after the migration everything would be much easier to work with.

**Comment by dangtony98** [comment]
@akhilmhdh you're a legend.

**Comment by muhsinkamil** [comment]
@akhilmhdh Is it something open to contribute ? If so, could you please point out any issues / PRs that does it

**Comment by Budhathoki356** [comment]
> @akhilmhdh Is it something open to contribute ? If so, could you please point out any issues / PRs that does it

I would also like to contribute.

**Comment by akhilmhdh** [comment]
Closing as stale. We will be moving to nextjs 14 soon. But its gonna be slower.
