### ISSUE TITLE
Pressing enter in a modal refreshes the page which requires re-authentication

### ISSUE THREAD

**Issue by shark0der** [Infisical/infisical#571]
### Describe the bug
Pressing enter in a modal refreshes the page which requires re-authentication.

### To Reproduce
1. Go to a project settings
2. Try deleting a service token
3. Type in the service token name
4. Press enter - page refreshes (which is very annoying)

### Expected behavior
"Delete" should be triggered (modal button).

### Screenshots
![image](https://github.com/Infisical/infisical/assets/528959/8c8da970-3a0b-455c-909b-b6a4028e89ba)

### Platform you are having the issue on:
- Chrome 112
- infisical/frontend      latest    eed68a0eb9d8

### Additional context
UX.

**Comment by maidul98** [comment]
@shark0der I have just tested this on Infisical cloud and did not run into this issue. Are you on self hosted by any chance?

**Comment by akhilmhdh** [comment]
Hey @shark0der , we have tested this on our latest ones and think its fixed. 

Feel free to re-open this or create a new one if its still exist.
