### ISSUE TITLE
API POST /api/v3/secrets/{secretName}: server ignores a null string comment and creates a broken secret body

### ISSUE THREAD

**Issue by ntwrick** [Infisical/infisical#593]
### Describe the bug
When a client creates a secret via the API and there is no comment provided (i.e. it is a null string), the secret body contains `"secretCommentCiphertext": ""` (plus its IV & Tag). However, the server then ignores the null comment and saves and retrieves an incomplete body without any of the `"secretComment*"` keys present. 

This breaks any secret retrieval by an SDK that expects and validates a complete secret body including the comment keys. 

Furthermore, if you try to create a secret via the API, the body must have all the `"secretComment*"` keys present or it will fail with a `400 return code`. So, a null comment cannot be represented with missing comment keys.

Also, when there is no secret comment, the webUI always creates/updates a complete secret body that contains the null comment represented as `"secretCommentCiphertext": ""` (plus its IV & Tag). So if you update the API's broken secret's value via the webUI, the next version of the broken body will be corrected with all the null `"secretComment*"` keys in place as expected.

### To Reproduce
1. `POST /api/v3/secrets/{secretName}` with a body containing `"secretCommentCiphertext": ""` (plus its IV & Tag). 
2. Server then saves an incomplete secret body missing all of the `"secretComment*"` keys returning a `200 response code`.
3. `GET /api/v3/secrets/{secretName}` then retrieves the incomplete secret body returning a `200 response code`.

### Expected behavior
Creating, updating and retrieving a secret via the API should behave the same as the webUI.

### Platform you are having the issue on:
Self-hosted Ubuntu Linux docker containers via docker-compose infisical-frontend, infisical-backend:
```bash
$ docker pull infisical/frontend
Using default tag: latest
latest: Pulling from infisical/frontend
Digest: sha256:940e73ebc4bfc0e053022c7b1e419b478e4fe959980164f25d839102f1589ed1
Status: Image is up to date for infisical/frontend:latest
docker.io/infisical/frontend:latest

$ docker pull infisical/backend
Using default tag: latest
latest: Pulling from infisical/backend
Digest: sha256:b76f8a221ea7e7af77360aee82d7edbad1dcef209ca08d841af98bfb04c98678
Status: Image is up to date for infisical/backend:latest
docker.io/infisical/backend:latest
```
### Additional context:
`PATCH /api/v3/secrets/{secretName}` with a body containing `"secretCommentCiphertext": "updated comment"`. In this case the server completely ignores the updated comment  returning with a `200 response code`. The secret's value and version are updated, but the updated comment is not saved and the original comment is still there. This also does not fix the missing null comment `"secretComment*"` keys problem like a webUI update does when the broken body was created by the API as above.

**Comment by daninge98** [comment]
> Furthermore, if you try to create a secret via the API, the body must have all the `"secretComment*"` keys present or it will fail with a `400 return code`. So, a null comment cannot be represented with missing comment keys.

I couldn't repro this, when I `POST /api/v3/secrets/{secretName}` leaving out the `"secretComment*"` keys I seem to get a 200 return code and the secret is created ok? The GET and POST methods here seem consistent.

> ### Additional context:
> `PATCH /api/v3/secrets/{secretName}` with a body containing `"secretCommentCiphertext": "updated comment"`. In this case the server completely ignores the updated comment returning with a `200 response code`. The secret's value and version are updated, but the updated comment is not saved and the original comment is still there. This also does not fix the missing null comment `"secretComment*"` keys problem like a webUI update does when the broken body was created by the API as above.

It looks like `PATCH /api/v3/secrets/{secretName}`only allows you to update `"secretValue*"` keys. The web UI uses the `POST /api/v2/secrets/batch` endpoint to do the comment update which doesn't have that limitation. Agreed it could be nice to be able to update the comment using the v3 PATCH APIs, but maybe this was a deliberate decision, I'm not sure.

**Comment by akhilmhdh** [comment]
Hey there. I think this is fixed without recent release. Closing as its stale. Feel to free to reopen this if its still exist
