### ISSUE TITLE
GUI bug and no scrollbar in project tab.

### ISSUE THREAD

**Issue by Shabbirali-ali** [Infisical/infisical#594]
![image](https://github.com/Infisical/infisical/assets/73350953/b6ee8e73-354d-45bd-a0c4-951c7d0a78a1)
Above image shows GUI bug when delete tag.
![image](https://github.com/Infisical/infisical/assets/73350953/caffbce9-bbf0-490b-8568-f7208c6d3a35)
no Scrollbar in project list.

**Comment by vmatsiiako** [comment]
This should be fixed now thanks to @piyushchhabra!
