### ISSUE TITLE
Integration with Vercel

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#60]
### Feature description
Automatic secret sync with Vercel. As soon as the secrets are added to Infisical, they should be propagated to Vercel.

### Why would it be useful?
Saves time and effort from users. Reduces secret sprawl across different platforms. Decreases room for error with secrets.

### Additional context
Vercel supports Oauth, so this would a similar integration compared to what we already with Heroku.

**Comment by dangtony98** [comment]
On it.

**Comment by mv-turtle** [comment]
Implemented; soon to be deployed
