### ISSUE TITLE
bug: typo

### ISSUE THREAD

**Issue by vikyw89** [Infisical/infisical#608]
### Describe the bug
typo on UI

### Expected behavior
no typo

### Screenshots
![image](https://github.com/Infisical/infisical/assets/112059651/5448921f-c614-48d7-9631-e9dd1bcdb050)

### Platform you are having the issue on:
self hosting

### Additional context
no

**Comment by Budhathoki356** [comment]
Can you assign this to me?

**Comment by vmatsiiako** [comment]
Hi @Budhathoki356! Sorry for the slow reply. I missed this issue. I just assigned the issue to you. Really appreciate your help! :)
