### ISSUE TITLE
Add 2FA

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#61]
### Feature description
When a user logs in, they should (optionally) be prompted to do a 2FA.

### Why would it be useful?
Many users have asked for it. This would increase security of Infisical significantly.

**Comment by dangtony98** [comment]
This is currently under work in the MFA branch :)

**Comment by mv-turtle** [comment]
@anatolinicolae @gaahrdner 2FA is now available for Infisical :)
