### ISSUE TITLE
Feature: Environment Variable Inheritance 

### ISSUE THREAD

**Issue by Braineanear** [Infisical/infisical#613]
### Feature description
Allow environment variable inheritance, so the user can create a base secret environment, and make other environments like dev and production inherit from the base one.

### Why would it be useful?
This will prevent lots of envs to be repeated in other secret envs in the project.

**Comment by vmatsiiako** [comment]
Hi @Braineanear! Indeed, this would be awesome and this is one of the features that are planning to start working on soon!

**Comment by akhilmhdh** [comment]
Hey @Braineanear This has been released with our new version [doc](https://infisical.com/docs/documentation/platform/secret-reference#import-entire-folders). Do check it out and feel free to open an issue, if its not the one your looking for.

**Comment by akhilmhdh** [comment]
Hey @dstockhammer .

For these kinda usecase there is secret import feature which basically links one board with another and it will pull all those secrets to here.

https://infisical.com/docs/documentation/platform/secret-reference#secret-imports

**Comment by dstockhammer** [comment]
Oh I see! That's great, I completely missed that, my bad! Thanks :)

**Comment by akhilmhdh** [comment]
@dstockhammer no worries feel free to create issues or discussions. Happy to resolve it and make infisical better each day
