### ISSUE TITLE
Secrets operator is not expanding secrets

### ISSUE THREAD

**Issue by alexbarcelo** [Infisical/infisical#619]
### Describe the bug

A secret with a reference (just as in the example project, something like `SECRET=https://${HOSTNAME}/api`) works as intended with the infisical CLI, but the secret generated in kubernetes does not expand).

### To Reproduce

1. Generate a secret with a reference.
2. Configure an InfisicalSecret resource in kubernetes.
3. Wait for the Secret to be generated by the operator.
4. The generated secret has `$...` instead of expanding the secrets (which, for instance, is the default behavior of `infisical run`)

### Expected behavior

The expand behavior to be the default for the operator (to match the behavior of the CLI).

### Screenshots
N/A

### Platform you are having the issue on:
Kubernetes `secrets-operator` installed via helm chart, version 0.1.6

### Additional context
N/A

**Comment by akhilmhdh** [comment]
Hey @maidul98,

This should have been fixed with our recent secret reference release, right. if so let's close this for now.

**Comment by maidul98** [comment]
Yes, secrets are now expanded on version 0.2.0 and higher

**Comment by McPatate** [comment]
Hello, are you sure this is fixed? I'm observing the same behavior.

I installed the secrets operator with the following command:
```sh
helm install --generate-name infisical-helm-charts/secrets-operator --version=v0.5.0 --set controllerManager.manager.image.tag=v0.5.0
```
And running infiscal standalone:
```yaml
  infisical-standalone-infisical:
    Image:          infisical/infisical:v0.51.5-postgres
```

**Comment by akhilmhdh** [comment]
Can you also upgrade the server please.

**Comment by andrewkachan** [comment]
@akhilmhdh I faced with the same issue. I use server  infisical/infisical:v0.63.1-postgres and operator infisical/kubernetes-operator:v0.5.1

**Comment by akhilmhdh** [comment]
You need to update the server and operator.

@DanielHougaard i remember you found the exact minimal version to expand secret reference

**Comment by WladyX** [comment]
I am on v0.77.0-postgres + v0.5.1 and the secret does not expand.

**Comment by WladyX** [comment]
For future generations, finally found out why it was not expanding, it did not have reads to read from the referenced secret, so it was not expanding it.
