### ISSUE TITLE
Add an `export` command with a few format options

### ISSUE THREAD

**Issue by edgarrmondragon** [Infisical/infisical#62]
### Feature description

A new `export` command that exports secrets in one of a few available formats. Some good initial formats may be:

- `dotenv`
- `json`
- `csv`

### Why would it be useful?

This would allow users to process secrets into a structure compatible with other tools.

### Additional context

This is similar to and inspired by [chamber](https://github.com/segmentio/chamber#exporting)'s export command.

**Comment by mv-turtle** [comment]
Hi @edgarrmondragon! This is a great idea! We are currently working on setting up a series integrations for Infisical with other staging/product 3rd party services, but we will try to work on this issue right after that. 

If you have time and interest, feel free to send a PR for this. Any help is appreciated :)
