### ISSUE TITLE
Failed to validate that the encryption key is correctly encoded in hex

### ISSUE THREAD

**Issue by filippocozzini** [Infisical/infisical#623]
During the deployment of Infisical (Helm chart), the pods of the backend service return this error: 

Kubernetes version: _v1.27.2_
Infisical chart: _infisical-0.1.17_
Infisical version: _1.17.0_
```
> infisical-api@1.0.0 start
> node build/index.js

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RequestError: Failed to validate that the encryption key is correctly encoded in hex.
    at InternalServerError (/app/build/utils/errors.js:91:12)
    at /app/build/utils/setup/validateConfig.js:40:52
    at Generator.next (<anonymous>)
    at fulfilled (/app/build/utils/setup/validateConfig.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  _logLevel: 400,
  _logName: 'ERROR',
  statusCode: 500,
  type: 'internal_server_error',
  context: {},
  extra: [],
  stacktrace: [
    'Error: Failed to validate that the encryption key is correctly encoded in hex.',
    '    at InternalServerError (/app/build/utils/errors.js:91:12)',
    '    at /app/build/utils/setup/validateConfig.js:40:52',
    '    at Generator.next (<anonymous>)',
    '    at fulfilled (/app/build/utils/setup/validateConfig.js:5:58)',
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  ]
}
```

**Comment by dangtony98** [comment]
Hi @filippocozzini!

Can you give an example value that you’re passing in for the encryption key?

I would recommend using ROOT_ENCRYPTION_KEY and passing in a 255-bit base64 string for it.

**Comment by dangtony98** [comment]
Can you paste an example value?

**Comment by filippocozzini** [comment]
Sure, `AD1102688170C3F1D182CB1F3E6BB222` was just generated following the example provided in the chart documentation.

**Comment by filippocozzini** [comment]
Sorry for the delayed response, I tested what you told me, but the error still persists.

The new generated key setted to backendEnvironmentVariables. ROOT_ENCRYPTION_KEY is: `VueLsQHYP0Lc22Smp2Kisp+jS0hw/8GA7vC9xJ9gO30=`

**Comment by filippocozzini** [comment]
I also tested with the key generated in lowercase, but the same error still occurs.

**Comment by dangtony98** [comment]
@filippocozzini Hmm perhaps something else may be wrong. @maidul98 can assist you with this.

Also, do feel free to join the [Slack community](https://infisical.com/slack); it's typically much easier to communicate/assist there.

**Comment by filippocozzini** [comment]
Thank you @maidul98, now everything is working correctly.
