### ISSUE TITLE
Disable Sign Up Environment Option On Selfhost

### ISSUE THREAD

**Issue by phamleduy04** [Infisical/infisical#644]
The current feature allows users to sign up for an environment on self-hosted instances of Infisical. However, there is a need to disable this option for certain use cases. This feature aims to provide the ability to disable the sign-up environment option on self-hosted instances.

**Comment by dangtony98** [comment]
Hi @phamleduy04 I'm not sure I understand what you mean by disable signup environment option on self-hosted — Could you elaborate?

**Comment by phamleduy04** [comment]
So after I create my account, I don't need to use the "Sign up" feature because only I use it. And I want to disable it through the environment option. For example, `DISABLE_SIGNUP=true`, when I want to enable it to create another account again, I just switch it to `false`.

**Comment by maidul98** [comment]
This is already out, please have a look under the `other` tab here https://infisical.com/docs/self-hosting/configuration/envars and you will see there is something called `INVITE_ONLY_SIGNUP`

**Comment by LFS-rmanichand** [comment]
Does the INVITE_ONLY_SIGNUP field still work?
