### ISSUE TITLE
TeamCity Integration

### ISSUE THREAD

**Issue by d11ahirst** [Infisical/infisical#646]
### Feature description
TeamCity Integration

### Why would it be useful?
It would aid in passing secrets to builds/projects using CI/CD

**Comment by dangtony98** [comment]
@d11ahirst Thanks for this! — I've since added the TeamCity integration to our [public roadmap](https://www.notion.so/infisical/be2d2585a6694e40889b03aef96ea36b?v=5b19a8127d1a4060b54769567a8785fa).

**Comment by b4s36t4** [comment]
@dangtony98 I would love to take this up. Any documentation to start will help. Thanks!

**Comment by dangtony98** [comment]
@b4s36t4 Any update on this?

I can assign you to this issue; alternatively, we can free it up for other contributors as a good first issue.

**Comment by b4s36t4** [comment]
@dangtony98 would love take up. Need your help in somethings... I'll connect with you soon. Timezone issues 😅

**Comment by dangtony98** [comment]
@b4s36t4 Sounds good.

Feel free to [schedule a time for a chat/walkthrough](https://cal.com/tony-infisical/30-min-meeting-contributing) — We do these frequently to get folks acquainted with the codebase 😄

**Comment by d11ahirst** [comment]
Thanks for looking to support this, much appreciated

**Comment by vmatsiiako** [comment]
Hi team! Curious if there is any progress on this integration?

**Comment by afrieirham** [comment]
## How to implement this.

### Undetstanding TeamCity
1. Create TeamCity account using email and password (GitHub login doesn't work, I've tried)
2. Create New Project from GitHub, feel free to use this [repo](https://github.com/afrieirham/infisical-cloud66). Just proceed with default config.
3. After project is set up. Click on "configure build steps manually" and choose Node.js. Fill in as below and save.

![image](https://github.com/Infisical/infisical/assets/32460534/f405d71b-da23-480c-8f05-2004c18c7a5a)

4. Go back to the projects page by clicking it in the breadcrumbs. 

![image](https://github.com/Infisical/infisical/assets/32460534/ec610e60-4230-43df-bff5-c9a615db3fe6)

5. In the left navigation bar, click on Show more > Parameters. This is where you can manage your secrets.

![image](https://github.com/Infisical/infisical/assets/32460534/57d22bb5-5cc1-4af7-bf4f-1f2b8f6478fc)

6. Click on "Add Parameters" and fill it out like this and save.

![image](https://github.com/Infisical/infisical/assets/32460534/af7744ca-4ce8-4330-b87e-0d2143bd63f9)

7. Go back to the projects page, you can click the button at the top right corner. Then navigate back to your project and click on the "Run" button. 

![image](https://github.com/Infisical/infisical/assets/32460534/f0cc9373-b4e4-4f7e-b812-ef412e7afe49)

8. Click on the build and navigate to "Build Logs" and if everything went right, you can see the value of the env variable.

![image](https://github.com/Infisical/infisical/assets/32460534/19a57db3-6ac5-45f6-8927-b93bf32a31f3)

### Understanding TeamCity API

Note that TeamCity API returns XML as response (i know 😩) but we can use JSON for the request body. You can refer to their docs [here](https://www.jetbrains.com/help/teamcity/rest/).

To integrate with Infisical, we typically need an endpoint to
- list the projects of the platform 
- show/update secrets

Also note that the base URL for the API is the domain you've configured when you signed up. For me it's this `https://infisicial-demo.teamcity.com`.

You can refer [here](https://www.jetbrains.com/help/teamcity/rest/quick-start.html#Authentication) to get the API tokens.

Here are the endpoints that you want to focus on:
- [List Projects](https://www.jetbrains.com/help/teamcity/rest/get-project-details.html#List+Projects) 
- [Manage Parameters](https://www.jetbrains.com/help/teamcity/rest/edit-project-settings.html#Manage+Project-Level+Build+Parameters)

Some notes:
- Can only add 1 secrets at a time
- Can only edit 1 secrets at a time. If you make a `PUT` request to `/app/rest/projects/<PROJECT_ID>/parameters` without providing secrets id, it will delete all secrets. 
- To handle this you can refer to this sample implementation [here](https://github.com/Infisical/infisical/blob/7bccfaefac01dd248669d3b704a05eca3f337cd9/backend/src/integrations/sync.ts#L2165C36-L2165C36).

**Comment by atimapreandrew** [comment]
Hello @dangtony98

Please, I would love to work on this.

**Comment by dangtony98** [comment]
Assigned!
