### ISSUE TITLE
Add Mock Server

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#65]
### Feature description
Add a mock server to the codebase such as [msw](https://github.com/mswjs/msw).

Preferably use a popular, production-ready library.

### Why would it be useful?
This would allow developers to mock implementation of backend server logic prior to building out the full thing.

**Comment by dangtony98** [comment]
Hey @SH5H - I think this is a great idea! Would love if you could implement this for us :)

Thanks so much. Let me know if you need any help!

**Comment by shabaz39** [comment]
Hi, is this still relevant ?

**Comment by akhilmhdh** [comment]
Closing as stale
