### ISSUE TITLE
Integration with Northflank

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#652]
### Feature description
It would be great to have an integration with [Northflank](https://northflank.com/).

### Why would it be useful?
This would enable users of Northflank to store and sync their environment variables from Infisical to Northflank.

### Additional context
This should be fairly simple with a ton of examples to go off of 😄

**Comment by ChukwunonsoFrank** [comment]
hey @dangtony98,

I would love to take this on.

**Comment by dangtony98** [comment]
Go for it @ChukwunonsoFrank 😄
