### ISSUE TITLE
Pub/Sub

### ISSUE THREAD

**Issue by d11ahirst** [Infisical/infisical#655]
### Feature description
Websocket pub/sub on key changes.

### Why would it be useful?
This would be useful for service integration on various SDKs integrating with infisical, being able to get notifications if a secret changes is a game changer.

**Comment by maidul98** [comment]
We plan to add web hooks to notify when secrets have been changed this. Would this fit your use case as well?

**Comment by dangtony98** [comment]
Great idea regarding webhooks @maidul98

**Comment by d11ahirst** [comment]
> 

Yes that would be perfect, thanks for looking into this

**Comment by maidul98** [comment]
Webooks are now available https://infisical.com/docs/documentation/platform/webhooks
