### ISSUE TITLE
Being able to modify secrets from the environment overview

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#656]
### Feature description
In the environment overview section (screenshot 1), users should be able to click on any of the rows, and get a modal popup that allows them to edit secrets for every environment. 

It should probably look like the popup in the screenshot 2 (though feel free to propose you own ideas). The only difference should be that next to each secret value there should be a save button that gets activates only when the value has been edited. 

<img width="1776" alt="Screenshot 2023-06-16 at 09 45 20" src="https://github.com/Infisical/infisical/assets/78047717/315f75f8-12e9-4139-a63d-3cd8aebf8901">
<img width="607" alt="Screenshot 2023-06-16 at 09 46 39" src="https://github.com/Infisical/infisical/assets/78047717/6bde188a-3c7c-424d-b140-703270e00f7d">

### Why would it be useful?
This increases the user experience significantly.

**Comment by unkletayo** [comment]
@vmatsiiako I'd love to take this up

**Comment by vmatsiiako** [comment]
Hi @unkletayo! That sounds great. I just assigned this issue to you. Do you need any help with this? Are you already in our Slack for contributors, by the way? (https://infisical.com/slack)

**Comment by unkletayo** [comment]
Hi @vmatsiiako sorry this dropped off, I'd like to reopen this and work on it

**Comment by vmatsiiako** [comment]
Hi @unkletayo! This has actually been implemented today. Would you want to find some other interesting issue? 

Feel free to ask any questions in our Slack community (link to join is https://infisical.com/slack)
