### ISSUE TITLE
Stripe Error

### ISSUE THREAD

**Issue by d11ahirst** [Infisical/infisical#660]
### Describe the bug
Selfhosted is calling the stripe api but resulting in a 401
```
[https://api.stripe.com:443/](https://api.stripe.com/) [401]
{
http.method: GET
}
```
### To Reproduce
Randomly move about the UI

### Expected behavior
No 403 on selfhosted

### Screenshots

![error](https://github.com/Infisical/infisical/assets/44964270/b1ff702f-0924-467d-b2ab-435db889aa67)

### Platform you are having the issue on:

Docker/Linux64

**Comment by maidul98** [comment]
@dangtony98

**Comment by dangtony98** [comment]
Hi @d11ahirst!

Thanks for this; you can ignore this for the time being (it's not relevant for self-hosting) but I'll have it removed in the next day or two :)

**Comment by d11ahirst** [comment]
Thanks for replying, great product BTW

**Comment by dangtony98** [comment]
@d11ahirst Does this issue occur when you take a specific action or navigate to a specific page? — Trying to reproduce it.

I think I found the case but just want to be sure.

**Comment by dangtony98** [comment]
Hi @d11ahirst!

The Stripe error should be gone now as of the last deploy 😄

Feel free to re-open this issue if you encounter this error again.
