### ISSUE TITLE
Selfhosted results in backend request error

### ISSUE THREAD

**Issue by d11ahirst** [Infisical/infisical#665]
### Describe the bug
Getting spammed with the following
```
2023-06-19T14:40:40.982Z [IFSC:@backend-main] error: The server encountered an error while processing the request
```

Not sure if its related but also getting spammed with:

```
Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly
```

### To Reproduce
1. Selfhost in docker
2. Move around the UI adding secrets and saving
3. Notice that the UI is very laggy

### Expected behavior
No errors to occur

### Platform you are having the issue on:

Docker, backend-main and frontend-main

**Comment by dangtony98** [comment]
Hi @d11ahirst!

Thanks for reporting this; I'll check on the backend.

@vmatsiiako Can you assist with checking on the `sharp` issue? (I believe it's on the frontend as well as with the laggy UI)?

**Comment by o10s** [comment]
Just saying that I did reproduce the issue using the standalone version of the docker image with tag 6b9aa20 @dangtony98

**Comment by ganga2166** [comment]
you also make sure that the SITE_URL environment variable is being provided to the infisical-backend as https://your-domain.com/

**Comment by mpsOxygen** [comment]
I have the exact same problem and SITE_URL is defined correctly.

**Comment by maidul98** [comment]
@mpsOxygen Infisical cloud is based on the same image that is available to all users. Can let us know which version you are using and how the container is being orchestrated (kubernetes, docker compose, etc)?

**Comment by mpsOxygen** [comment]
> @mpsOxygen Infisical cloud is based on the same image that is available to all users and I don't see any laggy UI issue. Can let us know which version you are using and how the container is being orchestrated (kubernetes, docker compose, etc)?

After some more debugging we found that the helm chart used to install infisical on our cluster set some limits on RAM that where to low, this caused the backend pods to be slow or even get OOM killed. We used the latest version of the chart to upgrade and it seems the limits where removed and all is fine now.

**Comment by maidul98** [comment]
Yes, awesome!
