### ISSUE TITLE
Remove backend dependencies: await-to-js and builder-pattern

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#666]
As part of the initiative to trim dependencies, it'd be great to remove the `await-to-js` and `builder-pattern` dependencies from the `backend`.

Currently, `await-to-js` is only used in `secretController` and `tagController`; both occurrences can be re-written to not use `await-to-js`. For example, in `backend/src/controllers/v2/tagController.ts`:

```js
const sanitizedTagToCreate = Builder<ITag>()
    .name(name)
    .workspace(new Types.ObjectId(workspaceId))
    .slug(slug)
    .user(new Types.ObjectId(req.user._id))
    .build();

  const [err, createdTag] = await to(Tag.create(sanitizedTagToCreate));

  if (err) {
    if ((err as MongoError).code === 11000) {
      throw BadRequestError({ message: "Tags must be unique in a workspace" });
    }

    throw err;
  }
```

Can likely just be condensed to something like:

```js
const createdTag = Tag({
     name,
     workspace: new Types.ObjectId(workspaceId),
     slug,
     user: req.user._id
}).save()
```

with the error thrown and caught in the error-handling middleware.

Same goes for `builder-pattern`.

### Additional context
This would trim some unnecessary dependencies on the backend.

**Comment by atimapreandrew** [comment]
Hello @dangtony98 

I would love to work on this, please can you assign it to me.

Thanks.

**Comment by atimapreandrew** [comment]
Hello @dangtony98 

I just submitted a Pull Request for this issue! 🚀 .
