### ISSUE TITLE
Terraform Cloud Integration

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#668]
### Feature description
It would be great to have an integration with [Terraform Cloud](https://app.terraform.io/session).

### Why would it be useful?
This would enable users of Terraform Cloud to store and sync their environment variables from Infisical to Terraform Cloud.

### Additional context
This should be fairly simple with a ton of examples to go off of 😄 — This integration involves using an API token (procedure should be similar to Render, Fly.io integrations, etc.).

**Comment by atimapreandrew** [comment]
Hello @dangtony98

I would love to work on this.

Thanks.
