### ISSUE TITLE
`Ctrl + Z` to undo tasks like. Deleted a secret by mistake. 

### ISSUE THREAD

**Issue by KunalSin9h** [Infisical/infisical#67]
### Feature description
If someone accidentally deleted any secret then it is very helpful to get it back by `Cltr + Z`.

**Comment by mv-turtle** [comment]
Hey @KunalSin9h! Thank you for submitting an issue. This is a great idea :)

Let me know if you would be interested in taking a stab at it yourself. If you want, we can schedule a quick pairing session to guide you through the codebase.

**Comment by KunalSin9h** [comment]
its not only `Ctrl + Z`. we can add a prompt to **UNDO** task. like what google drive does.
![image](https://user-images.githubusercontent.com/82411321/205474829-005799ac-7d23-4735-9290-49fdd19dbbf3.png)

**Comment by mv-turtle** [comment]
Yes, this would be amazing!
