### ISSUE TITLE
Web hooks for secret actions

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#670]
### Feature description
Create web hooks for when secrets get updated, newly added, or removed so that third party services can act on these events 

### Why would it be useful?
This has been requesed by a handful of users who want to run some processes such as reloading their app when changes occor

**Comment by jbaggs62** [comment]
+1 on this, would love this for my personal stuff so i can create webhooks for my discord servers!

**Comment by maidul98** [comment]
Wehooks are now available https://infisical.com/docs/documentation/platform/webhooks !
