### ISSUE TITLE
Laravel Forge Integration

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#672]
### Feature description
It would be great to have an integration with [Laravel Forge](https://forge.laravel.com/).

### Why would it be useful?
This would enable users of Laravel Forge to store and sync their environment variables from Infisical to Laravel Forge.

### Additional context
This should be fairly simple with a ton of examples to go off of 😄 — This integration involves using an API token (procedure should be similar to Render, Fly.io integrations, etc.).

**Comment by atimapreandrew** [comment]
Hello @dangtony98

I would love to work on this, please can you assign it to me.

Thanks.

**Comment by dangtony98** [comment]
Assigned!

**Comment by atimapreandrew** [comment]
Hello @dangtony98 

I just made a PR for this feature, please review it.
