### ISSUE TITLE
Edit secrets directly in the environment overview

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#676]
### Feature description
When users open the environment overview, they should be able to edit secrets by clicking any of the rows. After they click on a row a modal similar to this one should open (it should have save buttons for every environment): 
<img width="724" alt="Screenshot 2023-06-21 at 19 46 15" src="https://github.com/Infisical/infisical/assets/78047717/c76a45c0-1b07-4120-9248-5a5d80240eb4">

### Why would it be useful?
It would make it much easier for users to edit secrets. They wouldn't have to go into every environment. 

### Additional context
This feature has been requested by lots of users at this point :)

**Comment by Saksham294** [comment]
@vmatsiiako I would like to work on this issue

**Comment by lorinaX** [comment]
Could you please provide some additional information? I've attached a screenshot below for reference.
Would you prefer to have a button next to each 'secret' entry that allows users to edit their .env files directly? Alternatively, we can have a single 'Edit' button that opens a popup window displaying all the user's secrets for editing. Please let me know your preference.

![image](https://github.com/Infisical/infisical/assets/136234404/dea18e0c-bb74-4f3e-9f14-b06624009307)

**Comment by vmatsiiako** [comment]
I think after you click on any value in the dashboard (or potential on a pencil icon), it should look like this

<img width="1600" alt="Safari (Big Sur) - Dark" src="https://github.com/Infisical/infisical/assets/78047717/5221aa80-30b1-441a-af93-05e80b995918">

**Comment by lorinaX** [comment]
I added an edit button, but I'm not sure which files to check for the 'popup' component shown in your screenshot. It takes time to get familiar with a repository, so if you could let me know the name of that component (and one place where you have used it), I can finish implementing this feature.

![image](https://github.com/Infisical/infisical/assets/136234404/5c0a8a38-e77c-4447-8b68-4b03ff9b00d8)

**Comment by akhilmhdh** [comment]
This has been completed with our recent release. Thus closing this issue for now.
