### ISSUE TITLE
Windmill Integration

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#679]
### Feature description
It would be great to have an integration with [Windmill](https://github.com/windmill-labs/windmill).

### Why would it be useful?
This would enable users of Windmill to store and sync their environment variables from Infisical to Windmill.

### Additional context
This should be fairly simple with a ton of examples to go off of 😄

**Comment by nevvada** [comment]
hey @dangtony98, I'd be interested in working on this!
