### ISSUE TITLE
Audit Log export 

### ISSUE THREAD

**Issue by jbaggs62** [Infisical/infisical#680]
### Feature description
A way to expose the audit logs to be logged to other logging solutions like datadog, grafana or new relic.

### Why would it be useful?

- Exporting to long term logging solution would allow for better searching of audit logs
- ability to build dashboards on top of audit logs
- setup custom alerts via audit logs that integrate with slack, jira etc via other logging solutions

**Comment by vmatsiiako** [comment]
Yes, indeed that would be a great feature!

**Comment by ptdatta** [comment]
Hey @vmatsiiako  Can I work on it?

**Comment by akhilmhdh** [comment]
Closing as completed
