### ISSUE TITLE
Not work as expected in docker image since CLI version 0.7

### ISSUE THREAD

**Issue by Biromain** [Infisical/infisical#688]
### Describe the bug
Hello,

I'm using the PaaS version (although it's the same thing for self-hosted).

* I've created a project with two folders in it (backend/frontend)
* I'm using the CLI in my docker image.
* I have created my token with the path /backend. (Not API key)
I've created a secret dummy at the root of the project.

1. With versions 0.7+, when I do `infisical secrets`
I get `CallGetSecretsV3: Unsuccessful response ... [response={}]`

2. When I lock the CLI version (0.6.4),
I get the secrets at the root of the project and not the one in my folder (which seems normal given that the folder functionality is recent but also shows me that my setup can contact Infisical in version 0.6.4).

Note that I don't change my token, it is provided by variable env in the image.
It's the same configuration for both.

I can get encrypted version of my secrets from API.

### To Reproduce
Already reproduced by @maidul98 

### Expected behavior
Get my secrets :)

**Comment by jcollas** [comment]
I have this exact same problem.  I have my secrets in folders and when I create a service token scoped to that folder, infisical-cli  `infisical run` fails with `CallGetSecretsV3: Unsuccessful response ... [response={}]`.  When secrets are at the top level, no problem.

**Comment by maidul98** [comment]
The patch to this issue has been released in CLI version v0.8.1. Please update your CLI to the latest version

**Comment by jcollas** [comment]
That's great.  Does it also fix the kubernetes operator?

**Comment by maidul98** [comment]
@jcollas  Yes

**Comment by jcollas** [comment]
Yes, everything is working as expected now.  Thanks for the quick turnaround.  I have 70+ deployments in k3s and didn't want to have all the secrets in the top-level namespace, so much appreciated.  I have a bunch of new stuff to learn now :-)

**Comment by akhilmhdh** [comment]
Hey @Biromain , did this resolve for you. If so, can we close this issue.

**Comment by Biromain** [comment]
```
# infisical --version
infisical version 0.8.1
```

I can get all secrets in my folder.
Thank you
