### ISSUE TITLE
Add note in Development docs for changes in docker compose V2 command

### ISSUE THREAD

**Issue by sunilk4u** [Infisical/infisical#689]
### Describe the bug
Docker compose v2 supports `docker compose` not the older `docker-compose` by default. If you want to use `docker-compose`, then you have to enable alias in settings. A heads up / tip in local development docks would be great. 

### Screenshot of error
![error image](https://github.com/Infisical/infisical/assets/42198140/b7f1feb5-7d29-4588-8669-5f3d9cac5886)

### Platform you are having the issue on:
linux (linux mint xfce) / windows 11

### Additional context
![docker blog image](https://github.com/Infisical/infisical/assets/42198140/191143fa-1f56-4f89-974e-55e869695207)

**Comment by JayK1524** [comment]
I would like to work on this issue.

**Comment by shashank40** [comment]
Hi @jaykesarkar you are still working on it or should i take on from here?

CC: @sunilk4u

**Comment by jaykesarkar** [comment]
> Hi @jaykesarkar you are still working on it or should i take on from here?
> 
> CC: @sunilk4u

You can take on from here

**Comment by JunedKhan101** [comment]
Hi, First time contributing to this project. Kindly assign this task to me.

**Comment by unkletayo** [comment]
I'd love to work on this if this is still open

**Comment by akhilmhdh** [comment]
Closing as stale
