### ISSUE TITLE
Allow multi-line environment variables

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#69]
### Feature description
Something that we want to do is to make it possible to input multi-line environment variables into the Dashboard. Currently it's not possible yet, but some users have asked for it.

### Why would it be useful?
It would allow Infisical to support this type of environment variables. It is less common, but still many people need it

**Comment by adrianmarinwork** [comment]
Hello, I would like to take care of this new feature pls

**Comment by mv-turtle** [comment]
Hi @adrianmarinwork! That would be awesome! Do you need any help with understanding the codebase? If you want, we can schedule a quick call. Let me know

Also, you're very welcome to join our community Slack - where you can ask any questions, and discuss anything related to secrets management and Infisical :) Here is the link: https://join.slack.com/t/infisical-users/shared_invite/zt-1kdbk07ro-RtoyEt_9E~fyzGo_xQYP6g

Thank you so much for your help!

**Comment by adrianmarinwork** [comment]
Hello, this is not related to this issue but I came across this small problem. In the Login screen, because you have the class `h-screen` in the main container with the background color, the height of this container is fixed making the background not fit the height of the screen and leaving a blank space behind the Login box, also the Login box does not have a margin-bottom, so the box does not have space below. By removing this `h-screen` class and adding margin to the box it looks way better.

![image](https://user-images.githubusercontent.com/118568289/205635042-5b1dec0b-c919-4f57-b894-44d70a129116.png)
![image](https://user-images.githubusercontent.com/118568289/205635137-5871f40d-6db5-43a9-af49-3b82d4cab56e.png)
![image](https://user-images.githubusercontent.com/118568289/205635225-67f90dae-263e-4640-b1ea-1fd0f0039c44.png)

**Comment by adrianmarinwork** [comment]
I pretended to add it together with the PR to the solution of this issue #69. If you prefer you can update it and I discard the changes.

**Comment by mv-turtle** [comment]
Sounds good! You can just add it to #69 then. Thank you!

**Comment by mv-turtle** [comment]
[This page](https://infisical.com/docs/contributing/FAQ) should also be helpful! But yeah, if you join Slack, I can help you debug easily. Let me know if you need anything though

**Comment by adrianmarinwork** [comment]
I've managed to run the docker-compose and the localhost is running :D
Do you have a developing account or do I have to create an account?

**Comment by mv-turtle** [comment]
Perfect! Yes, you need to create one :) The database is personal for everyone because it's local

**Comment by dangtony98** [comment]
Hey Adrian!

The `SMTP_USERNAME` and `SMTP_PASSWORD` should be your email username and password. `team@infisical.com` was provided there as a placeholder for the username. In practice, we set up a test email for Infisical to send emails; this can be a gmail account.

As @mv-turtle  mentioned, if you run into any errors with authenticating into your email, [this](https://stackoverflow.com/questions/72547853/unable-to-send-email-in-c-sharp-less-secure-app-access-not-longer-available/72553362#72553362) may help.

Would be happy to assist you in real time over Slack or hop on a call to help you sort it out 😄

**Comment by mv-turtle** [comment]
@adrianmarinwork! Did it work? :)

**Comment by adrianmarinwork** [comment]
By the way, I'm not able to join the slack because my microphone is broken and I'm not able to speak.

**Comment by mv-turtle** [comment]
Hmmm, looking into this! You started registering an account in the local development environment, and then got an email with a code right? 

We use Slack for messages by the way. It's just a bit easier to message each other there. You don't need to speak :)

**Comment by adrianmarinwork** [comment]
Hello, by the environment variables and the dashboard we are talking about this inputs field right? 

![image](https://user-images.githubusercontent.com/118568289/205686031-91fc9791-aa7d-4386-bc28-16fc178753eb.png)

**Comment by mv-turtle** [comment]
Hey @adrianmarinwork! I'm wondering if you need any help. Let me know if you need anything at all :)

**Comment by adrianmarinwork** [comment]
Hey, yeah no problem, I've been working on other stuff.
To do this we will have to change the inputs for textareas with more styling, in order to accept multi-line variables.

**Comment by adrianmarinwork** [comment]
After some time, I noticed that this task is bigger than I excepted and I can't give it the time that it needs. Thank you for giving me the chance to work on it, but I would like to leave the task to someone else that has more experience with the codebase or wants to try, at least we have learned stuff along the way here right? :D
Anyway, as I said in Slack, I can take care of the documentation for the "first steps as a developer" to start with the localhost and work on the project. What do you think?
I'm sorry, thank you for giving me the chance!

**Comment by mv-turtle** [comment]
Hey @adrianmarinwork! No worries at all! Thank you so much for trying :) 

Yes, if you could help writing documentation for the "first steps as a developer", this would be awesome!!! I think we have many people struggling with that. If you want, just create a separate issue for that. 

If you're interested, I can also propose quicker/easier issues than this one. Let me know :)

**Comment by adrianmarinwork** [comment]
I'll create an issue and take care of the documentation!
What do you propose me?

**Comment by PylotLight** [comment]
@mv-turtle I'm reviewing this issue as it's a blocker for me to use this app without multiline secrets.
Why do we need to conditionally render textarea, can we not just use textarea for everything so that support is automatic? 
(which the app Lens does in it's UI)

**Comment by mv-turtle** [comment]
@PylotLight Yes, we can try that! I will look into that right after I merge the new dashboard rework

**Comment by vmatsiiako** [comment]
This [PR](https://github.com/Infisical/infisical/pull/692) is supposed to fix this issue.
