### ISSUE TITLE
Warning message in integration provider connect modal

### ISSUE THREAD

**Issue by akhilmhdh** [Infisical/infisical#691]
### Feature description

As requested by one of our user, it would be great to put a small warning message in the provider connection screen that tells user: The existing secrets will be removed and infisical provided ones will get replaced. 

### Why would it be useful?

Good user experience

### Additional context

This needs to be added below title of all the screens of providers. Like 
1. `/pages/heroku/create`
2. `/pages/vercel/create`

Ref UI:

![Screenshot 2023-06-28 at 11 03 34 AM](https://github.com/Infisical/infisical/assets/31166322/cc5d0422-53bc-4ce6-961c-932ef16728b6)

Something like above after title

**Comment by dragonRageX** [comment]
Hi, it's my first time solving bugs...
How do I get started?
Are there any docs that I can go through before I can get started?

**Comment by abhithory** [comment]
hi @akhilmhdh, I am interested in solving this issue. can you please assign me?

**Comment by akhilmhdh** [comment]
Hey there @dragonRageX you can read the [contribution guide](https://infisical.com/docs/contributing/overview) to help you get started. Also join our [slack space](https://join.slack.com/t/infisical-users/shared_invite/zt-1ye0tm8ab-899qZ6ZbpfESuo6TEikyOQ) to get your ans to any doubts.

**Comment by akhilmhdh** [comment]
@dragonRageX are you planning to work on this, or should i assign this to @abhithory

**Comment by dragonRageX** [comment]
> @dragonRageX are you planning to work on this, or should i assign this to @abhithory
I'm going through the docs for now... by the time, you can assign him this issue.

**Comment by akhilmhdh** [comment]
Thank you @dragonRageX 

hey @abhithory are you still interested in working on this issue. Then  I can assign it to you.

**Comment by abhithory** [comment]
@akhilmhdh , yes please

**Comment by abhithory** [comment]
hii @akhilmhdh , i have setup the project locally. but when i try to integrate with other providers then it is showing 404 error.
![image](https://github.com/Infisical/infisical/assets/76877003/6809a117-a5b1-420c-b4d9-ba5e0c8bea99)

how i can see `/pages/heroku/create` page?

**Comment by abhithory** [comment]
hello @akhilmhdh , i have added this warning message. Please check it and let me now if it is okay?? should i make PR of it?
 
Also i want to ask one thing
 - I have to stop the server and start it again every time to see new updated changes in the frontend. without it, it is not showing updated pages. why is that?? or is it only with me??

![image](https://github.com/Infisical/infisical/assets/76877003/c6a2f866-ee12-48fe-8a47-e24babfd6033)

**Comment by lokesh3097** [comment]
Hi @abhithory! Is there any update from you regarding this issue? Can I take it up if you aren't working anymore on this?

**Comment by abhithory** [comment]
@lokesh3097 , yes sure

**Comment by abhithory** [comment]
i wanted to confirm from them the design, but they have not responed anything

**Comment by lokesh3097** [comment]
Hi @akhilmhdh! Can I take up this issue?

**Comment by maidul98** [comment]
@abhithory your design looks good to me. I think it would look better if warning was put right above the create integration button instead. Either @abhithory or @lokesh3097 please make a PR for it and we will get it reviewed

**Comment by lokesh3097** [comment]
> @abhithory your design looks good to me. I think it would look better if warning was put right above the create integration button instead. Either @abhithory or @lokesh3097 please make a PR for it and we will get it reviewed

@abhithory If you have the code ready please feel free to raise a PR as you might have already worked on it. If not please let me know.

**Comment by akhilmhdh** [comment]
Closing as stale
