### ISSUE TITLE
Web: .env download button not working

### ISSUE THREAD

**Issue by harveysanders** [Infisical/infisical#698]
### Describe the bug
On the Infiscal website, the `.env` export download button is not working for me

### To Reproduce
1. Go to an environment
2. Click on the "Download as .env" button
3. Nothing happens

### Expected behavior
`.env` file downloaded to default browser downloads directory

### Screenshots
![image](https://github.com/Infisical/infisical/assets/9354822/25eddb0c-f58d-4b65-ab7d-7bf625603c39)

### Platform you are having the issue on:
Browser: Brave [Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (x86_64)]
MacOS

### Additional context
No errors in the Browser console

**Comment by harveysanders** [comment]
If anyone else is having this issue, someone in the Slack suggested this workaround using the CLI:
```shell
infisical export --env=dev --format=dotenv > .env
```

**Comment by akhilmhdh** [comment]
Hey @harveysanders can you try it in another browser without adblockers. Like firefox

**Comment by delavegar25** [comment]
hi @harveysanders  is this still an issue? if it is, then it's from the browser. You can clear your browser cache, check for the browser plugins or try another browser has @akhilmhdh mentioned.

**Comment by harveysanders** [comment]
@akhilmhdh @delavegar25 thanks for your responses.
Yes, It's still an issue. I've cleared the cache and used a Private window. I've tried Firefox, Brave, Chrome, and Safari all have the same behavior - nothing happens when the download button is clicked. No errors in the browser consoles.

Is the download button working for you all?

**Comment by chisom5** [comment]
@harveysanders I tried this using chrome on a MacOS and I can see the expected behaviour.

**Comment by harveysanders** [comment]
@chisom5 thanks for checking. I'll do some digging to see if and why it's just me

**Comment by delavegar25** [comment]
hi @harveysanders, I checked mine and it works, I think you need to do this: disable the browser extensions temporarily or contact the web administrator, if the error still persists.

**Comment by harveysanders** [comment]
@delavegar25 thanks for the update. Yeah it's still not working on any browser even with extensions off. I think it may be an issue with my account. The CLI workaround works for me for now and i seem to be the only one having this issue. I can close the issue and possibly reopen if i can later find a way for others to reproduce. 
Thanks for the help everyone : )
