### ISSUE TITLE
Web: Copy variables across environments

### ISSUE THREAD

**Issue by harveysanders** [Infisical/infisical#699]
### Feature description
I have variables defined in one environment and I'd like to define them for the other environments. It would be useful to be able to copy variable names and values from one environment to another.

![image (8)](https://github.com/Infisical/infisical/assets/9354822/a4e16bcc-7d17-40c9-bd47-40d08d9775ea)

### Why would it be useful?
Without this feature users need to rewrite variable names in each environment. 

I could use the `.env` import feature, but I initially defined the variables directly in Infisical and don't have them locally. I attempted to export the variables, but that[ feature is not working](https://github.com/Infisical/infisical/issues/698) for me.

**Comment by vmatsiiako** [comment]
Hey @harveysanders! This is actually under development right now and should come out next week. This has been a pretty requested feature as this issue has popped up multiple times throughout the previous months (#211, #232, #613) – so very excited to releases it :)

**Comment by harveysanders** [comment]
Glad to hear it! 

Apologies if I missed an existing issue and created a duplicate. Thanks for getting back so quickly.

**Comment by akhilmhdh** [comment]
Hey @harveysanders we have recently released this feature, which allows you to copy secret from another environment and then modify it as you wish. 

Do check it out later. Closing this issue as of now.

**Comment by harveysanders** [comment]
@akhilmhdh Thanks for the update. I'll check it out soon :)

**Comment by harveysanders** [comment]
@akhilmhdh Looks like the web side is not completely working for me. I have a bunch of vars set in the Staging environment, but none are showing the in the copy modal: 
<img width="1089" alt="image" src="https://github.com/Infisical/infisical/assets/9354822/daeb8a59-bb0b-4621-ac0e-4baafc9be875">

**Comment by akhilmhdh** [comment]
@harveysanders did u set those in root or in a folder

**Comment by harveysanders** [comment]
@akhilmhdh root

**Comment by harveysanders** [comment]
@akhilmhdh Appreciate it

**Comment by akhilmhdh** [comment]
Hey @harveysanders can you try now. This should be working fine now
