### ISSUE TITLE
[ENG-145] tags filter not working while exporting via cli

### ISSUE THREAD

**Issue by d11ahirst** [Infisical/infisical#705]
Trying to export secrets based on tags does not work via the cli tool

### To Reproduce

Set some tags on secrets and pass the --tags option to the cli as descibed in the --help documentation

` -t, --tags string         filter secrets by tag slugs`

### Expected behavior

To filter by tags

### Platform you are having the issue on:

Linux amd64

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-145](https://linear.app/infisical/issue/ENG-145/tags-filter-not-working-while-exporting-via-cli)</sub>

**Comment by neto210206** [comment]
Parece que você está enfrentando um problema com a exportação de segredos com base em tags usando uma ferramenta CLI. Para ajudá-lo a solucionar isso, sugiro as seguintes etapas:

1. **Verifique a Sintaxe do Comando:** Certifique-se de estar usando corretamente a opção `--tags` com as lesmas de tag corretas. O comando deve se parecer com algo como: `cli_tool export --tags tag_slug`.

2. Verificar Versão CLI Certifique-se de que você está usando a versão mais recente da ferramenta CLI, pois versões mais recentes podem ter correções de bugs ou melhorias relacionadas à filtragem de tags.

3. Revisar Documentação: Verifique novamente a documentação para quaisquer requisitos específicos ou detalhes de sintaxe ao usar a opção `--tags`.

4. Verifique a Conectividade: Certifique-se de que você tenha uma conexão de internet estável e que a ferramenta CLI seja capaz de se comunicar com o servidor para recuperar segredos marcados.

Se você fornecer mais detalhes sobre a ferramenta CLI específica que está usando, eu posso te ajudar mais ainda.

**Comment by LouisHaftmann** [comment]
still not working for me

**Comment by Merton** [comment]
Please can we have an update on when we can expect a fix for this? Thanks 😄

**Comment by jhonsfran1165** [comment]
still not working when trying to export secrets on version 0.36.17

`infisical export --path=/app --env=preview --tags=app`
