### ISSUE TITLE
Feaure: Batch CRUD operation for v3 secrets management when E2EE is disabled

### ISSUE THREAD

**Issue by pmbanugo** [Infisical/infisical#707]
### Feature description
I see no means to batch create, get or delete secrets when E2EE is disabled. There are options to create or get a secret when E2EE is disabled like so:

```
curl --location --request POST 'https://app.infisical.com/api/v3/secrets/raw/secretName' \
    --header 'Authorization: Bearer serviceToken' \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "workspaceId": "workspaceId",
        "environment": "environment",
        "type": "shared",
        "secretValue": "secretValue",
        "secretPath": "/"
    }'
```

I'd like that to be extended to support batch operations for create, update, retrieve, and delete operations. 

### Why would it be useful?

We don't have to send multiple request for a batch operation, that should be executed transactionally. There's currently a means to do this using the v1 API but that only supports E2EE mode and doesn't work with API KEy or service account token.

**Comment by dangtony98** [comment]
Hi @pmbanugo,

We made the decision recently to not do batch requests for `v3` endpoints at the moment to keep some of the backend logic + validation simpler/streamlined.

We'll re-think how to support batch operations for this one and keep you posted 😄

**Comment by pmbanugo** [comment]
So what will be the alternative for me in the meantime? Can I use the v2 API that seems to have batch request and just pass in raw secrets?
