### ISSUE TITLE
Bitbucket integration

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#710]
### Feature description
It would be great to have an integration with [Bitbucket ](https://bitbucket.org/product).

### Why would it be useful?
This would enable users of Bitbucket to store and sync their environment variables from Infisical to Bitbucket.

### Additional context
This should be fairly simple with a ton of examples to go off of 😄

**Comment by zwkee** [comment]
Hi @dangtony98 , I would like to work on this.

**Comment by dangtony98** [comment]
Assigned!

**Comment by Mgldvd** [comment]
No repositories found...

I'm trying to integrate with my Bitbucket account, but it can't find any repositories.
I should mention that this account has over **1000 repositories**, so I believe that might be the issue.
Is there any way to fix this?
Thanks.

![Image](https://github.com/user-attachments/assets/c2b321b8-897b-474a-bc51-95abbb2527c8)
