### ISSUE TITLE
Inject secrets from multiple paths

### ISSUE THREAD

**Issue by MohamedGouaouri** [Infisical/infisical#716]
### Feature description
Specify multiple paths to the secrets in CLI.

### Why would it be useful?
I want to categorize my secrets based on the microservice decomposition, so for each microservice, I can inject the configs and secrets. But I have some shared secrets that I want to inject as well, so it would be beneficial to inject secrets from different paths.

**Comment by akhilmhdh** [comment]
Hey @MohamedGouaouri, 

We will be releasing secret reference very soon 😄 then you will be able to inject secret from another environment or folder easily

**Comment by akhilmhdh** [comment]
With #713 released you should be able to reference secret. Feel free to open this issue again, if that's not what you were expecting
