### ISSUE TITLE
Pressing enter key on Login page does nothing. 

### ISSUE THREAD

**Issue by sunilk4u** [Infisical/infisical#718]
### Describe the bug
On the login page when after entering login credentials, hitting enter key on keyboard does nothing. I have manually press the login button or use tab. It would be nice if i could just hit enter after entering password.

I know that I am nit-picking but it would be really nice as users are used to it. 

### To Reproduce
1. Go to main login page
2. After entering credentials hit enter key on keyboard.
3. Nothing happens. Does not redirect.

### Expected behavior
Should authenticate and then redirect to dashboard.

### Screenshots
![image](https://github.com/Infisical/infisical/assets/42198140/3ad70c3b-1d57-44a6-bf03-3166250264aa)

### Platform you are having the issue on:
Linux Minx xfce

### Additional context
It could be a issue with my system as well, chrome and linux together create issues.

**Comment by akhilmhdh** [comment]
Hey @sunilk4u . 

This will be resolved very soon when #711 gets merged. 

Login pages will be soon be revamped to make it much more accessible. Thank you for raising this issue. 

We will keep this issue open until #711 is merged

**Comment by sunilk4u** [comment]
Awesome !
