### ISSUE TITLE
Duplicate Error on Original Key

### ISSUE THREAD

**Issue by asharonbaltazar** [Infisical/infisical#72]
### Describe the bug
An error should only apply to the new entry. It doesn't make sense to have an error present on submitted keys as well. 

### To Reproduce
1. Go to `/dashboard`
2. Create a duplicate key
3. See error is present on the new key and the original one

### Expected behavior
The error should apply only to the new key, similar to the no-number-in-the-beginning behavior. 

### Screenshots
![Screenshot 2022-12-04 at 9 14 30 PM](https://user-images.githubusercontent.com/58940073/205534496-7828cfb3-570d-42c0-8de4-9533cbd53989.png)

### Platform you are having the issue on:

N/A. It's a frontend issue. 

### Additional Context:
I believe this is due to the way errors are mapped. It seems like it's checking every entry with the same key name, regardless of whether it's an old key or not.

**Comment by mv-turtle** [comment]
I think you are right! When I created it, I just tried to find a quick solution, your way would be better! Thanks!

**Comment by akhilmhdh** [comment]
Closing as stale issue.
