### ISSUE TITLE
Folders not found after creating them via the API

### ISSUE THREAD

**Issue by pmbanugo** [Infisical/infisical#724]
### Describe the bug
Hello, it’s quite confusing that I’d get a 200 ok response when creating a folder via the API, which also gives me the folder ID and name. But when I check the UI, there’s no folder. Is this some sort of race condition where the response is dispatched before the data is persisted?

I have scenario where I need to create four folders via the API. The API calls go to the same workspace environment but different parent folders. They all return OK response but when I check the UI, not all the folders were created. Usually only one or two of those request actually worked.

### To Reproduce
1. Make multiple (e.g 4) API calls to create different folders in a workspace. The API request should run in parallel/concurrently. 
2. COnfirm that you got back a 200 Ok response for all.
3. Confirm that you can find all the folders from the UI. Most likely not all of them would show up. 

### Expected behavior
I expect to find the folders if the API call actually returns a 200 OK response with the folder id and name.

It'll be ideal if I can also get an endpoint that I can run a batch folder create for the same environment but separate parent folders.

### Platform you are having the issue on:

Infisical Cloud

**Comment by maidul98** [comment]
You mentioned running the calls concurrently. I'm curious what your use case is that requires concurrent folder creation. It could be that you are getting throttled depending on the number of projects you are creating. 

Can you confirm that a single folder create request works on your end? Can you also provide an example request you are making?
