### ISSUE TITLE
Does Infisical integrate with Digital Ocean's App Env variables

### ISSUE THREAD

**Issue by whoacowboy** [Infisical/infisical#732]
Does Infisical integrate with Digital Ocean's App Environment Variables?

**Comment by afrieirham** [comment]
I think it's has been discussed here #673 

But I don't think anyone's working on it though.

**Comment by whoacowboy** [comment]
@afrieirham Thanks for the response. I found out DO doesn't have an API to edit env variables. If it is something you are interested in you can vote and comment [here](https://ideas.digitalocean.com/interfaces/p/api-to-manage-environment-variables-in-app-platform).

**Comment by afrieirham** [comment]
> @afrieirham Thanks for the response. I found out DO doesn't have an API to edit env variables. If it is something you are interested in you can vote and comment [here](https://ideas.digitalocean.com/interfaces/p/api-to-manage-environment-variables-in-app-platform).

Oh wow didn't know that. Thank you for sharing that. 

In that case we need to wait for them to make the API available first. Otherwise it would be impossible to do the integrations.

**Comment by afrieirham** [comment]
Wait I think it's available now here https://docs.digitalocean.com/reference/api/api-reference/#operation/apps_update

Go to specs > services > envs

![image](https://github.com/Infisical/infisical/assets/32460534/f2d6f96f-5e5c-4b61-975c-4d1a4827abad)

**Comment by afrieirham** [comment]
Tested and verified, it works!

1. Deploy a project in App Platform and get the `id` in the url.
2. Make a request `PUT` to `https://api.digitalocean.com/v2/apps/{id}` with body below
```json
{
    "spec": {
        "name": "<YOUR_APP_NAME>",
        "envs": [
            {
                "key": "DB_NAME",
                "value": "infisical"
            }
        ]
    }
}
```

I think this issue can be worked on if anyone's interested.

cc @dangtony98

**Comment by dangtony98** [comment]
Oh wow thanks for testing and verifying @afrieirham! — This is excellent news.

I'll add it to the pinned integration issue so we can get some hands on it 😄

**Comment by afrieirham** [comment]
Working on this.

**Comment by dangtony98** [comment]
@whoacowboy This feature has been merged is now live in production 😄

**Comment by afrieirham** [comment]
cc @fruneen

**Comment by fruneen** [comment]
amazing, thanks a lot 🚀

**Comment by whoacowboy** [comment]
Wow, Thank you!
