### ISSUE TITLE
Notify users ahead of time when their service tokens will expire

### ISSUE THREAD

**Issue by maidul98** [Infisical/infisical#734]
### Feature description
It'd be great if users are notified ahead of time when service tokens will expire so that they can be regenerated.  

### Why would it be useful?
Would reduce developer confusion and service interruptions

**Comment by piyushchhabra** [comment]
Hi @maidul98 , I would like to work on this. Can you assign this to me please?

Also, How do we want to notify the users/developers in this case? By email OR by some other means

**Comment by maidul98** [comment]
For starters, let's do email. Before you start to code, can you please provide a brief walk through of the workflow in mind and include any mock ups to demonstrate? This way, we can all be on the same page before development starts

**Comment by Sadaf-A** [comment]
@maidul98 Greetings!, it seems like this issue was left unattended.
I would love to work on this. If you could please assign it me to.
Thank you.

**Comment by maidul98** [comment]
@Sadaf-A Yes, you can take a crack at this. Can you provide a plan before getting started first?

**Comment by Sadaf-A** [comment]
@maidul98 I think my approach would be store an epoch value which is the sum of current epoch plus the expiry duration. And have a notifier application which runs in the background (please let me know if we are already using one or if you have a suggestion, That would be of great help). once the timestamp let's one day before the expiry is reached. A notification to the user will be sent.

**Comment by maidul98** [comment]
We are using bull-queue so I think you can have a queue and schedule items to be put in there ahead of time. Do you have any other questions?

**Comment by Sadaf-A** [comment]
> We are using bull-queue so I think you can have a queue and schedule items to be put in there ahead of time. Do you have any other questions?

Not as of now! I'll get started with this.
Could you please assign me

**Comment by maidul98** [comment]
Sure, these are the queues folder https://github.com/Infisical/infisical/tree/main/backend/src/queues that you will need to schedule a task for the future and here is the function for sending email https://github.com/Infisical/infisical/blob/5e24b517cc320d6b44723ac74eb855e8b67caf86/backend/src/helpers/nodemailer.ts#L16

**Comment by Sadaf-A** [comment]
@maidul98 Hey, My plan was to store `expiresAt` value along with the token in the DB. Are we already doing that? if yes then can you please link the file. I tried to find it but I could not.

**Comment by maidul98** [comment]
@Sadaf-A i don't think we can use expireAt because we'll need to trigger the notifications before hand. I recommend using the bull queue i have linked to schedule such tasks

**Comment by Sadaf-A** [comment]
> @Sadaf-A i don't think we can use expireAt because we'll need to trigger the notifications before hand. I recommend using the bull queue i have linked to schedule such tasks 

sure that sounds great, could you please share link for the files where token creation and storage takes place

**Comment by maidul98** [comment]
It should be this https://github.com/Infisical/infisical/blob/main/backend/src/routes/v2/serviceTokenData.ts you can also check the network logs to see which api are triggered when you create a service token

**Comment by nabby27** [comment]
Hi everyone! Seeing that this issue is not having too much movement currently I will be more than happy to create a reward for this issue through [Opire](https://opire.dev), the project I've recently launched. With this I hope other developer will be willing to solve the issue faster. The only thing you would have to do is install the app in your GitHub repository. Check our [documentation](https://docs.opire.dev) to know more about it

**Comment by akhilmhdh** [comment]
Closing as we have depreciated service token and moved to machine identity
