### ISSUE TITLE
Standalone Docker Image

### ISSUE THREAD

**Issue by neo3k** [Infisical/infisical#737]
Hello.

First of all, congratulations for the good work. I have been deploying the Standalone version of Infisical (https://hub.docker.com/r/infisical/infisical).

This Docker image you do not update it as frequently as the Backend and Frontend images.

For example, I am having a problem with the rate limit in the backend. Looking at the code in the image, I have seen that it is an old version from a month ago without the changes.

Is it possible for you to update this image more frequently?
Thanks

**Comment by maidul98** [comment]
Hey @neo3k, i have triggred a update to this image

**Comment by neo3k** [comment]
Great. I've done the builds manually for the latest versions for now.

**Comment by maidul98** [comment]
It will always be updated now https://github.com/Infisical/infisical/commit/a00fec9bcae1a3ab8109f185feac9203861fd133
