### ISSUE TITLE
(Feature) - Integration with Openshift for Secret Management

### ISSUE THREAD

**Issue by riginoommen** [Infisical/infisical#738]
### Feature description
Dynamic Secret Management is a unique feature of the infisical. If the Devs and Admins can sync for secret management in one place the deployments gets more easier

### Why would it be useful?
Why would this feature be useful for Infisical users? 
Change Management will be easier for the end level user and admins dependency can be reduced

### Additional context
https://youtu.be/PK23097-25I?t=117

**Comment by vmatsiiako** [comment]
Hi @riginoommen! Please check out this guide: https://xphyr.net/post/infisical_ocp/
