### ISSUE TITLE
Sort integrations in alphabetical order

### ISSUE THREAD

**Issue by afrieirham** [Infisical/infisical#750]
### Feature description

Just a suggestion, I think sorting integrations in alphabetical order would make it easier to browse. 

![image](https://github.com/Infisical/infisical/assets/32460534/14b9a068-a7a8-41e0-b77b-3329674cf74e)

### Why would it be useful?
Easier to browse.

### Additional context
I would love to work on this if it's needed.

**Comment by dangtony98** [comment]
@afrieirham That’d be great actually if you could make a PR for that 😄

I was thinking at some point having a search bar but it probably isn’t needed yet.

**Comment by afrieirham** [comment]
> @afrieirham That’d be great actually if you could make a PR for that 😄
> 
> I was thinking at some point having a search bar but it probably isn’t needed yet.

Cool, I'll work on it right away.

**Comment by akhilmhdh** [comment]
Thank you @afrieirham for your valuable contribution
