### ISSUE TITLE
Typo in Docs

### ISSUE THREAD

**Issue by subh-cs** [Infisical/infisical#753]
### Describe the bug
There's a little typo that I encountered

### To Reproduce
1. Go to [here](https://infisical.com/docs/documentation/platform/token)
2. See the typo error

### Screenshots
![image](https://github.com/Infisical/infisical/assets/75121304/87c9d642-bbd3-4a2d-939e-c6d92c62eb91)

**Comment by JunedKhan101** [comment]
@subh-cs Can I pick this up?

**Comment by akhilmhdh** [comment]
Sure @JunedKhan101 its a good first issue indeed

**Comment by JunedKhan101** [comment]
@akhilmhdh I have created a PR for this. Please review.
