### ISSUE TITLE
Deleting an environment deletes all service tokens

### ISSUE THREAD

**Issue by JamesArthurHolland** [Infisical/infisical#766]
### Describe the bug
Deleting an environment deletes all service tokens (even ones that aren't relevant).

### To Reproduce
1. Go to Project Settings
2. Delete an env
3. Go to service tokens
4. See them all no longer existing.

### Expected behavior
Only service tokens for that env should be deleted. Not all of them.

**Comment by maidul98** [comment]
This bug has been patched and will be deployed on next deploy https://github.com/Infisical/infisical/commit/af650ef4c73261a5d8a45ac19d95c1394e43d468
