### ISSUE TITLE
Log into Infisical via GitHub

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#771]
### Feature description
Currently, you can login/sign-up to Infisical via email or Google (pending release in the next few days).

It would be great if users can sign up for Infisical via GitHub.

### Why would it be useful?
This would add another option for users to authenticate with for the platform.

### Additional context
[Google](https://www.passportjs.org/concepts/authentication/google/) and [SAML SSO](https://www.passportjs.org/packages/passport-saml/) is currently implemented with the help of [Password.js](https://www.passportjs.org); you can reference how the Google SSO strategy is implemented to do the one for GitHub.

**Comment by afrieirham** [comment]
Can refer this PR https://github.com/Infisical/infisical/pull/535

**Comment by JunedKhan101** [comment]
@dangtony98 I would love to pick this up.

**Comment by dangtony98** [comment]
Hi @JunedKhan101!

Happy to assign it to you; I think this is an exciting one to work on 😄

Let me know if you need any help with it over Slack.
