### ISSUE TITLE
Secrets from Infisical are not parsed when syncing

### ISSUE THREAD

**Issue by afrieirham** [Infisical/infisical#775]
### Describe the bug
Secrets that uses other secrets should be replaced when synced.

### To Reproduce
1. Go to Infisical dashboard and create new platform integration.
2. Sync secrets to platform.
3. Go to said platform and see the secrets.

### Expected behavior
DB_USERNAME and DB_PASSWORD should be replaced with their actual values in DATABASE_URL

### Screenshots
Secrets from Infisical
![image](https://github.com/Infisical/infisical/assets/32460534/3917bf0e-8415-4297-ac65-35eec1294c72)

Secrets on platform integration (bug)
![image](https://github.com/Infisical/infisical/assets/32460534/7784e00e-1261-4006-bf48-7d4ebe026fe6)

Secrets on platform integration (expected)
![image](https://github.com/Infisical/infisical/assets/32460534/74772cee-3983-4c25-b76a-6f5b096703f1)

**Comment by whoacowboy** [comment]
@afrieirham Yes.
![Screenshot 2023-07-28 at 9 31 58 AM](https://github.com/Infisical/infisical/assets/8116953/aca900bb-ffcc-41a2-84bd-1d1f5847ec52)

**Comment by maidul98** [comment]
@akhilmhdh can you please add the logic for secret referencing/import to the integrations sync logic?

**Comment by afrieirham** [comment]
Hey @maidul98, sorry for not informing but I've open PR for this. 🙏

**Comment by akhilmhdh** [comment]
This has been resolved with our recent release. Now integrations do have secret import and reference feature, and its get filled up before putting it into their env space
