### ISSUE TITLE
Change default sort order 

### ISSUE THREAD

**Issue by whoacowboy** [Infisical/infisical#789]
### Feature description
I would like the ability to reorder secrets after their initial import.

### Why would it be useful?
It would help me find secrets faster.

### Additional context
Not this but like this. You could replace the numbers, because really what do they mean in the context of an env, with a grabber handle so we could reorg the initial input. 

![infisical](https://github.com/Infisical/infisical/assets/8116953/4a9ac80f-e18d-4457-92dc-d7060d095c5a)

**Comment by whoacowboy** [comment]
I think this might need to be changed to sorting in general.

It might be nice to sort environments too.

![Screenshot 2023-07-26 at 7 32 20 PM](https://github.com/Infisical/infisical/assets/8116953/22e2154b-01f4-4075-804c-b7cc854556d5)

**Comment by Owobilum** [comment]
Assign this to me

**Comment by harveysanders** [comment]
To add to this, it would be nice if the **Key** column would sort in alpha order rather than by [dateAdded].

**Comment by harveysanders** [comment]
Really what I'm looking for is to persist the changes across reloads : )

**Comment by EBEN4REAL** [comment]
I am looking at picking this up if it hasn't been picked up yet.

**Comment by akhilmhdh** [comment]
With our recent release we now support sorting, then there is reordering of environment, prefix based views that groups together similiar secrets by prefix like DATABASE_ etc.

And filteration with tags. Thus i think this is no needed for user's as the provided would reduce the user cognitive load a lot. Closing this issue, Feel free to update this thread if more people are interested in this
