### ISSUE TITLE
Add members to multiple projects at once

### ISSUE THREAD

**Issue by itssubhodiproy** [Infisical/infisical#791]
### Feature description
![image](https://github.com/Infisical/infisical/assets/75121304/d87e8bfc-13ee-467b-85cc-c0017afefb8e)

Link: https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1690322207127719

**Comment by subh-cs** [comment]
Assign this to me

**Comment by sonmac1203** [comment]
I'm happy to pick this up if it is available!

**Comment by akhilmhdh** [comment]
Closing as this is possible with our recent releases
