### ISSUE TITLE
Digital Ocean App loses all setting when infisical syncs env variables.

### ISSUE THREAD

**Issue by whoacowboy** [Infisical/infisical#794]
### Describe the bug
Every time I save changes to my environment when it is linked to DO App Platform it uploads my env variables nicely but it wipes all the other information off of the server.

### To Reproduce
Set up your DO App Platform.
Link environment to DO.
Add env variable. 
Save environment.
See DO App as only env variables and all other settings on DO App are lost including GitHub integration. Go figure.

### Expected behavior
It would publish the env vars and not effect anything else on the server.

### Additional context
The odd part is that even the plan changes from a pro plan to a starter.

Re: https://github.com/Infisical/infisical/pull/779#issue-1817142783

**Comment by maidul98** [comment]
When you say `wipes all the other information off of the server` do you mean it wipes out all other environment varables? Or are you talking about other kinds of settings?

**Comment by afrieirham** [comment]
investigating this

**Comment by dangtony98** [comment]
Thanks @afrieirham 😄

**Comment by afrieirham** [comment]
Hey @whoacowboy, I've open PR to fix this issue 🙌

While we're at it, have you experience this issue too? https://github.com/Infisical/infisical/issues/775
