### ISSUE TITLE
Secrets import fail when key contains colon (:)

### ISSUE THREAD

**Issue by ryansorensen** [Infisical/infisical#795]
### Describe the bug
Importing a secrets file will silently skip lines when the key contains a colon

### To Reproduce
1. Go to secrets page 
2. Explore environment (empty secrets list makes this easier to observe)
3. Import sample file

### Expected behavior
All the secrets in the file should be merged into the list

### Actual behavior
Only one secret is added from the sample file

### Screenshots
![image](https://github.com/Infisical/infisical/assets/21267460/26c88b6a-f673-4937-b53d-ab88f9412e40)

![image](https://github.com/Infisical/infisical/assets/21267460/fa22b614-86bc-4838-a7ea-ffeea86cfd2b)

### Platform you are having the issue on:

infisical/infisical:latest (1ea37dc3581b)

[sample.txt](https://github.com/Infisical/infisical/files/12185823/sample.txt)

**Comment by ChukwunonsoFrank** [comment]
hey @ryansorensen, would you mind shedding light on your use case of colons? Most .env files I've seen make use of "=" as the delimiter between key-value pairs, just like the first line of your file.

cc @dangtony98

**Comment by vmatsiiako** [comment]
Hey @ChukwunonsoFrank! Pasting @ryansorensen's explanation from Slack: "This is a very common convention in the .aspnet world."

I have just released the fix for this, so it should work as expected now. Please, let me know if something still doesn't work.
