### ISSUE TITLE
Support writing secrets with Terraform

### ISSUE THREAD

**Issue by thehedgefrog** [Infisical/infisical#797]
### Feature description
I would like to be able to write secrets to infisical with terraform.

### Why would it be useful?
This would be useful to populate secrets from, for example, a secret manager such as 1password.

### Additional context
As requested in #250

**Comment by akhilmhdh** [comment]
I think @maidul98 released a terraform provider for Infisical.

**Comment by akhilmhdh** [comment]
Ahh got it. There is not CRUD ability in there. 

Doc: https://infisical.com/docs/integrations/frameworks/terraform

**Comment by akhilmhdh** [comment]
@thehedgefrog can you please provide one your usecase where this will be beneficial please. Because my opinion the secrets should flow from infisical to others from a terraform perspective. Love to hear more about this.

**Comment by ben-z** [comment]
> @thehedgefrog can you please provide one your usecase where this will be beneficial please. Because my opinion the secrets should flow from infisical to others from a terraform perspective. Love to hear more about this.

I'm working with an organization that version controls their secrets using Ansible vault. Having a CRUD Terraform provider would allow for incremental adoption of infisical. Also, perhaps in a separate ticket, it would also be good to have the ability to manage users using the provider.

**Comment by kirinnee** [comment]
> @thehedgefrog can you please provide one your usecase where this will be beneficial please. Because my opinion the secrets should flow from infisical to others from a terraform perspective. Love to hear more about this.

There are auto-generated secrets from Terraform when creating resources, and I would like to skip the step of manually copying each of this secret from terraform output to infisical!

**Comment by maidul98** [comment]
You can now write secrets via terraform https://registry.terraform.io/providers/Infisical/infisical/latest/docs/resources/secret
