### ISSUE TITLE
Infisical truncates multi-line values to one line.

### ISSUE THREAD

**Issue by whoacowboy** [Infisical/infisical#801]
### Describe the bug
When I sync or download multiline values they are truncated to one line.

### To Reproduce

Create a secret like this.

```
PASSPORT_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9jZ3S235DtKcBfO3EFAAOCAg8AEA395Wzw0BAQrNqDU6iLzw+D3XHW/d/RtvTY6kP0ATpTCWz==
-----END PUBLIC KEY-----"
```

Download or sync with integration.

### Expected behavior

It would keep the entire value.

### Platform you are having the issue on:

Digital Ocean and local

### Additional context

This is the only way I have found to add persistent certs on my DO App. I either access the certs directly or a post install script copies it to the server.

**Comment by whoacowboy** [comment]
So I looked at it a bit more closely and when I create one value, multiple lines work as expected. When I import an .env that has multiple lines I see the issue.

I also get an error saying failed to save, but everything is in there. I will start another bug when I have the time to walk through exactly how to reproduce.

**Comment by afrieirham** [comment]
Didn't manage to reproduce this with DO integration but I think here's the problem with local. 


1. After downloading the .env file, here is what we get. And when I use the .env file in one of my project, this is what it shows:

<img width="775" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/5b82a94c-15d7-491f-ac3a-ca5992b6b86b">

<img width="1440" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/91450d3d-332e-4a81-8b5c-01a7513b6144">



2. Adding double quotes "" doesn't fix it.

<img width="789" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/e890ffff-9282-4baf-91bb-e9ea5fd30707">

<img width="1440" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/c06c1b7c-d7b6-4d25-b784-ab7f1e248fc2">


3. To fix this, we need to use `\n`

<img width="1094" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/b81a58c8-d1e2-461a-a794-a144a0d54912">

<img width="1440" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/52be2e0f-284c-441a-876f-0b49bfc9e646">

4. But we can't omit the double quotes "" even with \n

<img width="1078" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/45fb90ad-c183-4629-8f4f-7680d4278f28">

<img width="1440" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/bfa76c25-bbf0-4449-8782-35fc46652df3">


5. Same behaviour in console with console.log

<img width="1064" alt="image" src="https://github.com/Infisical/infisical/assets/32460534/9222c015-030d-46c9-9cd3-d941487b5b24">

**Comment by akhilmhdh** [comment]
Thank you @afrieirham for sharing your finding.

I see, now I understood the issue, don't worry will get this fixed within next two days

**Comment by akhilmhdh** [comment]
Closing this request as this has been released. Now you can download multi line secret or use in integrations. 

Multiline will be as @afrieirham found out put in a double quotes with `\n` seperator
