### ISSUE TITLE
Support for monorepos

### ISSUE THREAD

**Issue by matt-aitken** [Infisical/infisical#81]
### Feature description
We use [Turborepo](https://turbo.build/repo/docs/getting-started/create-new) for our monorepo (a repository that has multiple packages and projects inside it). This means our web apps are inside subfolders, e.g. `/apps/webapp/`.

We need different environment variables for the different projects. So, we would like to have an Infisical project for each of those.

it would be great if the Infisical CLI could be run on the root folder of a monorepo and grab all the environment variables from the sub-projects and inject them.

### Why would it be useful?
It would mean Infisical works with monorepos, made with tools like Turborepo and NX.

**Comment by edgarrmondragon** [comment]
An alternative and something supported by other CLIs is a `--cwd /path/to/project` flag to execute in the context of that directory, so maybe something like that is useful?

**Comment by matt-aitken** [comment]
That's a good idea 👍

It would make it possible for us to get the site working, although it would be cumbersome because we have 5 different services that need to run.

We normally just call `pnpm run dev` in the root and it runs all of the services (on their respective ports).

**Comment by maidul98** [comment]
@matt-aitken I have a path forward for local development but I'm curious to know how you run this monorepo in production so that it receives all the required environment variables?

**Comment by maidul98** [comment]
The new version with mono repo support is released! Connect each application to their respective Infisical project and then run your command like you did previously. ~ don't forget to update your CLI
