### ISSUE TITLE
Issue on docs: Security Mechanics sentence doesn't make sense

### ISSUE THREAD

**Issue by ericallam** [Infisical/infisical#810]
This paragraph:

> The 256-bit key is used to encrypt the private key; the 256-bit key itself is then encrypted by a key generated from the user’s password and salt with key derivation function argon2id. The resulting, 256-bit key the protected key.

Specifically this:

> The resulting, 256-bit key the protected key.

Not sure exactly what that is supposed to mean.

Path: /security/mechanics

**Comment by dangtony98** [comment]
Just fixed this issue [here](https://github.com/Infisical/infisical/commit/8ff33a4e637e8eb3f0db050922c9756619b8c512); thanks for flagging it.
