### ISSUE TITLE
Blog Section in API Reference Redirects to 404: NOT_FOUND Page Instead of Displaying Blog Posts

### ISSUE THREAD

**Issue by jamesoyanna** [Infisical/infisical#814]
### Describe the bug
The "Blog" section in the API reference redirects to a 404: NOT_FOUND page when clicked on.

### To Reproduce
1. Go to the  API reference documentation.
2. Navigate to the Blog section in the Sidebar Menu.
3. Click on the Blog tab.
4. Observe that it redirects to a 404: NOT_FOUND page.

### Expected behavior

I expect that when the "Blog" tab in the  "Menu,"  section is clicked, it should display a page with at least one or two blog posts related to the platform, instead of redirecting to a 404 page. 

Blog posts are a valuable resource for educating users on how to use the platform effectively

### Screenshots
![blog-screenshot](https://github.com/Infisical/infisical/assets/26815113/bf6fa704-495a-4a3c-aaba-a6fb7d6c3dac)

![404-page](https://github.com/Infisical/infisical/assets/26815113/ca4eb67c-8f2d-446b-8ab8-315a6ba719f8)

### Additional context
We can display a page to show that blogs are coming soon or we can add one or two blog posts there for now instead of having it display a NOT_FOUND page.

**Comment by jamesoyanna** [comment]
Assign this to me.

**Comment by dangtony98** [comment]
Hey @jamesoyanna! — We can link it to this page [here](https://infisical.com/blog).

**Comment by WingZer0o** [comment]
Is anyone currently working on this? I have some free time this coming week and should be able to produce a PR in a "short time frame".

**Comment by akhilmhdh** [comment]
Closing as our main landing page has been updated and this bug is fixed
