### ISSUE TITLE
Symbol `<` causes text to be removed 

### ISSUE THREAD

**Issue by akhilmhdh** [Infisical/infisical#820]
### Describe the bug

The syntax highlighter has an html stripper, the only catch is the stripper removes even if user has value `<` in it. Need to fix this

### To Reproduce
1. Add a value in dashboard with `< >` both. 
2. It will be hidden

### Expected behavior
1. Should be visible

### Screenshots

![image](https://github.com/Infisical/infisical/assets/31166322/54d19189-05eb-4158-8814-52163f1d7d40)

![image](https://github.com/Infisical/infisical/assets/31166322/9c5ca0e1-848e-4a50-86a6-d161246c0c9c)

**Comment by shlokmehta21** [comment]
Hi @akhilmhdh, I would like to work on this issue. I do have some questions: Where is this happening, and which file? (I am new to infisical so I need more context). Thanks!

**Comment by akhilmhdh** [comment]
hey @shlokmehta21 sure if you wanna tackle this one. So the issue is basically there is a component called [SecretInput](https://github.com/Infisical/infisical/tree/main/frontend/src/components/v2/SecretInput) which handles the multi line secrets, hiding etc. 

The bug is essentially at first time when the value is passed it needs to be html encoded, as we are injecting raw html into it rather than via react. This needs to be done only at first time and not after that.

Let me know what do you think about? If you feel its a tough nut let me know ill give you more simpler task to get your hands wet with the codebase

**Comment by shlokmehta21** [comment]
Hi @akhilmhdh, Thanks for replying! I just checked the code, but I cannot log anything to the console to try to understand and debug. Is there a different way of logging the values in the project? 

Also, please let me know if you have other issues I can solve just to get started.

**Comment by akhilmhdh** [comment]
This has been fixed with our recent release closing the issue
