### ISSUE TITLE
Error message when saving secrets

### ISSUE THREAD

**Issue by pascalmtts** [Infisical/infisical#824]
### Describe the bug
Currently when saving secrets there is an error message stating "Failed to save changes".
Sometimes the secrets are saved anyway.

### To Reproduce
1. Go to a environment
2. Add new secret
3. Click on Save Changes

### Screenshots
![image](https://github.com/Infisical/infisical/assets/12157131/323dca9b-c032-44ff-8aa0-5158f200df73)

### Platform you are having the issue on:
Cloud

**Comment by akhilmhdh** [comment]
Hey @pascalmtts do u have any integrations.

**Comment by pascalmtts** [comment]
I think you already found the answer. We are using the supabase integration 👍

**Comment by pascalmtts** [comment]
Should be fixed with fixing the Supabase Integration in #823
