### ISSUE TITLE
Bring back file vault type

### ISSUE THREAD

**Issue by KSJaay** [Infisical/infisical#830]
### Feature description
I have Infisical setup on WSL Ubuntu 22.04 for dev environment and have been using it for a while. But with the recent removal of vault type file, I have been having issues with trying to get credentials. Through Slack, it was suggested to me to set up `gnome-keyring-daemon` and `dbus-x11`. 

However, I am having issues with `gnome-keyring-daemon`, once I set it up and start it on my current terminal it keeps giving me an error saying the password is incorrect. I used a simple password (`Password123`) and this password was also incorrect. I purged `gnome-keyring-daemon` from my instance and then reinstalled/set the password and I am still getting the same issue.

### Why would it be useful?
Users on Ubuntu may have issues with setting up `gnome-keyring-daemon`, using the file vault makes it a lot easier to set up infisical.

**Comment by akhilmhdh** [comment]
CC: @maidul98

**Comment by abdalem** [comment]
+1
I am on WSL too, and my whole teams (10 developers) too. We were left with no choice to go back to 0.10 for now

**Comment by akhilmhdh** [comment]
Hey everyone, just providing an update over this issue:

Sorry everyone, we initially was using keyring in mac and it caused us a bit headache, by asking users to login again when updating CLI. So then we went for how Github CLI does it. Yes removed vault options also to avoid possible bugs.

But we do realize that many people are using it and yes your feedback are indeed valuable. We are looking to it and will be fixed soon. More information will be provided here.

**Comment by arpadgabor** [comment]
Sortly related and normally I would wait for the fix, but in this case I can't. With homebrew I can't even find a way to revert back to 0.10.0 as the versions are no longer available it seems.

```sh
❯ brew search infisical
==> Formulae
infisical/get-cli/infisical ✔                         infisical/get-cli/infisical@0.11.0                    infisical/get-cli/infisical@0.11.1
```

**Comment by maidul98** [comment]
@arpadgabor it sounds like you are on mac, this shouldn't be an issue for you. This only effects systems without a keyring

**Comment by arpadgabor** [comment]
I am on WSL2 and installed Infisical using [homebrew](https://docs.brew.sh/Homebrew-on-Linux), need the `file` vault. Anyways, I installed 0.10.0 using the `.deb` file provided in releases.

**Comment by maidul98** [comment]
Hey all, the `file` vault has been brought back. Please feel free to update at your convenience. Docs: https://infisical.com/docs/cli/commands/vault

**Comment by vmatsiiako** [comment]
Closing as this is completed
