### ISSUE TITLE
Using EMAIL for authentication, the EMAIL address is case sensitive

### ISSUE THREAD

**Issue by cmaahs** [Infisical/infisical#833]
### Describe the bug

EMAIL field for Members used for logging in, is case sensitive.  This is less of a bug and more of an annoyance that will likely result in frustration with the product.

### To Reproduce

1.  Invite a new member, and use mixed case for the email address
2. Have the user attempt to confirm email or login using the email address entered in all lower case
3. The account will NOT be found (error message reads: Wrong Credentials)

### Expected behavior

EMAIL addresses are not normally case sensitive, as such people generally expect any use of EMAIL addresses to also be case insensitive.  

### Platform you are having the issue on:

Test self-hosted instance

**Comment by Killian-Smith** [comment]
Hi, I would be happy to give a go at this!

**Comment by maidul98** [comment]
@Killian-Smith go for it! let us know if you have any questions

**Comment by subhajit20** [comment]
@maidul98 would like to work on it. can you assign it to me?

**Comment by dangtony98** [comment]
The PR for this issue has now been merged 😄
