### ISSUE TITLE
Service token environment is not infered automatically

### ISSUE THREAD

**Issue by tjazsilovsek** [Infisical/infisical#842]
### Describe the bug
I am using infisical CLI to inject environment variables into my working process.

I use service token, with only one scope defined (staging with “/” as path), and when using latest cli version (0.11.1) I get the following error:  `error: CallGetSecretsV3: Request to access secrets with [environment=dev] [path=/] [workspaceId=xxxxxxxxx] is denied. Please check if your authentication method has access to requested scope.`

If I specify staging as environment, than it works as expected.

### To Reproduce
1. Create service token with single scope (on anything but dev environment)
2. Install infisical cli
3. Run infisical run -- "your command"

### Expected behavior
I would expect that when using token with single scope, environment would be inferred automatically.

**Comment by daninge98** [comment]
+1 on this, this would be useful

**Comment by akhilmhdh** [comment]
Closing as we have depreciated service token and moved to machine identity
