### ISSUE TITLE
CLI[FEATURE]: Removing truncation of long values in secret list table and get value of a secret

### ISSUE THREAD

**Issue by harveysanders** [Infisical/infisical#845]
### Feature description
- Add a flag to view the entire value of a secret.
and/or
- wrap long values to new line

#### `--value` flag to only output the value
```
$ infisical secrets get --value LONG_SECRET
dadadnasdnaasdnadnadmakd
```
#### Current output
```
$  infisical secrets get LONG_SECRET
┌───────────────┬────────────────┬─────────────┐
│ SECRET NAME   │ SECRET VALUE   │ SECRET TYPE │
├───────────────┼────────────────┼─────────────┤
│ LONG_SECRET   │ dadadnasdna... │ shared      │
```

#### Proposed output
```
┌───────────────┬────────────────┬─────────────┐
│ SECRET NAME   │ SECRET VALUE   │ SECRET TYPE │
├───────────────┼────────────────┼─────────────┤
│ LONG_SECRET   │ dadadnasdnaddd │ shared      │
│               │ asdnadnadmakd  │             │
│ ANOTHER       │                │ shared      │
```

### Why would it be useful?
This table output of the CLI is great most of the time. However, I sometimes have long values and they're truncated in the table view. It would be nice to be able to pipe this value to something else or simply print to `stdout` for copying.

**Comment by akhilmhdh** [comment]
hey @harveysanders yah please. We are actually a bit houseful with feature request and a lot of them are under cooking. 


It would be really great if you can tackle on this. Feel free to ping me or @maidul98 regarding any doubt. Let me know if your taking it, ill assign this issue to you

**Comment by harveysanders** [comment]
I haven't had a chance to get to this yet. In the meantime, I just realized there is a (POSIX) workaround using `export`:
```
infisical export | grep [SECRET_NAME] | cut -d "=" -f 2
```

**Comment by davidhonig** [comment]
Yeah the value would be pretty useful to have ability to source just the value of the secret. I'd vote for adding `--value` or `--raw` as jq/yq have.

**Comment by maidul98** [comment]
If we go with the `--raw` flag approach, what should be the expected behavior when the user specifies multiple secrets to be returned? Would putting them on new lines make sense?

for example `infisical secrets get <secret-key1> <secretkey2>`

**Comment by CmdrSharp** [comment]
I think having them separated by a single empty line would make sense. The lack of an ability to fetch a secret value (regardless of length) without formatting is, at least for me personally, rather troublesome. This is made worse by the output of `yaml` not guaranteeing correct YAML if the content _itself_ is yaml.

**Comment by realfresh** [comment]
> I think having them separated by a single empty line would make sense. The lack of an ability to fetch a secret value (regardless of length) without formatting is, at least for me personally, rather troublesome. This is made worse by the output of `yaml` not guaranteeing correct YAML if the content _itself_ is yaml.

I'd say it's more than troublesome, it's almost unbelievable/unbearable that I can't just get the value of a secret and need to resort to stupid workarounds 😂

**Comment by maidul98** [comment]
Once this https://github.com/Infisical/infisical/actions/runs/8205760239 workflow finishes, you can use --raw-value on `infisical secrets get `. It has been documented here https://infisical.com/docs/cli/commands/secrets
