### ISSUE TITLE
Jenkins integration

### ISSUE THREAD

**Issue by delanym** [Infisical/infisical#849]
### Feature description
Allow Jenkins to integrate with Infisical to manage its secrets.

### Why would it be useful?
Jenkins has limited functionality for managing secrets via its Credential Management plugin, and external providers are complex to setup and manage.

**Comment by Raju-kadel-27** [comment]
@akhilmhdh I want to work on this issue. Please assign this to me.

**Comment by vmatsiiako** [comment]
@Raju-kadel-27 I assigned this to you. Please let me know if you have any questions, and you are welcome to join our contributor slack: https://infisical.com/slack

**Comment by vmatsiiako** [comment]
Hi @delanym, this should be released now. Could you please check [these docs](https://infisical.com/docs/integrations/cicd/jenkins) and let me know if this works for you? I'm closing this issue for now, but feel free to reopen.
