### ISSUE TITLE
Keyboard enter not triggering form submission on password input

### ISSUE THREAD

**Issue by sreehari2003** [Infisical/infisical#850]
### Describe the bug
In password input keyboard enter is not triggering form submission , it felt weird that enter was not working

### To Reproduce
 
Go to  https://app.infisical.com/login/sso?token=1234

### Expected behavior
  After password entering keyboard enter should trigger form submission

### Screenshots

![image](https://github.com/Infisical/infisical/assets/66205494/698ec50f-969b-469f-925c-b9e97a53a9f4)

### Platform you are having the issue on:
Arc browser , mac os , cloud version

**Comment by neto210206** [comment]
<!DOCTYPE html>
<html>
<head>
  <title>Exemplo de Envio de Formulário ao Pressionar Enter</title>
</head>
<body>
  <form id="loginForm">
    <label for="password">Senha:</label>
    <input type="password" id="password" name="password">
    <button type="submit">Enviar</button>
  </form>

  <script>
    const form = document.getElementById('loginForm');
    const passwordInput = document.getElementById('password');

    passwordInput.addEventListener('keyup', (event) => {
      if (event.key === 'Enter') {
        form.submit();
      }
    });
  </script>
</body>
</html>

**Comment by neto210206** [comment]
![image](https://github.com/Infisical/infisical/assets/136292911/9bcd7a6c-6d71-43b1-8803-ee6459802f87)

**Comment by neto210206** [comment]
**EXEMPLE OF GENERIC CODE**

**Comment by neto210206** [comment]
I hope I have helped you with something

**Comment by wasimTQ** [comment]
@sreehari2003 @akhilmhdh I prefer `Ctrl+Enter` instead of `Enter`. What's your opinion?
