### ISSUE TITLE
GitHub Oauth2.0 sign up process redirects to empty tab

### ISSUE THREAD

**Issue by ragnarbull** [Infisical/infisical#852]
### Describe the bug
Redirected to empty tab on authorizing Infisical with GitHub OAuth 2.0

### To Reproduce
1. Click "Get started" button up on infisical.com
2. Select GitHub
3. OAuth2.0 (click authorize)
4. Redirected to another tab with a {}

### Expected behavior
Should redirect to the right callback on register success (eg. login page). Check callback URL.

### Screenshots

![Screenshot 2023-08-13-infisical-login-github](https://github.com/Infisical/infisical/assets/83689282/76b49750-ebde-4897-987e-6d7b4ed5e555)

https://github.com/Infisical/infisical/assets/83689282/25ae9ef4-ce5a-4c44-a86d-b2a7357248c2

### Platform you are having the issue on:
N/A

### Additional context
N/A

**Comment by ragnarbull** [comment]
Actually it's also the login too. Check the callback URL. I can't login with GitHub but I've authorized Infisical.

https://github.com/Infisical/infisical/assets/83689282/da36e17d-0d96-4e65-9688-a4f6313af901

**Comment by dangtony98** [comment]
Hey @ragnarbull,

This can happen if you’ve previously signed up to Infisical using the regular email-password method. If this is the case, you’ll have to login normally and then head over to your User Settings where you can enable logging in with Google/GitHub.

Let me know if this helps!

**Comment by ragnarbull** [comment]
Ah that makes sense - I just remembered I read your Medium article in the morning and clicked on sign up with email and didn't want to type a long password on my phone. Sure I'll do that. Thanks for the very fast response!
