### ISSUE TITLE
Dockerconfigjson template

### ISSUE THREAD

**Issue by WladyX** [Infisical/infisical#859]
Infisical should have a docker config secret template so that we could deploy image pull secrets as code.
Vault example: https://blog.kelbert.fr/posts/acces-private-docker-registry-with-vault-secret-operator-s-help/
External secrets example: https://external-secrets.io/latest/guides/common-k8s-secret-types/#dockerconfigjson-example

**Comment by neto210206** [comment]
It seems that you are suggesting that Infisical should provide a Docker configuration secret template to facilitate the deployment of image recovery secrets as code. This could improve the process of accessing private Docker records. You provided examples using Vault and External Secrets for Kubernetes. This is indeed a valuable feature that improves security and automation in Kubernetes deployments.

By offering a Docker configuration secret model, Infisical could simplify the integration of access to private Docker records in Kubernetes deployments. Users could easily manage their Docker credentials and authentication information, promoting consistency and reducing manual configurations.

This functionality is aligned with modern DevOps practices, where infrastructure as code (IaC) is critical to maintaining consistent, reliable and version-controlled deployments.

If you are suggesting this improvement to the Infisical team, you can provide your examples and explain how this functionality could benefit users in terms of security, automation and ease of use. In addition, you can share the examples provided from Vault and External Secrets to illustrate how this approach has been successfully implemented in other tools.

**Comment by maidul98** [comment]
The operator now supports `kubernetes.io/dockerconfigjson` which you can set via the `secretType` here https://infisical.com/docs/integrations/platforms/kubernetes. Ensure you have a key in your Infisical project called `.dockerconfigjson:` set to the plain text docker json config

**Comment by WladyX** [comment]
Great news, thank you @maidul98 and @Allex1 !

**Comment by Allex1** [comment]
@maidul98 can you pls also upload the latest helm chart version 0.3.2 containing this feature into the public helm repo so we can sub chart it ?
Thanks

**Comment by maidul98** [comment]
@Allex1 The new version has been released. Are you able to install it?

**Comment by Allex1** [comment]
yes, all good. Thanks
