### ISSUE TITLE
Using HTTP Client instead of Fetch

### ISSUE THREAD

**Issue by SH5H** [Infisical/infisical#86]
### Feature description
Add HTTP Client

### Why would it be useful?
Fetch is good. But it's hard to handle HTTP errors.
So, I recommend using an HTTP client like Axios or Ky.

**Comment by maidul98** [comment]
Great suggestion, Axios does allow eaiser interceptor globally. Are there some usecases you can think of that would benefit Infisical by switching over from fetch? Other than global error handling, I can't think of much. fyi @mv-turtle

**Comment by SH5H** [comment]
We can reduce the amount of code. We use every fetch method with a new config. If we use an HTTP client instance, then we can set the config at once and re-use in every file.

**Comment by mv-turtle** [comment]
This is probably a good idea! Axios is great!

**Comment by mv-turtle** [comment]
@LemmyMwaura this is a very cool idea! I think someone else proposed it in another issue

**Comment by leanjunio** [comment]
Is this being worked on already? Would like to tackle this if it isn't?

**Comment by akhilmhdh** [comment]
Closing as its stale and we already migrated to this
