### ISSUE TITLE
Startup crash when REDIS_URL contains trailing '/'

### ISSUE THREAD

**Issue by jcollas** [Infisical/infisical#876]
### Describe the bug
backend should not crash if the REDIS_URL contains a trailing '/'

### To Reproduce
1. set REDIS_URL to 'redis://host:port/'
2. see crash in log on startup.

### Expected behavior
Removal of trailing '/' lets infisical backend start up properly.

**Comment by maidul98** [comment]
Hey @jcollas, thanks for informing us. What deployment method did you choose? Was this the standalone docker image or docker compose, etc?

**Comment by jcollas** [comment]
I deploy on k3s, still with hand-written yaml.  I added the REDIS_URL this morning, and crashed the backend when my url looked like 'redis://redis-host:6379/', and worked when I used 'redis://redis-host:6379'

**Comment by akhilmhdh** [comment]
CC: @maidul98 is this still valid. If this is from our side i guess could be a good first issue for others

**Comment by maidul98** [comment]
Infisical has moved to new backend + new queue system recently. Have you encountered this issue with redis / recenly as well @belyakov-am ?

**Comment by akhilmhdh** [comment]
Closing as this has been resolved
