### ISSUE TITLE
Sort by name/key in summary view

### ISSUE THREAD

**Issue by decarbonise** [Infisical/infisical#877]
### Feature description
Currently on the per environment view, we can sort the list by key. However, on the summary page, we cannot sort the table. The summary table should be sortable in the same way.

### Why would it be useful?
It's much easier to view secrets if they have a sensible ordering, and the value of this feature has already been recognised and implemented on the per-environment page.

**Comment by aditipatelpro** [comment]
Is this issue open? I would like to give it a try.

**Comment by vmatsiiako** [comment]
Hi @aditipatelpro, the fix to this issue has just been merged. Would you be able to look at some other issues? 

Thank you so much for contributing!
