### ISSUE TITLE
Can't delete secret.

### ISSUE THREAD

**Issue by JamesArthurHolland** [Infisical/infisical#880]
### Describe the bug
Deleting a secret doesn't work.

### To Reproduce
1. Go to secrets.
2. Create secret.
3. Try to delete secret.

### Expected behavior
Secret should be deleted.

### Screenshots
![Screenshot 2023-08-21 at 12 22 19](https://github.com/Infisical/infisical/assets/10409492/caab9d67-fb1d-4f59-838e-03c661a792af)

**Comment by maidul98** [comment]
This issue should be resolved now since we have recently isolated secret related operations to process independently and not depend on integrations as it used to. Closing the issue for now but please open it up again if you notice the same issue
