### ISSUE TITLE
Secrets don't get injected CLI run command

### ISSUE THREAD

**Issue by Julian-Hackenberg** [Infisical/infisical#888]
### Describe the bug
The secrets stored in Infisical do not get injected when using the run command.

### To Reproduce
1. Login with the CLI to your self hosted instance, setup the desired project.
2. Run "infisical run --env=yourenv -- echo Secret is $YOURSECRET"
3. See that echo misses your secret

### Expected behavior
Secrets get injected into the process

### Screenshots
![Screenshot from 2023-08-23 17-57-31](https://github.com/Infisical/infisical/assets/95275073/a9d4c26a-2579-44e5-aa71-a0cec3d96a06)

### Platform you are having the issue on:
Self-Hosted, Docker with reverse Proxymanager SSL termination. 
Docker image infisical/infisical:v0.31.2

**Comment by akhilmhdh** [comment]
CC: @maidul98

**Comment by maidul98** [comment]
Running the `echo` comamnd with the CLI will not work in this fashion. Can you try `infisical run -- printenv`? I have tested and all works as expected

**Comment by Julian-Hackenberg** [comment]
Hey, with printenv it shows up. 

Tested it with node, it seems to work there too!

Apparently one of my use cases won't work then, however awesome tool!

Thanks so much for the help!
