### ISSUE TITLE
Unable to persist trailing whitespace in Infisical secrets

### ISSUE THREAD

**Issue by jsnouffer** [Infisical/infisical#895]
### Describe the bug
I am unable to persist any trailing whitespace, like newlines at the end of secret values using the Infisical UI. With the case of SSH keys, the trailing newline is important for them to work correctly. When secret objects are created by the Kubernetes operator, we end up with invalid keys.

### To Reproduce
1. Create a new secret with a value that has a trailing newline
2. Save the secret
3. Refresh the page
4. Observe that the trailing whitespace has been stripped from the persisted value

### Expected behavior
The trailing newline persists in the saved value

### Platform you are having the issue on:
* Infisical frontend/backend image tags are both v0.32.0
* Kubernetes Operator image tag is v0.3.0

**Comment by akhilmhdh** [comment]
@jsnouffer yes we actually remove any trailing whitespace  for security reasons.

But now that u said it, i do know some instance like for some application the key must have trailing space. This will be a tricky. Let me read some more about this and provide you a proper resolution for this

**Comment by akhilmhdh** [comment]
😅 i guess easiest would be allow user to provide a trailing whitespace of max one

**Comment by erkerb4** [comment]
@akhilmhdh just curious. What is the security reason for removing trailing whitespace? This issue renders InfisicalSecrets unusable if the secret contents are certificate.

**Comment by akhilmhdh** [comment]
@erkerb4 the reason its always a good practice to trim whitespaces and line breaks from an input.

But the recent release we made sure to support certificates and ssh key in infisical. So closing this issue let us know any issue in ssh key
