### ISSUE TITLE
Gitlab SSO

### ISSUE THREAD

**Issue by binaryfire** [Infisical/infisical#896]
Great project! Any chance of adding Gitlab SSO support for the open source version?

Gitlab CE is open source and what many people who fully self-host everything are using.

**Comment by akhilmhdh** [comment]
CC: @dangtony98

**Comment by dangtony98** [comment]
Yeah definitely we can do that 😄

Will keep you posted on this one @binaryfire

**Comment by atimapreandrew** [comment]
@dangtony98 

Please, assign me to this 😊

**Comment by dangtony98** [comment]
Assigned!

**Comment by vmatsiiako** [comment]
This has been released for some time now.
