### ISSUE TITLE
Pull secrets from all folders recursively

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#905]
I want to have defined one single k8s InfisicalSecret in my project that could retrieve all the secrets saved in a folder structure similar with the one described here: <https://infisical.com/docs/documentation/platform/folder#compare-folders-across-environments>. It is possible to configure infisicalsecret by using `secretsPath: /**` ? currently does not work. How can i tell InfisicalSecret to have a look in all folders created under project?

Note: this is not only relevant to K8S but also there clients.

[Slack Message](https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1693204518713749?thread_ts=1693204518.713749&cid=C04BSBMQAQ7)

**Comment by akhilmhdh** [comment]
The issue with recursively pulling is in what order will user's expect and which one would take precedence when two secrets of same key appears

**Comment by vwbusguy** [comment]
I would love to see this in the infisical client as well the Kubernetes operator, and for much of the same reasons.  It would be particularly useful for exporting/importing yaml/json and preserving the multi-level structure.  For example, importing/exporting yaml secrets/deployment parameters for helm deployments to support CI builds.  This would be a much better overall experience for viewing and modifying the secrets than base64 encoding it all in one K/V in Infisical even if it might end up that way in a k8s secret, etc.

**Comment by vwbusguy** [comment]
For now, it seems I've found a bit of an awkward workaround using `yq` and storing the keys in infisical with props annotations, all in the same path:  `infisical export --env=dev -fyaml | yq -pprops -o yaml`.

Merging them into an existing helm values.yaml like: `infisical export --env=dev --format=yaml --token $TOKEN | yq  -pprops -o yaml > secrets.yaml && yq -i ". *= load(\"secrets.yaml\")" dev.yaml`

I think I see your point for compatibility for flat ENV vars, but in this case, this project space is specific for inject secrets and environment config into YAML for Jenkins CI/CD, so having a `--path=/**` even just for `export -fyaml` could be helpful.

This isn't specific for exports, IMO, as having it with `secrets get --path="/**"` could be useful if the output showed folders as well.  Currently there is no was to `ls` folders in an environment with the Infisical CLI.

**Comment by DanielHougaard** [comment]
Hi @vwbusguy. We've recently introduced support for recursively fetching secrets through Infisical. You can now pass `recursive: true` when listing secrets to recursively fetching secrets in all sub-directories. 

Recursive fetching has also been added to all SDK clients & the CLI!

[API documentation](https://infisical.com/docs/api-reference/endpoints/secrets/list).
