### ISSUE TITLE
Integration with CircleCI

### ISSUE THREAD

**Issue by mv-turtle** [Infisical/infisical#91]
### Feature description
It would be amazing to be able to automatically inject secrets (environment variables) into CircleCI. 

Basically, people can connect their Infisical project to CircleCI. Then, the secrets from Infisical would automatically sync into CircleCI 🚀

### Why would it be useful?
It would automate secret management for CircleCI. The more integrations Infisical has, the more useful it becomes!

**Comment by gmgale** [comment]
Hey! Is this linked to #54? As we spoke about refactoring and generalising multiple integrations. Thanks!

**Comment by Aashish-Upadhyay-101** [comment]
I will work on this issue.

**Comment by mv-turtle** [comment]
@Aashish-Upadhyay-101 Thank you so much! Feel free to ask for any help or questions. I think CircleCI is a token kind of integration. @dangtony98 did a similar so he should be able to help

**Comment by mv-turtle** [comment]
Are there docs for this integration? I couldn't find anything :)

**Comment by dangtony98** [comment]
@mv-turtle Yeah I accidentally wrote them in the MFA branch lol but they'll be merged soon.
