### ISSUE TITLE
CLI missing path variable for secrets GET endpoint

### ISSUE THREAD

**Issue by davidhonig** [Infisical/infisical#910]
### Describe the bug
`infisical secrets` does have `--path` flag
`infisical secrets get` does not have `--path` flag -> there is no possibility to get single variable in directory

### Expected behavior
`infisical secrets get` has `--path` flag available

### Platform you are having the issue on:
Self-hosted

**Comment by subhajit20** [comment]
@davidhonig  can you give some more explanation regarding this issue?

**Comment by dangtony98** [comment]
@subhajit20 He's referring to that in Infisical you can store secrets under a specific folder or path.

It's possible to fetch secrets from a folder/path via the REST API or SDK but the CLI seems like it doesn't currently support this functionality; the requested feature would be to support a `--path` flag so users can indicate which path they want to get secrets for.

**Comment by Salman2301** [comment]
fixed : https://github.com/Infisical/infisical/pull/969
@maidul98

**Comment by maidul98** [comment]
issue has been addressed https://github.com/Infisical/infisical/pull/969
