### ISSUE TITLE
[ENG-71] Generate/download a service token via the CLI

### ISSUE THREAD

**Issue by theothertomelliott** [Infisical/infisical#911]
### Feature description

We would like to have our Terraform modules pull secrets from Infisical on demand using the Terraform provider (per [these docs](https://infisical.com/docs/integrations/frameworks/terraform)). Our CI/CD builders will have access to a token, but we would also like to allow our developers to easily execute these modules without having to go into the UI to create a token and manage it within their developer environment.

A very basic workflow could look something like:

```
infisical login
TF_VAR_infisical_token=$(infisical token) terraform apply
```

### Why would it be useful?

This would allow us to use the same code in CI/CD and locally, and have confidence that our local testing was representative.

### Additional context

This could potentially roll into `infisical run` in some way, but it may be confusing to have that command pulling double duty between secrets and tokens.

<sub>[ENG-71](https://linear.app/infisical/issue/ENG-71/generatedownload-a-service-token-via-the-cli)</sub>

**Comment by vmatsiiako** [comment]
This feature has just been released, please check out the documentation here: https://infisical.com/docs/cli/commands/service-token
