### ISSUE TITLE
Issue on docs with docker

### ISSUE THREAD

**Issue by Roarca** [Infisical/infisical#914]
Path: /self-hosting/deployment-options/standalone-infisical

When you start infiscal with a single image , it is impossible to use any service to register , and therefore unusable . If the application needs mongo and redis to work properly , it should be indicated at least in the documentation . 

And for my opinion , if a single image containing everything is given , they should be embedded in it .

**Comment by akhilmhdh** [comment]
@Roarca agreed regarding the documentation part but embedding that's may be a good way for user's to get started in dev mode or something.

Else first its too hard to get embedded work as somethings will always be broken and another dependency we need to care about too.

**Comment by Roarca** [comment]
@akhilmhdh The target I assume is to be able to have everything in a self-contained and functional image, which right now is unusable. It's like if I give you a car without wheels, so that you put the ones you have at home, it makes no sense.

Regarding this embedded, the user does not want (or need) you give external services to run the application. It makes the system more cumbersome to use without reason and more prone to failures and if you can not guarantee that the system works with specific versions of Mongo and redis .... there is a problem

Translated with www.DeepL.com/Translator (free version)

**Comment by maidul98** [comment]
The documentation points out that Mongo and Redis are required environment varables. Is this what you were referring to? Maybe it would help if we made this stand out a bit more?

<img width="884" alt="Screenshot 2023-08-30 at 10 24 51 AM" src="https://github.com/Infisical/infisical/assets/9300960/8aad1c76-2883-4c3e-ad14-3649615128ab">

**Comment by rbudiharso** [comment]
This is happen to me. There's no mention about needing to provide `MONGO_URL` in the documentation when trying to run with Docker nor the docker-compose. Trying to follow the documentation to run the docker command you'll encounter `MongooseError`.

**Comment by maidul98** [comment]
Infisical has moved to Postgres recently. Here are the deployment options with updated docs https://infisical.com/docs/self-hosting/overview

**Comment by maidul98** [comment]
The required config has been updated: https://infisical.com/docs/self-hosting/configuration/envars
