### ISSUE TITLE
Issue deploying secrets-operator helmchart

### ISSUE THREAD

**Issue by xphyr** [Infisical/infisical#922]
### Describe the bug
When attempting to deploy the secrets-operator helm chart per these instructions: https://infisical.com/docs/integrations/platforms/kubernetes#install-operator

helm outputs an error:
```
$ helm install --generate-name infisical-helm-charts/secrets-operator
Error: parse error at (secrets-operator/templates/deployment.yaml:60): unclosed action
```

This error appears to be related to the extra line-break here: https://github.com/Infisical/infisical/blob/37ae05fa2ace7576404d4c9118d1e0ae87e48998/helm-charts/secrets-operator/templates/deployment.yaml#L60-L61

There are additional issues with extra line breaks at lines 67-68, 83-84 and 98-99. 

### To Reproduce
Follow the instructions here: https://infisical.com/docs/integrations/platforms/kubernetes#install-operator

```
$ helm repo add infisical-helm-charts 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/'
"infisical-helm-charts" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "infisical-helm-charts" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm install --generate-name infisical-helm-charts/secrets-operator
Error: parse error at (secrets-operator/templates/deployment.yaml:60): unclosed action
```

### Expected behavior
The helm chart should install without issue

### Platform you are having the issue on:
helm chart install of the secrets-operator

### Additional context
I will be submitting a PR momentarily to address these issues.

**Comment by maidul98** [comment]
New version of the helm chart has been released
