### ISSUE TITLE
[ENG-73] Editing secrets in environment overview breaks when the folder doesn't exist in a certain environment

### ISSUE THREAD

**Issue by vmatsiiako** [Infisical/infisical#927]
### Bug description
Trying to fill in secrets with a folder across environments fails to save if the folder doesn't already exist (imo it should create the folder)

https://github.com/Infisical/infisical/assets/78047717/13723518-4505-43c3-8492-a69326135ae2

### Why would it be useful?
Currently secrets are not being saved if a folder does not exist yet. 

<sub>[ENG-73](https://linear.app/infisical/issue/ENG-73/editing-secrets-in-environment-overview-breaks-when-the-folder-doesnt)</sub>

**Comment by vmatsiiako** [comment]
Test

**Comment by pratik-codes** [comment]
Can pick it up if its open @akhilmhdh @vmatsiiako

**Comment by vmatsiiako** [comment]
@pratik-codes, yes, that would be a great one. @akhilmhdh do you have any thoughts about the implementation?

**Comment by akhilmhdh** [comment]
If the folder not existing user should be given a prompt on creation of the nested folder. 

The create folder APi needs to be modified to support folder creation in deep. May be by passing some parameter. Also quick question: are you working on this or #1015 

Kindly comment one at a time and take one also

**Comment by maidul98** [comment]
Yes @pratik-codes, please work on one issue at a time. Let us know which one you would like to work on first

**Comment by pratik-codes** [comment]
@maidul98 as PR is already created for https://github.com/Infisical/infisical/issues/1015 I will work on this one.

**Comment by pratik-codes** [comment]
@akhilmhdh @vmatsiiako just wanted to confirm so basically here you are accepting the api to create a new folder in staging environment and add the secret there. The api is also giving 500 so I will modify it in a way to do that/

https://github.com/Infisical/infisical/assets/64960569/8e6e18cc-dcdf-41d6-89e8-589d656bb245

**Comment by vmatsiiako** [comment]
This has been fixed. Closing the issue
