### ISSUE TITLE
Cannot upload json secrets file

### ISSUE THREAD

**Issue by dylanseago** [Infisical/infisical#931]
### Describe the bug
JSON file secret upload doesn't work. JSON files in finder not selectable and drop+drop does nothing 

### To Reproduce
1. Go to "project > explore development"
2. Click on "Drag and drop"
3. Try to select a json file

OR

1. Go to "project > explore development"
2. Drop and drop a json file onto the zone

### Expected behavior
JSON file contents are set as secrets on the enviroment

### Screenshots
<img width="814" alt="Screenshot 2023-09-01 at 3 02 47 PM" src="https://github.com/Infisical/infisical/assets/3598502/b4a13f13-1fc5-4dcb-9ceb-476fcacd13f7">
<img width="114" alt="Screenshot 2023-09-01 at 3 09 57 PM" src="https://github.com/Infisical/infisical/assets/3598502/886568f8-09e3-4275-a060-dc4e61e89b73">

### Platform you are having the issue on:
MacOS 13.5
Chrome 116
Infisical 1.17.0

### Additional context
Example json file
```bash
$ cat test.json
{ "secret1": "value1", "secret2": "value2" }
```

**Comment by akhilmhdh** [comment]
@dylanseago from the screenshot it seems your using an old version of infisical. Can you update it please

**Comment by maidul98** [comment]
This issue has been resolved
