### ISSUE TITLE
[CLI] StoreUserCredsInKeyRing: unable to store user credentials

### ISSUE THREAD

**Issue by SmartPhoneLover** [Infisical/infisical#936]
### Describe the bug
The **error: StoreUserCredsInKeyRing: unable to store user credentials** error is shown when I try to login via Infisical CLI.

### Screenshots
![23874897394578358-4](https://github.com/Infisical/infisical/assets/42898749/8dd558aa-71a3-4f7f-bc19-62ee2932ebef)

### Platform you are having the issue on:
- Docker environment (Debian 11 VM)

### Additional context
- I tried the commando, with and without root access.
- I tried also with 'infisical login -i', but the same error shows up.
- The user from Debian (VM) has the correct rights for it, I think.

**Comment by SmartPhoneLover** [comment]
Solved it by switching vault type from 'auto' (default) to 'file'.

**Comment by YoanAncelly** [comment]
Thank you it helped me !
