### ISSUE TITLE
Helper text for secret path

### ISSUE THREAD

**Issue by akhilmhdh** [Infisical/infisical#946]
From slack:

I believe the placeholder should be less confusing i.e.
```glob pattern / or /**/* or /{dir1,dir2}```

Secret path should add a helper text telling users can put glob pattern.

Possibly user should get some example of various glob pattern in a popup window too

**Comment by JanetEne** [comment]
@akhilmhdh I would like to work on this, can it be assigned to me? 

I found a use-case for this as shown. The placeholder looks as expected, should the helper text and the popup window be implemented with this also?

![image](https://github.com/Infisical/infisical/assets/60752117/d1ef146e-aa7b-4e7b-b8ea-c7e1951ae909)
