### ISSUE TITLE
[ENG-76] Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [Infisical/infisical#960]
### Describe the bug
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

### To Reproduce
Scroll to footer section and see twitter old logo

### Expected behavior
Twitter logo should be changed to X

### Screenshots
<img width="960" alt="Screenshot 2023-09-10 195849" src="https://github.com/Infisical/infisical/assets/91591901/d1c7efaf-4702-48df-a26d-f23b80d1cfd0">

### Additional context
@arthurzenika 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

<sub>[ENG-76](https://linear.app/infisical/issue/ENG-76/request-to-update-twitter-icon-to-x)</sub>

**Comment by mdhruvil** [comment]
I am working on it.

**Comment by Rhythm-08** [comment]
Hey, @akhilmhdh I would like to work on this issue, Can I work on it

**Comment by vmatsiiako** [comment]
Hey there! The website is not open sources yet – it will be very soon! For now, I have just changed the icon myself. 

Please feel free to check out any other issue we have or join contributor community here: https://infisical.com/slack
