### ISSUE TITLE
[ENG-83] Set tsconfig path and move all imports in backend from relative to `@app`

### ISSUE THREAD

**Issue by akhilmhdh** [Infisical/infisical#965]
### Description

All the imports in frontend that needs to access from top level like from src are imported  using `@app/...` using tsconfig paths.

This avoid long relative import lines like `./../../`. Backend should also have this  same setup and replace all these long imports lines with `@app` absolute import.

### Expected Behavoir

All long relative imports in backend should use `@app` based absolute import

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-83](https://linear.app/infisical/issue/ENG-83/set-tsconfig-path-and-move-all-imports-in-backend-from-relative-to-app)</sub>

**Comment by PepeGonzale** [comment]
Can I work on this task?

**Comment by 23solo** [comment]
can I work on this ?

**Comment by akhilmhdh** [comment]
Sure @23solo . its all yours. 

Let me know if your stuck anywhere. If you haven't joined our [slack](https://infisical.com/slack) channel do join their too for additional help from community.

**Comment by 23solo** [comment]
sure @akhilmhdh  I've created the PR, please let me know if I've missed something.

**Comment by akhilmhdh** [comment]
@23solo Just need to hold this PR coz of the sheer size, we are releasing some important things. After that ill get back to this

**Comment by akhilmhdh** [comment]
Closing as stale and we moved to new backend
