### ISSUE TITLE
[ENG-86] Time limit for permissions

### ISSUE THREAD

**Issue by yaronlevi** [Infisical/infisical#967]
Link to the original slack thread:
https://infisical-users.slack.com/archives/C059EMM8H97/p1694504161712469

Our “production” env is not accessible for any of our devs.
But many times a day, they just want to quickly add something to it or view it just for a short period. Maybe to debug something even.
So they request that I’ll just open it up for them:

![image](https://github.com/Infisical/infisical/assets/5398977/3f693a79-2f15-4ee4-a242-6d3ad6a74e38)

But the problem is that you need to remember to close it back.

So if we could add on that “eye” button drop down, an options to “make visible for X hours”

This will be SOOO useful.

Escecially for small/medium companies where you don’t have a dedicated DevOps team, and sometimes you just need to give some access to a developer and know for sure that it will not be left open.

I know many dev teams who will die for such feature.

![image](https://github.com/Infisical/infisical/assets/5398977/f5e9dc1c-d2f3-4f25-8878-8904ac0dadbe)

There would be a small UI challange here - how to set the number of hours in that small screen.

Thanks!

<sub>[ENG-86](https://linear.app/infisical/issue/ENG-86/time-limit-for-permissions)</sub>

**Comment by pratik-codes** [comment]
Hi, @vmatsiiako would love to contribute to this feature request if In case it's open.

**Comment by akhilmhdh** [comment]
With new permission system and temporary role feature this issue is completed

**Comment by yaronlevi** [comment]
This is a-m-a-z-i-n-g.
Thank you!
