### ISSUE TITLE
[ENG-103] Integrations should be removed or when E2EE get's enabled

### ISSUE THREAD

**Issue by akhilmhdh** [Infisical/infisical#997]
### Feature description

When E2EE is enabled back integrations gets stop working because bot key gets removed. If disabled back integrations work again.

The issue is user's may not know that integration will stop working on enabling E2EE back. Thus we need provide clear message in both integrations and settings page regarding this.

Also when e2ee is enabled back it should remove integrations or integrations page should be blocked until the bot key is activated again.

### Why would it be useful?

1. Better UX
2. Avoid breaking the system

### Additional context

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-103](https://linear.app/infisical/issue/ENG-103/integrations-should-be-removed-or-when-e2ee-gets-enabled)</sub>

**Comment by unkletayo** [comment]
I would love to pick this up @vmatsiiako
